### ISSUE TITLE
Ready for Testing Arabic Target Language.

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#100]
As a Product Owner, I want to ensure that the product is ready for an upcoming demo for Arabic.
- [x] Import Arabic projects
- [x] Render RTL properly in Target pane.
- [ ] Render RTL properly in Proposed Changes.
- [ ] Select Arabic Text
- [ ] Propose Changes in Arabic Text
