### ISSUE TITLE
User Workflow

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#108]
As a user, I want a defined workflow so that I am confident I know what I'm doing.

As a user, I want to see where I am in the workflow so that I can easily switch between steps and not lose my context in the workflow.
- [ ] Choose a project
- [ ] Choose a check
- [ ] Complete a check
- [ ] Apply a check

![fullsizerender 2](https://cloud.githubusercontent.com/assets/118073/18392102/7d3f8a5e-767e-11e6-8f6e-4d671704498c.jpg)

These could be visually represented like bread crumbs across the top of the screen.

Not adding functionality but additional UX for the workflow.
- [ ] Give overview of workflow in Tutorial.
- [ ] Breadcrumbs?
- [ ] Spike to research implementation.
- [ ] Design before develop.

**Comment by klappy** [comment]
Latest mockup to new UX/UI:

![image](https://cloud.githubusercontent.com/assets/118073/19493792/28886414-954a-11e6-9181-2b5d7203b971.png)
