### ISSUE TITLE
Nested Menu

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#109]
As a user I want an improved menu so that I can visualize my progress and navigate easily.
- [ ] The idea is that they would collapse as you move to the right.
- [ ] Nested menu from group to checks.
- [ ] Progress indicator as pie chart for each group.
- [ ] Progress indicator for each check type.
- [ ] progress meter that wraps around the check icon on the far left.
- [ ] progress meter to the right of the word or “group” checks.
- [ ] the selected highlighted word to be visible beside the reference on the right to see for consistency.
- [ ] The expanding menu that drills down and collapses items on the left as you drill in.

![fullsizerender 3](https://cloud.githubusercontent.com/assets/118073/18392704/c5b1af7c-7680-11e6-8854-d8d00b7166d3.jpg)

**Comment by mannycolon** [comment]
![screen shot 2016-09-16 at 1 47 43 pm](https://cloud.githubusercontent.com/assets/17072300/19196847/24d9dfc8-8c85-11e6-8f92-bfde1a5aea3f.png)

**Comment by benjore** [comment]
## QUESTION

@klappy Has the above mockup been approved? The whiteboard drawing is different from Thomas' mockup. Which do you want?

**Comment by benjore** [comment]
Thomas' mockup is 80% of the way there. Start with that. We'll pivot from there.

**Comment by klappy** [comment]
There is a new series of mockups that address these issues and more. It also addresses #108 and more.
