### ISSUE TITLE
SPIKE: Navigational issues

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1104]
## Some Symptoms
- [ ] "Save and Continue" clicked, worked the first time, didn't work the next time. 
- [ ] ContextID not always showing properly when first opened. 
- [ ] Clicking continue doesn't advance past a group and advance to the next group

**Comment by klappy** [comment]
@benjore, @mannycolon: I need help recreating this. I have tried on all my projects on fresh load and on reload and cannot recreate this on tW or tN.

**Comment by klappy** [comment]
Created tasks for these and considering spike completed.
