### ISSUE TITLE
No title on expanded panels

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1279]
Both from the expanded scripture panel and the expanded edit panel
May also want to consider making the expanded references and Helps panels look more similar to each other.

**Comment by benjore** [comment]
Display the book name in the header bar.

Do this for the expanded Scripture Pane as well as the expanded Target Language (found in the verse edit).

**Comment by richmahn** [comment]
- [x] [2] Add titles to the expanded scripture panel, the expanded edit panel and expanded target language; displaying book name
- [x] [1] Make the expanded references and Helps panels look more similar to each other.
- [x] [3] Write unit tests for title on expanded panels

**Comment by richmahn** [comment]
Note: to test, you could check out the branch `feature-rich-1279-add-titles-to-expanded-panels` in both the `tC_Apps/ScripturePane` and `tC_Apps/VerseCheck ` in your dev env to test them together (just making sure those expanded panes have a title like translationHelps has)
