### ISSUE TITLE
Unexpected behavior when deleting all of the text in a verse

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1299]
Any edits made to a verse are accepted and saved except if all of the text in the verse is deleted. If that is the desired behavior, we should probably warn the user that that will happen.

**Comment by cckozie** [comment]
0.7.0 - The delete does not do anything.

**Comment by benjore** [comment]
Show a pop-up warning asking if they really want to delete.

**Comment by klappy** [comment]
# Tasks
- [ ] [3] Allow blank verses to be saved when editing one with text.
  - [ ] Find where blank verse is ignored in order to save the edit.
  - [ ] Update code to handle blank verse in saving the edit.
  - [ ] Add confirmation for deleting all text.

**Comment by cckozie** [comment]
There are 2 problems.
1) Improper grammar on the warning dialog. "a blank verses" should be changed to "a blank verse"
![image](https://user-images.githubusercontent.com/8171759/27404637-6746e3d6-5694-11e7-9958-1b3376766934.png)

2) If the verse being deleted has selected text, after clicking Save blank verse on the warning message, the screen dims and is unresponsive.
![image](https://user-images.githubusercontent.com/8171759/27404800-fe81d1a2-5694-11e7-9e0c-bcb4b0b82e6c.png)

**Comment by klappy** [comment]
Fix should be in latest build (0.7.1-beta.22).

**Comment by cckozie** [comment]
Number 2. above is still a problem in beta.54
![image](https://user-images.githubusercontent.com/8171759/28030682-63551bbe-656a-11e7-9633-9adb8db5bc17.png)

**Comment by RoyalSix** [comment]
Fixed in #974 PR
