### ISSUE TITLE
Break down Bibles into Book/Chapter/Verse

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1464]
All checkData follows the convention of being persisted to disk into folders of book/chapter/verse, and allows it to be read as individual files. This paves the way to be more memory efficient in the future to read/write dynamically and not store it all in memory. For example, the contextIdReducer only shows one contextId at a time. Similarly we can do the same to read into a smaller reducer for the current verse and/or chapter, instead of the entire book.

This can help the app be ready for larger books like Matthew and Psalms in which it is currently crashing on.

- [ ] Determine if subdividing in Chapters is most appropriate.
- [ ] Saving to disk
- [ ] Loading from disk
- [ ] Optimizing what is used in state (current chapter instead of whole book)
