### ISSUE TITLE
Entire tC window went blank

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1572]
I had loaded a project that had a merge conflict in one chunk and opened it with tW. It came up to the first check and did not display any text for the verse either in the Select area or the scripture pane. I then went to the file system to verify that there was in fact text for that verse, and while doing that the tC window went blank. I could not get the developer tools to open.
![screen shot 2017-05-16 at 10 13 08 am](https://cloud.githubusercontent.com/assets/8171759/26113501/5218a584-3a20-11e7-965d-ed8411a48db4.jpg)

**Comment by cckozie** [comment]
This also happens when I just load the project with tW and then let it sit there for a while or click around the screen. Once this happens the project will no longer load.
[rmy-x-vc_mrk_text_reg.A.zip](https://github.com/unfoldingWord-dev/translationCore/files/1005020/rmy-x-vc_mrk_text_reg.A.zip)

**Comment by cckozie** [comment]
May want to combine with #1573 and #1568

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/26116184/d10ed1b8-3a27-11e7-91d7-0282809ceb40.png)

**Comment by benjore** [comment]
- [ ] When a user tries to select an imported project that has one of the following problems: 
  - [ ] Merge Conflicts
    - [ ] Prohibit the loading of this project
    - [ ] Error message: "Oops! The project you are trying to load has a merge conflict and cannot be opened in this version of translationCore! Please contact Help Desk (help@door43.org) for assistance."
  - [ ] No Project Manifest
    - [ ] Prohibit the loading of this project
    - [ ] Error message: "Oops! Your project does not have a project manifest! Please contact Help Desk (help@door43.org) for assistance."
  - [ ] Blank Verses
    - [ ] Allow the loading of this project after the following warning is displayed
    - [ ] Warning message: "Oops! Your project has blank verses! Please contact Help Desk (help@door43.org) for assistance with fixing this problem. If you proceed without fixing, some features may not work properly." Buttons: "Cancel" "Continue Without Fixing"

**Comment by benjore** [comment]
- [ ] When a user tries to select an imported project that has one of the following problems: 
  - [ ] Merge Conflicts
    - [ ] Prohibit the loading of this project
    - [ ] Error message: "Oops! The project you are trying to load has a merge conflict and cannot be opened in this version of translationCore! Please resolve the merge conflicts (for instance in translationStudio) and reimport the project into translationCore and try again."
  - [ ] Corrupted Data
    - [ ] Prohibit the loading of this project
    - [ ] Error message: "Oops! Something happened and your project cannot be opened. Please contact the Help Desk (help@door43.org) if you have any questions."
  - [ ] Blank Verses
    - [ ] Prohibit the loading of this project
    - [ ] Error message: "Oops! Your project has blank verses! Please fix this problem, reimport the project into tC and try again."
  - [ ] No Project Manifest
    - [ ] Prohibit the loading of this project
    - [ ] Error message: "Oops! Your project does not have a project manifest! Please fix this problem (saving your project in translationStudio will create a project manifest), reimport the project into tC and try again."

**Comment by cckozie** [comment]
Unable to import projects in 0.7.1 so I cannot test.
