### ISSUE TITLE
translationCore package manager

### ISSUE THREAD

**Issue by ihoegen** [unfoldingWord/translationCore#159]
# What it should do

Workflow - So we need to have a package manager. In the the system app data folder, we will have a translationCore folder, which will have 2 folders: packages, and packages-compiled. When a module is downloaded, it is downloaded to the packages folder, then compiled into packages-compiled. When an update is available, the same thing is done. Uninstall just deletes the folder inside of packages and packages-compiled. When a package is required, it is pulled from packages-compiled.

Package Manager - Needs to give a way to view the list of projects in the manifest.json, and the option to install, uninstall, and to check for updates.

**Comment by ihoegen** [comment]
@mannycolon If you come up with functionality you'd like, or things that would make the front end to this easier, add them to the list:
- [x] A way to see if a package exists locally, `isExist`
- [x] Get version of a package
- [x] Don't compile if there's no babelrc

**Comment by EvanWiederspan** [comment]
why cant they just download the package already compiled?

**Comment by ihoegen** [comment]
@EvanWiederspan Well when we download the packages, they will be downloaded from the creators repo, and they wouldn't be pushing their compiled code to their repos. I do need to add a way to check for a babelrc file, that way we can skip compilation if they decided to go with just plain JavaScript. However, I think 99% of modules will be written in React anyways
