### ISSUE TITLE
Multiple issues with Export to CSV

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1637]
[fr_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1015131/fr_eph_text_ulb.zip)

[EPH_français.zip](https://github.com/unfoldingWord-dev/translationCore/files/1015076/EPH_francais.zip)
- [x] 1. Timestamps should be separated into two fields, date and time. 
- [x] 2. The time field should be adjusted to the PC's local time zone.
- [x] 3. In Selections.csv, the text field has unrecognizable characters. Same in VerseEdits, and I expect will be a problem in all non-English text.
- [x] 4. In Selections.csv, commas are interpreted as field separators. This causes the text field to be split into the text and selection/occurance fields, and causes all fields except for "text" to appear in the wrong column. I assume this will get worse if there are multiple commas in the selection.
- [x] 5. In the attached file, row 41 shows an empty text field
- [ ] 6. In the attached file, row 41 shows occurrence 2 of 31 for TRUE which only occurs once in Eph 3:6.
- [x] 7. After the Export button is clicked, there is no indication to the user that anything is happening until the Success (or Fail) alert comes up. On my field grade Windows machine, this is can be several seconds.

**Comment by cdwhitfield73** [comment]
@RoyalSix I will take care of issue 7 above in a separate PR

**Comment by RoyalSix** [comment]
@cdwhitfield73 are all of these addressed now? Can I close this?

**Comment by cdwhitfield73** [comment]
@RoyalSix No.  I only addressed issue 7.  You still need to look at 1 thru 6, dealing with the data itself.

**Comment by RoyalSix** [comment]
Finished most of these just, looking at the edge cases right now with number 5,6

**Comment by RoyalSix** [comment]
Issue 3 is not a problem with tC but Excel

**Comment by cckozie** [comment]
Testing on 0.7.1
I copied the project in the first comment into the tC directory and did the export to csv. I received the failure message indicating that there had not been any checks made in the project. When I opened the project in both tN and tW I saw there the checks were all gone. Is this a problem caused by our refactoring? If so, do we have plans (issues) for data migration?
Also, what needs to be done to fix the problem in #3?

**Comment by cckozie** [comment]
beta.54
Number 4. above is still a problem (but different) in beta.54
![image](https://user-images.githubusercontent.com/8171759/28035357-016a9068-657a-11e7-827d-f288b42f4a65.png)

**Comment by cckozie** [comment]
beta.54
I don't know if this is related to 5. and/or 6. above, but row 6 in selections.csv does not accurately reflect what is in the project.
[fr_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1136811/fr_eph_text_ulb.zip)

![image](https://user-images.githubusercontent.com/8171759/28036118-b409162a-657c-11e7-823d-32351f482050.png)
![image](https://user-images.githubusercontent.com/8171759/28036146-d10faca2-657c-11e7-84cb-8d0a915c6a6c.png)

**Comment by cckozie** [comment]
Export to csv needs a lot of work. I seen and listed quite a few, but I suspect there are others as well. It needs to be thoroughly tested before going into a build. In addition to the issues listed above, here are some others:
1. Commas in the text cause data to go into the wrong columns
2. #NAME? shows up in the "text" column
3. Unrecognizable characters in "text" column
4. Both tN and tW entries show up in both the Notes and Words Selections.csv
5. All selections and edits appear in the files rather than only the last one.
6. I've seen "selection/occurance" as high as 81 and "selection/occurances" as high as 183. Is that correct?

**Comment by RoyalSix** [comment]
- Get project from Koz for testing

**Comment by klappy** [comment]
@cckozie: New CSV exports optimize the files that get exported. There were issues in the previous export workflow that complicated the consistency. The new files aren't grouped by type, and have included all data on tests projects.

For issue 6:
The test data provided didn't have the checkdata included so there are some assumptions that the data will be clean on export. If issues are found, we can include more test data to ensure they pass as expected. One of the errors above, could be related to a selection bug for the "occurrences" as it could highlight a word or characters that happen N number of times in the target verse. Currently each selection has it's own row, so a single check that has 4 selections, will display 4 rows. This is what was expedient in getting consistency in the data export that would be meaningful to re-import if needed. Combining selections into a single row would either make the data no longer human readable or unparsable. We can revisit that issue and plan how we want to export if this isn't best for the user.

**Comment by cckozie** [comment]
.beat57
Issue 3 is still a problem
[Selections.csv.zip](https://github.com/unfoldingWord-dev/translationCore/files/1261010/Selections.csv.zip)
I'm still looking for a project that now has multiple occurrences of a word.

**Comment by klappy** [comment]
What software are you opening the csv file with?

Also can you upload the latest csv that you are having troubles with?

Csv is a flat file, no configuration. The library only uses UTF8 encoding. There's not much we can do other than open it with software that understands the utf8 encoding.

**Comment by klappy** [comment]
@cckozie: I found some articles as this seems to be a common issue with Excel: 
https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0
https://stackoverflow.com/questions/35294443/does-excel-for-mac-2016-properly-import-unicode-in-csv-files

**Comment by cckozie** [comment]
The special character problem does not appear when the file is opened in LibreOffice. Unfortunate that it doesn't work in Excel, but that's probably for another day.
I need to do more testing on multiple occurances.

**Comment by cckozie** [comment]
It appears to me that there are no longer any tW checks with multiple occurrences in the same verse so I can't check that issue.
But I have found a new problem:
If there have  been no selections, no edits, and no comments in the exported project, when the zip file is uncompressed, no folder is created to contain the checks file.

**Comment by klappy** [comment]
@cckozie: With the new issue that you are encountering, you have edits, but no other data in the project, and that is how to recreate your issue?

**Comment by klappy** [comment]
@cckozie I deleted my last comment after re-reading and seeing the edits in the list. 
As long as I can remember we always failed the export if no checkData, (selections, edits, comments, reminders) was in the project. There is a message that says, export failed.

To recreate the problem you are facing, I had to do some checks, then delete the checks from the filesystem. 

I am now looking into how to force a folder to hold the single file, as it should be there but isn't.

**Comment by klappy** [comment]
After opening a second tool for the same project, doing no checks and going back to export to csv, it has a subfolder that holds the two files. 

This appears to be an operating system issue, if you have a zip file with a single file in it, it unpacks it with just the filename. If it has more than one file, it creates a folder of the same name as the zip file. 

If I add a subfolder, then when we have more than one file, there will be a subfolder in the folder that holds our data. This will cause inconsistencies. 

Do we want the subfolder in the unzipped folder? So that the case of the single file has more context?

**Comment by klappy** [comment]
@cckozie: I have an idea how to address the issue with consistency. I'll try that and report back. See the previous comment for context.

**Comment by cckozie** [comment]
@klappy Would it be a big deal to create all of the files and just leave them empty if they have no data?

**Comment by klappy** [comment]
That makes sense. I'll look into that.

**Comment by klappy** [comment]
That worked!

**Comment by cckozie** [comment]
beta.69
Looks good.
Creating a new issue to display the error message about no tools yet being loaded before having the user select the destination path.
