### ISSUE TITLE
Support for USFM import

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1689]

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] Determine what logic can be used from for usfm to JSON (usfm-parse)
- [ ] [1] Determine workflow for opening project without a manifest
- [ ] [2] Write new action to handle usfm importing (Project Selection Actions.js)
- [ ] Consider naming convention for USFM projects, because right now it is just the book abbreviation in all caps

**Comment by cckozie** [comment]
I am able to import properly formed USFM files, but there are several problems. There does not appear to be any error handling, the project does not get a good name, and the language displayed is wrong. Since the issue did not include details on how these things should be handled, I'm going to pass this issue and write up the problems in #2190
