### ISSUE TITLE
Support for USFM Export

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1690]
This feature will be available in the 3-dot menu in the projects part of the stepper. The three-dot menu will say "Export to USFM" and be located right underneath the "Export to CSV" option.

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] Create UI component for feature
- [ ] [2] Determine what code we can use for JSON to USFM exporting logic from our local module npm (usfm-parse)
- [ ] [1] Connect ui to new action
- [ ] [2] Write/run tests for exporting project

**Comment by cckozie** [comment]
1. The identification markers should appear in the same order as in the spec. The \id should be first in the file.
2. There should not be a comma next the the book abbreviation in the \id marker. (Some apps, tS included, are looking for a space as the abbreviation delimiter.)

**Comment by RoyalSix** [comment]
- [ ] [2] Fix id markers in USFM Export Format

**Comment by RoyalSix** [comment]
@cckozie Can I have an example id tag to go off from?

**Comment by cckozie** [comment]
@RoyalSix 
[php_usfm.usfm 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/1180694/php_usfm.usfm.2.zip)
