### ISSUE TITLE
Show (truncated) highlighted text in the side menu

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1691]
Once a selection has been made and saved:
- [ ] the Bible reference should change from the full name of the book (e.g. "Ephesians") to the 3-letter code of the book (e.g. "Eph").
- [ ] The highlight should show up after the reference and should truncate with a "..." when necessary. (Note: this feature should be responsive for when the side menu is expandable)
- [ ] If a user hovers over a truncated menu item, the whole highlighted selection appears in a pop-over

**Comment by benjore** [comment]
User feedback from Ludhiana

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [1] Convert reference to abbreviation on active selection
- [ ] [2] Get data from highlighted text and populate in menu with truncation (responsive)
- [ ] [3] Create on hover popover with above data for corresponding element

**Comment by cckozie** [comment]
Hovering over the text always causes the full selected text to be displayed, even if it was not truncated when displayed in the menu. Checking with Ben to see if that's OK.
Ben says "yes, it's ok"
