### ISSUE TITLE
Import Unlocked Hebrew Bible (UHB) & ensure it displays correctly

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1717]
- [x] Import the UHB Bible 
- [x] Make sure it displays correctly in the Scripture Pane
- [x] ~No need to parse the tW links at this time~ this is already working but we currently only have one link in the entire OT - so tWords will not work.  
- [x] Make sure it works in the Source content updater - need to add support for UHB since it does not currently parse.

**Comment by jag3773** [comment]
Blocked by #3414

**Comment by jag3773** [comment]
Available at https://api.door43.org/v3/subjects/Hebrew_Old_Testament.json .

**Comment by PhotoNomad0** [comment]
#### Tasks
- [ ] [4] Fix source content updater - to download and parse UHB.
- [ ] [4] Fix scripture pane to display UHB for OT books. 
- [ ] [10] Fix rendering of UHB - rtl issues, etc.

**Comment by PhotoNomad0** [comment]
@benjore - is this sufficient for the UHB display in the scripture pane?

![screen shot 2018-11-15 at 5 37 25 am](https://user-images.githubusercontent.com/14238574/48547576-f5202e00-e898-11e8-94b6-ce614e429b32.png)

**Comment by benjore** [comment]
For now that is great. There is an issue to deal with this comprehensively. This is fine for now.

**Comment by mannycolon** [comment]
@benjore @PhotoNomad0 Its missing the highlighting in the scripture pane

**Comment by PhotoNomad0** [comment]
Tested latest build for windows (https://tc-builds.door43.org/build/develop/translationCore-win-x64-1.1.0-d22908a.setup.exe) and it crashes when Expanded Scripture Pane is opened.  But Mac build works.  Moving this back in progress to fix.

**Comment by PhotoNomad0** [comment]
Looks like a change to our build process caused the WA fixes to not be pulled in.

**Comment by PhotoNomad0** [comment]
Tested in build https://tc-builds.door43.org/build/develop/translationCore-win-x64-1.1.0-f7160ac.setup.exe.

@cckozie - note for now you will need to download "Ancient Hebrew" resources (hbo) before WA will work on OT books.

**Comment by cckozie** [comment]
1.1.0 (413b11c) 
I did see the crash when opening the scripture pane, but cannot reproduce the problem. Passing for now.

**Comment by cckozie** [comment]
1.1.0 (8b1ff72)
After a clean install and then importing an OT book and opening it in wA, the UHB text is not displayed until the user changes verses (selects a different verse in the menu other than the one the project opened to). This does not happen with the UGNT for NT books.

**Comment by PhotoNomad0** [comment]
Blocked waiting for https://github.com/unfoldingWord-dev/translationCore/pull/5535

**Comment by da1nerd** [comment]
moving this to the QA Fail column

**Comment by cckozie** [comment]
Works in 1.1.0 (4d06842)

**Comment by cckozie** [comment]
1.1.0 (4d06842)
The requirements in the first comment have been mostly met, but there is a problem with the source content updater which I've described in issue #5553. Since similar problems exist for the Greek, I've written it up there instead of failing this issue.
