### ISSUE TITLE
Dropdown menus

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1720]
Without the "Most recent"

(Team estimated adding "most recent" at an additional 8 SP)

**Comment by benjore** [comment]
https://github.com/unfoldingWord-dev/design/issues/157

**Comment by benjore** [comment]
- [ ] Should be "Log out" not "Sign out"
- [ ] There will be no Online/Offline mode
- [ ] Align the menu to the left (Home | User | Project | Tool)

**Comment by RoyalSix** [comment]
![](https://cloud.githubusercontent.com/assets/21183377/26319115/542bad72-3ee3-11e7-9936-6e69d4bde99e.png)

![](https://cloud.githubusercontent.com/assets/21183377/26319114/542b68bc-3ee3-11e7-81e5-1b1584d75446.png)

![](https://cloud.githubusercontent.com/assets/21183377/26319116/542c8c9c-3ee3-11e7-9c48-7c4f003a31d2.png)

![](https://cloud.githubusercontent.com/assets/21183377/26319118/542e3fd8-3ee3-11e7-952f-0b4a8a1feb17.png)

![](https://cloud.githubusercontent.com/assets/21183377/26319117/542d7a4e-3ee3-11e7-8d04-5800940151f4.png)

![](https://cloud.githubusercontent.com/assets/21183377/26319119/5430ed64-3ee3-11e7-864d-575e8cc3167a.png)

![](https://cloud.githubusercontent.com/assets/21183377/26319120/543daa2c-3ee3-11e7-963d-48d3532c7d80.png)

![](https://cloud.githubusercontent.com/assets/21183377/26319121/543eec5c-3ee3-11e7-993b-1496c6f5fcec.png)

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [5] Create blank UI for dropdown menu items
- [ ] [1] Add user functionality for dropdown menu
- [ ] [4] Add project functionality for dropdown menu (except recent project functionality)
- [ ] [2] Add tool functionality for dropdown menu
