### ISSUE TITLE
Select Mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1748]
- [ ] When a user navigates to a check that has no selection they go directly to select mode. 
- [ ] When a user navigates to a check that has a selection they go directly to standard mode. 

- [ ] Select Mode - No selection
  - [ ] The left side of the card below the Bible reference should be grayed out (or the text grayed out - it must be easy to see that the text is disabled) but the text still visible and no action should be allowed there. (If a previous selection has been made, that should be visible through the gray)
  - [ ] The top part of the right-hand side is the instructions
  - [ ] The bottom part of the right-hand side is the target language verse. This is where the selecting happens. 
  - [ ] "Cancel" disregards any selection that may have been made and brings the user to standard mode.
  - [ ] "Clear Selection" resets the selection - only on the right-hand side. (This button should be standard height, not as per mockup)
  - [ ] "Save" is deactivated until a selection is made. When a selection is made and "Save" is clicked, the data is saved and the user is brought to standard mode with the selection being retained on the left-hand portion of the card. 

- [ ] Standard Mode (Step 2. Check)
  - [ ] If no selection has been made, the instructions show on the right-hand portion of the card. 
  - [ ] If a selection has been made, it should read:
[English selection] 
has been translated as: 
[target language selection]
  - [ ] Buttons
    - [ ] Select - brings the user back to select mode
    - [ ] Edit Verse - brings the user to edit mode
    - [ ] Comment - brings the user to comment mode
    - [ ] Bookmark toggle - turns the bookmark on and off.

**Comment by benjore** [comment]
![new ui stuff](https://user-images.githubusercontent.com/13352518/26882205-bc065a6a-4b67-11e7-8899-d716c2946504.png)

**Comment by klappy** [comment]
## Tasks
[1] Select: Rename select mode to default mode
[1] Select:  Add new select mode
[2] Select:  Move old select mode into right side when in select mode
[2] Select:  Add new instructions to top of select mode
[1] Select:  Add new Select button for entering select mode
[1] Select:  lighten verse area to transparency to 50% when in select mode.

**Comment by cckozie** [comment]
1. The first item in the description was not implemented (When a user navigates to a check that has no selection they go directly to select mode.)
2. There is no Clear Selection button as specified in the description and UI design, only Cancel and Save Changes.
![select1](https://user-images.githubusercontent.com/8171759/28227235-9f96d982-689e-11e7-80a1-b9a47c4b99ba.png)
3. After a selection has been saved, the card on right (translated as) does not match the UI design. The selected text is highlighted rather than blue bold.
4. When the user reenters selection mode on a check that was done, the instruction card should return to what it was before the check was made rather than showing the selection a third time.
![image](https://user-images.githubusercontent.com/8171759/28227270-cf285680-689e-11e7-9d44-a272d3f29207.png)
5. In image above for 4., the text in the selection area spills out of the frame.

Also, I added issue #2176 to have the Select mode frame sizing mimic Edit and Comment modes.

**Comment by klappy** [comment]
## Tasks to address QA Failed:
[2] Select Mode: Select mode is the default if no quote is selected
[4] Select Mode: Create button and action to Clear Selection
[1] Select Mode: Update styles of selection to match mockup
[1] Select Mode: Show instructions at the top of select mode instead of the selection
[2] Select Mode: Optimize layout for overflowing verses

**Comment by cckozie** [comment]
Unexpected behavior when the verse to be checked is blank. I don't think we should automatically go into edit mode in that case. I've written up a new issue, #2289 to address this and other ideas about what to do when the verse is blank.
