### ISSUE TITLE
Technical Debt

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1753]
- [x] 8 Get Coveralls working
- [x] 3 Diagram Data Flow Architecture
  - [x] 1 Dataflow consistency
- [x] Codebase Cleanup
  - [x] 8 Deleting unnecessary files
  - [x] 8 Remove module API
  - [x] 8 Organize Reducers
  - [x] 5 Reorganize the actions
  - [x] 0.5 Requirements.js
  - [x] 5 Codebase folder structure
- [x] Performance on Loading
  - [x] 8 Book/Chapter/verse breakdown
  - [x] 13 Rewrite data/resource parsing
  - [x] 5 Move Resources from Tools to Core 
  - [x] 13 Rewrite project loading
  - [x] 8 Rewrite tool loading
- [x] 2 submodule updater
- [x] 2 USFM parsing library
- [x] 20 Writing test for existing code
- [x] 3 SPIKE: Explore combining tN & tW tools
- [ ] Documentation 
  - [ ] 8 Internal
  - [ ] 8 External
- [x] 20 Refactor Build Process
  - [ ] 13 Webpack
- [ ] 8 CSS Refactor

**Comment by mannycolon** [comment]
@benjore Could we create stories for the following if we don't already have them  

- [ ] Documentation
   - [ ] 8 Internal
   - [ ] 8 External

- [ ] CSS Refactor
