### ISSUE TITLE
Book/Chapter/verse breakdown

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1764]
## Overview
1. Bibles will be stored in book folders and chapter level json files.
    - eph/1.json
    - eph/2.json
    - tit/1.json
2. Reference bibles will be stored in the current place.
    - ~/translationCore/resources/bibles/en-ULB/v6/eph/1.json
    - ~/translationCore/resources/bibles/en-UDB/v9/eph/1.json
    - ~/translationCore/resources/bibles/UGNT/v0.2/eph/1.json
3. Target bible will be stored in the project root folder.
    - ~/translationCore/[project-name]/eph/1.json
4. Archive imported source files
    - ./apps/translationCore/importedSource/...
5. Bibles will be accessible by current verse in reducer (assuming they get organized under props.reducers)
    - props.reducers.currentVerse.target
    - props.reducers.currentVerse.en-ULB
6. Bibles will be accessible by current chapter in reducer
    - props.reducers.currentChapter.target
    - props.reducers.currentChapter.UGNT

**Comment by mannycolon** [comment]
- [ ] write action and helper to get the desired reference.

**Comment by klappy** [comment]
# Tasks
See above description in the first comment for overview.
## Filesystem
- [ ] [3] update how bibles are stored
  - [x] chapter level files
  - [x] target bible stored in the project's root folder
  - [x] reference bibles stored in ~/translationCore/resources/bibles/[bible-name]/...
  - [x] archive source files that were imported ./.apps/translationCore/importedSource/...
## Actions/Reducers
- [ ] [3] update how bibles are loaded into the memory from filesystem
  - [ ] populate currentVerse reducer (target and references)
  - [ ] populate currentChapter reducer (target and references)
  - [ ] chain reducer population to happen after contextId changes
## Components
- [ ] [2] update components to use updated reducers for verse and chapters
  - [ ] scripture pane
  - [ ] verse check
## Tests
- [ ] [3] write tests for updated bibles
  - [ ] filesystem tests that ensure the bibles are in the right place and format
    - [ ] reference bibles
    - [ ] target bible
  - [ ] reducer tests that ensure the bibles are there and usable
    - [ ] reference bibles
    - [ ] target bible

**Comment by mannycolon** [comment]
@klappy what do you mean when you say ` store the target Bible in the root folder in the native format`. what is the ` root folder`?

**Comment by klappy** [comment]
@mannycolon: haha, yeah, that is bad to just say `root folder`, I'll update it to say `project root`. I put examples in the top description.
