### ISSUE TITLE
Rewrite data/resource parsing

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1765]
Move out of tools to a script in the core.
Parse source formats into csv.
Convert csv to json that application would use.

**Comment by RoyalSix** [comment]
# Overview
Right now we are reading static data from the file system (not according to tC spec), parsing that data into a format for our components and then writing that data back to the filesystem in a different format
What we should be doing is loading data already formatted according to tC spec (pre parsed), and then importing it to our components. Then we can write out to the same format and never have to worry about parsing.

**Comment by RoyalSix** [comment]
# Tasks

## Prepare
  - [ ] [1] Gather all resources being used in a project
    - [ ] Make sure it is updated
  - [ ] [2] Determine format for input data for components (reducers)
  - [ ] [2] Create folder structure for resources
  - [ ] [3] Write script that will take those resources and create a zip file with individual files for each resource parsed in format specified above
## Move Resources From Tools
- [ ] [3] The tool component should only read from the file system and use that as props
## Tests
- [ ] [2] Write tests to ensure data loading is consistent
- [ ] [1] Write tests to check for errors in resource content
