### ISSUE TITLE
Refactor stepper for new UI

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1880]

**Comment by mannycolon** [comment]
## Tasks

- [ ] [0:30] Regain familiarity with Stepper implementation.
- [ ] [2] Spike: research what needs to be changed to implement new stepper UI.
- [ ] [3] Implement new stepper design.
