### ISSUE TITLE
Refactor moduleSettings generation for scripturePane

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#1881]

**Comment by mannycolon** [comment]
## Task
- [ ] [1] Create room in the resourcesReducer.Bibles for bibles manifest.
- [ ] [2] Create an action to load all bibles manifest files.
- [ ] [3] Refactor the `Scripture Pane` to use new bible manifest props.
