### ISSUE TITLE
Footnotes and other USFM markers should not be displayed in the ULB

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1941]
![image](https://user-images.githubusercontent.com/8171759/27440928-b7c0b81c-5731-11e7-8e5b-50162981fa7a.png)
![image](https://user-images.githubusercontent.com/8171759/31141323-b4f66454-a83c-11e7-8e55-89811f8502ea.png)

**Comment by cckozie** [comment]
Hide them for now.

**Comment by benjore** [comment]
In 0.7.1-beta 53, footnote showed up in 2 Peter 2:4: 
![screenshot 2017-08-24 09 38 03](https://user-images.githubusercontent.com/13352518/29671766-f766823a-88af-11e7-9628-842ea7b90b19.png)
"

**Comment by benjore** [comment]
- [ ] Check for other USFM format markers as well (`/q` , `/p`, etc.)

**Comment by benjore** [comment]
- [ ] Add tests

**Comment by klappy** [comment]
- Mask footnotes in two locations on render.
- Do not delete or remove the data.
- Hide it in Scripture Pane and Target text Check area.

Tasks:
[3] Footnotes: Create tests to ensure use cases are handled in usfm.js package
[2] Footnotes: Create function to filter out footnotes in usfm.js package
[2] Footnotes: Implement footnote filter on Scripture Pane rendering
[2] Footnotes: Implement footnote filter in Verse Check rendering 

  - Do not modify the data, just filter it on render

**Comment by cckozie** [comment]
I'm not seeing any difference.
![image](https://user-images.githubusercontent.com/8171759/31132374-3d5cd80c-a822-11e7-85ef-8547bd50525a.png)
![image](https://user-images.githubusercontent.com/8171759/31132406-5364fe5e-a822-11e7-8b8d-1e7f76844f4a.png)

**Comment by RoyalSix** [comment]
![image](https://user-images.githubusercontent.com/16184018/31237279-58fb9eb0-a9ab-11e7-9d1b-9eb67afc9f37.png)

**Comment by RoyalSix** [comment]
- [ ] [2] Find where scripture pane should be using footnotes filtering methods

**Comment by cckozie** [comment]
I can't test this until I can load non-Titus projects. (No footnotes in Titus ULB)

**Comment by cckozie** [comment]
The footnote USFM markers are being stripped out, but the footnote text is still being displayed. It should be stripped out too.

The \q and \p markers are being stripped out as desired.

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [1:30] Remove text between footnotes

**Comment by klappy** [comment]
@RoyalSix: I think I may have merged too early. It appears that either something's wrong with my local or there's a use case that's not handled properly.

@jag3773: Do we know if that is valid: `\f + \ft Some versions add, \fqa Amen \fqa* \f*`? 

If so, we should filter out everything between `\f` and `\f*` regardless of nested markers and text.

The footnote markers are filtered, but we should also be filtering out `Some versions add, Amen.` The footnote text is still visible but shouldn't be.

<img width="288" alt="screen shot 2017-11-09 at 8 54 26 pm" src="https://user-images.githubusercontent.com/118073/32639104-3ded02e8-c590-11e7-84e0-ab6728035768.png">

**Comment by jag3773** [comment]
Yes, that is valid markup.

**Comment by cckozie** [comment]
I've also noticed that when the /q markers and footnotes are hidden, it is also stripping out a space that should still be there; example from Ephesians:
![image](https://user-images.githubusercontent.com/8171759/32694728-bf227974-c70c-11e7-8c3e-c7c1be4520de.png)

**Comment by cckozie** [comment]
alpha.11
Now rather than it just stripping out the space in the "\q" markers, it's stripping the whole phrase. (See the comment from 6 days ago to see the missing text)
![image](https://user-images.githubusercontent.com/8171759/32961690-2728d1ae-cb8f-11e7-9670-bf6fdb573194.png)

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] Only strip out entire text for footnotes
