### ISSUE TITLE
New field in CSV exports

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1986]
Both of these categories are needed in the CSV export: 

- [ ] Category slug (e.g. figs_exclusive)
- [ ] The "Human Readable" version of the slug (e.g. "Exclusive We")

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [0:30] Get human readable name from index
- [ ] [2] Update export action file is recent project actions (Code involved in exporting should be factored out to export actions)
