### ISSUE TITLE
Selection of terms in unexpected verse

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1999]
## User Story

As a checker, I want to be able to complete a check for my translation even if the check occurs in a different verse than expected, so that I can complete all the checks despite different versification. 

Related to #1259 and #1260 

![image](https://user-images.githubusercontent.com/13352518/34490301-111fd814-efa5-11e7-9ccf-229270f23da5.png)

- [ ] Add a `+` button
- [ ] Add the hover over

![image](https://user-images.githubusercontent.com/13352518/34490316-1e106872-efa5-11e7-8599-88cb3ebff45d.png)

- [ ] Shift the screen split (from 50-50 -> 2/3-1/3)
- [ ] adjust heading (e.g. Titus, Swahili)
- [ ] Add `-` and hover over
- [ ] Add verse before & after
- [ ] Be sure the highlighting can transcend verses
- [ ] Whenever `+` is clicked, scroll to the top
- [ ] When making a selection in an unexpected verse, record the active chapter & active verse as we do in verse edits for CSV exports

**Comment by benjore** [comment]
Will need multiple issues to cover - 
- selections over verse spans,
- what happens when I click save - what is displayed (or navigate away from them check and back to it), 
- how to store the data (add reference to selections)
- crossing chapter lines. 

Possibly 
- consider changing the default view of the verse to look like the second mockup above (reference to the side of the verse instead of at the top).

**Comment by mannycolon** [comment]
- When making a selection in an unexpected verse, record the active chapter & active verse as we do in verse edits for CSV exports

**Comment by da1nerd** [comment]
The selections over verse spans requirement is related to https://github.com/unfoldingWord-dev/translationCore/issues/1259
