### ISSUE TITLE
Screen Real Estate Optimization

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#200]
- [ ] Tri-Pane to show only one verse, click for more.
- [ ] Analyze prototype's screen real estate. http://translationcore.s3.amazonaws.com/ceb-demo/app/index.html
- [ ] Don't show translationHelp until clicked, show a modal pop-up.
- [ ] Try to make functionality of check, highlighting in Tri-pane.
- [ ] Previous and Next buttons as arrows floating in the middle on the sides.
- [ ] Highlight gateway quote in Tri-pane, and don't display it with Note.
- [ ] Reference material together, and actionable or translation/checking material together.

**Comment by benjore** [comment]
![image](https://cloud.githubusercontent.com/assets/13352518/19316552/dc6916f2-906f-11e6-9889-5da3d7a89c66.png)

**Comment by klappy** [comment]
This has been greatly altered by new whiteboard mockups by Tim and designs by Thomas.
