### ISSUE TITLE
Edit verse not being checked

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2004]
## User Story

As a checker who sees an error in a verse that is not being checked, I want to be able to edit a verse that is not being checked so that I don't go crazy or have to try to find a check in that verse before I can fix the error. 

~May be covered by #1999~

## Specs
- [x] A reusable module needs to be created that contains the edit verse functionality. 
  - [x] A two step "stepper" is needed
  - [x] `Next` is not active until a change has been made 
  - [x] `Save` is not active until a reason has been selected 
  - [x] Multiple reasons may be selected
- [ ] For this iteration, this module will only be implemented in the expanded scripture pane
  - [x] __For the current project only__ add a pencil to each verse (Note: other resources opened in the Scripture Pane cannot be edited, only the current project)
  - [ ] When a user clicks the pencil, 
    - [ ] the `Edit Verse` module appears to the side of the verse
    - [x] All other pencils are deactivated. 
    - [x] The user must complete the module or cancel out of it (i.e. the rest of the screen is disabled)

![image](https://user-images.githubusercontent.com/13352518/37262527-94587946-2571-11e8-8e80-531cf7f1fd08.png)

![image](https://user-images.githubusercontent.com/13352518/37262538-a3a2d680-2571-11e8-9cdc-f070e123398b.png)

![image](https://user-images.githubusercontent.com/13352518/37262693-bac63c8e-2572-11e8-99a5-f45df91d8cc8.png)

![image](https://user-images.githubusercontent.com/13352518/37262697-c128b980-2572-11e8-81ac-b8cbacb54bbe.png)

**Comment by da1nerd** [comment]
next button will be disabled until you begin editing.

**Comment by da1nerd** [comment]
@benjore will this reusable component be used just in other areas of scripture pane or do you plan on using it in other tools as well?

**Comment by benjore** [comment]
@neutrinog Other tools as well.

**Comment by cckozie** [comment]
Why does this have the QA/Retest label on it? It has never been through QA before.
I'm not seeing the edit option in the expanded scripture pane. It looks the same as it always has.

**Comment by da1nerd** [comment]
I'm not even done building this! lol

**Comment by da1nerd** [comment]
The UI for this is done. I'm waiting to hear back if there is an existing method of writing the data to the file.

**Comment by da1nerd** [comment]
@benjore when a verse is edited should all the alignments be reset? Should anything else be reset?

**Comment by benjore** [comment]
@neutrinog So if any part of a word is edited, the entire verse needs to be realigned. For selections in the tW tool, only reset the selection if the words in the selection have changed, otherwise keep the selection as is.

**Comment by da1nerd** [comment]
@benjore ah. Ok right now any time a verse is edited it will reset all the alignments for the entire verse no matter what tool you are in. You're telling me you don't want that functionality?
What happens then if they are working in tW and make an edit then move into the word alignment? Technically those alignments will be invalid no matter what tool you were in while making the edit.

**Comment by cckozie** [comment]
1. Italic and non-italic has been switched. Missing verses warning should be italicized and the rest not italicized as in the previous build:
![image](https://user-images.githubusercontent.com/8171759/38164726-36b4a212-34ce-11e8-8acc-a404f5e76813.png)

2. Need to be able to edit missing verses.
![image](https://user-images.githubusercontent.com/8171759/38164601-aa73e2d2-34cc-11e8-9491-7add6b735443.png)

3. Can you reduce the amount of white space above and below the pencil so that more verses can be seen in the window as in the UI mockup above?

4. There is very little difference in appearance in the Back button when it is disabled and enabled. Maybe if you remove the fill on the button and change font color as in the mockup the difference in state would be more obvious.

**Comment by PhotoNomad0** [comment]
![screen shot 2018-04-02 at 6 56 07 am](https://user-images.githubusercontent.com/14238574/38194005-0cec5ae4-3643-11e8-8a94-c6c5e9d14392.png)

@neutrinog @cckozie - localization broken for verse edit.  Suspect integration with crowdin is not working.

**Comment by cckozie** [comment]
Need to verify that the problems noted in #4188 and #4212 are all dealt with when the above are fixed.

**Comment by richmahn** [comment]
Another issue I found with this: the change of `addVerseEdit` to `editTargetVerse` action function in `VerseEditActions.js` causes the Check pane's verse edit to not save and throw an error that `addVerseEdit is not a function`.

![2018-04-02](https://user-images.githubusercontent.com/2839925/38207357-b906d5f8-366a-11e8-8dd3-85f4442849af.png)

**Comment by da1nerd** [comment]
@richmahn there was actually a legacy action I left just in case something still needed it. I'll assign it to the correct action.

**Comment by cckozie** [comment]
translationCore 0.9.0 Travis build #7346 (from http://tc-release.unfoldingword.surge.sh/)
Now able to save edits.
Issues 1. Italics and non-italics, and 2. Edit missing verses from my comment "3 days ago" have not been address.
Also, there is missing localizations:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/6dcf3a5c-a710-4383-9881-56a3e095e22e)

**Comment by da1nerd** [comment]
@cckozie these fixes were just merged in. They may not be in a build yet because the last couple of builds have timed out.
