### ISSUE TITLE
Remove/Archive Offline Mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2007]
- [ ] Offline Mode should be removed
- [ ] The toggle for the online/offline mode needs to be removed. The User, Project, and Tool menus should be aligned to the left (with "Home" still being on the farthest left)
- [ ] The app should not access the Internet unless the user performs an explicit function that accesses the internet (e.g. import, upload)
- [ ] Every time a user triggers a function that will access the internet, they should receive a modal confirming that action before the app actually goes online. 
  - [ ] The warning modal should say: "You are about to transmit data over the internet, you sure you want to do that?"
  - [ ] The modal should have the Secondary button "Cancel", the Primary button "Access Internet"
  - [ ] The modal should also have a checkbox that says "Do not show this warning again". This needs to be saved on a per user basis.

**Comment by RoyalSix** [comment]
# Tasks
- [ ]  [2] Remove Offline UI components, update status bar
- [ ] [2] Ensure basic version of app can work without internet
- [ ] [2] Archive old internet toggling functionality
- [ ] [2] Determine user actions that require internet
- [ ] [3] Create confirmation modal allowing such actions

**Comment by RoyalSix** [comment]
@benjore question. How should we handle the user wanting to change the setting of using online mode or not? If they were to select do not show again

**Comment by benjore** [comment]
Do we have any way to store settings attached to the user? That's what I was envisioning.

**Comment by RoyalSix** [comment]
Only show for the current session

**Comment by cckozie** [comment]
There is a typo on the Internet warning card. Since it was specified incorrectly in the instructions for this issue, I will write up a new issue to fix it. Issue #2179
