### ISSUE TITLE
tN Tools

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2009]
## Specs
- [ ] Mock data structure: https://docs.google.com/spreadsheets/d/1NMIfdundjjRHo3EknFPLO6to2acQYvm6NL8uXU_0tmQ/edit#gid=495123398 
- [ ] More commentary: https://forum.ccbt.bible/t/translationnotes-tsv-format/57

## Breakdown
- [L] Parsing the TSV and generating the GroupIndex and GroupData (NPM Module)
   - parse during download
- [M] Create the initial tN tool - tW tool with tN data (for testing SPIKES)
   - Fork tW to prove the concept that it works
- [M] Verify (& fix as needed) that tN data is loaded correctly
- [L] Use filesystem to handle parent and child categories for the tN tool card (include the hover-over description) - for each GL (part of NPM Module)
   -  ![image](https://user-images.githubusercontent.com/16184018/52006945-59678c80-249b-11e9-8419-54385cd2761f.png)

- [M] Create Tool Card UI 
- [M] Add TSV parser to the Source Content Updater
- [S] Add the tN data to the build process (getting the latest data from the Catalog)
- Create tN tool 
  - [4] SPIKE: what else needs to be done for tN to work.
  - [M] Update the Smurf Bar to display data from new location (alignment data)
- [4] SPIKE: What needs to be done for tN quote highlight to show on the scripture pane.

## Questions
- [ ] How do we know the GL of the TSV file? **Check the [manifest](https://git.door43.org/unfoldingWord/en_tn/src/branch/master/manifest.yaml#L367)**
- [ ] Suggestion: label the `GL Language` as `not used` (in the CSV file)
- [ ] Should we add a Manifest file to the TSV file? **There is already a manifest file, see [this](https://git.door43.org/unfoldingWord/en_tn/src/branch/master/manifest.yaml#L367) for example**
  - [ ] Show the name of the tool? 
  - [ ] Ability to add the a jpg for the tool logo? 
  - [ ] Data version number? 

## Mockups
![image](https://user-images.githubusercontent.com/13352518/48024406-3761a680-e106-11e8-9c20-702f5f327690.png)

![image](https://user-images.githubusercontent.com/13352518/48024427-3d578780-e106-11e8-9dd1-0d048e2fb143.png)

![image](https://user-images.githubusercontent.com/13352518/48024433-421c3b80-e106-11e8-9065-c70aa25c7b1c.png)

![image](https://user-images.githubusercontent.com/13352518/48024449-47798600-e106-11e8-84c0-e354480352cd.png)

![image](https://user-images.githubusercontent.com/13352518/48024460-4c3e3a00-e106-11e8-95b0-e7d396e2b289.png)

![image](https://user-images.githubusercontent.com/13352518/48089705-b7514480-e1ca-11e8-8794-c2c0e3d5293f.png)

![tN Categories.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/a2332464-7080-4ccd-9426-86613c968f6d)

**Comment by benjore** [comment]
This issue probably makes #246 obsolete

**Comment by benjore** [comment]
All from original description:

- [ ] translationNotes - Figures of Speech
- [ ] translationNotes - Grammar
- [ ] translationNotes - General

### What needs to be learned
- [ ] What to do when there is no tA article
- [ ] What to do with General Information & Connecting Statement checks
- [ ] What to do with links to [dead] cross references, links, blank articles

### Blocker 
- [x] Need: Original Languages quotes in the TSV (and preferably confirmed)
- [ ] Parser to pivot/index categories/groups by support reference 
  - [ ] Pull in tA article - 
- [ ] 

### Notes
- [ ] Rather than separating the tN tool into several separate tools, make one big tool that can be internally filtered (based on user selection - probably in the tool card). In this way, it can be presented to the user as multiple tools. Use a single index regardless of visual approach.

**Comment by mannycolon** [comment]
Reference: https://github.com/translationCoreApps/tC_Resources/tree/master/resources/en/translationHelps/translationNotes/v0

## Index file sample (Previously used)

```
[
  {
    "id": "figs_imperative",
    "name": "Imperatives - Other Uses"
  },
  {
    "id": "figs_merism",
    "name": "Merism"
  },
  {
    "id": "figs_activepassive",
    "name": "Active or Passive"
  },
  {
    "id": "figs_personification",
    "name": "Personification"
  },
  {
    "id": "figs_doublet",
    "name": "Doublet"
  },
  {
    "id": "figs_pronouns",
    "name": "Pronouns"
  }
]
```

## Previous Group Data Item

```
[
  {
    "priority": 1,
    "comments": false,
    "reminders": false,
    "selections": false,
    "verseEdits": false,
    "contextId": {
      "information": "David calls himself \"your father\" because this is a very formal occasion. AT: \"my God\" (See: [[:en:ta:vol2:translate:figs_123person]])\n  ",
      "reference": { "bookId": "1ch", "chapter": 28, "verse": 9 },
      "tool": "translationNotes",
      "groupId": "figs_123person",
      "quote": "the God of your father",
      "occurrence": 1
    }
  }
]
```

**Comment by jag3773** [comment]
I added some comments in the Questions section.

**Comment by RoyalSix** [comment]
@mannycolon Isn't it redundant to have the     
    ```
    "comments": false,
    "reminders": false,
    "selections": false,
    "verseEdits": false,
```

**Comment by RoyalSix** [comment]
My branches: 
tC: feature-bspidel-5756-2
tW: feature-bspidel-5756-3
tN: feature-bspidel-5756-2

**Comment by cckozie** [comment]
Holding until all child issues pass.
