### ISSUE TITLE
Expanded tW tool (Other Terms & Names)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2010]
## User Story

As a checker, I want to more comprehensively check my translation so that I can be confident I'm using the correct words in my language

## Specs
- [x] All three checkboxes are always visible on the tool card
- [x] By default, all three checkboxes are preselected
- [x] If the user unselects a a checkbox or two, save those settings (pegged to the project)
- [x] If all checkboxes are unselected, disable the `Launch` button
- [x] The progress bar is calculated based on what has been checked (e.g. if 87% of the `Key Terms` have been completed and only `Key Terms` is checked, then display 87% progress. If the user then checks all the boxes, but only 43% of all of them is completed, then show 43% progress.)
  - [x] If it takes longer than 0.5 seconds to refresh the % complete, then show a little spinner on the progress bar (preferably where the % complete number is)
- [x] When the user clicks `Launch`, whatever checks correlate to the checkboxes are loaded in the tool. 
- [x] If a Gateway Language does not have content for all the checkboxes, disable those. 

## Notes
- `See more` still shows the tool description as per usual

## Mockups
![image](https://user-images.githubusercontent.com/13352518/46674451-c6c87800-cba1-11e8-9b4c-d81e3efca976.png)

![image](https://user-images.githubusercontent.com/13352518/46674544-01321500-cba2-11e8-93ae-01f5e18867b0.png)

![image](https://user-images.githubusercontent.com/13352518/46674843-be247180-cba2-11e8-8d8e-f17e2efbe758.png)

![image](https://user-images.githubusercontent.com/13352518/46675258-a39ec800-cba3-11e8-8f79-3e15b4f69129.png)

**Comment by benjore** [comment]
~~From jag3773 on 5/11/2017 "Content should be grabbed from https://api.door43.org/v3/catalog.json . The testing endpoint is https://test-api.door43.org/v3/catalog.json . This should all be in prod within a couple weeks."~~

Use https://api.door43.org/v3/subjects/Translation_Words.json

**Comment by RoyalSix** [comment]
@benjore On a high level how do we determine a Gateway Language does not have all the content for a specific checkbox (type of check)?

Do we have a master list of all the info supposed to be in a check such as the `Keyterms`?

@mannycolon @jag3773

**Comment by mannycolon** [comment]
@RoyalSix We could create the same list for tW as we mentioned for tN on #2009

> Create JSON file to handle parent and child categories for the tN tool card (include the hover-over description) - for each GL

**Comment by jag3773** [comment]
@benjore @RoyalSix I'd suggest that if the `other` or `names` **directories** *do not exist* in a GL that the checkboxes be disabled.  If those directories do exist, then enable the checkbox for that GL.

In conjunction, the tool should always fall back to the English tW entry if it missing in the GL.  Given that older versions of tW may be published in the catalog, they may not have all the same content as the latest English, so the tool should be smart enough to fall back to English and not crash.

**Comment by RoyalSix** [comment]
@benjore Do we want anything checked by default?

**Comment by RoyalSix** [comment]
What I have implemented so far is that the check boxes will dynamically be searched for and if the directory is there then it will show or else it will not. 

i.e. If I remove the Hindi key terms resource then it will only show Other and Names.

If that functionality is not preferred then I can make a static list "Key Terms, Other, and Names" and then since we know what to expect everytime I can make them disabled. But if we take this approach then if new resources become available that are not on the list "Key Terms, Other, and Names"  then the checks will not be available to show until we add them to the static list in the code.

Hope that makes sense.

Also note that I had to create a static list of names that convert to the display name
i.e. kt => "Key Terms", and other => "Other Terms" etc
These can be translated but theres no where I could find that tells me what kt should be shown as.

**Comment by cckozie** [comment]
1.1.0 (42d80de) 
[en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2696690/en_ulb_tit_book.zip)

This happens when I load the project in tW with only Key Terms checked.
![image](https://user-images.githubusercontent.com/8171759/50251233-d259cb80-03a8-11e9-90fe-44345bcc9192.png)

**Comment by RoyalSix** [comment]
Fixed in 8586b02

**Comment by cckozie** [comment]
1.1.0 (b287d3d)
[fr_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2721815/fr_ulb_tit_book.zip)

Still seeing problems when loading with only Key Terms selected. This does not always happen. I'm working on getting the sequence of events to reproduce. This appears to show the problem:
1.Shut down tD
2. Unzip the attached project into the projects folder
3. Start tC and select the project
4. Load the project in wA
5. Click on the tools icon in the menu bar to return to the tools page
6. Unclick the Other Terms and Names checkboxes
7. Load the project in tW and note the error

![image](https://user-images.githubusercontent.com/8171759/50608614-bff48d00-0e92-11e9-8b2d-68c0789d5616.png)

**Comment by RoyalSix** [comment]
@cckozie Having trouble recreating this. Going to investigate the error further.

**Comment by cckozie** [comment]
@RoyalSix I've been unable to reproduce this in the latest builds, so don't spend much time on it if the error doesn't tell you much.

**Comment by RoyalSix** [comment]
@cckozie Yea no luck for me. I guess I'll just put QA Retest on this one? Or should we close it

**Comment by cckozie** [comment]
@RoyalSix Moving it to QA

**Comment by cckozie** [comment]
All child issues have passed.
