### ISSUE TITLE
Refactor build process - Part 3 (Windows)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2100]
Finish remaining tasks on implementing new build process
- [ ] Local builds for Windows
- [ ] Appveyor builds for Windows
- [ ] Decide on bundling Git installer or use git library

**Comment by cckozie** [comment]
dup
