### ISSUE TITLE
Refactor build process - part 2 (Mac)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2101]
Begin implementing the new build process based on the investigation done

- [x] Electron-Forge
- [x] Minimal Travis-CI config
- [x] Minimal Appveyor config
- [x] Non-destructive builds
- [x] Travis-CI Builds for Mac/OSX
- [x] Local builds for Mac
