### ISSUE TITLE
Find alignment tool mockups & evaluate

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2146]
- Find mockups
- Evaluate mockups

**Comment by klappy** [comment]
## Questions to answer about mock-ups:
- [x] Are they clear and understandable?
- [x] Do they fit with our intended use case?
- [x] Is there enough detail in them to create the UI?
- [x] What problems exist in the mock-ups?
  - Source Greek words need to be visually consistent with the target words.
  - Scripture pane isn't close to ours.
  - Not clear how to handle drop-able containers.
- [x] What would you change in the mock-ups?
  - Change source Greek words to have their own box like the target words.
  - Use our existing scripture pane.
  - When dragging a word, emphasize the containers that they can be dropped into.
  - Skip example two for now since we aren't implementing predictions yet.

**Comment by cckozie** [comment]
Need to have group review of the UI/UX
