### ISSUE TITLE
Multiple fixs / enhancements to Import USFM

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2190]
1. After importing, the USFM project name is wrong. I imported es-419_luk_text_ulb.usfm. In tC it appears as "unlocked_luk".
2. After importing, the USFM target language is wrong. For the above file, the language appears as "Literal (unlocked).
3. USFM import needs to handle bad/missing data. There should never be an instance where the import does not work and the user does not receive an error message. At a minimum it needs to deal with:
- Missing or bad book code
- Missing or bad language code
- Missing or out of sequence verse markers
----Need to verify that last verse in chapters are not missing
- Missing or out of sequence chapter markers
4. During the import, display a dialog that indicates what is happening. When it completes, show the success or failure dialog as appropriate.

**Comment by RoyalSix** [comment]
## Tasks:
- [ ] [2:30] Fix naming issue on usfm file import
- [ ] [2] Fix language name detection
- [ ] [4] Better error handling for usfm imports
- [ ] [2:30] Dialogs for project import feedback

**Comment by klappy** [comment]
I'm thinking that since the ProjectValidation will check the manifest and have the user confirm the Project book and language names, we can leverage that for USFM too. We still need handle missing/out of order chapters/verses.

So the tests that we should write cover:
1. missing chapter marker
2. out of order chapters
3. missing verses
4. out of order verses

I had an idea, that I don't think is far fetched. 
Since we're assuming these are completed books, we could use the number of chapters, as well as number of verses in each chapter to detect which book is being imported. We could also use that data to verify chapters/verses missing in the above.

**Comment by RoyalSix** [comment]
@cckozie You mentioned having a dialog for importing a local usfm project. Should we have a dialog for all local imports? If so what should it say?

**Comment by cckozie** [comment]
@RoyalSix Similar to the online import:
![image](https://user-images.githubusercontent.com/8171759/29854048-30722914-8d09-11e7-9e70-842e0aa8e60d.png)

**Comment by cckozie** [comment]
1. App hangs when importing a project that has a missing chapter marker. 
![image](https://user-images.githubusercontent.com/8171759/29975934-ea5f0360-8efd-11e7-9aa2-17b8d5286eaf.png)
[php_usfm_NoC2.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1270672/php_usfm_NoC2.usfm.zip)
2. Also, did you add a project loading dialog? I'm not seeing one, although it may be because the computer is too fast

**Comment by RoyalSix** [comment]
This is fixed in #2618

**Comment by cckozie** [comment]
.beta63
1. I am again able to import an existing project.
2. The file  en-x-demo1_php_text_reg_old.zip still causes the app to hang when importing.
![image](https://user-images.githubusercontent.com/8171759/30120422-627cb8b2-92ee-11e7-8608-1d7d705b17e2.png)

**Comment by cckozie** [comment]
Here is another one that causes the app to hang:
[php_usfm_NoV.usfm.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/1284875/php_usfm_NoV.usfm.txt.zip)

![image](https://user-images.githubusercontent.com/8171759/30166832-282dc2b6-93aa-11e7-9a14-cb90dd19be4e.png)

**Comment by cckozie** [comment]
This one did not report missing verses, but when I get into the project I see that there are missing verses.
[php_usfm_2C2.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/1284937/php_usfm_2C2.txt.zip)
![image](https://user-images.githubusercontent.com/8171759/30167562-69c8b5b2-93ac-11e7-95c3-108bfb64975c.png)

**Comment by klappy** [comment]
@RoyalSix: I see this was moved but no PR or comment as to how it was resolved. Can you provide more information?

**Comment by RoyalSix** [comment]
Its connected to PR #2586. 
It should have been pending build. But now its already been merged and in the latest build

**Comment by cckozie** [comment]
beta.65
1. Regarding the project php_usfm_2C2.txt above:
The only problem with the usfm file is that both chapters 1 and 2 have the \c 2 marker.
When it is imported, tC reports all verses missing except for chapter 2.
When opened, tC is confused about the chapters and verses as shown in this shot for the scripture pane and there are lots of errors in the console:
![image](https://user-images.githubusercontent.com/8171759/30388921-e6111b86-9876-11e7-8b88-2ffd06e6d70a.png)
After clicking around in the checks menu, then changing to tN, then closing and restarting tC, when I open the project in tW I get a blank checking screen.
2. Regarding project php_usfm_NoV.usfm.txt referenced above, I am seeing exactly the same behavior as reported there.
3. Regarding project php_usfm_NoC2.usfm referenced above, tC now does not hang when importing it, and the list of missing verses is correct, but when opening with tW, the checking screen is blank. After that occurs, I am no longer able to select a different project on the project list screen.
![image](https://user-images.githubusercontent.com/8171759/30389669-2697793c-9879-11e7-8be4-939bbae3f876.png)
4. The 
[en-x-demo1_php_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1306618/en-x-demo1_php_text_reg.usfm.zip) project does now import, but the app throws an error and becomes unusable when opening the merge conflict.
 project
5. If the USFM file has a bad or missing book ID, the app hangs on the import.
6. Please add the path and file name to the importing alert as in the screenshot of the online import.

**Comment by cckozie** [comment]
Moving out of sprint 40. Will retest after the new USFM3 parser is implemented.

**Comment by cckozie** [comment]
It is worse now. I cannot open any project in either tN or tW after importing from USFM.
Also, none of the issues that I can now test in the beta.65 comment above have been fixed.

**Comment by cckozie** [comment]
beta.86
1. This project is missing the v1 and v2 markers. When imported to tC I get this alert and the app is frozen: [php_usfm_NoV1V2.usfm.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/1359574/php_usfm_NoV1V2.usfm.txt.zip)
![image](https://user-images.githubusercontent.com/8171759/31230658-44c7adea-a9aa-11e7-9052-5ad25e02f923.png)
2. USFM files that do not have a book id cause the same alert as above.
3. USFM files that have an invalid book id cause the same alert as above.
4. USFM files that have a merge conflict do import, but the merge conflict screen does not show the conflicting data, so the conflict cannot be resolve and the project cannot be loaded.
![image](https://user-images.githubusercontent.com/8171759/31231178-b2f1ea28-a9ab-11e7-98df-91feaa7a2f79.png)
5. tC ignores chapter markers that have a leading zero (\c 01) and reports all of that chapter's verses are missing. (Need to be able to handle 2 leading zeros for Psalms)

**Comment by RoyalSix** [comment]
[ ] [3] Handle USFM Projects With No ID Tag

**Comment by cckozie** [comment]
Referring to the above comments referencing beta.63:
I am not prevented from importing an existing project.

Referring to the above comments referencing beta.86:
1. I no longer get the empty alert. After entering the copyright and project info screens I'm taken to the Tools screen without notice of the missing verses. If I change projects then come back to try to open this one, I am correctly presented with the missing verses panel. (This occurs on multiple projects with missing verses.)
2. fixed
3. fixed
4. 
5. fixed
(I cannot be 100% sure issues 2-5 have been fixed until I am able to open them in tW, or I am able to create the appropriate test files for Titus.)

**Comment by cckozie** [comment]
beta.96
Not sure if the bug is in this issue or #2821. Let me know if it should be there.
1. I now get the can't import existing project alert even though I don't have a project with that name or that book and language.
[projects.zip](https://github.com/unfoldingWord-dev/translationCore/files/1443605/projects.zip)
[php_usfm.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1443604/php_usfm.usfm.zip)
This happens on every project I attempt to import, so I am unable to test any of the other issues related to USFM. It may allow me to import one file after an upgrade of tC, but then no more. Happens on both Windows and Mac.

**Comment by RoyalSix** [comment]
@cckozie This has been fixed in #3056. This PR has not been merged yet.

**Comment by cckozie** [comment]
This is still broken in 0.8.1-alpha.1

**Comment by RoyalSix** [comment]
- [x] [2] Fix Duplicate Project Feature

**Comment by RoyalSix** [comment]
I tested multiple times on the build and verified this is fixed.

**Comment by cckozie** [comment]
I think all of these issues are fixed or handled in other issues.
