### ISSUE TITLE
Newly imported projects do not appear initially in the project list

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2192]
This error shows up in the log. If I go back to the user screen and them proceed forward, the project does show up on the list, but I am not able to select any project. The same error keeps getting generated.

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [:30] Re-test newly imported projects bug
- [ ] [3] Research method to detect when a new project is imported
  - Note: Thinking that a interval checker may be easiest but least efficient. Look at node fs change listeners.
- [ ] [2] Implement method to detect newly imported projects on the fly
 
@benjore @cckozie If newly imported projects cannot be detecting do we want to have a refresh button and/or a interval checking for new projects imported every 2 secs or so (only while on the projects screen)? (Performance impact for interval checking is very minimal)

**Comment by cckozie** [comment]
@benjore @RoyalSix 
Since newly imported projects always go through the validation stepper, could we hook something into the action that closes the stepper to then refresh the project list too?

**Comment by RoyalSix** [comment]
@cckozie At what point are you not seeing projects you imported?
Are you saying when you take a project through the validation stepper, it doesn't show in the list after going back to the projects step?
Because if so I'm not seeing the same behavior.
My steps are:
1. Select project that is on my desktop from 'import local' button
2. Go through project validation stepper (I can do this or cancel and get the same result)
3. Go back to projects list by either pressing cancel on the stepper or pressing the projects button
4. Newly imported project is there

I initially thought this issue was created from copying and pasting a project in the tC projects folder from the filesystem and them not showing up in the projects folder. We are currently not handling this use case.

Also since you said there was an error, I'm assuming the issue is unrelated to the projects not showing up from the stepper but a silent crash resulting in half-functionality in the stepper which can also be looked at. Do you have the error message by chance?

**Comment by cckozie** [comment]
@RoyalSix It looks like this is no longer a problem in .beta63. Imported online and local projects do show now in the project list after the validation stepper is completed or canceled out of. I'm going to pass it.
