### ISSUE TITLE
Slow Load On Refresh

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#2236]
The app takes a longer time to reload now (CMD + R), possibly related to electron forge.

- [x] (L) Update to React 16 (enables profiling, see https://building.calibreapp.com/debugging-react-performance-with-react-16-and-chrome-devtools-c90698a522ad )
- [ ] (m) Add Hot Reloading
- [x] (m) Add Redux logger

**Comment by MarshallOfSound** [comment]
@RoyalSix You'll notice slightly longer reload times in development mode only because `electron-compile` transpiles your files on the fly, it doesn't pre-run babel on anything it only transpiles what you need when you need it.

When packaged up your application won't have this slow-down because everything will have been precompiled during the packaging step

**Comment by RoyalSix** [comment]
@MarshallOfSound Am I able to / Are there any downsides to, not transpiling on the fly.

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [4] Research why the reload is slower
  - [ ] [2] Test to ensure the app is only slower in development 
- [ ] [4] Implement (Configure) method to make the refresh faster

**Comment by MarshallOfSound** [comment]
If you don't transport on the fly, overall it will be slower because you will have a significantly longer "transpile everything " step before you can even launch your app.  By transpile on the fly we do things like hash checks and load cached already transpile versions of your code.

In the long run your better off with it doing this :D

**Comment by RoyalSix** [comment]
## Testing on my 2015 MBP i5 8GB ram
- Development Build: 3.8s
- Production Build: 4.5s

**Comment by RoyalSix** [comment]
@MarshallOfSound Are the above times fairly decent for a moderately large react app?

**Comment by RoyalSix** [comment]
https://github.com/electron/electron-compile#react-hot-module-loading

**Comment by klappy** [comment]
@RoyalSix The hot module loading is something I've wanted to implement since we moved to electron-forge. Let's do that. If we need to create a new task for it let's add it to the sprint story backlog and check with Koz and Ben on priorities at tomorrow's standup.
