### ISSUE TITLE
Inconsistent use of icons for language

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2251]
![image](https://user-images.githubusercontent.com/8171759/28539882-dfbb4ea8-7078-11e7-9110-0cf0d0dbc32d.png)
![image](https://user-images.githubusercontent.com/8171759/28539921-04cf13d2-7079-11e7-8fca-5d2176fb2180.png)

**Comment by benjore** [comment]
- [ ] Go with characters icon
Projects page
Overview page

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [2] Modify projects page to use characters icon for language
- [ ] [2] Modify overview page to use characters icon for language
- [ ] [4] Add Unit tests
