### ISSUE TITLE
Alignment Tool: Implementation in tC

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2257]
Via Wiki: https://github.com/unfoldingWord-dev/translationCore/wiki/Alignment-Tool-Plan

The estimates will likely need to be re-evaluated now that more of the planning prerequisites are completed.

## Blocking
While most of the UI can be created while blocking components can be worked on it cannot be completed until it is completed.
- [Blocking] UGNT USFM 3 exposed via DCS v3 API.
- Import UGNT USFM 3

## [73] Tool in tC
User Interface can be developed concurrently to TACT/MAP Preparation.
### [73] User Interface
- [5] Create a new blank tool that brings in Scripture Pane and a new area for the rest of the checking area to be used for alignment.
- [13] Create Initial Layout for UI
- [5] Evaluate React D&D for creating drag and drop UI.
- [21] Create D&D Interface for aligning words/phrases between source/target.
- [21] Create Actions/Reducers for storing/retrieving alignment data.
  - Reference for alignment data: https://github.com/unfoldingWord-dev/translationCore/wiki/Alignment-Data-Structure:-USFM-3
- [8] Style UI components

**Comment by benjore** [comment]
MODIFICATIONS TO THE ALIGNMENT TOOL UI MOCK-UPS

- [ ] When a word has been moved from the "Word List" (panel on the left), remove the blue bar (since blue bar means that something is movable)
- [ ] If two Greek words are in the same alignment box, then each word should be in its own black box with a blue bar (that is, make the Greek words behave like the English) - this updates the mockups in Example 4
- [ ] For the first iteration, there will be no MAP integration. As such, there will be no animation upon hover
- [ ] The Scripture Pane in use should be the same as in the regular tC, with this change:
    - [ ] the Greek & the translation being aligned must be displayed and cannot be removed from display. 
- [ ] When a user clicks on a Greek word in the Scripture pane, the UGL popover should appear, as will be implemented in #689 
- [ ] When dragging a word...
  - [ ] Note: any alignment box with no English should have a white, dashed box as per the mockups
  - [ ] When an English word is being dragged, the bottom half of every card should display a light blue dashed box (to indicate where the word can be dropped). 
  - [ ] When a Greek word is being dragged, the top half of every alignment card should display a light blue dashed box (to indicate where the Greek word can be dropped). 
  - [ ] If two Greek words are dragged into the same box so that a gray alignment box has nothing in it, the alignment box should disappear and the rest of the cards shift to fill the space. (If English words are in the box, they should return to the word list, then the alignment box should disappear.)
    - [ ] If there are two Greek words in the same alignment box and if a user starts to drag one of them, a new alignment box should appear at the end of the verse (bonus points if it appears in the correct place in the verse order) with the blue "drop" box, so that the user can divide out two Greek words that have been bundled together. The alignment box would then jump to the correct place in the verse so that the Greek is in the correct order (as it shows up in the verse).
  - [ ] Note: The blue dashed "drop" box shows up for all alignment boxes irregardless of the presence or absence of words for that translation. Upon release, the blue dashes turn back to white for alignment boxes where there is no translation, if there are words, there should not be the white dashed "drop" box. In other words, there should never be a white dashed "drop" box with words inside it. 
  - [ ] If multiple words are dropped into the same alignment box, the user cannot determine the order within the box. The order will automatically be determined according to how it appears in the source. This is true for Greek as well as English.
  - [ ] Note: Greek words can only be conjoined to contiguous words (the words right on either side of it). 
  - [ ] Note: There will be no highlighting in this iteration of the Alignment Tool

**Comment by benjore** [comment]
https://github.com/unfoldingWord-dev/translationCore/wiki/Alignment-Tool-Plan

**Comment by benjore** [comment]
- [ ] The checkmark in the side menu appears only when the following 2 criteria are true:
  - [ ] All the English words have been used
  - [ ] All Alignment boxes have at least one Greek & one English word
