### ISSUE TITLE
Refactor the verbiage on the tools cards

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2264]
1. If we're not going to show any of the description on the basic card, then showing the word "Description" and the "See more V" doesn't make any sense.
2. If we are going to have tW parts 1 and 2, then is it proper for the description of part 1 to say "comprehensively check the meaning of all key terms"?

![image](https://user-images.githubusercontent.com/8171759/28579131-5eae4474-7121-11e7-9a1b-8851950f8379.png)

![image](https://user-images.githubusercontent.com/8171759/28579103-409c48a0-7121-11e7-9856-71320e104ae8.png)

**Comment by benjore** [comment]
- [x] Move "description" inside the "See More"
- [x] Remove "all" from the description
- [x] Change color of #% complete (see below)

## User Story

As a user, I want to be able to see the % complete even after I have surpassed 50%. 

## Details

When the % complete passes 45%, change the text `46%` (etc.) to white in the progress bar.

**Comment by benjore** [comment]
- Changes should apply to Alignment Tool card as well.

**Comment by richmahn** [comment]
- [x] [2] Change text and move description
- [x] [2] Change color of percent meter 
- [x] [4] Write until tests

**Comment by richmahn** [comment]
**Example floating percentage after 25%:**

![2017-11-09 4](https://user-images.githubusercontent.com/2839925/32615804-ecfd3162-c52d-11e7-83f4-29cb9c1d51f6.png)
![2017-11-09 5](https://user-images.githubusercontent.com/2839925/32615805-ed2a1fe2-c52d-11e7-890e-c3adec2954de.png)
