### ISSUE TITLE
App hangs when importing corrupted project

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2288]
I tried to import https://git.door43.org/benjore/sw_tit_text_ulb . The logo spun forever. 

- [x] Is there a way to catch this beforehand and prevent it from happening? Make it a part of the project import stepper?
- [x] Allow the user to cancel out

![image](https://user-images.githubusercontent.com/13352518/28602944-b44d4b22-7186-11e7-961e-51d1ea29f024.png)

**Comment by RoyalSix** [comment]
Just tested this project and got no errors

**Comment by mannycolon** [comment]
# Tasks 
- [4] implement a button to cancel project loading if it's taking too long.

**Comment by cckozie** [comment]
@benjore The app now catches the problem and issues a message, but my sense is that we want a message that is more meaningful to the user. What say you?
![image](https://user-images.githubusercontent.com/8171759/29670350-0a5894ae-88ac-11e7-9bed-22595d4d4b33.png)

**Comment by cckozie** [comment]
"Cannot clone repository" will not be meaningful to most users. Change the alert message to "This project has fatal errors and cannot be imported. Please contact help@door43.org for further assistance.”

**Comment by mannycolon** [comment]
# Tasks
- [3] Add button to cancel project loading if it takes too long.
- [2] Change "Cannot clone repository" alert message to "This project has fatal errors and cannot be imported. Please contact help@door43.org for further assistance.”

**Comment by RoyalSix** [comment]
- [ ] [3] Make catch all for loading errors to be displayed

**Comment by RoyalSix** [comment]
@benjore @cckozie I believe it will take about 3 hours to make a catch all for errors happening during the loading process. 
Theres many places it can fail, and its not entirely straight forward how to catch them all and display a nice dialog letting the user know and cancelling the load.
Do we want to do this? What I've done already is made an automatic cancel button for a project load that displays after 3 seconds.
What are the requirements?

**Comment by cckozie** [comment]
@benjore @RoyalSix 
In my opinion: A cancel option when loading projects is not a bad idea, but it is not a proper fix for the problem of the app hanging. We have no way of knowing how long any particular project will take to load on any particular machine. The typical user would probably just try to load it again after canceling. We need to inform the user that there is a problem with the project. Trapping the errors that cause the program to hang is the proper approach. I would normally expect that to happen as part of the project validation phase.
