### ISSUE TITLE
Rework Select mode

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2290]
I believe we need to rethink how we display the instructions and the verse in select mode. I think most new users will find it very confusing. Here are some of the major issues:
1. If not in Select mode, the instructions tell the user to select something when it is not possible to do so. Maybe modify them with something like "Click the Select button and then highlight the text that is the translation of ...........'.
2. Having the text and instructions bounce back and forth between the left and right panels is distracting and very confusing.
3. With the current implementation showing the ULB in the first scripture panel, selecting the text in the right panel is more difficult.
4. I think the verse text displayed when not in Select mode should be grayed so that it is more evident that it cannot be acted upon.

**Comment by benjore** [comment]
- [x] *When in Main mode...*
  - [x] The Scripture in the Action card should be a dark gray (same color as the Scripture reference)
  - [x] If nothing has been selected, the right side of the action card should say: 
`No selection has been made.`
`Click the Select button, then select the translation for this check.`
  - [x] If a selection has been made, the right side of the action card should remain the same. ("ABC has been translated as XYZ")
  - [x] If the verse is missing, the righthand side should say: 
`No selection can be made because the verse is blank. `
`You may fix this by editing the verse.`
`If desired, you may also leave a comment or bookmark this check.`


- [x] *When in Select mode...*
  - [x] The translation should stay on the left-hand side
    - [x] It should appear the same way as the Main Mode: 
      - [x] Language name on the top
      - [x] Bible reference underneath
      - [x] passage under that
      - [x] passage color should now be black
  - [x] The verbiage on the righthand side should say:
`Please select the translation for: [ABC]`
  - [x] If the verse is missing, the righthand side should say: 
`No selection can be made because the verse is blank. `
`You may fix this by editing the verse.`
`If desired, you may also leave a comment or bookmark this check.`

**Comment by klappy** [comment]
## Tasks: 
- [2] Select Mode: Evaluate UI expectations and determine if new behaviors needed
- [4] Select Mode: Update UI behavior and verbiage

**Comment by RoyalSix** [comment]
@benjore do we want the modal popup to work the same as in the main mode while in select mode?
