### ISSUE TITLE
Import from USFM overwrites an existing project without any warning

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2304]
I think we need to prevent importing a USFM project if it already exists in tC.
We will probably need to know the language of the USFM file in order for us to determine if does already exist. See issue #2303

**Comment by benjore** [comment]
- [ ] Prohibit importing

**Comment by RoyalSix** [comment]
## Tasks:
- [ ] [1:30] Detect usfm project that already exists in tC
- [ ] [1] Show dialog of importing already existing project
- [ ] [2] Prevent from importing project

**Comment by cckozie** [comment]
The alert should have the same text as when attempting to import a duplicate project from Door43.
![image](https://user-images.githubusercontent.com/8171759/29081790-24c123cc-7c29-11e7-8388-6b0fe2473376.png)

**Comment by cckozie** [comment]
beta.44
[eph_usfm.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1225283/eph_usfm.usfm.zip)
I had imported this project in a previous release, and it has the project name eph_usfm. I now tried to import it again to test the overwrite issue, and rather than giving me an error, it imported it again but this time with the project name of eph_usfm_ (It added the underbar at the end of the name). 
When I tried to import it again, I do get the proper error message.

**Comment by RoyalSix** [comment]
- [ ] [3] Check previously import projects on a basis of book/language or book/usfm(and language if available) combination for stopping duplicate imports

**Comment by klappy** [comment]
## Tasks
[2] Determine project name structure for consistency
[3] Rename all projects get renamed to bookId_languageId_[ulb|udb]
[2] Ensure projects are not overwritten
[4] Write tests for project importing

**Comment by cckozie** [comment]
@RoyalSix @klappy 
The original issue has been fixed. 
Since we didn't support USFM imports in earlier versions, I am going to pass this issue because the auto-renaming should not cause a problem. 
Any additional work needed for renaming or testing can be handled in the future.
