### ISSUE TITLE
Remove menu bar in the Stepper and make stepper steps clickable

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2309]
- [x] Remove menu bar in the Stepper
- [x] make stepper steps clickable 
- [x] Show selections in the stepper (username, selected project, etc.)
  - [x] Keep on the same line (e.g. User: benjore)
  - [x] Truncate if it runs into the next step

**Comment by benjore** [comment]
- [ ] Only steps that are clickable - currently completed steps and the current step (e.g. a user can't skip to Projects before logging in, etc.). Home button is always clickable.

**Comment by cckozie** [comment]
1. The menu bar has been removed, and the steps are clickable, but the selections (username, selected project, etc.) are not being displayed.
2. The out of sequence steps should not be clickable.

**Comment by cckozie** [comment]
1. When a logged in user opens tC and clicks "Get Started", on the home screen the Projects step is disabled but should not be. It does become enabled after clicking the Home step.
As opened:
![stepper1](https://user-images.githubusercontent.com/8171759/29827953-0cb3f772-8ca1-11e7-8020-37cf99e6a923.png)

After clicking Home:
![stepper2](https://user-images.githubusercontent.com/8171759/29827952-0c9e3f9a-8ca1-11e7-87c2-a9312b686613.png)

2. The selection are being displayed in the stepper bar, but the names are not being truncated if they run out of space. Instead, the tools step is pushed out of the window.
