### ISSUE TITLE
Update Core for DCS API v3 Resources

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2310]
- [x] Core: update references to new resources DCS API v3.
- [x] Create migrations to move old resources to new resources.
- [x] Extract DCS API v3 to submodule

**Comment by RoyalSix** [comment]
@klappy Can you add as much info as you can to how this one will be complete, sorry I'm a bit unfamiliar :/

**Comment by klappy** [comment]
Based on conversations, we can take the resource updating script and package that as a standalone repository that is self-contained and imports the resources directly in it. Then the app needs to be updated to look in this new location.

See the sample below that Manny uploaded:

**Comment by mannycolon** [comment]
[tC_resources.zip](https://github.com/unfoldingWord-dev/translationCore/files/1264337/tC_resources.zip)

**Comment by mannycolon** [comment]
[tC_resources.zip](https://github.com/unfoldingWord-dev/translationCore/files/1264347/tC_resources.zip)

**Comment by mannycolon** [comment]
![screen shot 2017-08-30 at 1 37 48 pm](https://user-images.githubusercontent.com/17072300/29886541-6e4f557a-8d88-11e7-9b70-365fbd5013ad.png)

**Comment by cckozie** [comment]
Only tested by performing an upgrade on a 0.7.0 installation and then opening some projects.
