### ISSUE TITLE
ProjectValidation: CopyrightCheck

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2353]
## Front End
- Create ProjectValidation CopyrightCheck component
  - ProjectValidation/CopyrightCheck Folder with index.js for main component
- ProjectValidation CopyrightCheck Instructions
- Create ProjectValidation CopyrightLicenceCard component
  - Icon, license id, license name, overview text.

## Back End
- CopyrightCheckReducer has an array of all valid copyrights and their data
  - Icon, license id, license name, overview text, path to license md
  - Find license file and overview paragraph of each license.
- CopyrightCheckActions
  - Saves current copyright in project manifest and LICENSE file.

**Comment by benjore** [comment]
- [ ] Public Domain / CC0 [the number `0`, not a capital `o`]
  - [ ] Use the (PD) icon
  - [ ] In the "See more" pop-up, it should say: 
Public Domain
No known copyright. 
CC0 Public Domain Dedication
[verbiage of the main headings + body of https://creativecommons.org/publicdomain/zero/1.0/ . Include this link at the bottom of the page.]
- [ ] Creative Commons Attribution (CC BY)
  - [ ] Use the [man] icon
  - [ ]  In the "See more" pop-up, it should quote: https://creativecommons.org/licenses/by/4.0/ and include the link at the bottom of the page. 
- [ ] Creative Commons Attribution-ShareAlike (CC BY-SA)
  - [ ] Use the [circle arrow] icon
  - [ ] In the "See more" pop-up, it should quote: https://creativecommons.org/licenses/by-sa/4.0/ and include the link at the bottom of the page. 
- [ ] None of the Above
  - [ ] Use the [prohibited] icon - same as in the mockups. 
  - [ ] In the "See more" pop-up, it should say, "Any project whose copyright status or license is something other than Public Domain, CC0, Creative Commons Attribution, or Creative Commons Attribution-ShareAlike."

**Comment by cckozie** [comment]
1. Reduce size of copyright icons by 35%
2. Left align all of the text on the copyright cards
3. Change the License names to be:
       CC0 / Public Domain      (it’s CC zero, not the capital letter "o")
       Creative Commons Attribution (CC BY)
       Creative Commons Attribution-ShareAlike (CC BY-SA)
4. After a box is checked, the user should be able to check a different one without first unchecking the selected one. (Normal radio button action)

**Comment by mannycolon** [comment]
# QA Tasks
- [1] Reduce size of copyright icons by 35% & left align all of the text on the copyright cards
- [1] Change the License names for the copyright check.
- [3] Change copyright check from check boxes to radio buttons.
