### ISSUE TITLE
Edit Project Details

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2416]
## User Story

As a user who has already imported a project, I want to be able to modify the project details so that I can correct any errors that were made during the project import check. 

## Requirements
- [x] In 3-dot menu add "Edit Project Details" with pencil icon
- [x] Display just the Project Info portion of the Project Import Stepper
  - [x] Two buttons: `Cancel` Which discards all changes and `Save Changes` which saves the changes and returns the user back to the projects step of the stepper.

**Comment by mannycolon** [comment]
# Tasks
- [3] Add to the project info card the option to open the project details modal
- [6] Make the necessary modifications to the project validation stepper to accommodate for the new project details option in the project card.

**Comment by mannycolon** [comment]
@benjore I thought that In another story we said we would use `cancel` and `continue` instead of `Save Changes` as label for the buttons

**Comment by cckozie** [comment]
@benjore Did you agree to the button text of "Continue" instead of "Save Changes"?

**Comment by cckozie** [comment]
Change the verbiage on the button from "Continue" to "Save Changes" as defined in the requirement.
