### ISSUE TITLE
Action Card verbiage clean-up

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2465]
- [x] The Card header in `Main Mode` should say, "Step 2. Check"
- [x] The card header in `Select Mode` should say, "Select"

Note: 
`Edit Mode` is correct "Edit Verse". `Comment Mode` is also correct "Comment".

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [1] Change UI Text For Select Mode
