### ISSUE TITLE
Project Import: Missing Verses Check

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#247]
# User Story

As a _user sideloading a translation project_, I want to _check that my translation is complete_, so that _I can be assured that my translation will work well in tC_.

# Definition of Done

- [ ] All missing verses & chapters are identified

**Comment by RoyalSix** [comment]
## Tasks:
- [ ] [2] Persist completion of missing verses check on projects
- [ ] [2:30] Perform missing verses check on new projects

**Comment by RoyalSix** [comment]
@benjore Should this be identified in a list thats showed to the user?

**Comment by cckozie** [comment]
Need to ensure that all missing verses are accounted for in the list.

**Comment by cckozie** [comment]
Covered by other issues.
