### ISSUE TITLE
Add a spinner or other method to indicate something is happening when searching for projects on Doo43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2474]
On a field grade Windows machine it takes a few seconds to return results, and on the first use during that time the "No project found..." message is displayed. There should be some indication to the user that something is happening during the search time.

**Comment by benjore** [comment]
Use the small spinner.

**Comment by PhotoNomad0** [comment]
- [ ] [4] - Add Spinner when searching and remove spinner when done. 
- [ ] [2] - Change message on search to indicate search is in process. 
- [ ] [2] - Add unit tests.
