### ISSUE TITLE
Use langnames.json in Project Import Stepper

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2528]
- [ ] No "refresh" option for now
- [ ] Create local copy - bake it into the app
- [ ] Requires an existing language

- [ ] Design
  - [ ] Make the `Language Name` and `Language Code` each a search box
  - [ ] If the user starts typing in either box, a drop down "type ahead" appears with matching options.
  - [ ] If searching by name, search for matches in the language name field. If searching in the code field, then search for matches in the code field
  - [ ] If a language & code is selected, both boxes are filled in with the selection
  - [ ] Entries must validate against langnames.json 

Source at https://td.unfoldingword.org/exports/langnames.json

Consider http://jedwatson.github.io/react-select/ for implementation.

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [16] Embed languages.json and add autocomplete
- [ ] [8] Add unit tests

**Comment by PhotoNomad0** [comment]
> Consider http://jedwatson.github.io/react-select/ for implementation.

Unfortunately this is not compatible with the styling we currently use with material-ui controls, but material-ui does have a SelectField control.

**Comment by PhotoNomad0** [comment]
@benjore - it looks like using selection boxes with 8000+ language items is going to be too slow (takes about 10 seconds to render the screen initially on a fast machine, and then 6+ seconds to display options, and another 6 seconds delay once item is selected).  Going to try using autocomplete, should be much faster.

**Comment by benjore** [comment]
@jag3773 Do you remember what we did with tD (or elsewhere)?

**Comment by jag3773** [comment]
Yes, OP mentions "type ahead"/"autocomplete" functionality, which is what we are looking for.  A simple select box will not work.

**Comment by PhotoNomad0** [comment]
@benjore @jag3773 - the autocomplete control in material-ui is sweet.  behavior is similar to ts where we get drop down menu with partial matches as the user types.

**Comment by PhotoNomad0** [comment]
@ben_jore @jag3773 - have a question about Language Name matching to langnames.json.  Do we want to match the ln field exclusively, or do we want to match the ang field also (english version)?

It looks like ts only shows the ln field.

**Comment by jag3773** [comment]
@PhotoNomad0 I think it would be good to match either if that's possible.

**Comment by PhotoNomad0** [comment]
Requirements of menu selection from @benjore :

1. They can't have the option of selecting a mismatching language and code. 
2. They should be able to search code, localized name, or anglicanized name
3. I'm not conceptually opposed to putting them all together, but it's impossible for me to "sign off" on it without seeing it.

**Comment by cckozie** [comment]
The sort for the items in the dropdown list should not be case sensitive. (I typed in "fran" and initially thought francais was not in the list of options. Eventually I noticed that it is, but it is at the bottom of the list after Zoque. I think that will be as confusing to our users as it was to me.)

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - I would maintain that this is technically this met requirements, and that this is a new requirement that this was failed under.

**Comment by cckozie** [comment]
@benjore Your call on whether this should be fixed now or a new issue created.
