### ISSUE TITLE
Projects with long names overflow off of the project card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2604]
And the select button moves off the card too.
![image](https://user-images.githubusercontent.com/8171759/29837373-8ebe189e-8cbd-11e7-8191-c479c5178532.png)

**Comment by benjore** [comment]
- [x] Truncate the file name
- [x] Show complete name on hover

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] Truncate the file name on overflow
- [ ] [2] Show complete name on hover
