### ISSUE TITLE
Reorder the result cards on the Door43 import search screen to match the search field order

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2605]
Also change the Language Id label to Language Code.

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [2] 2605 - Change language ID label to language code
- [ ] [2] 2605 - Change results cards to be title, user, language, book
- [ ] [4] Testing - 2605 - validate new order and new label?

**Comment by PhotoNomad0** [comment]
@cckozie - Have a question about the title on the result cards.  Where do we put that?  Do you want the title first (title, user, language, book) or last (user, language, book, title)?

**Comment by cckozie** [comment]
@PhotoNomad0 I think title, user, language, book would be the best.
