### ISSUE TITLE
Search for online projects does not return results

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2631]
.beta63
There are multiple French projects for Ephesians on Doo43, but tC does not return any results when performing that search.

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] Find Why Online Search Online Is Broken
- [ ] [3] Fix Online Project Search Methods

**Comment by cckozie** [comment]
The example in the first comment appears to be fixed, but the search still sometimes fails to return the correct result set. When no user is specified, this is the result:
![image](https://user-images.githubusercontent.com/8171759/32410123-51d31430-c187-11e7-982b-2394c24705d6.png)

When I add a different user I see that there is a project that did not get returned in the first search.
![image](https://user-images.githubusercontent.com/8171759/32410135-7fce1006-c187-11e7-8e8d-7543a8e2c3e6.png)

**Comment by mannycolon** [comment]
# Tasks
- [ ] [3] Improve door43 project search results

**Comment by jag3773** [comment]
@cckozie @mannycolon As I mentioned this morning in standup, some of this will be alleviated when we get DCS updated later this month.  Specifically, the API endpoint will be able to return more results, which will make the list on screen more accurate.

I would suggest not over-tuning this until we get the API endpoint fixed.

**Comment by cckozie** [comment]
I don't have a problem with delaying this, but do not want it closed until I can verify that it works correctly after the DCS update.

**Comment by cckozie** [comment]
The cited example does work correctly in 0.8.1-alpha.11
Putting it on hold until the API is updated.

**Comment by mannycolon** [comment]
@cckozie I already made it good enough it doesn't need to be on hold pending API changes. It should be good enough now with the changes I added.

**Comment by cckozie** [comment]
I'll reopen if there are still issues after the API update.
(But the dev does not get to decide when it is "good enough for now". That is the PO with and assist from QA.)

**Comment by mannycolon** [comment]
@cckozie When i said good enough it meant it matches what you were asking for it to display in the search results

**Comment by mannycolon** [comment]
and i said "should"

**Comment by mannycolon** [comment]
@cckozie 

"(But the dev does not get to decide when it is "good enough for now". That is the PO with and assist from QA.)"

that was not my intention.
