### ISSUE TITLE
Select GL

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2640]
## User Story

As a checker, I want to be able to select the Gateway Languages from which I want to check, so that I don't have to use English. 

- [x] Mockup for where to make the selection
- [ ] Display the GL that is in the manifest as the default option
- [ ] Test to see if we have the book/tool combos that will show up in the dropdown
- [ ] When a new language is selected, refresh the % complete
- [ ] The app should remember what GL was selected

**Comment by benjore** [comment]
![image](https://user-images.githubusercontent.com/13352518/34573243-323f4a44-f139-11e7-97a8-5fdb0efdddda.png)

![image](https://user-images.githubusercontent.com/13352518/34573286-5a80f6f6-f139-11e7-9490-a9fd541a3c20.png)


![image](https://user-images.githubusercontent.com/13352518/34573262-43b29f74-f139-11e7-99fb-d99fb999c8c5.png)




![image](https://user-images.githubusercontent.com/13352518/34573319-75f1cafa-f139-11e7-87ed-5393b93e361b.png)

**Comment by jag3773** [comment]
Looks good @benjore .  One suggestion would be to make the "Gateway Language" drop down have full opacity in the first mockup.  The way that mockup looks now it appears that the drop down list is disabled.

**Comment by benjore** [comment]
@jag3773 I updated the image. That look better?

**Comment by cckozie** [comment]
@benjore @jag3773 I think "Gateway Language" and the "V" for the dropdown should never look as though they are disabled.

**Comment by cckozie** [comment]
@benjore Which of the 5 items listed in the first comment above should I expect to see completed on this issue?

**Comment by cckozie** [comment]
The first item in the list is mostly complete, the others will be handled elsewhere.
I'm writing up a new issue to change the dropdown list frame and down arrow so that it doesn't look disabled. I see the same problem in the book selector for online imports and the locale selector. (Issue #3766)

**Comment by cckozie** [comment]
The design mockup shows "Gateway Language" as a label for the field. I'm not seeing that in the implementation. Instead I'm seeing "Gateway Language" as one of the selection options.

**Comment by benjore** [comment]
Note: In the build it says `Gateway Lanugage` instead of `Gateway Language` - This happens 3(+?) times.

**Comment by mannycolon** [comment]
@RoyalSix this is supposed to be in review not QA fail

**Comment by RoyalSix** [comment]
Ok my bad when you said it was a ```QA fail``` I thought you meant it was still in ```QA fail``` @mannycolon

**Comment by mannycolon** [comment]
@RoyalSix Its alright.
