### ISSUE TITLE
Get current Greek Lexicon working with the new UGNT

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2647]
- [ ] Persist UGNT ver 0 in resources submodule 
- [ ] Add failsafe so that the app doesn't crash is Greek is opened for a non-Titus project 
- [ ] Copy Lexicon from core folder to user folder

**Comment by klappy** [comment]
Add this data to the resources reducer as well
ResourcesReducer.lexicons

**Comment by klappy** [comment]
Tasks:
[3] UGL: Move Greek Lexicon data to Resources Submodule
[3] UGL: Add lexicon to Resources Reducer and Actions
[3] UGL: Change Greek Popover component to use Resources Reducer
[3] UGL: Test and debug potential issues
