### ISSUE TITLE
Automatically assign CC BY-SA to projects coming from Door43

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2711]
## User Story

As a Door43 user, I want tC to automatically assign CC BY-SA to projects that have no copyright explicitly mentioned in the manifest and imported from Door43 so that I don't have to figure it out myself or mis-represent reality

**Comment by mannycolon** [comment]
# Tasks
- [ ] [3] Write code to properly check and determine which projects need to automatically be assigned CC BY-SA
- [ ] [3] Add functionally to assigned CC BY-SA to projects coming from Door43
- [ ] [3] Write tests for project license checking
