### ISSUE TITLE
Cannot get to projects page

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2713]
beta.69
I started by deleting the translation/Core folder.
I started tC and imported several projects, some which caused errors when going through the stepper or opening the project.
Now I can no longer get to the projects page with this error in the console:
![image](https://user-images.githubusercontent.com/8171759/30559068-0681f1be-9c79-11e7-999e-4082c9e70554.png)

[projects.zip](https://github.com/unfoldingWord-dev/translationCore/files/1311846/projects.zip)

**Comment by benjore** [comment]
The app should not crash. We should tell the user what we know about the problem.

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [3] Gracefully handle project imports that have problems
 - May need to contact cckozie for the projects that caused the problem
- [ ] [2] Add tests to support new use cases for project imports

**Comment by RoyalSix** [comment]
Blocked until #3109

**Comment by RoyalSix** [comment]
- [ ] [1] Debug projects page bug to see if still problem

**Comment by cckozie** [comment]
I have not seen this problem since the import refactor was done.
