### ISSUE TITLE
Integrate new USFM3 parser into tC

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2723]
Release NPM package. 

Update tC Core to handle breaking API changes.

Use cases:
Importing USFM
Exporting USFM

Blocked on alignment based project
Exporting USFM3
Importing USFM3

**Comment by RoyalSix** [comment]
- [ ] [1] Publish module and update usfm package in tC
- [ ] [3] Update toJSON and toUSFM method uses in tC for usfm 3
- [ ] [3] Update usfm exporting to usfm3
- [ ] [4] Update usfm importing to usfm3
- [ ] [3] Update tests in the core to match new outputs/inputs

**Comment by cckozie** [comment]
Cannot open imported USFM projects.
Exporting a project to USFM creates an empty file.

**Comment by cckozie** [comment]
The problem of not being able to open successfully imported projects has been fixed in beta.86.
Exporting USFM still creates an empty file.

**Comment by RoyalSix** [comment]
Was fixed in #2190

**Comment by cckozie** [comment]
Export looks good in beta.91
