### ISSUE TITLE
Information on project validation stepper bar seems to not be consistent with the stepper page

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2811]
It appears that there are 3 states of the icons. I think it's confusing as to what they mean since blue seems to indicate both what steps have been done and the current step. My preference would be for blue to indicate what has been done, black to indicate the current step, and gray to indicate the remaining steps.

![image](https://user-images.githubusercontent.com/8171759/30990889-8a930988-a468-11e7-9b25-caa1cef08c49.png)

![image](https://user-images.githubusercontent.com/8171759/32281119-eca2cfee-beeb-11e7-8404-911eb625965c.png)

**Comment by mannycolon** [comment]
Replicate what we did in the home screen stepper. Basically starting from `0` instead of `1`

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] Start with correct index for project validation stepper
- [ ] [2] Add tests to check project validation stepper color / index

**Comment by cckozie** [comment]
@benjore 
Once I have gone through the stepper, loaded a project, then clicked "User" in the menu bar, the Project and Tool icons are gray just as they are before a project and tool have been selected. I would expect all of the icons to be blue at that point. Your thoughts?
![image](https://user-images.githubusercontent.com/8171759/32967022-a463fb8c-cba1-11e7-9369-26b7a8880226.png)

**Comment by cckozie** [comment]
All active (clickable) icons, except for the one for the current step, should be blue.

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] Make home stepper persistent.

**Comment by cckozie** [comment]
0.8.1-alpha.12-8a1618d
I'm not sure that this problem was caused by work on this issue, but all links in the menu bar now take me to the home screen instead of user, project, or tool.

**Comment by RoyalSix** [comment]
- [ ] [2] Fix Menu Icon Links
