### ISSUE TITLE
% complete not showing on Alignment tool card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2866]
beta.86
% complete always indicates 0

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [3] WordAlignment: Calculate % on new check
- [ ] [2] WordAlignment: Send % to menu side bar
- [ ] [1] WordAlignment: Send % to tool card
- [ ] [2] WordAlignment: Fix Saving On Population

**Comment by cckozie** [comment]
Held pending response to questions in #2873

**Comment by cckozie** [comment]
@RoyalSix I failed #2873 because we want the % to be calculated based on verses, not words. Will making the changes in that issue automatically change this one too, or will you also need to rework this one?
