### ISSUE TITLE
Alignment tool - Automatically scroll target area to the top when moving to new verse

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2867]
At first glance it looks like the target boxes are missing for some of the Greek because those boxes got scrolled out of the viewing area during work on the previous verse.

**Comment by bspidel** [comment]
# Tasks
- [ ] [2] Research React component life cycle 
- [ ] [1] Find place to make change
- [ ] [2] Learn how this is done elsewhere
- [ ] [1] Add command to scroll to top
- [ ] [1] pull request

**Comment by cckozie** [comment]
Tested in tC_Test_Alignment_Persistence.sikuli
