### ISSUE TITLE
Make it more obvious what to do after logging in when there are no existing project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2938]
It's not real obvious what the user is supposed to do (even tho it is on the instruction card). Maybe add a "Import Project" button in the middle of the screen similar to what we do in tS when the project list is empty.
![image](https://user-images.githubusercontent.com/8171759/31558670-7cd565e6-b013-11e7-83f7-cf9faa16219d.png)

**Comment by benjore** [comment]
In the gray space under `Projects` add "No projects have been found. Follow instructions at left to import a project."

**Comment by bspidel** [comment]
## Tasks
- [ ] [1] add clause if no projects
- [ ] [2] Add div below projects
- [ ] [3] Create test for branching 
## Test
1. Login to account with no projects
1. Note the hint
1. Add a project
1. Note hint is replaced by project

**Comment by bspidel** [comment]
![noprojects](https://user-images.githubusercontent.com/4968713/32818902-2e55b53e-c994-11e7-8afb-3d4af3b4caea.PNG)

@benjore Here is what I heard in this story, Is this what you wanted?

**Comment by richmahn** [comment]
Probably needs to be on a white background, like a card other things are on.
