### ISSUE TITLE
tC generated project names for USFM files are not consistent with tS

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2959]
1. tC format uses only language code and book code. Consequently, those projects imported into tS show with a blank book name and cannot be opened. Is that acceptable?
2. Do we need more information in the project name so that users can have multiple USFM imported projects for the same book/language?

See also #3037, #3038 

See the naming specification at https://git.door43.org/Door43/registry .

From #3037 : 

[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1437975/es-419_luk_text_ulb.usfm.zip)
When this project is imported to tC, it gets the name es_luk. That implies that the language is es (Spanish) rather than es-419 (Latin American Spanish).

#3038 

(The portion of this issue that deals with project naming is in issue #2959 and #3037 )
[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1438013/es-419_luk_text_ulb.usfm.zip)
1. Import this file into tC
2. Upload it to Door43
3. Import it into tS desktop (note that it gets a blank book name in tS)
4. Export it as a project file from tS (note that it gets an inappropriate name)
5. Importing the tstudio file into tC causes this to happen. (Same result regardless of whether the previously imported USFM project has be removed from tC or not)
![image](https://user-images.githubusercontent.com/8171759/32329898-6100c27c-bfac-11e7-973d-20545fd401c4.png)

[There is a lot more discussion on that issues.]

**Comment by benjore** [comment]
The USFM export from tC should have the same naming convention as tS uses. 

See the naming specification at https://git.door43.org/Door43/registry

**Comment by PhotoNomad0** [comment]
### Tasks
- [ ] [3] - research how we currently name USFM exports
- [ ] [3] - make USFM exports names standard
- [ ] [6] - add unit tests.

**Comment by PhotoNomad0** [comment]
Set as blocked - waiting to see if this issue has been fixed in https://github.com/unfoldingWord-dev/translationCore/pull/3369.

**Comment by cckozie** [comment]
The original intent of this issue was to name projects IMPORTED from usfm according to the convention used in tS. Somehow it got misinterpreted to standardize the naming of projects EXPORTED to usfm. That was not the problem since we allow users to change the exported file name.
I've added issue #3421 to deal with the original intent and will pass this one since we do now have standardized the way we name the imported usfm projects.
