### ISSUE TITLE
manifest.json file getting created in translationCore\Projects folder

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2980]
Sometimes importing projects (tstudio, I think) causes this file to get created and left in the projects folder.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [3] LocalTstudioImport: Research what exactly is wrong with .tstudio poroject import
- [ ] [3] LocalTstudioImport: Reaserch and plan an approach/implementation to solve the problem
- [ ] [3] LocalTstudioImport: Implement fix to local .tsutio import.
- [ ] [3] Local .tstudio Import: Write tests

**Comment by mannycolon** [comment]
By working on this story I added one line of code that fixed issue #2551 as well

**Comment by cckozie** [comment]
alpha.12
I'm not seeing this happen anymore, although I'm not completely sure what the use case was that was causing it. Passing it anyway.
