### ISSUE TITLE
USFM import allows importing a project that already exists

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3030]
Scenario 1: Import a project from Door43, then import a USFM project for the same book and give it the same language name and id of the Door43 project. The user is not warned that the project already exists.

[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1437919/es-419_luk_text_ulb.usfm.zip)
Scenaria 2: Import this project, go thru the validation stepper, and Launch it with the Alignment tool.
Go back to the projects page and re-import the same file. You will see that it now gets a different name, and that the scripture text is missing in its Projects folder.

**Comment by RoyalSix** [comment]
First scenario is resolved.
Second scenario should not even be allowed because opening a non-titus book in the alignment tool isn't possible.
I can make it so that this functionality it not allowed. What would be a good message to display?
@cckozie @benjore

**Comment by RoyalSix** [comment]
This was completed in #3056

**Comment by cckozie** [comment]
@RoyalSix I don't know if scenario 2 was related to Word Alignment or just that the project had been opened, as the tW tool was not available for testing at that time. In 0.8.1-alpha 1 I cannot import the file because tC thinks it is a duplicate when it's not. I also do not have any evidence that this couldn't happen to a Titus project.
In any case, we need to get to the underlying problem that causes the USFM import to give two different names to the same project.

**Comment by cckozie** [comment]
I think the problem is that going through the stepper causes the project's name to be changed. I'm putting this on hold until we have refactored the USFM import.

**Comment by cckozie** [comment]
0.8.1-alpha.13-7fb1c1f 
Scenario 1. is still broken
Scenario 2. is now fixed

**Comment by jag3773** [comment]
For scenario 1, see related user story at https://github.com/unfoldingWord-dev/translationCore/issues/3559 .

**Comment by cckozie** [comment]
0.8.1-alpha.17-fd2ffe9
I believe the usfm import refactor is done, so moving this from QA Watchlist to Fail.
Scenario 1. is still broken.
Scenaro 2. is fixed.

Scenario 1. in reverse order is also a problem. (Importing project first from USFM, then from Door43)
[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1741601/57-TIT.usfm.zip)
https://git.door43.org/tc01/English_tit

**Comment by RoyalSix** [comment]
# Tasks 
- [ ] [2] Find point in workflow to make check for existing project
- [ ] [2] Check for existing project
- [ ] [1] Show alert and don't allow import of existing project
- [ ] [2] PR Review

**Comment by cckozie** [comment]
Scenario 1. is still broken in 0.8.1-alpha.23-6d7614d

**Comment by RoyalSix** [comment]
How are you able to do this exactly? I am not able to repeat on the latest build.
I made a screen recording.

**Comment by RoyalSix** [comment]
@cckozie The project from `https://git.door43.org/tc01/English_tit` has the language code and the language id [swapped](https://git.door43.org/tc01/English_tit/raw/branch/master/manifest.json), therefore it is technically a different project than (en) English

**Comment by RoyalSix** [comment]
<img width="615" alt="screen shot 2018-03-12 at 3 39 06 pm" src="https://user-images.githubusercontent.com/16184018/37313237-87af0026-260b-11e8-9a09-163b533dc217.png">
