### ISSUE TITLE
tC tools do not handle missing verses correctly

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3057]
beta.96
[en_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1443575/en_tit.zip)
This project is missing verses 1:3 and 1:14.

Open the project in tW. 
Click on "command, commands..." in the menu.
Notice that the Select pane is still displaying 1:1.
Click on Titus 1:14 in the same group in the menu.
Notice that again the Select pane is still displaying 1:1.
Click back to Titus 1:3.
Click Cancel
Click Save & Continue
Click Skip
Notice that the selected verse in the menu changes, but the Attention dialog is still displayed
Click Cancel
Notice that nothing happens

## Specs
- [ ] The check needs to show the correct verse. In this case, it would be a blank verse.
- [ ] Clicking the cancel button (on save & continue) does not function properly. It should advance to the next check.

**Comment by cckozie** [comment]
0.8.1-alpha.13-17f8690
It looks like the problem has been fixed in tW, but Word Alignment displays the word list based on the resources ULB rather than the target text.
![image](https://user-images.githubusercontent.com/8171759/34360781-aabd725a-ea29-11e7-991d-73e1e87b0b04.png)

**Comment by cckozie** [comment]
If the ULB also is missing the verse, e.g. Matt 17:21, then the word list is empty as expected. But we need to make sure that the word list is based solely on target text, even if it is blank and the ULB is not.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [4] Debug and find problems causing bugs for missing verses in the tools.
- [ ] [3] Fix missing verses bugs in tC tools.
- [ ] [2] Cleanup

**Comment by cckozie** [comment]
This appears to no longer be an issues in  0.8.1-rc.6-4b73715 .

**Comment by cckozie** [comment]
The Word Alignment problem is an issue (again/still) in 0.8.1-alpha.13-65c49d1
![image](https://user-images.githubusercontent.com/8171759/34679436-9239ce9a-f45b-11e7-84b4-3fd12f4949a3.png)

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [3] Make word list empty if target bible verse is missing
- [ ] [3] Write tests
- [ ] [2] PR Review

**Comment by cckozie** [comment]
Both issues appear to be fixed in 0.8.1-alpha.26-61679a7. Moving it to QA Done.
