### ISSUE TITLE
The alignment tool reports missing verses as being complete

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3059]
beta.96
[fr_tit_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1443621/fr_tit_text_ulb.tstudio.zip)
This project is missing 1:1. When opened with the alignment tool, the verse has the check mark.
@benjore How do we want to handle this?

**Comment by benjore** [comment]
- [ ] Green checkmark is only given when: all words in word bank are used + all Greek are aligned to something

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [10] Fix WA tool progress
- [ ] [5] Unit tests
- [ ] [5] PR Review for [3059]

**Comment by da1nerd** [comment]
@PhotoNomad0 fyi I've already been working on the wA tool progress as part of the wA migration. Also a LOT of the wA tool has been completely rewritten. I just haven't submitted a PR yet.

@jag3773 did  you mean to re-assign this task?

**Comment by PhotoNomad0** [comment]
Blocked until Joel finishes WA rewrite.

**Comment by PhotoNomad0** [comment]
@cckozie - Looking at translationCore 0.10.0-a90d7b8 (Travis build #7934). It looks like it is fixed now.
