### ISSUE TITLE
Invalidated Checks

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3086]
## User Story

As an aligner, I want to be able to update my translation and only re-aligning what has changed so that it saves me time and keeps me from discouragement. 

As a checker, I want to be able to edit my translation and know which checks have been invalidated and have to be redone.

## Notes
- [ ] If there is an invalidation, the alignment for the whole verse is reset. (If the text for the verse is different.)

![image](https://user-images.githubusercontent.com/13352518/34791960-24d0d210-f60c-11e7-86d7-8a1d37879ac4.png)

![image](https://user-images.githubusercontent.com/13352518/34791970-2da91582-f60c-11e7-80ba-57ea9dbab1e1.png)

![image](https://user-images.githubusercontent.com/13352518/34791975-33e4b712-f60c-11e7-9c92-a2bf7faa137e.png)

![image](https://user-images.githubusercontent.com/13352518/34791982-3ad355d8-f60c-11e7-9db8-d6da985d8c27.png)

**Comment by PhotoNomad0** [comment]
@benjore - can you verify my understanding (listed below) of the logic for the display of badges? 

#### Notes:
- Badges (only show one at a time):
  - bookmark badge - show if bookmark - remains until removed?
  - comment badge - show if comment set - remove when comment is removed?
  - broken link badge - show if verse has been edited after checking, cleared when new selection is made?
  - check badge - show if checked and no bookmark, no comments, and verse has not been changed since last edit
  - no badge - if not checked and no bookmark, no comments

**Comment by richmahn** [comment]
My issue, #3676, is what displays the Badges @PhotoNomad0 . I even have an invalidated icon all set up for this issue which I spent a lot of time on yesterday. This issue just needs to make a .json like we have for verseEdits, reminders, etc. is updated when ever a verse is edited which changes text that was either highlighted in tW or aligned in wA. We need to be able to know all at once for a whole project what verses are invalid. Right now we only look when a user clicks on that verse in the group menu.

**Comment by richmahn** [comment]
@PhotoNomad0 To hook this up to what I did, the contextIdReducer needs to have a boolean named 'invaludated' set to true like we do with contextId.reminders, contextId.comments, etc.

**Comment by richmahn** [comment]
Used here: https://github.com/unfoldingWord-dev/translationCore/blob/7532881e43329eebecf1c1bfc2653f3fa578a3c8/src/js/containers/GroupMenuContainer.js#L117

**Comment by richmahn** [comment]
Screen shot of what is already in place (This is from my branch, but I forced the invalidated boolean to be true for a few):

![2018-04-05](https://user-images.githubusercontent.com/2839925/38385926-6ab91f38-38d0-11e8-99f9-72a5e1bec647.png)

**Comment by PhotoNomad0** [comment]
Dependent on https://github.com/unfoldingword-dev/translationcore/issues/3676.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [5] Update TW tool to set invalidate flag
- [ ] [5] Unit tests
- [ ] [5] PR Review for [3086]

**Comment by PhotoNomad0** [comment]
@benjore - Question:  In WA tools when verse is invalidated, we currently reset the alignments.  Should  we also flag all checks in the verse as being invalidated?

Answer: no

**Comment by PhotoNomad0** [comment]
@benjore - Question: when we do an usfm3 import, should we be checking each verse for changes and invalid selections before we open the tW tool.

Answer: On tw open, we recheck all alignments.

**Comment by PhotoNomad0** [comment]
Notes:
- Tool actions that need to be intercepted:
  - action for edit verse: editTargetVerse()
  - action for changed selection: changeSelections()
  - check if selections are still valid in a target verse: ~validateSelections()~ changeSelections()
- tCore calls that need to be intercepted:
  - resetVerseAlignments()

- Also need to verify all checks for the verse on edit.

- current selections are loaded by loadSelections()

**Comment by cckozie** [comment]
0.10.0-7f20ffa 
I'm not seeing the text about the invalidation in the instructions pane for a check that was invalidated by an edit performed in the alignment tool. 

![image](https://user-images.githubusercontent.com/8171759/39656455-82b21aca-4fc5-11e8-9e65-4e8db11bcae9.png)

**Comment by cckozie** [comment]
@PhotoNomad0 This is what is in the mockups that I am not seeing:
![image](https://user-images.githubusercontent.com/8171759/39826083-30316492-5379-11e8-9824-5f9e3f38f51b.png)

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [5] Update TW tool to display selection invalidated text.
- [ ] [5] Unit tests
- [ ] [5] PR Review for [3086]

**Comment by benjore** [comment]
@PhotoNomad0 Also note the invalidated icon that shows up in the blue bar (next to the other icons). The invalidated icon never shows up transparent (like the other icons) - it is either there in white, or completely gone. 

This will cover #4442

**Comment by PhotoNomad0** [comment]
@cckozie - discussed this with Ben: since the current tooltip component we use does not natively support grey backgrounds, we are implementing invalidated popup with black background such as:

![screen shot 2018-05-18 at 9 55 54 am](https://user-images.githubusercontent.com/14238574/40239816-24777cd2-5a85-11e8-9435-76580e3de272.png)

**Comment by PhotoNomad0** [comment]
Blocked waiting for https://github.com/unfoldingWord-dev/translationCore/issues/4318

**Comment by PhotoNomad0** [comment]
Still need to fix showing invalidated on default verse.  See this problem when you have selected an invalidated verse in tw, exit tool, and reopen tw tool.  new branch to fix in UI toolkit: feature-mcleanb-3086/ShowInvalidatedSelection.5

**Comment by PhotoNomad0** [comment]
~Localization is still not in for invalidation warning.~

Localization is in now.

**Comment by PhotoNomad0** [comment]
@cckozie - you should be able to test this now.
