### ISSUE TITLE
Add full morphological data

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3087]
## User Story

As a checker or aligner, I want to see the full morphological information (rather than the code) in the lexical pop-up so that I can easily understand and not misinterpret the data. 

## Specs
- [ ] This should be included in the app localization wordlist.
- [ ] There is an extra field of data in the 12th position that is not represented in the chart. It should be as follows: 
  - [ ] `I` = `Indeclinable`
  - [ ] `D` = `Diminutive`
  - [ ] `C` = `Comparative` 
  - [ ] `S` = `Superlative`

**Comment by benjore** [comment]
@jag3773 Can you explain what needs to be done? Do you have the secret decoder ring to how to interpret the morphological data?

**Comment by jag3773** [comment]
Description of the codes starts on page 43 of https://greekcntr.org/downloads/project.pdf .

**Comment by benjore** [comment]
This is the answer key: 
<img width="613" alt="screen shot 2017-12-19 at 9 37 37 am" src="https://user-images.githubusercontent.com/13352518/34164901-6cfbed9a-e4a0-11e7-8094-326a883aba14.png"><img width="610" alt="screen shot 2017-12-19 at 9 37 48 am" src="https://user-images.githubusercontent.com/13352518/34164906-706fc7a8-e4a0-11e7-8f4f-c42e006d3314.png">

So if you get a morphology that looks like this: 
![screen shot 2017-12-19 at 9 39 58 am](https://user-images.githubusercontent.com/13352518/34164994-afb3abd2-e4a0-11e7-9ada-341817f89f32.png)
It should show up like this: 
`Noun, Genitive, Masculine, Singular`

![screen shot 2017-12-19 at 9 46 19 am](https://user-images.githubusercontent.com/13352518/34165317-862e16e8-e4a1-11e7-885f-6d0e5a155dcd.png)
Should show up: 
`Verb, Indicative, Aorist, Active, 1st, Singular`

## Specs
- [x] The initial `Gr` (Greek) should not be displayed
- [x] All "pieces" should be separated by a comma, the first letter of each should be capitalized, and there should be no boldface for any of them. 
- [x] If a field is blank, nothing should be displayed for it (e.g. there should never be `, ,`)

**Comment by richmahn** [comment]
- [ ] [1] Build word list in localization file
- [ ] [3] Write converter for Morphological string
- [ ] [3] Have lexicon card use morphological converter
- [ ] [2] Test case for Morphological converter and lexicon card
- [ ] [1] PR Review for #3087

**Comment by PhotoNomad0** [comment]
Verified in build https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-5ebb84f.setup.exe

**Comment by cckozie** [comment]
1.0.2 (5ebb84f)
There are missing translation keys
![image](https://user-images.githubusercontent.com/8171759/47722601-c8c1ac00-dc20-11e8-9c5f-e868d18f0795.png)

![image](https://user-images.githubusercontent.com/8171759/47722630-d4ad6e00-dc20-11e8-9da8-b15e25801f76.png)

**Comment by richmahn** [comment]
Isn't this something for Crowdin to provide?

**Comment by richmahn** [comment]
Ok, now has Hindi translations and the English substantive_adj key fixed.

**Comment by cckozie** [comment]
1.0.2 (f3e86ca) 
It looks like the translation key problem has been fixed.
However, when the user has wA open and then changes the locale, the language is changed in the Greek popup in the alignment area, but not in the scripture pane. If the project is reopened in the tool, then the proper language appears in the popups in both places. 

![image](https://user-images.githubusercontent.com/8171759/47865130-6821a300-ddc9-11e8-9f9b-c55bb68bd459.png)

![image](https://user-images.githubusercontent.com/8171759/47865238-aae37b00-ddc9-11e8-919c-c19a3fadcbe3.png)

**Comment by cckozie** [comment]
1.0.2 (f3e86ca)
It looks like the translation key problem has been fixed.
I am moving the problem in the previous comment to a new issue since it was an existing bug (#5361).
