### ISSUE TITLE
There should be a cancel option when uploading to Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3155]
The user should have the option to cancel the upload.

**Comment by richmahn** [comment]
- [ ] [2] Add cancel button to Door43 Upload
- [ ] [2] Write test to verify Door43 Upload cancel button & test functionality
- [ ] [1] PR Review for #3155

**Comment by richmahn** [comment]
Put this on the backburner since no seeable way to stop the download/clone process once it has been triggered. Would need a different way to handle (git) processes so they can be killed.
