### ISSUE TITLE
Dynamic Source Content Update

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3175]
## User Story

As a user, I want to be able to update the source content (resources) in the app so that I don't have to wait for, download, and install a new release just to update tC's resources. 

## Specs
- [ ] This feature needs to find and give the opportunity to update: 
  - [ ] New/updated UI strings
  - [ ] New/updated books of the Bible + versions of the Bible (e.g. aligned UST + ULT, unaligned Bibles)
  - [ ] Updated tHelps 
- [ ] This feature will be implemented in conjunction with opening up the whole NT to the tW tool. Incorporated in this feature is making the app smart enough so that if a new book is imported, that book will become available for checking. This applies both to making a new book available in a GL that is currently in tC as well as adding a book in a GL that is new to tC. 
  - For example, if the NT gets opened, but Romans in English has not yet been aligned, checking for Romans will not be possible. But if Romans gets aligned and a user updates their source content, then a Romans project should be able to be opened (assuming all other dependencies are met). 

## Notes
- For a GL to show up in the dropdown list of the tool card for tW, there must be at least one aligned translation in that GL for that book + translated tW. 

## Breakdown
- L - UI Strings Update system - Deferred
- ~~M - API Endpoint - create new spec/tC endpoint POSTPONED~~
- - ~~[4] SPIKE: Research about the tC API Endpoint~~
- Develop NPM module to:
 - L - Design UI with Mock Data 
      - Select subset of new or updated resources
  - M - Write a helper function to Fetch Catalog
  - L - Write a helper function to Parse Catalog
  - M - Differentiate between Latest and Current Resources, which are newer resources, which need to be updated
  - M - Write helper function that gets list of resources to display UI that shows all resources that are not current
  - M - Write helper function to Retrieve selected resource
  - M - Write helper function to Parse USFM3 data into json (Converting) 
  - M - Write helper function to Generate translation helps data 
  - M - Write helper function to move resources to target locations (Source Importing)
  - M  - Write code to figure out which language should be displayed in the tool dropdown based on available book/tool/language combo
  - L - Drop tc_resources sub module

## Questions
- Spike  - Figure out versioning/packaging of GL packages 
- Does the project need to know which version of the GL package it is using?
- Do we want to add a `GL_selection` attribute so that updated GL selections can automatically invalidate those verses? 
- How do we want to handle content data in the app (from the install) verses content in the user folder, and where does dynamic update content go? 
- Do we want to pivot to downloading zipped files? 
- How do we get UI strings updates downloaded to the core and then updated to the tools?

## Notes from April

* Bundle zip of resources with app installer
* Extract resources to user directory
* Allow user to download updates which overwrite the data in the user directory
* Also allow user to select newly available content
* Drop tc_resources sub module
  * Implement as a npm package that updates or gets new content
  * Process the source content at runtime

## NEED
* Minimum requirements for a checking tool: aligned `default_literal` translation + required tH (e.g. tW for tW Tool, tN + tA for tN Tool, etc.
* to differentiate in the code between original languages, aligned ULTs (part of GL), other GL texts, and Target Languages.))

**Comment by benjore** [comment]
![image](https://user-images.githubusercontent.com/13352518/35885410-559b577e-0b53-11e8-86d9-432bf9c1d2d0.png)

![image](https://user-images.githubusercontent.com/13352518/41996291-088ed6b4-7a1a-11e8-9af8-e29556d79f46.png)

![image](https://user-images.githubusercontent.com/13352518/35885509-aad4cd60-0b53-11e8-893e-0b583cfd1d57.png)

![image](https://user-images.githubusercontent.com/13352518/35885514-b0b213dc-0b53-11e8-93e0-ac48eca3b680.png)


Per @cckozie and @benjore on slack:
For unsuccessful download of the `Dynamic Source Content Update`  use the following as alert message 'Failed to download source content updates.' 

Also, It would probably be good to put 'Retry' and 'Cancel' options on the alert. If the failure was caused by no Internet connection, then that alert should be used instead of a custom one for this issue.

**Comment by da1nerd** [comment]
Here's a diagram of the proposed architecture.

![dynamic update](https://user-images.githubusercontent.com/166412/41997014-93f220d0-7a0b-11e8-8758-1d66d0b0d6c9.png)

**Comment by da1nerd** [comment]
Or here's a fancier version built with https://mermaidjs.github.io/

![graph](https://user-images.githubusercontent.com/166412/42004512-f114d1ae-7a24-11e8-9262-c7953ac24b3a.png)

**Comment by jag3773** [comment]
@benjore Has noted that we will need to support side loading local resources, which means we will need local code to handle some conversion/ingestion steps.  This is *part* of the reason for differing server side pre-processing of the catalog.

**Comment by da1nerd** [comment]
With side loading in mind we'll likely have a separate UI (minimal compared to the UI for downloading) and converter (maybe). Here's a **separate** process for side loading.

![output](https://user-images.githubusercontent.com/166412/43665997-dd775bf2-9726-11e8-9e9c-2508b8fb3f6d.png)

Depending on the format of the imported file we may have a separate `Converter`. The `Importer` will the same in both cases.

**Comment by PhotoNomad0** [comment]
@benjore - how do we support if there is more than one bible in a language?  The UI above has no way of selecting between various bibles in a language (e.g. ULT and UST updates for English).  Current plan I believe is to bundle by bible in catalog.

**Comment by benjore** [comment]
@PhotoNomad0 All of the resources for a language would come down together (e.g. UST, UDT, tW, tN, tA, etc.). We tried splitting it out, but it gets too complicated. So, from the user's perspective, it will all come together per language. From the dev's perspective, if you can see that the of that bundle only the UDT updated, then you're fine to just download that resource.

**Comment by PhotoNomad0** [comment]
~@benjore - to be clear.  It looks like we are using anglicized language name in the prompt - at least for now.  Is this correct?~

Answer: We will be using localized language name from the translationDatabas and language code.

**Comment by PhotoNomad0** [comment]
@benjore - When we update a new version of a resource, do we remove the older version(s)?
 
Specifically for example if we have a new v12.2 bible, do we remove the older v12.1 bible?
