### ISSUE TITLE
Display any user project in Scripture Pane

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3179]
## Story

As a translator who is working on multiple translation projects at the same time, I want to display multiple projects in the Scripture Pane at the same time so that I can see how different dialects dealt with the verse in question. 

## Specs 
- [ ] Any project that has been imported into tC should be able to be displayed in the Scripture Pane (only for that book). 
- [ ] Current functionality: user can load target project + projects from Catalog
  - [ ] New functionality: user can load any project in tC (that matches that book)

## Issues
- [x] (M) Identify the list of available resources (all projects with that book available locally)
- [x] (L) Support for project in Scripture Pane settings (persistence, error handling for if the project is removed)
- [x] (L) Populate resource reducers with Other projects
- [ ] (S) Update the UI to differentiate items on the list between projects and resources (add "User Project")
