### ISSUE TITLE
GL Alignment Data Export from tC as Target Language Project to USFM 3 File

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3185]
- GL Alignment Data Export from tC as Target Language Project to USFM 3 File
  - tC Helpers: Combine Target Verse String and Alignment Data to Verse Objects
  - USFM.js: Verse Objects to USFM 3 conversion
  - Add Export to USFM 3 in Projects three dot menu

**Comment by klappy** [comment]
[8] USFM3 Export: Tests for Combine Target Verse and Alignment Data to Verse Objects
[8] USFM3 Export: Helper to Combine Target Verse and Alignment Data to Verse Objects
[4] USFM3 Export: Release and update USFM.js with Verse Object support
[4] USFM3 Export: Add Export to USFM 3 in Projects three-dot menu with Tests

**Comment by PhotoNomad0** [comment]
#### Additional tasks:
- [ ] [4] - update usfm-js to handle alignment data output. milestones containing attributes for strong and ugnt.
- [ ] [8] - update app from using `strongs` to `strong` 
- [ ] [6] - Update unmerge for real world alignment data.

**Comment by RoyalSix** [comment]
- [ ] [2] Auto-export alignment data on DCS upload, file chooser for normal export

**Comment by cckozie** [comment]
0.8.1-alpha.15-633b904 
No Export to USFM3 in 3 dot menu, so unable test the rest of it.

**Comment by PhotoNomad0** [comment]
#### Known issues:
https://github.com/unfoldingWord-dev/translationCore/issues/3756 - Fix issues with USFM3 alignment export:
  * verse markers are not at beginning of line 
  * unaligned chapters are not included in the output

**Comment by cckozie** [comment]
I think the export is working, but can't really tell until the import has been fixed.

**Comment by cckozie** [comment]
Checking with @benjore to see if "Export Word Alignments" is acceptable rather than "Export to USFM 3".

**Comment by cckozie** [comment]
@benjore 
USFM 2 exported file name defaults to the project name, e.g. en_eph.usfm.
USFM 3 exported file name defaults to the name of the originally imported file name, e.g. 50-EPH.usfm.
It seems like it would be better to use the project name in both cases. What say you?
Also, it looks like we remove all (or most) of the line feeds when exporting to USFM 2 so the exported file is not formatted very well for anyone looking at it.

**Comment by jag3773** [comment]
File name *must* always match 50-EPH.usfm pattern, following the examples at https://git.door43.org/Door43/en_ulb . Line breaks *must* also match what is show in those files.  Usually it's 1 line per verse for USFM2 or 1 line per word for USFM3.

**Comment by cckozie** [comment]
Make the following changes as seen in the 2 preceding comments:
1. USFM2 and USFM3 exports both need to use the same naming convention as specified above; e.g. 50-EPH.usfm
2. Line breaks need to be added back into the USFM2 exports as was previously the case. Line break on each verse, chapter marker, etc. as in https://git.door43.org/Door43/en_ulb

**Comment by PhotoNomad0** [comment]
> Line breaks need to be added back into the USFM2 exports as was previously the case. Line break on each verse, chapter marker, etc. as in https://git.door43.org/Door43/en_ulb

@cckozie - This was a known issue mentioned above.  This is being addressed in: https://github.com/unfoldingWord-dev/translationCore/pull/3868.  The problem is that older USFM imports had all whitespace stripped out and newer imports do not.  So added special check on USFM export so that newlines are added between verses if they are not present in the json data.

Working on item 1 now.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [x] [2] Fix naming of USFM export
- [x] [2] update tests
- [ ] [2] PR Review

**Comment by cckozie** [comment]
Issue 1. has been fixed.
Issue 2. has been fixed with the possible caveat of multiple words sometimes on the same line in USFM3 exports. See question left on #3756.
Waiting for USFM3 import to be finished so that I can test round trip of USFM3 file.

**Comment by cckozie** [comment]
Cannot round trip usfm3 file.
Export USFM3 from a project that contains alignment data
Import the exported USFM3 file
Export USFM3 from the newly imported project. The exporting alignments dialog hangs.

Project file:
[English_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1791167/English_tit.zip)

Exported USFM3 file:
[57-TIT3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1791170/57-TIT3.usfm.zip)

**Comment by PhotoNomad0** [comment]
Testing:
1. exported project and got same USFM3 as Kos (except date).
2. cleared project and imported project from USFM3 
3. do another USFM3 export and see error thrown at on tit 2:16:
      throw Error(`The words "${verseWordsJoined}" from the target language verse are not in the alignment data.`);

The original project only has 15 verses for titus 2, but on USFM export we expect 16.

**Comment by PhotoNomad0** [comment]
Looks like a bug in USFM3 import that we don't clear alignments for each chapter so we had extra alignments.

**Comment by cckozie** [comment]
0.8.1-alpha.24-ffc2bed
1. I don't know if this is an export, import, or changed verse detection problem, but doing a round trip using usfm3 causes the first verse to get reset because the app thinks there has been a change in the text. The test was run using the English_tit.zip file above.
2. App hangs when exporting USFM3 of partially aligned project.
[en_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1807524/en_tit.zip)
![image](https://user-images.githubusercontent.com/8171759/37351545-54378602-26a9-11e8-9947-3a61f6d8ff81.png)

**Comment by PhotoNomad0** [comment]
@cckozie - Have a PR to fix generateBlankAlignments is not a function.

**Comment by cckozie** [comment]
0.8.1-alpha.25-8a82d4e
The problems noted above regarding export of the en_tit projects have been fixed.

Now the app hangs on USFM3 export of this project.
Not sure if this will be handled by work on #3850 or not.
[en_act.zip](https://github.com/unfoldingWord-dev/translationCore/files/1819544/en_act.zip)

![image](https://user-images.githubusercontent.com/8171759/37526319-008031f2-28fd-11e8-8692-9749e6381e97.png)

**Comment by PhotoNomad0** [comment]
Yes, This should be handled in #3850

**Comment by cckozie** [comment]
Waiting for #3850 to get to QA
