### ISSUE TITLE
Import aligned English Titus, GL Aligned Bibles Import from D43 Resource Catalog as USFM 3 to tC_Resources

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3188]
Import the aligned USFM3 file of the English ULB/UGNT book of Titus.

## Notes

The Titus alignment that we have is not complete.  What we have is uploaded in the project at  https://git.door43.org/pjoakes/English_tit.

However, the text changes that occur in [this commit](https://git.door43.org/Door43/en_ulb/commit/25f4d045b0dbf1e5b33f90306559249a90c3fe86) need to be made in that project above (possibly manually?).  If they need to be made manually please work with @jag3773 to let him know which files in the project need updated to fix this.

Also, note that the USFM3 file probably will not be in the Door43-Catalog by the time this task is ready to be worked, that component is not an essential part of this.

## Parts

- GL Aligned Bibles Import from D43 Resource Catalog as USFM 3 to tC_Resources
  - tC_Resources: Convert USFM 3 GL Aligned Bibles to Verse Objects
  - tC_Resources: Store GL Aligned Bibles as Verse Objects

**Comment by PhotoNomad0** [comment]
Test Process:
- imported project above
- exported aligned data as USFM3
- uploaded aligned USFM (57-TIT.usfm) to https://git.door43.org/photonomad0/AlignedUlb_en
- now to develop script in tc_Resources to process.

**Comment by jag3773** [comment]
@PhotoNomad0 Were you able to fix the text?  Or are you bypassing that for now?

**Comment by PhotoNomad0** [comment]
#### Tasks: (IN PROCESS)

- [ ] [4] - Modify Script to import English Aligned ULB
- [ ] [5] - update scripture pane to support clicking on ULB resource to show words.
- [ ] [5] - update tc to support clicking on ULB resource to show words.
- [ ] [4] - PR Review

**Comment by PhotoNomad0** [comment]
@jag3773 - Just writing down the steps I have been taking to try to get my mind around tasking this out.  This is all prototype.  Sandbox build worked well generating the USFM3 aligned files.  And discovered that the scripts can process the USFM3 aligned files to resources in verseObject format.  The updated ULB displays in scripture pane, but Discovered that there is work to be done to show the strongs notes when clicking on the words in ULB resource.

**Comment by PhotoNomad0** [comment]
[English_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1712626/English_tit.zip)

@jag3773 - here are the corrections

**Comment by PhotoNomad0** [comment]
Created a temporary repo for the aligned ULB USFM files at https://git.door43.org/photonomad0/AlignedUlb_en.  Exported the corrected English aligned file and uploaded there.

**Comment by PhotoNomad0** [comment]
Was decided to use v12.1 for new resource since this is a beta of Titus alignment.  All other files have same content as last release.
