### ISSUE TITLE
GL Alignment Data from D43 Resource Catalog via USFM 3

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3189]
## User Story

As an aligner, I want to be able to upload my alignment data as USFM3 so that I can get it in the API and bring it back (eventually) into the tC app. 

## Specs
- [ ] Include Selection data in the USFM3 alignment file such that it can seed the Alignment Tool. 
- [ ] `Upload to Door43` - this needs to upload all checking data as it currently is & include alignment data in USFM3 format
  - [ ] Put alignment data in the root of the project
- [ ] Local `Export Alignment Data as USFM3`
- [ ] Add support for importing a USFM3 source from API
- [ ] Add support for importing a USFM3 target from DCS
- [ ] Reference for data structure: https://github.com/unfoldingWord-dev/translationCore/wiki/Alignment-Data-Structure:-USFM-3

The following changes are needed once the USFM.js library preserves and supports parsing/generating USFM 3 text/punctuation outside of word markers. It is dependent on the changes to the USFM.js library.

- GL Alignment Data Export from tC as Target Language Project to USFM 3 File
  - tC Helpers: Combine Target Verse String and Alignment Data to Verse Objects
  - USFM.js: Verse Objects to USFM 3 conversion
  - Add Export to USFM 3 in Projects three dot menu
- GL Alignment Data Import as Target Language Project from USFM 3 File
  - USFM.js: Improved USFM 3 to Verse Objects
  - tC Helpers: Split Verse Objects to Target Verse String and Alignment Data
- DCS Upload of Alignment Data as USFM 3 file in root
  - tC Actions: Snapshot USFM 3 to project root prior to uploading to Door43 
- GL Aligned Bibles Import from D43 Resource Catalog as USFM 3 to tC_Resources
  - tC_Resources: Convert USFM 3 GL Aligned Bibles to Verse Objects
  - tC_Resources: Store GL Aligned Bibles as Verse Objects

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [3] Include Selection data in the USFM3 alignment file such that it can seed the Alignment Tool.
- [ ] [3] Put alignment data in the root of the project
- [ ] [4] Local Export Alignment Data as USFM3
- [ ] [3] Add support for importing a USFM3 source from API
- [ ] [3] Add support for importing a USFM3 target from DCS

**Comment by RoyalSix** [comment]
# Tasks
- [x] [2] GL Alignment Data from d43: Review process of implementation
- [ ] [4] GL Alignment Data Export from tC as Target Language Project to USFM 3 File
- [ ] [4] GL Alignment Data Import as Target Language Project from USFM 3 File
 - [ ] [4] GL Aligned Bibles Import from D43 Resource Catalog as USFM 3 to tC_Resources

**Comment by cckozie** [comment]
Moving this to QA Watch because there are still several incomplete issues under it.
