### ISSUE TITLE
Error Handling Verse Changes and Alignment Data

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3193]
There are a few use cases that can cause Alignment Data to be broken and cause issues for the Alignment Tool. Basically any change to either language in the alignment. If the Primary (ie. Greek BHP) or the Target Language (ie. English GL) changes, it will cause problems for the Alignment reducer, for both Word Bank and the Alignments.

There is a related issue that somewhat affects this one. When a GL that is being aligned as the target language needs to update the text, how does that update this project? There are some high-level decisions to be made that are out of scope. Editing in tC makes this easier and simplifies the workflow. But that would add a complexity of its own. (See #3086 )

This does not appear to have any blocking dependencies.

## Notes
- Invalidate alignments where words no longer exist.
- Invalidate alignments where occurrences change.

- WordAlignment: Validate previous alignments in case of changes
  - WordAlignment: Handle change in Primary Language
  - WordAlignment: Handle change in Gateway Language

**Comment by benjore** [comment]
If a word has changed in either the Greek or the GL (target), then the whole verse should be reset.

**Comment by RoyalSix** [comment]
Regenerate alignments on tool open

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [4] Alignment Data Errors: Create helper to find verses that are invalidated
- [ ] [2] Alignment Data Errors: Create helper to clear invalidated verses back to original
- [ ] [2] Alignment Data Errors: Write tests
- [ ] [2] Alignment Data Errors: PR Review

**Comment by RoyalSix** [comment]
@benjore Do we want an alert when this happens? Such as the one for invalidated selections.

**Comment by RoyalSix** [comment]
Notes from meeting 
Alert that says dialog changed and just change them
Any change renders invalid
Updated approach, maybe use an array instead of a string to compare
```
[{
word:string
occurence:number,
occurences:number,
}]
```

**Comment by PhotoNomad0** [comment]
@RoyalSix - Adding notes from Slack

> Chris Kosieracki [18 minutes ago]
> I believe that is what was decided... warning that alignments for the verse will be reset without option to cancel. @ben_jore Do you agree?
> 
> Bruce McLean [17 minutes ago]
> What we have now is that alignments are reset and then the user is alerted.
> 
> Ben Jore [16 minutes ago]
> That is correct.
> 
> Ben Jore [16 minutes ago]
> We already have similar functionality in the tW tool when a selection is edited.
> 
> Chris Kosieracki [14 minutes ago]
> The message text should indicate that the alignments have been reset rather than will be.

If we just make the change to reset after the user hits OK, then I think this is good to go.

**Comment by cckozie** [comment]
The warning message is displayed even if there were not existing alignments for the verse that was changed (there was nothing to reset). The message should only be displayed when the verse has changed and there were previous alignments for the verse.
