### ISSUE TITLE
tW/tN: Alignment Prediction - WordMAP

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3195]
## User Story

As a checker who has to check the same thing over and over, I want tC to pre-populate suggestions based on previous work so that I can save time. 

## Specs 
- [ ] Suggestions are made when
  - [ ] The user navigates to a new check (and is taken to the `Select` mode)
  - [ ] The user navigates away from `Select` mode and then goes back to `Select` Mode
  - [ ] The user clicks the `Refresh` button
- [ ] Suggestions
  - [ ] Suggestions are always in green
  - [ ] If the user hovers over a green highlight for 0.5 seconds, display the pop-over
  - [ ] If the user clicks on the suggestion, this accepts the suggestion and the highlight turns to yellow. 
    - [ ] If there are discontiguous suggestions, clicking on one suggestion will only accept that suggestion. (Note: This is the only use case when green & yellow highlights will be on the board at the same time.)
  - [ ] If the user selects a word (that is not suggested) either by double clicking or dragging, all remaining suggestions are removed. 
- [ ] `Clear` button
  - [ ] If the user clicks `Clear`, all suggestions and all selections are cleared
- [ ] `Refresh` button
  - [ ] If there are no suggestions on the board, the `Clear` button becomes a `Refresh` button. 
  - [ ] If the user clicks the `Refresh` button and there are suggestions, the suggestions appear in green and the button becomes `Clear` again. 
  - [ ] If the user clicks the `Refresh` button and there are no suggestions, a toast should appear that says `No new suggestions.` (Just like the wA tool.)
- [ ] `Cancel` button
  - [ ] If at any time the user clicks the `Cancel` button, all changes or selections are disregarded and the user is taken back to `Check` mode. 
- [ ] `Save` button
  - [ ] If the user clicks `Save` all suggestions and selections are saved. 
  - [ ] If there are no suggestions or selections on the board, `Save` is inactive
    - [ ] The only exception is when the `No selection needed` checkbox is checked (see below)
- [ ] `?` button
  - [ ] If the user clicks on the `?` button, the pop-over shows the instructions. 
- [ ] If the user checks `No selection needed`
  - [ ] all suggestions and selections are cleared, 
  - [ ] the `Refresh` button is disabled, 
  - [ ] the `Save` button is activated (even though nothing is suggested or selected) 

## Mockups
[#3195 WordMAP in tW.pdf](https://github.com/unfoldingWord-dev/translationCore/files/2681905/3195.WordMAP.in.tW.pdf)

![image](https://user-images.githubusercontent.com/13352518/47180623-93df5c00-d2e6-11e8-80b2-130a266d815f.png)

![image](https://user-images.githubusercontent.com/13352518/47180642-9b066a00-d2e6-11e8-9f3a-b0d6f2934fe7.png)

![image](https://user-images.githubusercontent.com/13352518/47180650-a0fc4b00-d2e6-11e8-8481-0a6e60004cd5.png)

NOTE: If there is a yellow highlight on the board, the "no selection needed" should be disabled. 
![image](https://user-images.githubusercontent.com/13352518/47180656-a5286880-d2e6-11e8-94cc-294828d54d23.png)

![image](https://user-images.githubusercontent.com/13352518/47180661-a9548600-d2e6-11e8-8f09-8a644a045770.png)

![image](https://user-images.githubusercontent.com/13352518/47180668-af4a6700-d2e6-11e8-95c7-885137e88f46.png)

==========

For tN/tW tools...

Alignment prediction is a long ongoing feature that can be started with less complexity with a good return on investment. Without using complex data analysis, we can simply use past saved alignments to search for potential matches and use them. For example, if God in the GL language is commonly aligned to the same Primary language, and the respective forms appear in both GL and Primary languages, it can be used as a prediction. This should help reduce repetitive alignments.

Furthermore, different forms of the same root word/lemma could be leveraged when the specific form had not been used. This is likely to be the next big increase in prediction matches as the Primary languages use many forms of the same words. It may be worth noting that taking this approach from the beginning may be the best way. This reduces the need for a refactor of the first approach to support the second.

There are no known blockers for starting work on this.

- [13] Alignment Prediction: Explore UI changes for suggestions vs. manual/confirmed alignments
- Alignment Prediction: Leverage Saved Alignments to prepopulate alignments (needs design)
  - [8] Alignment Prediction: SPIKE: Research approach for searching saved alignments
  - [13] Alignment Prediction: Implement searching saved alignments
  - [13] Alignment Prediction: Implement predicting alignments from search results
- Alignment Prediction: Add support for lemma/strongs as an alternative lookup
  - [8] Alignment Prediction: SPIKE: Research approach for searching with lemma/strongs
  - [13] Alignment Prediction: Implement searching with lemma/strongs

**Comment by benjore** [comment]
Jan 2017: 

Ludhiana Feedback: "When we select a particular Key Term in one reference, if the same KT occurs in the other references, those should get highlighted automatically (instead of going each verse and selecting them)"

"Need some way to select the root word and not with all the inflections."

**Comment by benjore** [comment]
Question: Should the button say `Refresh` or `Suggest`?
