### ISSUE TITLE
Truncate full name of translation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3210]
![image](https://user-images.githubusercontent.com/13352518/32902876-2b99a9e2-cab9-11e7-8c57-ec0d1fde9462.png)

- [ ] The `Bunning Heuristic Prototype` should only take one line in the Scripture Pane. 
- [ ] If a title like this goes too long truncate it
- [ ] If truncated, a hovering over the text show give a pop-over that has the complete title
