### ISSUE TITLE
Project Import: Retrieve Online project

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3228]
To include:

* [x] Validate URL, some conversion cases to account for:
  * [x] Strip whitespace
  * [x] Convert https://git.door43.org/katalakay/English_tit to https://git.door43.org/katalakay/English_tit.git
  * [x] Convert https://live.door43.org/u/katalakay/English_tit/ to https://git.door43.org/katalakay/English_tit.git
  * [x] Convert https://door43.org/u/katalakay/English_tit/ to https://git.door43.org/katalakay/English_tit.git
* [ ] Git clone

**Comment by richmahn** [comment]
- [ ] [2] Import - Code import action
- [ ] [3] Import - Code URL verification helper
- [ ] [1] Import - Test for import action
- [ ] [2] Import - Test for URL verification helper
