### ISSUE TITLE
Residual text is displayed when changing texts in scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3230]
This occurs in tW. Word Alignment just displays a blank screen.
This could be due to a missing verse in https://git.door43.org/TC_SAVE/abu_tit_text_reg
Start with these texts in the scripture pane:
![image](https://user-images.githubusercontent.com/8171759/32964251-34ad4fea-cb98-11e7-8047-eecdef768e01.png)

Delete the Abure text to get this result:
![image](https://user-images.githubusercontent.com/8171759/32964282-4eb7dcb6-cb98-11e7-8770-cc4e4131f93c.png)

Add back the Abure text to get this result:
![image](https://user-images.githubusercontent.com/8171759/32964308-6751d330-cb98-11e7-8d6e-cb4259ecad99.png)

Delete the Greek text to get this result. Note that we now have two Abure texts, one with the ULB text for the verse, and one with empty text:
![image](https://user-images.githubusercontent.com/8171759/32964344-88a785e8-cb98-11e7-83f0-9299a89283a0.png)

This error is displayed in the console after deleting the Greek.
![image](https://user-images.githubusercontent.com/8171759/32964620-6e4f991e-cb99-11e7-88ee-392659ded0f9.png)

**Comment by richmahn** [comment]
- [x] [2] Figure out & Fix missing verse ScripturePane error
- [x] [2] Write test for ScripturePane missing verse
- [x] [1] PR Review for #3230

**Comment by cckozie** [comment]
This is no longer a problem in 0.8.1-alpha.13-65c49d1

**Comment by richmahn** [comment]
Closing since no longer a bug.
