### ISSUE TITLE
Project Import: Convert USFM Project and Import it to imports folder

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3232]
Input: usfm file
Output: tc project folder

**Comment by mannycolon** [comment]
# Tasks
- [ ] [1] SPIKE: Meet with klappy and the team to discuss USFM stories
- [ ] [8] write helpers to import and convert a USFM project.
- [ ] [8] generate a manifest.json for USFM project 
- [ ] [8] Write tests for USFM import process

**Comment by cckozie** [comment]
0.8.1-alpha.13-1042daa
[en-x-demo1_php_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1560220/en-x-demo1_php_text_reg.usfm.zip)
1. Blank Alert dialog and console errors when importing USFM.
![image](https://user-images.githubusercontent.com/8171759/34006278-54558e80-e0c3-11e7-8865-ab49db778e7f.png)
2. USFM import does not support leading zeros in chapter markers. All verses show as missing. 
0.8.1-alpha.13-4ef6c94
[en_EPH_Ephesians-A.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1564056/en_EPH_Ephesians-A.usfm.zip)

**Comment by mannycolon** [comment]
- [3] Research why some usfm projects fail to import in tC.
- [5] Fix USFM project import bug.
- [6] Add support to USFM for leading zeros in chapter markers.

**Comment by cckozie** [comment]
Works on the Sandbox build.
