### ISSUE TITLE
Project Import: Project Migration Module

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3235]
Needs broke down into smaller parts, to include at least:

* [ ] (M) Identify project’s tC version number (somehow), previous manifests don't have version number.
* [ ] (M) Upgrade .x projects to latest version
  * [ ] Filesystem structure
  * [ ] Manifest updates
* [ ] (S) Add latest version number to manifest.json file

**Comment by klappy** [comment]
## Notes:
- Version of USFM.js as updates to it may change project data. This may be implied with tC version.
- Each migration is standalone, could be named after timestamp or tC version/release.

## Path needs chosen:
- Each migration is chained together and picked up where needed.
  - Pros: only new migrations needed, old ones need less maintenance.
  - Cons: each migration isn't standalone.
- Each migration updates to latest version of tC
  - Pros: each one is stand alone and updates to latest.
  - Cons: each one needs maintained after each new migration is added.

**Comment by RoyalSix** [comment]
## Notes
1. There are many different iterations of tC projects that are drastically different architecturally.
   - How can we document these types and label them as a certain type and from there run the appropriate migration.
   - Is there a way to find the data we need from old versions, not worry about the specifics but all projects can go through a sort of catch all migration (without losing data) and officially make it a tC project starting a version 1 (1 can be exchanged with the latest build number) right now
2. The lowest tStudio type we are supporting is 11 or greater.
   - Knowing this we will not have to worry about migrations happening in the manifest, or parsing (locating) tS target language data
   - Knowing this should projects like [this](https://git.door43.org/royalsix/Import-From-TS/src/master/manifest.json]) should not have to be supported because it was originally from a manifest not supported.
3. tC Generated Manifest
   - Unfortunately when tC manifest generation was created (the implementation is still like this) we did not assign it with a number corresponding to when it was created. the only Information we have is when it was last changed (from git).
   - The creation date of the project or even the manifest is not a good indicator of a projects version even if it was made by tC because the manifest and project data are changed independently.
   - **It may also be important to note that 90% of projects that have been created(or updated in tC upon opening) have the same manifest at the time of creation and it will never be changed.**
      - It may be possible to use this for versioning but it will have edge cases.
      - May be good to use injunction will another indicator.
The only things a tC project <em>really</em> needs:
 - Manifest with:
   - target language id
   - target language name
   - project id
   - project name
 - tS chunk type folders with scripture files
 - OR USFM with the above information
 - OR tStudio zip with above information

## Scope Of The Story
1. Should we even think twice about opening a project that have a manifest version field below 11.
2. Should we make an attempt to open a project if we can find the right things (TBD)? 
   - These things may be updated in the future and supposedly the only things that tC needs.
   - If we can find these things then technically we can migrate it to the current version and add that as a new version number

**Comment by RoyalSix** [comment]
What is the official tC latests manifest version ?

**Comment by RoyalSix** [comment]
@jag3773 @klappy @benjore @mannycolon Thought you guys might want to see the conversation I have been having with myself as well as the question above

**Comment by cckozie** [comment]
One of the child projects is still in review.

**Comment by RoyalSix** [comment]
Completed in #3367 and #3245

**Comment by cckozie** [comment]
Holding until issue #3366 is fixed.

**Comment by cckozie** [comment]
#3366 is now fixed.
