### ISSUE TITLE
Project Import: Prompt for missing project details (lang name, code, etc.)

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3238]

**Comment by richmahn** [comment]
- [ ] [3] Import - Component to prompt for missing details
- [ ] [3] Import - Helper to handle missing details
- [ ] [2] Import - Test component for missing details
- [ ] [2] Import - Test helper for missing details
