### ISSUE TITLE
Mock Migration Module

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3245]
* [ ] Add any migration methods that currently exist
* [ ] Return as if success

**Comment by RoyalSix** [comment]
## Tasks:
- [ ] [2] Make Mock Migration Method Into Import Workflow
- [ ] [3] Add Existing Migration Methods
