### ISSUE TITLE
Finish importing projects

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3246]
## User Story

As a user I want to be able to finish importing a project after I start it so that I don't lose any work that may have been done and have to restart the project from scratch. 

## Specs

- [ ] A new menu item in the FAB only when there are incomplete project imports in the import folder, "Finish importing project"
- [ ] When clicked, a list of projects in the import folder appears
- [ ] When a project is selected from the import folder, the project import continues from where it left off.

**Comment by klappy** [comment]
## Tasks:
[4] Resume Import: Create new FAB menu item for "Finish Importing Project" with tests
[8] Resume Import: Replicate Local Project Import as "Finish Importing Project" with tests
[8] 
...

**Comment by cckozie** [comment]
Superseded by #3347
