### ISSUE TITLE
Pull in the UGNT (with linked tW)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3273]
This is needed to get the tW tool working with aligned data. 

Text is available at https://git.door43.org/Door43/UGNT .

- [ ] Pull in the latest text
- [ ] Rename the Greek Text from BHP -> UGNT (Unlocked Greek New Testament)

UGNT `master` branch includes tW links for the following books as of 2017-12-28:

* Galatians
* 1 Thessalonians
* 2 Thessalonians
* 1 Timothy
* 2 Timothy
* Titus
* Philemon

**Comment by benjore** [comment]
- [x] Blocked until Larry Sallee has completed the manual review

**Comment by jag3773** [comment]
Titus is available at https://git.door43.org/Door43/UGNT/src/master/57-TIT.usfm

**Comment by jag3773** [comment]
Check with @jag3773 before actually pulling this in so that I can verify we have all the completed books merged into the `master` branch for tC to pull in.

**Comment by benjore** [comment]
Note: ensure that the tW attribute is in the verse object

**Comment by PhotoNomad0** [comment]
#### Tasks

- [ ] [4] Determine what to do with k-s tags (new verse object format)
- [ ] [6] Update usfm-js to support k-s tags
- [ ] [3] Unit tests for usfm-js to support k-s tags
- [ ] [2] PR Review forusfm-js changes
- [ ] [2] Update resources with UGNT
- [ ] [2] PR Review for Updated resources changes
- [ ] [4] Update app to use new UGNT resources
- [ ] [3] Unit tests for tC app to use new UGNT resources
- [ ] [2] PR Review for tC app changes

**Comment by cckozie** [comment]
0.8.1-alpha.14-a0bd340 
There are two separate issues:
1. The app does not properly handle existing projects that had the BHP as a resource displayed in the scripture pane. (It also assigns the BHP to newly imported projects)
![image](https://user-images.githubusercontent.com/8171759/35233819-d113a7bc-ff64-11e7-9d76-15291667fde6.png)
2. Unable to merge Greek words

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - To clarify on opening old projects that were using BHP.  What is desired behavior here?  Do we just automatically switch to UGNT in the greek pane and update the manifest?

**Comment by cckozie** [comment]
@PhotoNomad0 That would be my recommended action. Would that cause any issues in projects that were aligned using the BHP?
@benjore Any other ideas on this?

**Comment by benjore** [comment]
@PhotoNomad0 @cckozie What Koz said is correct, namely, we want everything automatically shifted over to the UGNT. There are no changes with the text itself, only the metadata at this point. So there shouldn't be any problems with invalidated alignments or checks.

**Comment by cckozie** [comment]
Can merge Greek words (issue #2) in  0.8.1-alpha.14-1820928  on Windows.
Issue #1 is still failing.
