### ISSUE TITLE
ScripturePane: Highlight words in Aligned GL via highlighted Primary Language quote

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3302]
As a user, I want the tW to be highlighted in the Greek and all aligned translations in the Scripture Pane so that I can instantly see how that tW was translated. 

- In the Scripture Pane in tW tool. 
- Dependent on #3204 for the Greek highlight
- Dependent on #3188 for GL highlight

#### More dependencies: 
- [x] https://github.com/unfoldingWord-dev/translationCore/issues/3963
- [x]  https://github.com/unfoldingWord-dev/translationCore/issues/3964
- [x] https://github.com/unfoldingWord-dev/translationCore/issues/3925
- [x] https://github.com/unfoldingWord-dev/translationCore/issues/3920

**Comment by klappy** [comment]
@mannycolon: Here's another brain dump of my thought process for this one.

First, the Greek UGNT highlighting. In theory, the tW tool will be using a new set of data generated from the UGNT that bases the checks from the Greek occurrences of words. This means that the contextIds now include Greek UGNT quotes and no longer include English ULB quotes. So the first thing that needs to happen is allow the Greek words to be highlighted from the contextId, since we use to limit that to the ULB.

Second, the English ULB highlighting. The updated English ULB includes USFM3 milestones that embed the alignment to the Greek. These milestones will need to be leveraged to see if their attributes, whether strong or content matches that of the Greek UGNT quote. If any of the milestones' content(text) and/or strong and occurrence number match that of the contextId's Greek/UGNT quote and/or strong and occurrence, then we need to highlight the VerseObjects nested inside of the children attribute of the matching milestone.

**Comment by jag3773** [comment]
> Second, the English ULB highlighting. The updated English ULB includes USFM3 milestones that embed the alignment to the Greek. These milestones will need to be leveraged to see if their attributes, whether strong or content matches that of the Greek UGNT quote. If any of the milestones' content(text) and/or strong and occurrence number match that of the contextId's Greek/UGNT quote and/or strong and occurrence, then we need to highlight the VerseObjects nested inside of the children attribute of the matching milestone.

*Note:* I would strongly recommend that we only use the `content` field for highlighting.  If we attempt to use Strong's numbers we will run into false positives very quickly.

**Comment by klappy** [comment]
@jag3773 Thanks for that input! We thought it might be more resilient than the content since the content might change from time to time. It is good to know before we did this that it could cause more harm than good.

**Comment by benjore** [comment]
## Note: 
- The title of the check shows up in three places (side menu, check info card, tHelps)
- The GL word/phrase being checked shows up in two places (highlighted in the Scripture Pane, spelled out in the check card)
- The Greek word/phrase being checked should be highlighted, but should not appear anywhere else.
- Once selected and the user clicks `Save`, the Target Language selection should show up 4 places (spelled out in the side menu, highlighted in the left side of the check card, spelled out in the right side of the check card, highlighted in the Scripture Pane)

![image](https://user-images.githubusercontent.com/13352518/36269458-db48e0ac-123e-11e8-9d9c-059737a2e432.png)

![image](https://user-images.githubusercontent.com/13352518/36269435-d148e8b8-123e-11e8-8e5e-335adf5c6c7a.png)

**Comment by mannycolon** [comment]
#### This is a list of checks that are currently missing the highlighting for Greek and/or ULB because either the alignment data from the Greek to the ULB  is missing and/or misaligned (Titus project)

#### Have gaps not fixable because English word order is different than Greek:
- ~chosen one, chosen ones~
     - ~1:1~ - gap not fixable because English not in same order as greek
- ~holy, holiness~
     - ~Titus 3:5 (ugnt)~ - looks good
- ~life, live, lived, lives, living, alive~
     - ~1:2~ - gap not fixable because English not in same order as greek
     - ~3:7~ - gap not fixable because English not in same order as greek
- ~power, powers~
     - ~1:9~ - gap not fixable because English not in same order as greek
- ~God the Father, heavenly Father, Father~
     - ~1:4~ - gap not fixable because two different words tagged

#### Words missing due to Program bug not showing alignment to multiple greek words (issue https://github.com/unfoldingWord-dev/translationCore/issues/3925):
- [ ] exhort, exhortation 
     - [ ] Titus 2:15 - Program bug not showing alignment to multiple greek words
- [ ] God
     - [ ] Titus 2:5 - Program bug not showing alignment to multiple greek words  
     - [ ] 2:11 - Program bug not showing alignment to multiple greek words 
- [ ] godly, godliness
     - [ ] Titus 2:12a - Program bug not showing alignment to multiple greek words 
- [ ] grace, gracious 
     - [ ] Titus 3:15  - Program bug not showing alignment to multiple greek words
- [ ] Savior, savior 
     - [ ] Titus 2:10 - Program bug not showing alignment to multiple greek words  
     - [ ] Titus 3:6 - Program bug not showing alignment to multiple greek words
- [ ] Testimony, testify 
     - [ ] 1:13 - Program bug not showing alignment to multiple greek words
- [ ] word of God, words of God, word of Yahweh, word of the Lord, scripture, scriptures
     - [ ] 2:5 - Program bug not showing alignment to multiple greek words 
- [ ] world, worldly
     - [ ] Titus 2:12 - Program bug not showing alignment to multiple greek words 

#### Words missing (task https://github.com/unfoldingword-dev/translationcore/issues/3963)
- discipline, disciplines, disciplined, self-discipline
     - [ ] 1:8 - alignment doesn't work because tC is not highlighting controlled under category, due to typo in the UGNT.

#### Alignments combined (task https://github.com/unfoldingword-dev/translationcore/issues/3964)
- [ ] God
     - [ ] 1:1 - combined - due to bug in TW generating script

#### Errors due to UGNT aligned to wrong occurrence (issue https://github.com/unfoldingWord-dev/translationCore/issues/3920):
- [x] command, command 
     - [x] 1:3, 
     - [x] 1:14
disciplined.
- [x] everlasting, eternal, eternity
     - [x] 1:2b
- [x] faith
     - [x] 1:1
- [X] fool, fools, foolish, folly
     - [X] Titus 3:3 - Program bug not showing alignment to multiple greek words
- [X] good, goodness 
     - [X] Titus 3:8 swapped
- [X] pure, purify, purification
     - [X] 1:15a,b
- [X] save, saves, saved, safe
     - [X] 2:11

*** revised 2/28/2018

**Comment by mannycolon** [comment]
The user doing the aligning couldn't tell which occurrence of the word they were highlighting causing the following to happen.

![screen shot 2018-02-21 at 2 49 46 pm](https://user-images.githubusercontent.com/14238574/36502072-c9c9adca-1716-11e8-84b7-adda6d978ab6.png)

![screen shot 2018-02-21 at 2 50 11 pm](https://user-images.githubusercontent.com/14238574/36502091-d05d6b0e-1716-11e8-8719-fd486d305319.png)

**Comment by jag3773** [comment]
@mannycolon @benjore We want to fix this but we don't have a method to do fix it.

If you can manually make the adjustments I'd be happy to jump on a call and explain what goes where.

**Comment by cckozie** [comment]
I think the wrong "the" is being highlighted in this verse
![image](https://user-images.githubusercontent.com/8171759/36698177-cceb0516-1b0e-11e8-8e29-908a400d4cf5.png)

**Comment by mannycolon** [comment]
@cckozie This is a data issue. not implementation issue.
The user miss aligned it in the wordAlignment tool

**Comment by mannycolon** [comment]
> @mannycolon @benjore We want to fix this but we don't have a method to do fix it.
If you can manually make the adjustments I'd be happy to jump on a call and explain what goes where.

@jag3773 What do you mean?

**Comment by cckozie** [comment]
@mannycolon Where can I find the actual data that is displayed in this project so that I can verify that the implementation is correct?

**Comment by cckozie** [comment]
I think there may be some alignment problems.
There is no GL highlighting for the following:
discipline ἐγκρατής in 1:8
exhort παρακαλέω in 2:15 (possibly intentional)
God in 1:1 - the first occurrence of "of" is highlighted, the second isn't

This one matches the data but looks strange:
![image](https://user-images.githubusercontent.com/8171759/36820305-d62c581e-1cb2-11e8-8a07-3eda657dcd61.png)

**Comment by cckozie** [comment]
The highlighting does not appear to match the data in the following:
faith 1:1 - ULB indicates occurrence 1 of "the", occurrence 2 is highlighted
fool 3:3 - ULB indicates occurrence 1 of "were", occurrence 2 is highlighted
pure 1:15 - There are multiple instances of καθαρός in the Greek. It doesn't seem like the highlighting matches the ULB, but I'm not really sure. Related to that, there are two instances of θεός (God) in 1:1, and in tW both instances in the menu are highlighted. For pure in 1:15, each of the instances are highlighted separately in the menu. I believe that behavior should be consistent, either highlight them in the menu individually, or all together.
Stopping the checking at this point.

**Comment by cckozie** [comment]
There is a problem with the ULB text displayed in the following:
Last phrase should be "so that God's word may not be insulted."
![image](https://user-images.githubusercontent.com/8171759/36819792-742e9836-1cb0-11e8-9a10-c23008cb5cf9.png)

Same problem for God in 2:11, godliness in 2:12, grace in 3:15, the appearance in 2:13, everyone in 3:2, Savior in 3:6
I suspect there are more similar problems, but I think that should be enough examples to figure out what's causing the missing words.

**Comment by PhotoNomad0** [comment]
Blocked by https://github.com/unfoldingWord-dev/translationCore/issues/3925

**Comment by cckozie** [comment]
0.8.1-alpha.22-21f62ad 
ULB highlight missing in Titus 1:8 for hyphenated words
![image](https://user-images.githubusercontent.com/8171759/37293093-5a992038-25e0-11e8-9c85-dbf6247851e8.png)
![image](https://user-images.githubusercontent.com/8171759/37293162-8930f68c-25e0-11e8-9657-e8d52c4a521c.png)

**Comment by cckozie** [comment]
Multiple occurrences are displayed as same check.
![image](https://user-images.githubusercontent.com/8171759/37294926-f645f44e-25e4-11e8-9242-36928707c962.png)

**Comment by cckozie** [comment]
I think the display of highlighting is wrong on this one, but am not sure that it isn't an alignment problem.
![image](https://user-images.githubusercontent.com/8171759/37296156-17f484c2-25e8-11e8-9857-1cae46c91efa.png)

**Comment by cckozie** [comment]
Please be sure to look at my last 3 comments.

**Comment by PhotoNomad0** [comment]
@cckozie - this is working now with translationCore 0.8.1-alpha.22-1c7652b, the previous build did not have the latest resources.  The ULB above had the typo "ἐνκρατῆ", which has now been updated with "ἐγκρατῆ";

**Comment by cckozie** [comment]
@PhotoNomad0 The problem with self-controlled has been fixed, but I'm still seeing the other two example problems in 0.8.1-alpha.23-222cfb1.

**Comment by PhotoNomad0** [comment]
@cckozie @mannycolon - in 0.8.1-alpha.24-ffc2bed:
- the God Titus 1:1 issue is still there even though the ULB has been fixed.  Looks like a scripture pane bug not recognizing occurrence number of English word.
- the God Titus 2:11 issue is fixed in this build

**Comment by cckozie** [comment]
The last 2 noted problems have been fixed.
