### ISSUE TITLE
translationWords: Cleanup defunct code & fix linting errors

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3303]
- There shouldn't be any linting errors
- Cleaning up defunct code includes going through methods and making sure they are all call, if not remove them.

**Comment by richmahn** [comment]
- [x] [3] Cleanup defunct code for tW
- [x] [1] Verify linting errors are all fixed for tW
- [x] [2] Write simple test to increase test coverage for tW
- [x] [1] PR Review for tW code cleanup

**Comment by cckozie** [comment]
I don't know if it was specifically caused by work on this issue, but there is a bug now in tW that prevents some selections from being made.
[53-1TH.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1717580/53-1TH.usfm.zip)
Import this project and open it with tW.
Click on the "brother, brothers" menu option
In verse 3:2 double click the word brother, then click Save
You will receive the "Some selections are invalid..." message and will not be able to save the selection. No errors in the console.

**Comment by richmahn** [comment]
Finding this has to do with Footnotes now existing in a verse, thus throwing off the occurrence count (I assume from #3190). That is why 1 Thes 3:2 is unique, as it has a footnote (https://git.door43.org/Door43/en_ulb/src/branch/master/53-1TH.usfm#L79). Selecting any word in the text that also appears in the footnote will cause this error message, where other words like "comfort" won't give this error message. Needs a new issue/story. Putting this back "In QA".

**Comment by cckozie** [comment]
Wrote up the noted problem in #3853
