### ISSUE TITLE
Project Migration Module: Upgrade .x projects to latest version

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3321]
* [ ] Upgrade .x projects to latest version
  * [ ] Filesystem structure
  * [ ] Manifest updates

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [1] Determine Types Of Projects That Need Upgrading
- [ ] [2] Create Helper To Migrate Legacy Manifests (For Supported Versions)
- [ ] [2] Determine Best Practices For Future Migrations
