### ISSUE TITLE
Warn users that canceling an import during the validation stage will require reimporting the project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3347]
- When a user clicks the Cancel button during any stage of the validation process, display an alert with this text: 
```
Canceling now will abort the import process and the project 
will need to be reimported before it can be used.
```
- The alert should display two buttons with this text: "Cancel Import" and "Continue Import". 
     - If the user selects "Cancel Import", the imported file(s) should be deleted and the user should be returned to the Projects screen.
     - If the user selects "Continue Import", just dismiss the alert.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [2] Research implementation in the codebase to add an alert in project validation stepper.
- [ ] [3] Create/set up data to be used by alert modal.
- [ ] [3] Add support for multiple options "Cancel Import" and "Continue Import"
- [ ] [2] Write tests for new action that handles selecting to continue or not a import process

**Comment by cckozie** [comment]
0.8.1-alpha.13-4ef6c94
This new warning message is displayed for projects that have missing verses, even if they have already been all the way through validation and have been loaded. In those cases, the user will not be required to reimport their project and should get the same message as we issued before.

**Comment by mannycolon** [comment]
- [5] Don't show the cancel import alert when the project comes from the projects folder.

**Comment by cckozie** [comment]
Works in Sandbox build.
