### ISSUE TITLE
Need a build with full NT for alignment

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3381]
- [ ] The aligners need a stable build that has the whole NT so that they can keep working on aligning the NT. 
- [ ] Go back to before the project refactor, create a release branch (0.8.1)
- [ ] Remove the Titus restriction

**Comment by klappy** [comment]
## Tasks
[4] v0.8.1 Release: Find a commit prior to refactoring and create a release branch v0.8.1
[4] v0.8.1 Release: Create a build and test everything
[4] v0.8.1 Release: Find a second commit that might be more stable and replace branch v0.8.1
[4] v0.8.1 Release: Replace the build and test everything
[2] v0.8.1 Release: Create a tag for v0.8.1 and publish release
