### ISSUE TITLE
Import workflow is broken when project has merge conflicts

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3385]
When an imported Door43 or tstudio project has merge conflicts, a console error is generated and the user is not taken to the tool selection screen. The same behavior is seen when importing a local tstudio file and from Door43.
1. Import https://git.door43.org/tc06/en-x-demo1_php_text_ulb or 
[en-x-demo1_php_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1552112/en-x-demo1_php_text_ulb.tstudio.zip)
2. Choose a license and click Continue
3. Select a version for the two merge conflicts and click Continue
4. Click Continue on the Missing Verses screen
You are now returned to the projects page and the project is not listed there
If you reimport the same project locally, the license page is bypassed.
If you reimport the project from Door43, the Project has already been imported alert is displayed even though it doesn't show up in the project list.
![image](https://user-images.githubusercontent.com/8171759/33891909-ffcdd22a-df1c-11e7-8b2e-f0e1ec7adbc9.png)

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [1] Debug Issue With Broken Merge Conflict Projects
- [ ] [2] Fix Import Stepper Done Workflow
- [ ] [1] Write new tests case
