### ISSUE TITLE
Convert OSHB OSIS to UHB USFM3

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3414]
## Task

The [OSHB OSIS](https://github.com/openscriptures/morphhb/tree/master/wlc) files need converted to USFM3 and uploaded to the [UHB repo](https://git.door43.org/Door43/UHB) like we have done with the [UGNT](https://git.door43.org/Door43/ugnt).

## Specs

* [x] This will need to be a repeatable process as the morphology for the OSHB is being updated on a regular basis.
* [x] The "/" character that occurs in the Hebrew words needs to be replaced with a Unicode zero-width space.  This is painful but it should allow the text to be displayed correctly while also allowing multiple lemma and morphological encodings to be encoded.  See discussion on https://github.com/ubsicap/usfm/issues/50.
* [x] The conversion process should take into account that we'll be encoding the tW links directly into the text as well, see #3365 .

**Comment by da1nerd** [comment]
@jag3773 do you want the output USFM files to be formatted as `01-GEN.usfm`?

**Comment by da1nerd** [comment]
Some more questions:

* some words are missing either the lemma or the morph. What should I do in those cases?
* for the csv conversion I had a bunch of information (umedieval, ulemma, lexeme, syn, morph, lex) but with osis I only have the lemma, morph, and text. How should I structure the words since I'm missing all that info? 
* what is `<seg type="x-maqqef">־</seg>`? For example in Hag.1.1 there's this line `<w lemma="1697" morph="HNcmsc">דְבַר</w><seg type="x-maqqef">־</seg><w lemma="3068" n="0.1.1.0" morph="HNp">יְהוָ֜ה</w>`

**Comment by da1nerd** [comment]
Here's a sample output of the parsing (incomplete) for the passage in Hag mentioned above:

```
\w דְבַר|lemma="1697" strong="G00000" x-morph="Gr,HNcmsc"\w*
־
\w יְהוָ֜ה|lemma="3068" strong="G00000" x-morph="Gr,HNp"\w*
```

**Comment by jag3773** [comment]
@neutrinog See these clarifications:

1. The `lemma` field in the OSHB is actually the Strong's number.  These should be converted to the `strong` field in the USFM3 files. For example, `\w דְבַר|lemma="דָּבָר" strong="H1697" x-morph="He,Ncmsc"\w*`.
1. The `lemma` field needs to be populated via convergence with the XML file at https://github.com/openscriptures/HebrewLexicon/blob/master/HebrewStrong.xml, via Strong's number.  For example, taking `H1697` from point 1 you should find the lexical entry for that term in the `w` attribute, in this case on line 10142 of HebrewStrong.xml, I've included the expected output in the snippet above.
1. As you see in my example in point 1, the x-morph grouping should not have a `Gr` prefix.  Instead, the first letter in the OSIS `morph` attribute stands for either Hebrew or Aramaic.  Lets convert the H to `He,` and the A to `Ar,`.  Daniel has both Hebrew and Aramaic so you could use that as a test case to make sure the conversions are happening properly.
1. There are several types of punctuation marked with the `seg` OSIS marker, please include those in the text.
1. Per discussion discussion on ubsicap/usfm#50 , note that the `/` characters in the `morph` attribute should be converted to `:` characters for our USFM3 `x-morph` attribute.

I think that takes care of your outstanding questions but let me know if I missed any.

**Comment by da1nerd** [comment]
@jag3773 a lot of the strong numbers have extra characters.

* `b/3027`
* `1121 a`

What should I do with these? Right now I'm removing the extra characters and just focusing on the numbers.

## Update

* in the first example we will write the strong number as `b:3027` and just strip out the letter when looking up the lemma
* in the second example we will keep the letter in the usfm output but strip it out for the lemma lookup.

## Another Update

* the suffix e.g. `a` will be smashed against the number. e.g. `H1121a`

**Comment by da1nerd** [comment]
also what about when the morph is missing? For example `<w lemma="2232">זְרַעְתֶּ֨ם</w>` in Hag 1:6

## Update

* don't add the morph if it doesn't exist.

**Comment by neutrinog** [comment]
What is the `n` property? e.g. `<w lemma="d/2233" n="1.1.0" morph="HTd/Ncmsa">הַ/זֶּ֨רַע֙</w>`

**Comment by da1nerd** [comment]
@jag3773  I've finished the tool. And here's some sample output.

* [37-HAG.usfm.txt](https://github.com/unfoldingWord-dev/translationCore/files/1596503/37-HAG.usfm.txt)
* branch with updates: https://git.door43.org/Door43/UHB/src/usfm

I've also linked the log output

* [errors.log](https://github.com/unfoldingWord-dev/translationCore/files/1596505/errors.log)

Most of the errors in the log are one of two forms:

```
[WARNING] Word and morph components are not aligned at Jer 52:17
[ERROR] No match in lexicon for strong's "b" at  Jer 52:18
```

The first warning indicates, for example, that the morphology had a single `/` while the word had either none or more than one. From my understanding the morphology pieces should match the word pieces. If that is not the case I can disable this check.

**Comment by da1nerd** [comment]
I've updated the the [usfm branch](https://git.door43.org/Door43/UHB/src/usfm) with the latest adjustments.

**Comment by jag3773** [comment]
@neutrinog This looks good.  Where is the code for the conversion?

**Comment by jag3773** [comment]
Also, we just released OSHB 1.3 with more morphology, can you update the USFM files and then create a PR for me to merge?

**Comment by da1nerd** [comment]
The code for this is at https://github.com/unfoldingWord-dev/d43-catalog#convert-osis-to-usfm3

**Comment by da1nerd** [comment]
Here are the errors associated with OSHB 1.3

[errors.log](https://github.com/unfoldingWord-dev/translationCore/files/1623972/errors.log)

**Comment by da1nerd** [comment]
Here is the pull request. https://git.door43.org/Door43/UHB/pulls/328

**Comment by jag3773** [comment]
@neutrinog Looks like there is an extra 0 pad in the `strong` key.  For example, the first word in Genesis shows `H07225` but it should show `H7225`.

Also, looks like there are several misses in the error log where there is a `+` sign in the Strong's number.  These should be stripped.  For instance, `[ERROR] No match in lexicon for strong's "378+" at  2Sam 2:8` is true, but `H0378` is valid and should be used here.

**Comment by jag3773** [comment]
Bump!  I need this updated soon as we need to take the next step of encoding the tW links in the UHB (#3365) as soon as we can.

**Comment by da1nerd** [comment]
OK! these updates have been applied and added to the PR.
Here's an updated list of errors as well. While I was at this I fixed another tiny bug I found `H0000bH0000` probably isn't a correct strong number :)

[errors.log](https://github.com/unfoldingWord-dev/translationCore/files/1678972/errors.log)

**Comment by jag3773** [comment]
Great, thanks!
