### ISSUE TITLE
Enhancements to project import naming

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3421]
This issue addresses three separate issues: 

*Assign names to imported projects according to the naming standards*
See the naming specification at https://git.door43.org/Door43/registry .
This will also require adding the resource type field to project information page.
This will probably also require converting legacy tS project names to the new format since we're not using the project name to detect duplicates.
Suggestion from Russ that we pop up a notice to inform the user that we are renaming his project.
Do we want to rename Door43 projects to match the spec?  

#4352 Support for udt and ulb projects at the same time

and Allow renaming of project on import #2546

## Specs
- [ ] Put tC logo spinners in for any step that might take longer than 1 second.
- [ ] append the `_book` to the end of the project name. Support for `bundle` types may come later in #1991 .

## Notes
- When the user opens a project that doesn't have this naming convention, then force a migration
- Case insensitive for the Identifier

To address all of these we will do the following: 

![image](https://user-images.githubusercontent.com/13352518/41745252-f71d3f54-756b-11e8-85d6-65d46aa68946.png)

![image](https://user-images.githubusercontent.com/13352518/41062275-f9c4d1b8-699a-11e8-90ee-bdc971c26e24.png)

![image](https://user-images.githubusercontent.com/13352518/41062352-31f31202-699b-11e8-9827-e5545e6530a7.png)

![image](https://user-images.githubusercontent.com/13352518/41062344-2ab79076-699b-11e8-9208-9190b3c403bf.png)

Warnings: 

![image](https://user-images.githubusercontent.com/13352518/41112597-0b1075d0-6a45-11e8-964e-f877a71b04eb.png)
**NOTE: This ^^^ warning (and feature) is covered under #3559**

![image](https://user-images.githubusercontent.com/13352518/41112567-f4dfbd98-6a44-11e8-8a91-21e0dc2a00e3.png)

![image](https://user-images.githubusercontent.com/13352518/41112619-19257832-6a45-11e8-8dd5-9927d990912d.png)

![image](https://user-images.githubusercontent.com/13352518/41112639-2b0a97da-6a45-11e8-99a7-31e43d2f75cc.png)

![image](https://user-images.githubusercontent.com/13352518/41112667-3d3d45b0-6a45-11e8-92a2-147d2a080143.png)

![image](https://user-images.githubusercontent.com/13352518/41112888-c8483570-6a45-11e8-883d-9cee9954a24d.png)

![image](https://user-images.githubusercontent.com/13352518/41061374-fc4c9144-6997-11e8-9c45-049a40b382c4.png)

## Breakdown 
- [ ] M - Forced Migration for existing projects
- [ ] L - Manifest updates & project naming
- [ ] M - DCS repo rename

**Comment by benjore** [comment]
The user should be prompted and asked if they want to update the name of their project to the new naming convention.

The repo should be renamed on DCS.

**Comment by PhotoNomad0** [comment]
@benjore - I am looking at the accepted format for the translation identifier (also called resource identifier) in https://git.door43.org/unfoldingWord/registry#Resources.  It seems like we need to validate the ID.  It looks like it must be:
- at least two characters long or we should warn something like "field must be at least two characters"
- must be restricted to certain characters.  current examples imply that we accept only english letters and dash.  Do we want to accept numbers and foreign letters?  foreign letters could be hard to filter.  How should we phrase the warning if characters are not acceptable?  Something like "only English letters and dash are valid"?

**Comment by PhotoNomad0** [comment]
@benjore - it also seems like we could accept both upper or lower case letters, and just convert to lower case when we make the project name?

**Comment by PhotoNomad0** [comment]
@benjore - Also warning strings must be short to fit the UI.

**Comment by benjore** [comment]
* Warning: "Must be 3-4 letters long"
* Let's start with just English letters, no dash (that is only used to differentiate sub-resources, like tN, etc. We'll figure that out if/when we start supporting those in tC). 
* Warning: "Only basic Latin Letters supported"
* I'm fine with accepting upper & lower case letters and converting to lower

**Comment by PhotoNomad0** [comment]
### Notes:
Project Nickname is optional. Default to showing the whole slug, unless there's a nickname.

Extracting Translation ID and Project Nickname from manifest on import:
- if new format (http://resource-container.readthedocs.io/en/v0.2/manifest.html) we use the dublin_core.identifier and dublin_core.title
- if older format (https://resource-container.readthedocs.io/en/v0.1/manifest.html) we use the resource.slug and resource.name

**Comment by PhotoNomad0** [comment]
@benjore - implementing dark background for hover text since grey is not available on our current tool tip component. Is this acceptable?  Similar to color choice made with invalided tooltip on VerseCheck.

**Comment by PhotoNomad0** [comment]
@benjore on this screen looking for clarification between flowchart and this image:

![image](https://user-images.githubusercontent.com/13352518/41112888-c8483570-6a45-11e8-883d-9cee9954a24d.png)

On "rename local project" button, I presume that we go back to project details page.
On "continue without renaming", does that just mean continue without renaming Door43 or without renaming local project as well?  I suspect the first, but the user may presume that the local project will not be renamed as well.

**Comment by PhotoNomad0** [comment]
@cckozie @benjore @rich - I think we need to make adjustment to the flow chart in the case of opening local project.  In this case we do not change the text to overwrite, and the save button is not enabled if there is a duplicate.

**Comment by cckozie** [comment]
I agree with ^^^

**Comment by richmahn** [comment]
Yeah. I don't get why anyone would want one project to be renamed to an existing project. Too confusing on what data takes precedence in the merge.

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - per conversation with Ben the workflow for overwrite has been changed to abort the import if the user selects cancel.  The button text has been changed to "Cancel Import".  This change has been made for time reasons - since the import stepper has finished at the merge prompt, restarting the import would take significant rework to the import stepper.

**Comment by PhotoNomad0** [comment]
![screen shot 2018-07-10 at 7 12 34 pm](https://user-images.githubusercontent.com/14238574/42542547-5093cb12-8475-11e8-96bd-0a4558504f3a.png)


@cckozie - talked with ben about button text not fitting on a button.  This is the updated screen shot for the DCS rename conflict.

Correction - that should be **"Do Not Rename"**

**Comment by PhotoNomad0** [comment]
@benjore - while you were out  brought a special case to @jag3773 and @cckozie:

In the case that the user imports a project that belongs to another user, I think we need to have a special case.  Certainly we don’t try to rename the DCS (which would throw an error anyway).  

It seems the simple case would be to follow the same path as “no Door43 repo” and do nothing on Door43 at the moment.  In this case we just prompt that the project has been renamed and NOT don’t do the prompting to rename or create a new repo.  Later when the user uploads to Door43, this issue will be resolved since it now becomes their own copy of the project.

----------------

After talking to @cckozie also need similar behavior on a locally imported tS project. Since it may have a git history from another user as well.  Also need to account for opening existing projects that may have been copied from another user and not try to rename on DCS.

**Comment by cckozie** [comment]
@PhotoNomad0 I agree with the above, that there is no need for renaming the D43 repo when the project comes from another user's repo. Also, the same is the case for tS projects imported locally.
