### ISSUE TITLE
tW Hindi: Import Hindi tW Part I

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3548]
Content is available from https://git.door43.org/Door43-Catalog/hi_tw .

**Comment by jag3773** [comment]
Added, "Content is available from https://git.door43.org/Door43-Catalog/hi_tw."

**Comment by richmahn** [comment]
- [ ] [2] Run tC_resources/index.js script to generate tW for hi
- [ ] [2] Verify articles and index.json file are properly generated

**Comment by richmahn** [comment]
Done in #3912

**Comment by cckozie** [comment]
The links in the kw's in the resources folder do not match what's on Door43.
Door43:
![image](https://user-images.githubusercontent.com/8171759/37116177-206ddf28-2213-11e8-9bee-9cbd8cdd386f.png)

Resources folder (link to en, not hi):
![image](https://user-images.githubusercontent.com/8171759/37116136-f56eae92-2212-11e8-8574-b78469a9a9bc.png)

**Comment by jag3773** [comment]
Probably means hi_tw needs pulled in again/updated.

**Comment by richmahn** [comment]
Will pull again, but we don't even do anything for tN any more as we don't have any articles for that in the resources directory. We just strip those out when we display in the tHelps article viewer.

**Comment by richmahn** [comment]
- [ ] [2] Pull Hindi tW again

**Comment by richmahn** [comment]
I checked that the latest build has the latest Hindi tW files. Please try `rm ~/translationCore/resources/hi` and try latest build again (restart app). Note you only have to remove the `hi` dir.

**Comment by cckozie** [comment]
looks good in 0.8.1-alpha.21-320865f 
Did not have to manually delete the resource (and shouldn't have to)
