### ISSUE TITLE
tW Hindi: Export to CSV

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3554]
Add: 
- [ ] GL language code
- [ ] GL quote

```
{
    ...,
    gatewayLanguageCode: 'en',
    gatewayLanguageQuote: 'quote',
    ...
}
```

**Comment by mannycolon** [comment]
@benjore Please, could you add a description to this story. I honestly have no idea what it means. 
is it just verifying it works?

**Comment by richmahn** [comment]
@mannycolon Will let Ben respond, but most of these issues are just to check that everything is working with another language... not even sure how that matters such as with Export if the Gateway/Source language isn't really involved with the alignment, just a help.

**Comment by benjore** [comment]
@mannycolon This issue is to verify that the CSV export is working properly. When a target language has been checked with the Hindi tW tool, then the CSV export should have the Hindi check info (not the English). 

- [ ] Check to see that the info looks correct to you
- [ ] Contact a Hindi speaker (@klappy can help you get in contact with the right person) to have them verify that it is indeed showing up correctly.

**Comment by richmahn** [comment]
Just realized this won't show the Hindi the "groupName" column of the CSV file even if the exported project is open and GL is set to Hindi. We have it exporting the groupName only in English (hard coded at the top of csvHelpers.js), and since we currently don't save a project's GL to file but can export the CSV of a project that isn't open, a bunch of changes would have to be made. Saving a project's selected GL to file to persist it would probably be outside of this story. Then we'd have to make sure the csvHelpers.csv doesn't read the index.json when it loads, but instead reads the project's saved settings, gets the GL, and passes that to the groupName() function and reads the index.json files there.

**Comment by richmahn** [comment]
@benjore Export to CSV needs to ask for a GL as well since Export to CSV actually isn't specific to the open project (it works for any project) and isn't specific to a given tool's GL (which we don't know if a project isn't open). Thus the Export to CSV probably also need a GL language select to properly give the groupName in the desired language. Should we prompt the user for a GL?
