### ISSUE TITLE
Reimport Existing Project with Updated Text From USFM

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3559]
## Story

As a _checker_, I want to be able to export a tC project as USFM, load it into another app, export from that app as USFM, and reimport into the *same* tC project so that I can make use of features in other apps without redoing work in tC.

As an _aligner_, I want to be able to make changes to my translation in a separate tool and then reimport the text from a USFM2/3 file so that I can realign the text that I changed.

## Notes

* Existing check data should be preserved, only the text should be updated
  * For a USFM3 import with alignment data, the imported alignments should overwrite existing alignments in the project, but the importer should preserve any existing alignments which the new file does not have alignments for.
  * For a USFM2 import, the alignment data should not be affected except where the text is overwritten.
* User should be prompted to "recheck" any previous check that may have been modified by changes to the text
* Import/Export testing should happen against Paratext
* If a USFM3 is imported (not reimported) then it should also work
* Make sure "invalidated checks" are calculated during the reimport process.

Related to #3086 & #3763

**Comment by benjore** [comment]
![image](https://user-images.githubusercontent.com/13352518/36040664-c8b6a1de-0d8b-11e8-86c7-ca8dea15e9b9.png)

![image](https://user-images.githubusercontent.com/13352518/36040672-cf269e70-0d8b-11e8-8fc4-8d6d8f2350ac.png)

![image](https://user-images.githubusercontent.com/13352518/36040679-d5e80b90-0d8b-11e8-8f28-4edae1fdcb51.png)

![image](https://user-images.githubusercontent.com/13352518/36040692-dc161732-0d8b-11e8-860a-aaedf091aed5.png)

**Comment by benjore** [comment]
- If the user tries to reimport a project, prepopulate the language field. If they change the language, then create it as a new project, not a reimport. 
- Do a Git commit (so that eventually this merge can be undone).

**Comment by richmahn** [comment]
- [ ] [25] Code reimport for existing project with updated text
- [ ] [8] Write tests for reimport
- [ ] [2] PR Review for #3559

**Comment by richmahn** [comment]
@benjore Is the "import" icon ok for this? The add file to folder icon is a bit misleading, plus doesn't exist in Bootstrap's icons. Here's an actual screenshot using bootstrap:

![screenshot](https://user-images.githubusercontent.com/2839925/39897548-e7a70d24-546f-11e8-9d1b-37dc64115253.png)

**Comment by benjore** [comment]
@richmahn I don't like that. Are there any other options?

**Comment by richmahn** [comment]
@benjore Easiest is to use the Bootstrap3 Glyphicons, but we could try to make another svg icon like we did for invalidate. https://getbootstrap.com/docs/3.3/components/

**Comment by richmahn** [comment]
@benjore I think the glyphicon-level-up is kind of similar to what you have, and has a nice "re"import feel to it (search for that icon name in the page)

**Comment by benjore** [comment]
@richmahn What I used was font awesome. I still like that one best.

**Comment by richmahn** [comment]
@benjore What I finally realize I need are how various prompts and warnings should look, from size of window, to buttons, to verbiage, and when in the process one can cancel the re-import due to them realizing things aren't quite right. Off the top of my head, realizing how much more "noisy" the reimport process is:

  1. What to say when importing a bad file (not USFM) [I assume like in the import process]
  2. Importing a USFM file but it isn't the same book as the project 
  3. Should there be a stepper like in a new project import (this is what I was originally making it to be like but now canning that):
      * Verses missing (just like with new import?)
      * how to show missing alignments and and checks for each tool (sectioned, each its own page?)
      * Anything else that needs to be displayed if wrong?

**Comment by richmahn** [comment]
@benjore Never mind about the first one, I already run the USFM validator which throws the proper message.

**Comment by benjore** [comment]
@richmahn I apologize for this, but I'm gonna change things slightly. It think it will improve the reimport process and hopefully will lessen your work. 

When a user clicks "Reimport", the process should be the same as a regular import (e.g. don't automatically fill in (c) info, project info, etc.). The user should fill in the "Stepper" info as if it were a regular Import. 

Currently, the user is only informed that the project is a duplicate after the whole "Stepper" is completed. This needs to change. When the user clicks "Continue" on the "Project Information" step of the "Stepper", tC should check to see if it is a reimport. That is when the reimport warning should be thrown. If I was trying to reimport an `en_1th` project, but accidentally select an `en_2th` project (and import it as such), then it should be imported as normal. 

![image](https://user-images.githubusercontent.com/13352518/40427525-91eaec90-5e63-11e8-8539-7d744e9665ce.png)

**Comment by PhotoNomad0** [comment]
@richmahn - a missing translation (at least 1) and a question.  Otherwise looks good to go.

**Comment by da1nerd** [comment]
@richmahn

Thoughts:

We will eventually develop an npm library for extracting alignment data from from usfm and injecting alignment data into usfm. 
* Perhaps we could support static api methods from the tool api that would allow performing actions with out any sort of redux context. With such a situation in mind we could give the extracted alignments, and source text (from tC) to a static api method from wA to validate the alignments.
* note: validation at this point need only check for continuity of source tokens in the alignments.

I don't yet completely understand what other checks are performed, however I think static api methods may provide the needed solution.

Questions:
* Do we need to repair invalid alignments immediately or just know if they are invalid?

**Comment by da1nerd** [comment]
The summary from our meeting was that @richmahn will not perform any validation during the import, and I will move the tool API initialization and book loading to the project selection so that the tools page can retrieve validation information from the tools.

**Comment by da1nerd** [comment]
@benjore @jag3773 @richmahn I was inspecting what would be involved in initializing the tool APIs earlier in tC and discovered it will require lot of rewriting for the project loading and some in the tool loading.

We'll need to make these changes anyway in order to support https://github.com/unfoldingWord-dev/translationCore/issues/4659, but this means we won't be able to update the error counts on the tools page (without manually opening the tools) until after this refactoring is complete.

Just to be clear, the above is not blocking this issue at all. It's just that visually there will be discontinuity between the invalid counts after importing the project. So visually it will seem related, but technically it's a separate concern.

see #4672

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - per conversation with Ben the workflow for overwrite has been changed to abort the import if the user selects cancel. The button text has been changed to "Cancel Import". This change has been made for time reasons - since the import stepper has finished at the merge prompt, restarting the import would take significant rework to the import stepper. Ref: https://github.com/unfoldingWord-dev/translationCore/issues/3421

**Comment by cckozie** [comment]
0.10.1 (79a25a9)
1. I have seen this happen twice, but have not yet been able to define the sequence of events that will replicate it. If the text of the reimported file is no different than the existing text for the project, the user receives the 'Reimporting existing projects is not currently supported' message. @richmahn @PhotoNomad0 - Any ideas on why this may be happening?
2. After importing the new text I am unable to delete the project. I don't know if this will potentially cause any issues for users, but it does make my testing more difficult.

**Comment by PhotoNomad0** [comment]
> 2. After importing the new text I am unable to delete the project. I don't know if this will potentially cause any issues for users, but it does make my testing more difficult.

@cckozie - I know you can't delete a project that is currently selected.  Is that the case here?  Either have to select a different project or restart the app to delete.

**Comment by cckozie** [comment]
@PhotoNomad0 No, that is not the problem. A different project is the one selected. On the Mac when I try to delete the project folder I get this dialog, but even after giving it a password, it does not get deleted. I am able to rename the folder, but haven't found a way to delete it.
![image](https://user-images.githubusercontent.com/8171759/42475368-0bf36048-8390-11e8-8fd1-8ff20284efec.png)

**Comment by richmahn** [comment]
I didn't even know we could delete projects. How does one go about doing that?

**Comment by richmahn** [comment]
Ah, you meaning manually from the File browser? Interesting...

**Comment by cckozie** [comment]
Going to fail this while doing further investigation.

**Comment by PhotoNomad0** [comment]
@cckozie - this may not make a  difference, but are you doing "move to trash" or "delete immediately"?

**Comment by cckozie** [comment]
@PhotoNomad0 - I'm doing a 'move to trash'

**Comment by cckozie** [comment]
0.10.1 (ee3f8f5)
1. I have a local project named en_ult_act_book
I did an online import of https://git.door43.org/tc02/en_act
On the project details screen I set the Translation Identifier to 'ULT'
Instead of being warning on that screen that a project with that name already exists, it lets me continue the import and at the end gives me this message:
![image](https://user-images.githubusercontent.com/8171759/42907793-80a417a0-8aa4-11e8-8376-bbcbb0936e79.png)
 
2. When the user selects the 'Reimport' option on the 3dot menu, they should not be allowed to import a project that has a different language and/or book than the one selected on the project menu. Currently it works like a normal import with no messages other than the 'Project has been named..' one, and both projects now show on the projects page. (I am going to contact @benjore about moving this to a new issue that we'll deal with in the future)
3. When the user selects the 'Reimport' option on the 3dot menu, the project details screen should be pre-populated based on the meta data (language, book, translation id, nickname) for the project being reimported. (I am going to contact @benjore about moving this to a new issue that we'll deal with in the future)
4. Imported a good usfm file. Reimported the file again choosing the overwrite option, then loaded in tW. Same error encountered if changes were made to the original file before the reimport. Same error in wA. Same in 0.10.1 (b411d84) Looks like this may not be a problem on Win64  [57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2207546/57-TIT.usfm.zip)

![image](https://user-images.githubusercontent.com/8171759/42910914-c7d7c8d8-8aae-11e8-800f-03b5f86e7d90.png)

5. ### Error: ** I AM NOT SEEING THIS PROBLEM IN 0.10.1 (b411d84) **
~~Overwrite/merge of usfm project fails when not in developer mode~~

 ### Steps to reproduce
  ~~switch out of developer mode~~
  ~~import Titus USFM file to create new project
  make a couple alignments
  export as USFM3 file
  reimport the USFM3 file just exported
  set project details that same and click overwrite
  select overwrite project
will see message that only New Testament projects are supported even though this is a Titus project.~~

**Comment by richmahn** [comment]
@cckozie Yes, #2 is because in Ben's diagram of this whole workflow, reimport isn't really known about until the user has selected a project and renamed it, then knowing it is a reimport. I think Ben spoke about removing it, but in my opinion it helps the user know he/she can reimport a project, yet this button only does local import, not both local and online. Probably best to do away with it. The menu "Reimport Project" simply does what the FAB does for "Import Local"

**Comment by richmahn** [comment]
@cckozie Understand all your issues on repopulating project details and such, as I brought all those up with Ben. Yet this has actually become more of an "overwrite" or "merge" feature (rather than a "reimport" feature) where the user should just go through the regular import of a local or online project, but once they give it an identifier/book/language which generates a project name, and that name exists, then they are prompted if they want to overwrite, and if they do, we keep alignment/selections as needed (importing new alignments if there is alignment data in the new import). So we really shouldn't have the "Reimport Project" option as that seem to be misleading and also what you base your expectation on as I did. 

@benjore We probably need this to be considered "Overwrite" concept of imports with the same given project name. There is so much we don't know until they finally name the project and specify the book and language in the Project Details page to be able to force them to select the right book/language as Koz (and I) wanted for a reimport feature. All that is really needed is to do away with the "Reimport Project" context menu for projects and be told/prompted when existing project will be overwritten/merged.

**Comment by cckozie** [comment]
Recreate on 0.10.0 (db8cd53) with Hindi project.
![image](https://user-images.githubusercontent.com/8171759/43023112-4a199d86-8c2f-11e8-95d3-695ef5d919be.png)

**Comment by PhotoNomad0** [comment]
@richmahn - it looks like a timing problem.  @royalsix doesn’t see the problem when he has debug tools open, but sees a crash when he doesn’t.  Looks like the project is is not being deleted from the projects folder before trying to copy the new one from imports.  Maybe try Spidel's fix of renaming the old project before deleting it and after that moving from imports?  that way you shouldn't see any collisions when moving.  And then if the renamed old project is still around, you could see if there was a permissions problem like a file/folder was locked.

![screen shot 2018-07-20 at 5 13 30 pm](https://user-images.githubusercontent.com/14238574/43025595-5fdfe858-8c40-11e8-9851-ec5f0ae56e9d.png)

**Comment by benjore** [comment]
Sorry to be late to the party!

>2. When the user selects the 'Reimport' option on the 3dot menu, they should not be allowed to import a project that has a different language and/or book than the one selected on the project menu. Currently it works like a normal import with no messages other than the 'Project has been named..' one, and both projects now show on the projects page. (I am going to contact @benjore about moving this to a new issue that we'll deal with in the future)
>3. When the user selects the 'Reimport' option on the 3dot menu, the project details screen should be pre-populated based on the meta data (language, book, translation id, nickname) for the project being reimported. (I am going to contact @benjore about moving this to a new issue that we'll deal with in the future)

Let's not do these for this release. We can move them into a new issue. @cckozie Seeing that this won't be possible, would you rather that we hide the "Reimport" option from the 3-dot menu? 

Created #4756 to add back the Reimport option

**Comment by cckozie** [comment]
@richmahn As suggested above, please remove the 'Reimport' option from the 3 dot menu.

**Comment by cckozie** [comment]
0.10.0 (9b04f29) Using project [55-1TI.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2229451/55-1TI.usfm.zip)

The problem noted '5 days ago' above still exists and is possibly worse.
![image](https://user-images.githubusercontent.com/8171759/43224250-5204277e-901b-11e8-8e00-73d24fe9dc50.png)
1. Import a Titus usfm2 project
2. Import the same usfm2 project giving it the same language and translation id as the previous import
3. Click the Overwrite button
4. Click the Overwrite Project button
5. Open the project in tW, see the error
NOTE: This error occurs regardless of whether or not the second usfm2 file is identical to the first or if it has changes. It also does not matter if the first project imported is opened in tW before the second import is performed.

**Comment by cckozie** [comment]
On Win64 it did work when I imported the file a second time. However, when I imported it a third time I got the error again.
![image](https://user-images.githubusercontent.com/8171759/43225768-93a1b5c6-901f-11e8-8f54-d9174df7a8bc.png)

**Comment by cckozie** [comment]
0.10.0 (4566b9d)
I did a successful import, then overwrite multiple times, all with usfm2 files. Then I got this. It comes up after clicking the Overwrite button. I now get this message every time, even after restarting tC.
After deleting the Projects folder it does again work correctly.
Could this be tied to my being unable to delete the project's folder so I am renaming it?

![image](https://user-images.githubusercontent.com/8171759/43292632-d09b54a0-90fb-11e8-834b-cf0467270cc4.png)
