### ISSUE TITLE
tC needs to know which gateway languages are supported for each book/tool combination

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3643]
## Notes
This information will then populate the GLs available in the GL selection in the tool card (see #2640 )

For a language to qualify as a GL for the tW tool, the Door43-Catalog would need to list at least the following for the language:

* [ ] ULB text, at checking level 3, with alignment data for at least some books
* [ ] translation of tW, at checking level 2 or 3

Blocked by not having any aligned data in the RESOURCE "world" #3188

## Notes: 
- Some items in #2640 cannot be completed until this issue is complete. Please ensure that the following is completed: 

- [x] Mockup for where to make the selection
- [ ] Display the GL that is in the manifest as the default option (Is this considered to be the "source language" in the manifest? If there are multiples defined, should it be the first one?)
- [ ] Test to see if we have the book/tool combos that will show up in the dropdown
- [ ] When a new language is selected, refresh the % complete (Hey @benjore, do we really want the % complete to be calculated based on which GL was used during the checking process?) 
- [ ] The app should remember what GL was selected
- [ ] The place to change this to determine the valid GLs, get those items from src/assets/langnames.json, is at in src/js/helpers/LanguageHelpers.js (line 11 at the time of this comment: export const gatewayLanguages = [{lc: 'en', name: 'English'}, {lc: 'hi', name: 'Hindi'}];) (comment by richmahn)
  
![image](https://user-images.githubusercontent.com/13352518/34573243-323f4a44-f139-11e7-97a8-5fdb0efdddda.png)

![image](https://user-images.githubusercontent.com/13352518/34573286-5a80f6f6-f139-11e7-9490-a9fd541a3c20.png)

![image](https://user-images.githubusercontent.com/13352518/34573262-43b29f74-f139-11e7-99fb-d99fb999c8c5.png)

![image](https://user-images.githubusercontent.com/13352518/34573319-75f1cafa-f139-11e7-87ed-5393b93e361b.png)

## Tasks
1. [5] Write unit tests with increased code coverage  for 3643

1. [3] Read manifest of current project for 3643

1. [3] Read manifests of all local resources for 3643
   1. [1] Filter by those of the same book of the bible as current project for 3643
   1. [1] Filter by those that are ULB resources for 3643
   1. [1] Filter by those that are Checking Level 3 for 3643
1. [4] For each ULB for 3643
   1. [1] filter by those that are checking Level > 1 for 3643
   1. [1] Provide list to UI for 3643
   1. [1] Indicate which Language is default GL for selected project for 3643
   1. [1] Write selected GL to project manifest for persistance for 3643
1. [9] Push to completion for 3643
   1. [3] Clear Travis builds for 3643
   1. [1] Process review for 3643 
   1. [2] Process PR for 3643
   1. [1] Test in build for 3643
      1. [1] Manual testing per PR review process for 3643
   1. [1] Write JSdocs ensure Sphinx builds for 3643

1. [4] Update UI to for 3643
   1. [2] Read from provided list for 3643
   1. [1] Select default Gateway for 3643
   1. [1] After selection update % complete

**Comment by benjore** [comment]
- [x] Please update the build so that the label `Gateway Language` appears above the language dropdown (after a language is selected). See the mockups above.
- [ ] Make only English available (for now) for the Alignment Tool

**Comment by richmahn** [comment]
The place to change this to determine the valid GLs, get those items from `src/assets/langnames.json`, is at in `src/js/helpers/LanguageHelpers.js` (line 11 at the time of this comment: `export const gatewayLanguages = [{lc: 'en', name: 'English'}, {lc: 'hi', name: 'Hindi'}];`)

**Comment by cckozie** [comment]
Should the test include checking the manifest to ensure that the checking level is 2 or 3? That does not appear to be happening in 0.10.0-7f20ffa.
Per Jesse, until we have dynamic updating of resources there will not be any at less than checking level 2, so the test for that is not legitimate at this point.
