### ISSUE TITLE
Display the target language book name 

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3656]
## User Story

As a speaker of an OL, I want to see the book name in my language so that I can easily understand which book I'm working on. 

Note: Use target language in USFM manifest.
Note: No reference to ProjectPage-ProjectCard

## Specs
- [x] If the localized name is available through the project, use that.
  - Possibly in manifest.yaml, like this https://git.door43.org/Door43-Catalog/sw_ulb/src/branch/master/manifest.yaml#L97
  - Possibly also available in USFM source as `\h` tag, like https://git.door43.org/Door43-Catalog/sw_ulb/src/branch/master/66-JUD.usfm#L3
  - https://git.door43.org/johnkerim/lno_jud_text_reg/src/branch/master/front/title.txt
- [x] If the localized name is not available, use the GL book name. 
- [x] If the GL book name is not available, use English
- [x] Occurrences
  - [x] Check pane (In the tW tool, the bottom card ("Step 2. Check"/"Select"/"Edit Verse"/"Comment")
  - [x] Title of Expanded Scripture Pane
  - [x] Title of Expanded Checking Pane
  - [x] Project panel in the Home Screen (project step in the stepper, each individual card should have the book name that is in the Manifest)
  - [x] Left Side Menu of Word Allignment Tool

## Tasks
1. [2] In convert, write a migration to add gl bookname to project manifest for 3656

1. [2] Write unit tests with increased code coverage  for 3656

1. [3] Make a module of for 3656
   1. [2] Check manifest projects.title for localized name and projects.identifier for name
   1. [1] If still not found check catalog front/title.txt
   1. [1] If still not found Use GL book name
   1. [1] If still not found use English

1. [2] Call Module from Check Pane  for 3656
1. [1] Call Module from title of expanded checking pane for 3656
1. [1] Call Module from project panel in home screen  for 3656
1. [1] Call Module from Side Menu for 3656

1. Push to completion for 3656
   1. [3] Clear Travis builds for 3656
   1. [1] Process review for 3656
   1. [2] Process PR for 3656
   1. [1] Test in build for 3656
      1. [1] Manual testing per PR review process for 3656
   1. [1] Write JSdocs ensure Sphinx builds for 3656

The following images show the label target_titus where the book name was taken from the USFM manifest target_language. The en manifest for titus was instrumented to have this value.

![target_language-tw-checkpane](https://user-images.githubusercontent.com/4968713/36549569-16b3db7e-17c1-11e8-9eca-acb272efd314.PNG)

![target_language-homepage-projectcard](https://user-images.githubusercontent.com/4968713/36549585-219b6610-17c1-11e8-9c03-dcf3420c28eb.PNG)

![target_language-leftmenuandexpandedscripturepane](https://user-images.githubusercontent.com/4968713/36549601-2c64c5e6-17c1-11e8-94bb-9529a03bfd34.PNG)

![target_language-homepage-projectcard](https://user-images.githubusercontent.com/4968713/36549611-31b24d48-17c1-11e8-965e-b1531a53a9eb.PNG)

**Comment by da1nerd** [comment]
This is related to https://github.com/unfoldingWord-dev/translationCore/issues/2003

**Comment by cckozie** [comment]
I believe it should also be used on the missing verses page. Wrote up in #4024
