### ISSUE TITLE
Pre-Publication Tool

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3669]
(These are some categories found in ParaTExt)

- [ ] Spell Check 
  - [ ] Characters Inventory 
  - [ ] Characters (combinations)
- [ ] Unmatched Pairs of Punctuation 
  - [ ] Punctuation Inventory
  - [ ] Quotation Rules 
- [ ] Repeated Words 
- [ ] Punctuation Followed by a Lower Case Letter 
- [ ] Capitalization
- [ ] Mixed Capitalization 
- [ ] Grammar Check
- [ ] Numbers
  - [ ] Numbers Settings
- [ ] References 
- [ ] Quotations
  - [ ] Quoted text

- [ ] USFM Checks 
  - [ ] chapter/verse numbers 
  - [ ] Markers
    - [ ] Markers Inventory
  - [ ] Markers Missing Final Sentence Punctuation 
  - [ ] Markers Followed by a Lower Case Letter
