### ISSUE TITLE
A single alignment box is displayed for verses that do not have any Greek text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3670]
0.8.1-alpha.14-a0bd340
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/980e0331-7316-44cc-8f6f-bc76a3082a76)
I think we should not display an alignment box is the Greek is empty for the verse.
Additionally, I think it would be good to supply an explanation in the ULB and Greek that the verse is intentionally left blank (and maybe why).

**Comment by benjore** [comment]
- [x] alignment box should not display
- [ ] display this message `[WARNING: This Bible version does not include text for this reference.]`
  - [x] Where the alignment box normally is
  - [ ] In the Scripture Pane for the target translation (this used to work)
  - [ ] In the Scripture Pane for reference translations.

**Comment by cckozie** [comment]
0.8.1-alpha.28-050acd8 
The target language warning about missing text is no longer being displayed.
@benjore Do we want similar warnings in the other scripture panes, or is that covered in you (NEED THIS) above?
![image](https://user-images.githubusercontent.com/8171759/38203793-04a02578-3666-11e8-8778-21a4439934fe.png)

**Comment by benjore** [comment]
I added that to the description above @cckozie

**Comment by mannycolon** [comment]
@benjore @cckozie Since new work was added to this story maybe the estimate should go up as well?

**Comment by mannycolon** [comment]
@benjore Is this part of 0.10 ?

**Comment by RoyalSix** [comment]
I'm still getting a blank section on the scripture pane for the UGNT, I think ben wanted the text `[WARNING: This Bible version does not include text for this reference.]` there too
<img width="1280" alt="screen shot 2018-04-10 at 12 06 10 am" src="https://user-images.githubusercontent.com/16184018/38541176-22a2486a-3c53-11e8-95b8-3f58c6aa0d76.png">

**Comment by mannycolon** [comment]
@RoyalSix Did you pull both branches (feature-mannycolon-3670) for the scripture pane and wordAlignment tool?

**Comment by cckozie** [comment]
0.10.0-7f20ffa
Only 2 of the 4 items listed in the 3/23 comment have been implemented.
![image](https://user-images.githubusercontent.com/8171759/39653997-d238cb1e-4fb8-11e8-8d57-f4f9261e4a37.png)

**Comment by mannycolon** [comment]
Should be handle by #4309

**Comment by mannycolon** [comment]
Pending `tc-ui-toolkit` integration into tW tool

**Comment by cckozie** [comment]
Cannot fully test until the footnotes problem noted in #4319 is fixed.
