### ISSUE TITLE
Badges for the icons in the menu with hover-over

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3676]

**Comment by richmahn** [comment]
- [ ] [4] Add "chips" to badges in tW to show number of badgets if > 1
- [ ] [3] Mouse-over badge to show all badges of given verse in tW
- [ ] [2] Write tests for badges
- [ ] [1] PR Review for #3676 - badge chips and mouse-over

**Comment by PhotoNomad0** [comment]
@cckozie - this is a v10 feature, test this in sandbox build.

**Comment by cckozie** [comment]
This has been implemented in tW but not wA.

**Comment by richmahn** [comment]
This was for tW. WA works differently in what info is available. It only has the selected (aligned) badge.
