### ISSUE TITLE
Expanded Checkbox filter

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3677]

**Comment by richmahn** [comment]
- [ ] [4] Add expandable checkbox filter menu to left sidebar of tW
- [ ] [3] Execute filter so filters are ORed showing desired verses
- [ ] [2] Write tests for tW left sidebar filter
- [ ] [1] PR review for #3677 - sidebar filter

**Comment by cckozie** [comment]
This has been implemented in tW but not wA.

**Comment by richmahn** [comment]
The filter can be turned on fro WA, but then Bookmarks, comments, etc. make no sense. I believe something in the issue lead me to believe this was only to be turned on for tW.
