### ISSUE TITLE
Collapsed menu with "Chips"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3678]

**Comment by richmahn** [comment]
- [ ] [4] Make sidebar menu filter collapsible with "chips"
- [ ] [2] Write tests for collapsible menu filter
- [ ] [1] PR review for #3678 - collapsible filter menu

**Comment by cckozie** [comment]
This has been implemented in tW but not wA.
