### ISSUE TITLE
[6] Use VerseObjects instead of WordObjects 

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3722]

**Comment by PhotoNomad0** [comment]
#### Subtasks:
- [x] scripturePane:
  - [x] display other verseObjects with text (such as punctuation)
- [x] translationCore:
  - [x] update loadBiblesChapter() to preserve all verseObjects
  - [ ] ~change USFM import to preserve verseObjects (currently flattens to string)~ - _future issue for when we use verseObjects natively._
- [x] wordAlignment:
  - [x] make sure works with verse objects
- [x] translationWords:
  - [x] make sure works with verse objects

**Comment by klappy** [comment]
Not sure the best way to log these so I'll place the ones I find here:

- [x] `WordAlignmentActions.js` uses `word` attribute instead of `text` in multiple places - _these are now alignment objects, I clarified this in JSDocs_
  - [x] `removeWordBankItemFromWordBank()` 
  - [x] `unmergeAlignments()`
- [ ] `WordAlignmentHelpers.js` is based a lot off of WordObjects, move some of these helpers to AlignmentHelpers as they may fit there better. - _OK working on getting my head around which of these methods are alignment objects and which are wordObjects_
  - [ ] `getWordText()` remove use of fallback to wordObject and rename to verseObject
  - [ ] `populateOccurrencesInWordObjects()`  replace wordObject(s) variables to verseObject(s)
  - [ ] `wordObjectArrayFromString()` replace `word` attr for `text` and `wordObjectArray` renamed to `verseObjects` as Array is assumed with plurality.
  - [ ] `sortWordObjectsByString()` - same as last one.
