### ISSUE TITLE
USFM import does not preserve all header info

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#3758]
USFM import does not preserve all header info.  Some known items not preserved:

\ide UTF-8
\toc1 The Book of Psalms
\toc2 Psalms
\toc3 Psa
\mt The Book of Psalms
\ms Book One

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [x] [2] save import header info
- [x] [4] export header info
- [x] [4] update unit tests
- [x] [6] PR Review

**Comment by PhotoNomad0** [comment]
fixing ID tag format to be:

TIT EN_ULB Kiswahili_sw_ltr Wed Jul 26 2017 22:14:55 GMT-0700 (PDT) tc

**Comment by cckozie** [comment]
[php_usfm.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1741499/php_usfm.usfm.zip)
I'm not sure that this is what caused the issue, but this usfm projects now open to a blank checking screen in tW with no console errors. It does open properly in word alignment.

[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1741551/es-419_luk_text_ulb.usfm.zip)
This project also opens to a blank checking screen in tW. It does open in word alignment but it has verse markers displayed in the word list and scripture pane when there are missing verses.
![image](https://user-images.githubusercontent.com/8171759/36444941-4e548658-1642-11e8-9e1f-2de087fe9627.png)

This may be the same problem causing footnotes to show up in the word list that I wrote up in #3209

**Comment by PhotoNomad0** [comment]
Can you check this again.  I think this has been fixed. Not seeing this problem in latest build - tested on windows.

**Comment by cckozie** [comment]
Both problems still exist in 0.8.1-alpha.18-f5cb8b8 on both Mac and Windows.

**Comment by cckozie** [comment]
The first issue is apparently due to missing tW data for non-Titus projects. I will ignore it in that case, and issue #3911 will address the problem of alerting the user as to why the project cannot be checked in tW.
The second issue was moved to #3913

**Comment by cckozie** [comment]
This was tested only using USFM2 data. USFM3 files do not yet contain all of the non-displayed elements.
