### ISSUE TITLE
Maintain punctuation and non-word markers for tstudio and  Door43 projects

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3780]
This is a spin-off of #3190. This currently works for USFM, now we need to make it work for translationStudio projects whether imported from Door43 or tstudio files. 

## Specs: 
- [ ] `/p` and `/s` markers need to be preserved, as well

## Notes: 
- This feature will not be backwards compatible - we won't try to reinsert markers that have already been stripped out, we will only not strip out markers moving forward.

**Comment by PhotoNomad0** [comment]
#### tasks:
- [ ] [8] Modify tstudio import to preserve USFM markers
- [ ] [4] Modify door43 import to preserve USFM markers
- [ ] [8] Unit tests
- [ ] [8] PR Reviews.

**Comment by cckozie** [comment]
In testing this I noticed that sometimes a USFM export from tC gets loaded into tS with all verses blank. I doubt that it is related to this issue, so wrote it up in #4018 
I also compared the usfm export from tC to that for tS for project https://git.door43.org/tc06/ar_mat_text_ulb.
It appears that tS adds 4 or 5 lines of header on usfm export that is not included in tstudio files.
