### ISSUE TITLE
Update "Export to USFM" workflow

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3850]
## Specs 
- [x] Update 3-dot menu to only have one `Export to USFM` option
- [x] If there is NO alignment data, just export to USFM2. If there is alignment data, then show the modal. 
- [x] When `Export to USFM` is clicked and there is alignment data, give them the dialog below that gives them the choice between exporting as USFM2 or USFM3
- [x] Update verbiage to "Upload to Door43" (NOT "Export to Door43")

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/8a5e59c0-5734-48d0-91c4-4c2990eb2e80)

![image](https://user-images.githubusercontent.com/13352518/37163356-2f75d156-22bd-11e8-881f-19a60b07757e.png)

**Comment by jag3773** [comment]
@benjore Can we *only prompt* them if they have used the word alignment tool with that project?

**Comment by benjore** [comment]
NOTE: Check with me for the final verbiage for USFM3 in the modal. (This is dependent on #3808 ).

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [1] Update 3-dot menu to only have one Export to USFM option
- [ ] [4] Create new export dialog
- [ ] [1] Update verbiage to "Upload to Door43" (NOT "Export to Door43")
- [ ] [1] Only show if there is alignment data
- [ ] [2] Write Tests
- [ ] [3] PR Review

**Comment by RoyalSix** [comment]
@benjore @cckozie  what do you think about me updating the workflow when cancelling so that there is no weird alert saying string must be a path? Instead just not showing an alert if they cancel an export.

**Comment by cckozie** [comment]
@benjore @RoyalSix I know we talked about that and I think an issue was created. (#3283) 
I'd say if it's not a significant time suck, to go ahead and remove the alert when they cancel.

**Comment by RoyalSix** [comment]
@cckozie  @benjore  
Cool, and one more thing. What do we want to do if there is an error in the alignments ? 
I think our options are:
1. Skip verses that have errors
2. Display what and where the error is
3. Cancel export altogether

**Comment by RoyalSix** [comment]
So I was wondering how should we handle alignment data errors when users export ? 

I'm not too sure why there happening because I thought that there couldn't be errors because all the data needed for exporting is in the alignments and its not based on external things like the target language in the users project, or greek in the resources.
@benjore @cckozie

**Comment by cckozie** [comment]
@RoyalSix Could the errors be caused by edits/changes being made to the language being aligned or to the Greek? (Same things that cause alignment resets)
@benjore Seems like we might need both a short term solution (maybe warn the user that there are invalid alignments and stop the usfm export like we do if the project has merge conflicts), and later a long term one that would help the user fix the problem before exporting.

**Comment by benjore** [comment]
@cckozie @RoyalSix How does this look? 

![image](https://user-images.githubusercontent.com/13352518/37468134-1d238cc8-2830-11e8-8f20-7a7ef308ec96.png)

**Comment by cckozie** [comment]
@benjore @RoyalSix Works for me, but wondering about the level of effort required to do the reset.

**Comment by RoyalSix** [comment]
@benjore Do we also want show this dialog in the door 43 upload ?

**Comment by benjore** [comment]
@RoyalSix yes. In this case, let me change the verbiage slightly so it will work for both... @cckozie does this work for you?
![image](https://user-images.githubusercontent.com/13352518/37487491-ad93c62c-285f-11e8-93cf-c6ddc75a8b62.png)

**Comment by cckozie** [comment]
@benjore Should we change the first sentence to "Some word alignments have become invalid because of changes made to the project text." so that they don't have to wonder what we did to their project?

**Comment by RoyalSix** [comment]
Which workflow makes more sense for usfm3 exports with alignment errors:
1. `Ask where to export` -> `Ask type of export` -> `Display export fix dialog`
2. `Ask type of export` -> `Display export fix dialog` -> `Ask where to export`

@benjore @cckozie

**Comment by cckozie** [comment]
@RoyalSix I think # 2 is best. 
BTW: tC currently remembers the path where the last usfm2 file was saved, but it doesn't remember for usfm3 exports (that is hard coded to Documents). It would be great if it used the remembered path for both.

**Comment by cckozie** [comment]
@benjore The instructions related to the second and third checkboxes have not been implemented exactly as specified. It works looks like it was implemented assuming the answer to Jesse's question from Feb 16 was answered "yes". Consequently, if the project has been opened in Word Alignment the modal is displayed even if there are no alignments. Did you answer his question in the affirmative?

**Comment by benjore** [comment]
@cckozie I never answered Jesse's question in the affirmative. I would rather do it as I speced (based on whether or not there is actual data). Two reasons: 1. you addressed this already, if a project was opened in the WA tool but nothing was done, you can export to USFM3 even though there's no alignment data. 2. If a USFM3 project is imported with alignment data, but is not opened in the WA tool, then there wouldn't be the option of getting that data back out without doing the work-around of opening it in the WA tool. Both of those seem less than desirable.

**Comment by cckozie** [comment]
Per the above comment and the 2nd and 3rd bullet points in the original description, please base the test on whether or not to give the option to export to USFM3 based on whether or not there is alignment data rather than whether or not the project had been opened in the alignment tool.
