### ISSUE TITLE
Cannot load projects that have merge conflicts

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3856]
Version 0.8.1-alpha.16-2079663
Suspect this is related to the change to verse objects. It did work in 0.8.1-alpha.15-ca3c0d1

https://git.door43.org/TC_SAVE/ar_eph_text_ulb
Import this project
On the merge conflict screen click the (V) to open the conflict
The app goes back to the projects screen (the project is not deleted from the imports folder)
Click on the FAB and the app goes back to the merge conflicts screen
Not able to deal with the merge conflict and load the project

![image](https://user-images.githubusercontent.com/8171759/36284376-0f795a54-126d-11e8-9f9e-4dfaa1bdd5ba.png)

**Comment by benjore** [comment]
@cckozie Did tC cause the merge conflict? Or is this a project that already had a merge conflict before it was imported into tC?

**Comment by cckozie** [comment]
@benjore The project had merge conflicts before being imported.

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [3] Detect bug in merge conflict detection
- [ ] [3] Fix merge conflict resolution
- [ ] [2] Add tests to support new conflicts use case
- [ ] [2] PR Review

**Comment by cckozie** [comment]
I am able to import and open the project, but it looks like a conflict flag is getting set and not cleared. To reproduce the problem:
1. Import https://git.door43.org/tc06/en-x-demo1_php_text_ulb
2. Resolve the merge conflicts and open in Word Alignment
3. Go back to the projects page
4. Click on the 3 dot menu on a different project and choose Export to USFM
5. Note that you get a message indicating that the project cannot be exported because it has merge conflicts.
6. Close the alert
7. Click on the 3 dot menu on the same project again and choose Export to USFM
8. Note that the error message is now not displayed.
