### ISSUE TITLE
Sort the tW group index by GL display name

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3912]
Alphabetize by the first word of the GL.

Note: 
- it has to be unicode-aware sort. 
- it should be case insensitive

From storytime discussion: The data should come to the menu already sorted. 

The English tW needs to be reimported. 

This task needs to be completed before the Hindi tW is imported. 

Note that this requires the tC_resources/index.js script to NOT generate Group Data for languages other than grc so that we can generate tW data for Hindi -richmahn

**Comment by benjore** [comment]
Alphabetize by the first word of the GL.

**Comment by richmahn** [comment]
- [ ] [2] Change resource generation script to only generate Group Data for grc
- [ ] [1] Write tests for resource generation to verify Group Data only generated for grc
- [ ] [2] Sort the index.json generated by "name" rather than "key"
- [ ] [2] Write tests to verify index.json is sorted by "name" and not "key"
- [ ] [2] PR review for 3 PRs (translationCore & tC_resources) for #3912

**Comment by richmahn** [comment]
@benjore @jag3773 This bumps English up to use v8 of translationWords. Is that ok? Do we keep v6 if the app uses v8?

**Comment by jag3773** [comment]
We definitely want the latest English tW in the app. Version number should be synced to the latest en_tw.

**Comment by richmahn** [comment]
Ok. Thanks. Yeah, I noticed a lot of markdown and typo fixes since v6. Will be best those who review this next sprint have the latest.

**Comment by richmahn** [comment]
@cckozie This is more than just sorting being done right on the left side of tW, but to do that new data had to be imported for English and Hindi tW, and a new way of figuring out what the latest version is since languages have different versions, and properly loading that data has to be updated. Also the old version of v6 for English and Hindi were deleted, so if you have tests that check for them, they will need to point to v8 and v8.1 respectively.

**Comment by cckozie** [comment]
@richmahn In the resources folder I'm seeing version 12.1 for en and 0 for hi and grc. Is that what your comment above is about? 
If not, what should I be seeing either in the UI or the file system besides properly sorted words in the check menu?

**Comment by richmahn** [comment]
@cckozie My changes have nothing to do with the Bibles, except that we do use my version-finding alogrithm to determine which Bible to show rather than hard-coded (I think some places it already had a way, but we standardized it and update the procedure). What I changed for sorting the tW for `en` and `hi` is now there is a translationWords/v8 for `en` and translationWords/v8.1 for `hi`.

**Comment by richmahn** [comment]
Greek also has a v0 translationWords, versioned off of the UGNT, but that also wasn't updated in this issue.

**Comment by richmahn** [comment]
I just told you above about the different versions in case your testing scripts had them hard coded or whatever... tW for 'en' before was v6.

**Comment by cckozie** [comment]
@richmahn 
I'm seeing v6 for tW for both en and hi
![image](https://user-images.githubusercontent.com/8171759/37166010-91f09af4-22c3-11e8-88b6-b0fb55164bf7.png)

**Comment by richmahn** [comment]
Hmm...that is old. Not sure why the change of the build version didn't update your resources. Trying it on my machine.

**Comment by cckozie** [comment]
I'm seeing v8 and v8.1 in 0.8.1-alpha.21-320865f
