### ISSUE TITLE
When there are verse markers for missing verses, the verse markers are displayed in the word list, scripture pane, and check pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3913]
0.8.1-alpha.18-f5cb8b8 
[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1741551/es-419_luk_text_ulb.usfm.zip)
This project displays verse markers in the word list and scripture pane when there are missing verses.
![image](https://user-images.githubusercontent.com/8171759/36444941-4e548658-1642-11e8-9e1f-2de087fe9627.png)

[57-TIT2.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1808559/57-TIT2.usfm.zip)
![image](https://user-images.githubusercontent.com/8171759/37368242-a52aece6-26d3-11e8-9062-84f2a0cbfec2.png)

Expected: 
- [ ] warning should show up in the Scripture Pane
- [ ] word bank should be blank
- [ ] check pane just shows reference

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] Scripture Pane warning if there is a missing verse(with verse markers)
- [ ] [3] Blank word list for missing verse (with verse markers)
- [ ] [1]  Check pane just shows reference for missing verse (with verse markers)
- [ ] [3] Write Tests
- [ ] [3] PR Review

**Comment by RoyalSix** [comment]
This issue is related to another problem.
You cannot open a `new` project on develop right now that is not: `1TH`, `2TH`, `1TI`,  `2TI`, `GAL`, `PHM`, or `TIT` 
By new I mean a project that has never been opened in tC before (either coming from tS, or usfm file)

**Comment by RoyalSix** [comment]
The following shows in the check pane when the verse is not there instead of showing just the reference, is this OK?
<img width="1280" alt="screen shot 2018-03-21 at 11 07 25 am" src="https://user-images.githubusercontent.com/16184018/37728681-2b94d772-2cf8-11e8-8698-6821862aca84.png">

Other issues have already been resolved. @cckozie

**Comment by cckozie** [comment]
@RoyalSix Yes, that is what is supposed to show.
