### ISSUE TITLE
Fix occurrences issues with the English ULB

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3920]
- [ ] Reference #3302

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [6] Implement intelligent reordering
- [ ] [6] Unit tests
- [ ] [6] PR Review

**Comment by PhotoNomad0** [comment]
#### Notes

How do we know if a word occurrence should be changed?
- only if there is more than one instance of the word
- If multiple GL words in an alignment: if another instance of a word is closer in GL word order to other GL words in an alignment?  And swapping doesn't make another alignment to have GL words more distant.
- if single GL word in an alignment:  if another instance of a word is closer in GL word order to GL words in surrounding alignments (to left and right).  And swapping doesn't make distance worse for another alignment.

If there is only one GL word in an alignment, can’t think of an easy way to determine which instance may be closer since alignment order is based on Greek ordering.

**Comment by PhotoNomad0** [comment]
Found out this is to be a manual alignment.

**Comment by PhotoNomad0** [comment]
##### Errors due to UGNT aligned to wrong occurrence.
- [x] command, command 
     - [x] 1:3, 
     - [x] 1:14
disciplined.
- [x] everlasting, eternal, eternity
     - [x] 1:2b
- [x] faith
     - [x] 1:1
- [X] fool, fools, foolish, folly
     - [X] Titus 3:3 - Program bug not showing alignment to multiple greek words
- [X] good, goodness 
     - [X] Titus 3:8 swapped
- [X] pure, purify, purification
     - [X] 1:15a,b
- [X] save, saves, saved, safe
     - [X] 2:11

**Comment by cckozie** [comment]
Waiting for #3302 to be completed so I can test in UI.

**Comment by cckozie** [comment]
Looks good in 0.8.1-alpha.24-9855833
