### ISSUE TITLE
Re-Architect loading tools into tC core

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#3927]
Dependencies of tools created for tC core such as wordAlignment or translationWords are not being installed. The current tools only work by accident because tC core happens to use the same dependencies. We need to redesign how tools are loaded into the core so that tools don't crash if using other libraries.

There are two approaches which could be taken in steps for simplicity.

1. add a script in package.json to install the tool dependencies. This would be fairly easy.
1. Move the tools out of the core and load them from an external location on the file system.

The final step would provide additional benefits:

1. Easy for developers to create and add new tools.
1. Tools could be piped through webpack to entirely remove the concern for dependencies.
1. Tools could be updated apart from the core.

**Comment by benjore** [comment]
- Core (functions that EVERY tool requires, but no tool business logic)
  - [ ] Source content update (#3175)
  - [x] Project import/export
  - [x] Data persistence
  - [x] Network access
  - [x] Menu bar (night colored)
  - [x] Actions menu
  - [x] Stepper/Home
  - [x] Alerts
- Independent NPM modules 
  - Business logic required by MULTIPLE tools or Core (each an NPM module)
    - [ ] Selections (M)
    - [ ] Word alignment helpers (L)
    - [x] Tokenization
    - [x] Word-map
    - [x] USFM
    - [x] tC tool
  - tC UI-ish toolkit (one NPM module) [initial setup] (L)
    - [ ] Scripture pane (L)
    - [ ] Scripture pain plugin - HOC (L)
    - [x] Verse check (L)
    - [x] Verse editor (M)
    - [ ] Menu (M)
    - [ ] translationHelps code (s)
    - [ ] Comment (M)
    - [ ] Bookmark (S)
    - [x] Checkinfo card thingy (Smurf bar) (S)
  - Tool - Business logic not required by any other tool
    - [ ] tW (would need rewritten to use above components) (L)
    - [ ] tN tools (already need rewritten)
    - [ ] Alignment Tool (L)
- [ ] One abstract interface in tC tool (needs architected/designed)
