### ISSUE TITLE
Import Aligned Hindi UDB (Titus)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3956]
The team is trying to get Titus aligned before we pull it in.

- [ ] Import into tC Resources
- [ ] Verify that it displays correctly in the Scripture Pane
- [ ] Verify that alignments are appearing correctly

**Comment by RoyalSix** [comment]
Make alignments appear correctly

**Comment by mannycolon** [comment]
@benjore @jag3773 @cckozie This is blocked by Hindi UDB not being available yet.

**Comment by mannycolon** [comment]
What steps do we wanna take next ? and do we still want to get this into tC before creating the Alpha Release for review by the English & Hindi Content Teams? @benjore

**Comment by benjore** [comment]
@mannycolon Let's queue up the Alpha build without the aligned Hindi UDB (Titus). It's not ready yet and we can't wait any longer for it. I'm not even sure when it is going to be done (I have a question out to find out its timeline).
