### ISSUE TITLE
Import Aligned English UDB (Titus)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3965]
- [ ] Import into tC Resources
- [ ] Verify that it displays correctly in the Scripture Pane
- [ ] Make  highlights appear correctly

- [ ] Rename: UDB -> UDT (unfoldingWord Dynamic Text) - note: update this when the aligned UDB/UDT is brought in.

**Comment by mannycolon** [comment]
## List of words currently not highlighting in the UDT
- evil, wicked, wickedness
  - [x] Titus 1:12
- faith
  - [ ] Titus 2:10
- God
  - [ ] Titus 2:10
- good, goodness
  - [x] Titus 1:16
  - [x] Titus 2:7
  - [ ] Titus 2:10
- love, loves, loving, loved
  - [x] Titus 2:4
- power, powers
  - [x] Titus 1:9
- Savior, savior
  - [ ] Titus 2:10
- testimony, testify, witness, witnesses, eyewitness, eyewitnesses
  - [x] Titus 1:13
- works, deeds, work, acts
  - [x] Titus 1:16

**Comment by mannycolon** [comment]
@cckozie Above is a list of checks that were not highlighting in the UDT.  I fixed all of them except for checks for Titus 2:10 because it hasn't been aligned to the greek.
> from Perry Oakes: "Yes, that verse is waiting on a major edit, so there was no point trying to align it as-is."

**Comment by mannycolon** [comment]
All three panes (Greek (UGNT), English (ULT) and English (UDT)) should display a highlighted word per alignment data, except for `Titus 2:10 ` in the UDT.
