### ISSUE TITLE
Prevent English word list from jumping back to top when a word is removed

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord/translationCore#3968]
When I align a long verse, or bridge, the English text scrolls down off the page. I often want to drag a phrase onto the Greek. But after I scroll down and drag the first word onto the Greek, the English list resets to the top. This forces me to have to scroll down and find my place each time I want to move the next word of the phrase.

Please set long English word lists to remain in the position to where I manually move it until I decide to scroll to another position.

**Comment by benjore** [comment]
- [x] NOT scroll automatically when on the same verse
- [x] Scroll to the top when navigating to a new verse

**Comment by richmahn** [comment]
- [x] [5] Fix the jump to top of word list in wA
- [x] [4] Write tests for #3968
- [x] [1] PR Review for #3968
