### ISSUE TITLE
Links embedded in tHelps do not work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3977]
0.8.1-alpha.20-0890ac6
Clicking on any of the links in the right tHelps panel in tW just brings up an empty window.

**Comment by richmahn** [comment]
- [x] [2] Check what tHelps links are broken and why
- [x] [3] Update code to properly get the location of the local article file for differnet tHelps
- [x] [3] Display proper error message if article/resource not found
- [x] [3] Write tests for properly finding articles and handling missing one
- [ ] [2] PR Review for #3977

**Comment by richmahn** [comment]
Should also unblock #3981 by adding a message that the article couldn't be found in the article pane rather than a stack trace that keeps the app from loading.
