### ISSUE TITLE
Tool previously selected does not show in stepper bar after returning to projects page

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3989]
Do a clean install (delete the translationCore folders in both user and Application Support folders prior to installing app)
Import a project and proceed through validation stepper
Load the project with Word Alignment tool
Click the project icon in the menu bar
Notice that Word Alignment does not show in the stepper menu (ditto if Home is clicked in menu bar)
![image](https://user-images.githubusercontent.com/8171759/37105503-f38462e8-21f4-11e8-83d2-b9665369e34a.png)

**Comment by benjore** [comment]
Can also be replicated by going to the Home Screen.
<img width="1200" alt="screen shot 2018-05-09 at 10 20 26 am" src="https://user-images.githubusercontent.com/13352518/39823420-a406678e-5372-11e8-9e95-a71240d47b96.png">

**Comment by da1nerd** [comment]
@richmahn there is that `getSelectedToolName` selector that you can use to fetch the current tool name.

**Comment by richmahn** [comment]
- [ ] [2] Make it so the selected tool name shows in stepper
- [ ] [1] Tests for the stepper
- [ ] [1] PR review for #3989

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-1968c66.dmg

**Comment by cckozie** [comment]
Works in 1.1.0 (ac75c11)
