### ISSUE TITLE
Remove constraint that limits the Alignment Tool to only opening Titus (but keep the constraint for the OT!)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4022]
- User should be able to open any NT book in the alignment tool
- User may *only* open Titus in the tW tool
- If a non-Titus book has been selected, the tW `Launch` button should be disabled with a hover-over that says "Book not supported"
- Update `In this version of ${app}, only Titus projects can be loaded.` in the Import Online Project window to say `In this version of ${app}, translationWords only supports Titus projects. The alignment tool only supports New Testament projects`
- In the instruction card of the tools page, add `In this version of ${app}, translationWords only supports Titus projects. The alignment tool only supports New Testament projects`

**Comment by richmahn** [comment]
- [x] [6] Set up proper non-dev mode user constraints for wA (NT) and tW (Titus)
- [x] [4] Have tW launch button be disabled with hover-over if not Titus
- [x] [1] Update Import Online Project message about supported books
- [x] [1] Update tW & wA tool instruction text about supported books
- [x] [5] Write tests to verify can only launch the tools of the allowed books
- [x] [2] PR Review for #4022 - Remove wA constraints

**Comment by cckozie** [comment]
The disabling of the Load button and hover over is working, but the text on the online search page and on the instructions card of the tools page is not updated per this issue. Is that work that has not yet been done, or was it superseded by work being done on localization?

**Comment by richmahn** [comment]
It was done. Checking...

**Comment by cckozie** [comment]
The English text on the import from Door43 and tools instructions is now correct, but it looks like the Hindi is still the old text. Noted in #4125
