### ISSUE TITLE
Update the ULB to ULT

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4025]
ULB -> ULT (unfoldingWord Literal Text)

**Comment by mannycolon** [comment]
# Tasks
- [ ] [3] Update the ULB to ULT in tC Resources
- [ ] [3] Update references of ULB to ULT in tC, tW scripture pane and wA as needed.
- [ ] [3] Code clean up Cleanup

**Comment by cckozie** [comment]
There are many references to the ULB in tHelps, but I'm assuming that is not part of this issue.

**Comment by cckozie** [comment]
0.8.1-alpha.25-8a82d4e
It looks like the references to ULB have been changed to ULT, but it now takes ~15 seconds to open the expanded scripture pane in tW, and ~5 seconds in alignment. I don't see any errors in the console.

**Comment by mannycolon** [comment]
> There are many references to the ULB in tHelps, but I'm assuming that is not part of this issue.

Like you said that is not part of this issue.

**Comment by mannycolon** [comment]
> 0.8.1-alpha.25-8a82d4e
It looks like the references to ULB have been changed to ULT, but it now takes ~15 seconds to open the expanded scripture pane in tW, and ~5 seconds in alignment. I don't see any errors in the console.

I will take a look at it now and figure out why that's happening. Although I don't expect both tools to perform the same way because the wA tool doesn't have highlighted words, I do expect the expanded scripture pane to perform much better than that.

**Comment by jag3773** [comment]
@cckozie @mannycolon @benjore the .9.0-alpha shows Hindi as "ULT" -- this should not be the case.  Only the English resources were supposed to be updated.  The Hindi text should remain as ULB.

**Comment by mannycolon** [comment]
@jag3773 That's not what the story says
