### ISSUE TITLE
Check instructions should show GL words, not tHelps article title

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4032]
See #3864 for mockups
![image](https://user-images.githubusercontent.com/8171759/37364713-4727f58a-26c9-11e8-8794-dffcd96f49b6.png)

![image](https://user-images.githubusercontent.com/13352518/37366334-2e0fbe2a-26ce-11e8-9518-587a142154eb.png)

- [ ] The fallback is Greek.

**Comment by richmahn** [comment]
- [ ] [5] Make check instructions card show GL word from the Bible and not tW title
- [ ] [3] Write tests that check info has GL word, and Greek word if no GL alignment
- [ ] [2] PR Review for #4032 - Check card uses GL text

**Comment by richmahn** [comment]
@benjore Want to address a design issue/confirmation that like the Scripture Pane of the GL ULT, the words aligned to the Greek are not always next to each other, so I wanted to confirm that the following looks ok in the Check area where it says "Please select the translation for:"

![2018-03-16 1](https://user-images.githubusercontent.com/2839925/37534564-cc297360-290a-11e8-8c9b-2679adf3b1d2.png)

Note also that like in the Scripture Pane, how things are currently aligned, we can't know that "the" is part of "God ... Father"...that word in between could be "our glorious" for all we know.

**Comment by richmahn** [comment]
@benjore Another example from Hindi:

![2018-03-16 3](https://user-images.githubusercontent.com/2839925/37535052-31116eda-290c-11e8-9d4d-9b8298dbca58.png)

**Comment by benjore** [comment]
@richmahn That is the correct implementation. I think this issue is actually one with the alignment - I'm pretty sure the aligners want `the` to be highlighted as well, but I don't want tC to guess at that. The implementation is correct to only highlight what is in the alignment data.

**Comment by benjore** [comment]
An exception to this might be `God`' `s`... in which case we would rather have `God's` highlighted... but I don't think this issue is dealing with that. (Same with words like `self-control` - NOT `self`-`control`

**Comment by richmahn** [comment]
@benjore I do have it making sure in-between punctuation is included in the GL aligned text instead of a space if it is there, but only if it is in-between, so I do show "God's" instead of "God ... s", "self-controlled" instead of "self ... controlled", etc.
