### ISSUE TITLE
Localization gaps

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4125]
Fixed in 0.8.1-alpha.28-29223a3
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a5f72088-bc43-4074-8847-b44c54e7d7a6)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37844173-e4dce61e-2e94-11e8-96a0-3027cadd2fdb.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37844254-32bc4af0-2e95-11e8-892b-41b31608dcf0.png)
Most fixed in Fixed in 0.8.1-alpha.28-29223a3. Remainder is related to #2004
![image](https://user-images.githubusercontent.com/8171759/37844504-fbdcf6f0-2e95-11e8-844e-5832fd7a5dad.png)
Greek and Hindi are fixed in 0.8.1-alpha.28-29223a3. English resources are still not localized, but Ben says that is OK for now.
![image](https://user-images.githubusercontent.com/8171759/37844549-3162bd0a-2e96-11e8-836a-a75e46a805c0.png)
OK for now.
![image](https://user-images.githubusercontent.com/8171759/37844832-eef63306-2e96-11e8-9067-dba7dbfaa5cd.png)

![image](https://user-images.githubusercontent.com/8171759/37844993-593247dc-2e97-11e8-855a-7027c0343499.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37845048-7b7af910-2e97-11e8-863c-d0bb66983e8a.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37845066-8ef39984-2e97-11e8-8038-b445bafd4dc0.png)
All are fixed in 0.8.1-alpha.28-29223a3 except for "English" and the book name.
![image](https://user-images.githubusercontent.com/8171759/37845445-8ff83654-2e98-11e8-9ea2-f49f3ca65b1c.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37845575-f1ba2672-2e98-11e8-8285-5969b85ae855.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37845667-329329be-2e99-11e8-877b-f324c9f4bdd5.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37845697-4f099c54-2e99-11e8-86da-b7382d738ce4.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37845762-8ad6bc76-2e99-11e8-879f-90301e636640.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37845874-f1599e00-2e99-11e8-929c-011c0d92c62d.png)
Fixed in 0.8.1-alpha.28-29223a3
![image](https://user-images.githubusercontent.com/8171759/37846025-4d2022ae-2e9a-11e8-8bb8-97fef0985e9e.png)

**Comment by PhotoNomad0** [comment]
#### Looks like a lot that needs to be done here:
- Scripture Pane in tools:
  - [ ] localize add resources dialog - everything
  - [ ] localize Original language pop up text
  - [ ] localize "Step 1.Read"
- tW tool
  - [ ] ~localize Book name on left~
  - [ ] localize Step 1, select, "Please  select..."
  - [ ] localize Step 1 buttons: "Cancel", etc.
  - [ ] localize Step 2 buttons: "Bookmark", "Save and Previous", "Select", etc.
  - [ ] localize Step 2: "has been translated","no selection has been made"
  - [ ] localize Comment Box prompt and buttons
  - [ ] localize Edit Verse prompt and buttons
- WA tool
  - [ ] localize "Chapter" on left

#### tCore Changes:
  - [ ] ~Need to add list of Bible Book Names to localization table~
  - door43 import dialog:
    - [ ] localize "Enter URL"
    - [ ] localize "Cancel"
    - [ ] localize Book drop down
  - Project Cards:
    - [ ] localize time ago
  - Tools Page
    - [ ] localize gateway language drop down
    - [ ] localize WA description
    - [ ] localize tW description
   - Missing Verses validation stepper:  
    - [ ] localize "verses" 
    - [ ] localize Book name


#### Maybe not possible to localize:
- Localization of fields read from manifest: Language description, codes, Book descriptions
- Many old projects have language code and language name reversed in manifest.

**Comment by cckozie** [comment]
**NOT FIXED IN 0.8.1-alpha.28-29223a3**
Moved to #4209
The project reimport alert needs to have two strings; keys = projects\project_exists and projects\reimporting_not_supported
Currently is:
![image](https://user-images.githubusercontent.com/8171759/37930299-f61c8cc0-3107-11e8-9462-bc940717d608.png)
Should be:
![image](https://user-images.githubusercontent.com/8171759/37930312-0237849c-3108-11e8-92d4-52c9b37100ba.png)






--

**Comment by cckozie** [comment]
**NOT FIXED IN 0.8.1-alpha.28-29223a3**
Moved to #4207
More missing localizations on import alerts:
1. ![image](https://user-images.githubusercontent.com/8171759/37937857-09537498-3121-11e8-8705-d198bb33d5a8.png)

2. translationCore does not support checking for translationWords. It will not be loaded.

3. translationCore does not support checking for translationQuestions. It will not be loaded.

4. translationCore does not support checking for translationNotes. It will not be loaded.

5. translationCore does not support checking for Open Bible Stories. It will not be loaded.

6. Unable to find the manifest for project ${project_name}. It will not be loaded.

**Comment by cckozie** [comment]
**NOT FIXED IN 0.8.1-alpha.28-29223a3**
Moved to #4208
I think this is the Hindi version of the old text
![image](https://user-images.githubusercontent.com/8171759/37945487-2305369a-3146-11e8-860d-6c1f0fa997a3.png)
![image](https://user-images.githubusercontent.com/8171759/37945673-e477bfb4-3146-11e8-84d4-237928b7bf54.png)

**Comment by PhotoNomad0** [comment]
Split into three separate issues.

**Comment by PhotoNomad0** [comment]
Hindi book names:

Joel Mathew 
Here is what I have:

[“matthew” : “मत्ती“,
    “mark” : “मरकुस“,
    “luke” : “लूका“,
    “john” : “युहत्रा“,
    “acts” : “प्रेरितों के कामों“,
    “romans” : “रोमियों“,
    “1-corinthians” : “1 कुरिन्थियों“,
    “2-corinthians” : “2 कुरिन्थियों“,
    “galatians” : “गलतियों“,
    “ephesians” : “इफिसियों“,
    “philippians” : “फिलिप्पियों“,
    “colossians” : “कुलुस्सियों“,
    “1-thessalonians” : “1 थिस्सलुनीकियों“,
    “2-thessalonians” : “2 थिस्सलुनीकियों“,
    “1-timothy” : “1 तीमुाथैयुस“,
    “2-timothy” : “2 तीमुाथैयुस“,
    “titus” : “तीतुस“,
    “philemon” : “फिलेमोन“,
    “hebrews” : “इब्रानियों“,
    “james” : “याकूब“,
    “1-peter” : “1 पतरस“,
    “2-peter” : “2 पतरस“,
    “1-john” : “1 युहत्रा“,
    “2-john” : “2 युहत्रा“,
    “3-john” : “3 युहत्रा“,
    “jude” : “यहूदा“,
    “revelation” : “प्रकाशितवाक्य“] (edited)

**Comment by cckozie** [comment]
Book names in Door43 search fixed in #4169 
Fixed in #4147:
-Enter URL
-Cancel
-Book names in project list
-(Language names in project list is not localized which I am assuming is OK since we display the language code and not language name)

**Comment by cckozie** [comment]
Per Ben, these do not need to be localized. He suggested that 'We should probably change the "unfoldingWord Greek New Testament" to "Original Language" and that should be localized... but we don't have to deal with that now.'
![resources](https://user-images.githubusercontent.com/8171759/38214165-670b3798-3689-11e8-9a15-cf3216b36903.png)

**Comment by cckozie** [comment]
All of the problems have already been fixed, or approved by Ben as they are, or moved to new issues.
