### ISSUE TITLE
Scripture Pane spacing of word with apostrophe adds extra space

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4126]
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/38a616e2-1d33-43ca-a431-c1f70cbb01b9)

See `God' s`

![image](https://user-images.githubusercontent.com/13352518/37851015-54761728-2eab-11e8-9083-3c0748bc9386.png)

See `self- controlled`

**Comment by mannycolon** [comment]
- [ ] [3] Plan out implementation to remove spacing after words with punctuation.
- [ ] [3] Implement removal of spacing after words with punctuation.
- [ ] [2] Code cleanup for 4126.
- [ ] [2] PR Review for 4126

**Comment by mannycolon** [comment]
# Verify The following checks:

**pure, purify, purification:** 
 - [ ] `Titus 1:15`

**word of God, words of God, word of Yahweh, word of the Lord, word of truth, scripture, scriptures**
 - [ ] `Titus 2:5`

**good, goodness**
 - [ ] `Titus 1:8`

**Comment by cckozie** [comment]
0.8.1-alpha.27-0936021
It looks like the apostrophe is handled but not the hyphen. 
![image](https://user-images.githubusercontent.com/8171759/38115001-1c5c03c4-3370-11e8-8ff2-001c0086bfa7.png)
![image](https://user-images.githubusercontent.com/8171759/38115406-90e25666-3371-11e8-8971-256268a8d0ee.png)

**Comment by mannycolon** [comment]
@cckozie I got it fixed. However, it will only work if you reload the project from the usfm file.
