### ISSUE TITLE
Punctuation in the middle of a word not highlighted in the Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4128]
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/d46d5375-4be2-4741-8adf-a506d6f7aed4)

So above all of `God's` should be highlighted. 

- [ ] make all punctuation in the middle of the word highlighted (if the words/letters are highlighted)
- [ ] If there is punctuation that is in between two elements that were both aligned to the same Greek word. 

In other examples, `self-control` should all be highlighted.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [3] Plan out implementation to highlight punctuation that is in the middle of a word.
- [ ] [3] Implement punctuation highlighting.
- [ ] [2] Code cleanup.
- [ ] [2] PR Review for 4128

**Comment by cckozie** [comment]
The "God's" example of above is fixed, but not "self-controlled".
![self-controlled](https://user-images.githubusercontent.com/8171759/38158094-d91fe17c-3453-11e8-8b79-2ca40ae5882d.png)

**Comment by mannycolon** [comment]
@cckozie You have to make the selection. when you highlighted self-control you must highlight the hyphen in order for it to work. That is in the verse check component.

**Comment by mannycolon** [comment]
The target language pane only highlights whats been selected/highlighted in the verse check (Step 2).

**Comment by cckozie** [comment]
@mannycolon It selects all of "God's" when I just click on "God". The last sentence in the first comment on this issue indicates to me that it should work the same way for "self-controlled".

**Comment by mannycolon** [comment]
That is a bug related to the verse check and not the scripture pane which this story is related to the scripture pane.

**Comment by mannycolon** [comment]
@cckozie
