### ISSUE TITLE
Inconsistent handling of disconnected selections

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4130]
When the gateway language is disconnected, it is handled like this, `"of ... chosen people"` But when a target language is disconnected, it is handled like this, `"la" "Mungu"`. 

- [ ] When there are highlights in the target language only divided by a space, treat those like one contiguous selection (which would display like `"la Mungu"`). 
- [ ] When there are two disconnected selections in the target language (with at least one letter in between them), then handle it the same way we treat the GL, e.g. `"neno ... Mungu"` (NOT `"neno" "Mungu"`)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/97b138cd-7678-403b-bffc-25f1fdf00934)

![image](https://user-images.githubusercontent.com/13352518/37850755-64b96938-2eaa-11e8-9ecd-14bccd356a56.png)

## Notes
- It appears that if the two words are separated by a line break, everything works as advertised. It is only when two words are on the same line that this is an issue.

**Comment by RoyalSix** [comment]
# Tasks 
- [ ] [4] Fix Disconnected Highlight Behavior
- [ ] [3] Write Tests
- [ ] [3] PR Review

**Comment by cckozie** [comment]
Since the second bullet point specifically states "at least one letter in between them", I believe that in this situation the entire "self-controlled" should be highlighted even though the two words were selected separately. Unless @benjore disagrees.
![self-controlled](https://user-images.githubusercontent.com/8171759/38158094-d91fe17c-3453-11e8-8b79-2ca40ae5882d.png)

**Comment by RoyalSix** [comment]
@benjore I am confused by the second point `When there are two disconnected selections in the target language (with at least one letter in between them), then handle it the same way we treat the GL, e.g. "neno ... Mungu" (NOT "neno" "Mungu"`

"neno" "Mungu" has no letter between them yet you are saying that it needs to have the ellipsis. Should the example above not have a continuous selection?

**Comment by benjore** [comment]
@RoyalSix That example is about the phrase `neno la Mungu`. So if just `neno` and `Mungu` are highlighted (not `la`) then it should show up `"neno ... Mungu"` and NOT `"neno"` `"Mungu"`.

**Comment by RoyalSix** [comment]
@benjore Ahh ok. I am going to have to make some changes then. Thanks for clarifying!
