### ISSUE TITLE
Fix Localization gaps in ScripturePane and WordAlignment

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4144]
Part of https://github.com/unfoldingWord-dev/translationCore/issues/4125

**Comment by PhotoNomad0** [comment]
#### To be done in Scripture Pane:
  - [x] localize add resources dialog - everything
  - [x] localize Greek Language pop up text
  - [x] localize "Step 1.Read"
  - [x] localize Hover Tips
  - [x] localize Chapter Dialog

#### To be done in WA tool:
  -  ~localize "Chapter" on left~ <= this is in tCore
  - [x] localize Greek Language pop up text for topWords on word cards.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [5] localize WA and SP
- [ ] [5] PR Review

**Comment by cckozie** [comment]
Testing:
#### To be done in Scripture Pane:
  - [x] localize add resources dialog - everything (The buttons have missing keys, but I'm assuming that is related to the problems in #2004)
  - [x] localize Greek Language pop up text
  - [x] localize "Step 1.Read"
  - [x] localize Hover Tips
  - [x] localize Chapter Dialog

#### To be done in WA tool:
  -  ~localize "Chapter" on left~ <= this is in tCore
  - [x] localize Greek Language pop up text for topWords on word cards.
