### ISSUE TITLE
Fix Localization gaps in TranslationWords

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4145]
Part of https://github.com/unfoldingWord-dev/translationCore/issues/4125

**Comment by PhotoNomad0** [comment]
#### to be done in tW tool
  - [ ] ~localize Book name on left~
  - [x] localize Step 1, select, "Please  select..."
  - [x] localize Step 1 buttons: "Cancel", etc.
  - [x] localize Step 2 buttons: "Bookmark", "Save and Previous", "Select", etc.
  - [x] localize Step 2: "has been translated","no selection has been made"
  - [x] localize Comment Box prompt and buttons
  - [x] localize Edit Verse prompt and buttons

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [5] localize TW and VC
- [ ] [5] PR Review

**Comment by cckozie** [comment]
Testing:
  - [ ] ~localize Book name on left~
  - [x] localize Step 1, select, "Please  select..."
  - [x] localize Step 1 buttons: "Cancel", etc.
  - [x] localize Step 2 buttons: "Bookmark", "Save and Previous", "Select", etc.
  - [x] localize Step 2: "has been translated","no selection has been made"
  - [x] localize Comment Box prompt and buttons
  - [x] localize Edit Verse prompt and buttons
