### ISSUE TITLE
[2] SPIKE: Align to unexpected verse

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4151]
What will be affect by this? 
What will need to be changed to make this possible? 

Goal: be able to break this epic into stories 

## Notes
- Mockups for Unexpected alignment is at #3739 . Please note that @klappy has done a lot of research into this already. 
- The work for this should also take into consideration support for verse spans covered in #4490 . 
- The data structure needs to be robust enough to also work for unexpected verse selection (tW & tN tools) and verse spans in tW & tN tools.

**Comment by PhotoNomad0** [comment]
### Notes from Klappy:

- add column to CSV with reference in "JAS001002".

#### examples:
##### **USFM**
```
\zaln-s | x-strong="G23160" x-lemma="θεός" x-morph="Gr,N,,,,,GMS," x-occurrence="1" x-occurrences="1" x-content="Θεοῦ"
\w परमेश्‍वर|x-occurrence="1" x-occurrences="1" x-reference="JAS001002"\w*
\zaln-e\*
```

##### **JSON**
```
{
 "contextId": {
  "reference": {
   "bookId": "tit",
   "chapter": 1,
   "verse": 1
  },
  "tool": "translationWords",
  "groupId": "apostle",
  "quote": "ἀπόστολος",
  "strong": [
   "G06520"
  ],
  "occurrence": 1
 },
 "selections": [
  {
   "text": "an",
   "occurrence": 1,
   "occurrences": 1,
   "reference": {
    "bookId": "tit",
    "chapter": "1",
    "verse": "2"
   }
  },
  {
   "text": "apostle",
   "occurrence": 1,
   "occurrences": 1
  }
 ],
 "userName": "klappy",
 "modifiedTimestamp": "2018-06-14T22:56:18.251Z",
 "gatewayLanguageCode": "en",
 "gatewayLanguageQuote": "apostle, apostles, apostleship"
}
```

**Comment by PhotoNomad0** [comment]
### tasks
- [ ] write sharable methods to convert between x-reference format and reference object format
- [ ] add column to CSV export for reference in x-reference format if present in alignment
- [ ] on USFM3 import convert x-reference to reference object in alignment object
- [ ] on USFM3 export convert reference object in alignment object to x-reference format

#### also note
- there are some estimates in https://github.com/unfoldingWord-dev/translationCore/issues/3739 for UI
- waiting for feedback about WA architectural changes.
