### ISSUE TITLE
Wrong text for book name in Word Alignment menu

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4161]
Could this be related to RTL languages or if book name is not in manifest? Seeing similar results in Urdu projects.
https://git.door43.org/TC_SAVE/ar_eph_text_ulb
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/25d75605-399a-4b9b-8e10-49ed6bda9e3c)
![image](https://user-images.githubusercontent.com/8171759/38038845-9286473a-3271-11e8-99a8-3e0446d972df.png)

https://git.door43.org/EllDoubleYew/ar_luk_text_ulb
![image](https://user-images.githubusercontent.com/8171759/38037094-bfaebe76-326d-11e8-8d54-9e1bb1d01d9b.png)
![image](https://user-images.githubusercontent.com/8171759/38038922-bd595a9c-3271-11e8-8368-cb764a3f8964.png)

**Comment by richmahn** [comment]
- [ ] [1] Determine what is causing wrong book names
- [ ] [5] Fix wrong book names
- [ ] [2] Write tests to verify names (ltr and rtl languages)
- [ ] [1] PR Review for #4161

**Comment by richmahn** [comment]
Don't see how these titles are wrong: "رِسَالَةُ بُولُسَ ٱلرَّسُولِ إِلَى أَهْلِ أَفَسُسَ" according to Google Translate is "Epistle to the Ephesians".

For the Luke one, "إِنْجِيلُ لُوقَا" translates to "The Gospel of Luke". Moving to QA and closing tasks.
