### ISSUE TITLE
Add new fields for Verse Edit & Comments

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4242]
Take-off on #4235

3 new fields will need to be created activeBook activeChapter activeVerse (actual names are negotiable). This would give the context needed to make all the above fields about which check was open make sense (for the tW tool). All of the above fields for the Word Alignment tool would still be blank except for the 3 new fields mentioned in this paragraph, which would still give helpful context. 

These fields should be added to the meta-data for at least Comments & Verse Edits. 

## Notes
- For edits in the Word Alignment Tool, only show which book + chapter + verse was open, keep the Group ID et. al. blank. 
- Be sure to include this data in CSV Export. Some fields were de-populated when we added "Edit Any Verse". This issue should allow those fields to be repopulated.
- Look at issue #4235 to see which columns were depopulated, and add that data back in to the files for tW.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [4] Add activeBook, activeChapter, activeVerse to verse edit and comments
- [ ] [4] Add activeBook, activeChapter, activeVerse to csv exports (for both verse edit and comments)
- [ ] [1] PR REVIEW for #4242
