### ISSUE TITLE
NPM Modules: Selections

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4307]

**Comment by richmahn** [comment]
- [ ] [3] Create NPM module for Selections
- [ ] [5] Move Selections business logic into Selections module
- [ ] [2] Verify tests for Selections module
- [ ] [1] PR review for #4307
