### ISSUE TITLE
tC UI toolkit: Comment

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4315]

**Comment by richmahn** [comment]
- [ ] [5] Move Comment UI to tC UI Toolkit
- [ ] [3] Write tests for Comments
- [ ] [1] PR Review fro #4315
