### ISSUE TITLE
tC UI toolkit: Bookmark

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4316]

**Comment by richmahn** [comment]
- [x] [3] Move Bookmark UI to tC UI toolkit
- [x] [3] Write tests for Bookmark
- [x] [1] PR Review fro #4316
