### ISSUE TITLE
Allow selecting and dragging multiple words together from the words list in Word Alignment

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4354]
As an aligner I would like to be able to select multiple words from the word list so that I can align them all to the same Greek word (or combination thereof) without having to drag them individually.

## Specs
- [x] This only works for words in the word bank
- [x] No `command` or `CTRL` necessary
- [x] A single click selects
- [x] Clicking again deselects it
- [x] Clicking `esc` deselects all

## Consider
(holding CTRL/CMD key down while clicking multiple words as in multi-select dropdown list)

![image](https://user-images.githubusercontent.com/13352518/40183112-997456dc-59b2-11e8-90f2-40d4a7a2bc3f.png)
![image](https://user-images.githubusercontent.com/13352518/40183120-9f0628f0-59b2-11e8-9e03-160cf0086c7b.png)

**Comment by da1nerd** [comment]
this is done except for the preview drag. For some reason there is a severe performance hit when rendering a custom drag preview.

**Comment by da1nerd** [comment]
@benjore @cckozie I spent a LOT of time trying to figure out how to get the drag preview to work correctly without a regression in performance. The drag preview is what the user sees while dragging the words.

The problem is that dynamically rendering the selected words makes the UI super duper slow.

The screenshot below shows the best solution I've found, which is to display a static image while dragging multiple words. The preview shows three tokens with the top and bottom fading out to white to indicate the user is dragging **some quantity** of words.

![screenshot from 2018-08-21 16-07-09](https://user-images.githubusercontent.com/166412/44433842-e86f9080-a55c-11e8-9454-f984452bada2.png)

Dragging single words still works as before.
Without going into a lot of detail, the rendering of single words happens for free so there is no performance hit.
![screenshot from 2018-08-21 16-13-03](https://user-images.githubusercontent.com/166412/44433877-2bc9ff00-a55d-11e8-8683-0858e4727cde.png)

Is this acceptable?

**Comment by benjore** [comment]
@neutrinog I'm understanding that the problem is showing more than one box moving at once. (Correct?) Let's try this modification: 

The user can still select multiple words from the word bank, they all turn blue (as per your screen shot above). When dragging that group, only one blue box gets dragged that says `[4 words]` or however many words are being dragged. When the user drops that box on a Greek box, the `[4 words]` disappears and the 4 individual words appear in the alignment box as expected, those same words in the word bank get grayed out as expected.

**Comment by cckozie** [comment]
@benjore OK'd displaying just the number of words when dragging as in:
![image](https://user-images.githubusercontent.com/8171759/44821809-243dd200-abbd-11e8-8253-62f5bd6d384e.png)
Works in 1.0.0 (71a9a28)
