### ISSUE TITLE
Manifest updates & project naming

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4403]
### Includes:
- UI changes to project details page
- UI changes to title bar to show project nickname instead of project file name as well as popup text (only if truncated)

### Notes:
- project name will be in format ("Explicit Project and Type"): `[lang_id]\_[resource_id]\_[project_id]\_[type]`
  - the `resource_id` ("Translation Identifier") will be stored in `manifest.project.resourceId`
  - the `project_id` will be stored in `manifest.project.id`
  - `lang_id` stored in `manifest.target_language.id`
  - the project `nickname` will be stored in `manifest.project.nickname` - not required

@photonomad0 - Revised 6/7/18 - Here is the revised list of QA fixes as well as addresses to spec changes:
1. The Translation Identifier field is now vertically aligned with the Language Name field
2. The info icon with popover is now implemented for "Translation Identifier"
3. The menu bar displayed when a tool is open displays the project name and will show the nickname as hover
4. If A-B is entered in the translation id field, the warning about Latin characters should appear after  the dash is entered rather than after the B is entered.
5. The UI should limit the field length length to 4 rather that re-disabling the Continue button when the 5th character is entered.
6. removed the text "Project:" in the menu title bar between the folder icon and the project name. 
7. did not change project card as it is outside of scope (at least at the moment).

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [8] Add translation id and nickname to project details page
- [ ] [8] Unit tests for project details page
- [ ] [16] Changes to title bar to show project nickname and popup text
- [ ] [16] Unit tests for title bar
- [ ] [3] Review PR [4403]

**Comment by cckozie** [comment]
There are UI differences between the design and implementation.
1. The Translation Identifier field is not vertically aligned with the Language Name field (regardless of whether or not there is a warning message displayed)
2. The info icon with popover was not implemented
3. The menu bar displayed when a project is open still displays the project name, not the nickname
Also:
4. If A-B is entered in the translation id field, the warning about Latin characters should appear after  the dash is entered rather than after the B is entered.
5. The UI should limit the field length length to 4 rather that re-disabling the Continue button when the 5th character is entered.

@benjore I think you mistakenly reverted the text in the menu title bar to add the word "Project:" between the folder icon and the project nickname in the mockup in #3421. Consequently, that was carried into the main screen menu bar in this issue. Do you want to expand the scope of this issue to remove it again, or create another issue to remove it? Also, did you intend to replace the project file name with the project nickname on the project card?

**Comment by PhotoNomad0** [comment]
> The UI should limit the field length length to 4 rather that re-disabling the Continue button when the 5th character is entered.

@cckozie - is this a suggested new requirement?
@PhotoNomad0  - I would suggest that such is or should be standard coding practice.

**Comment by PhotoNomad0** [comment]
> The menu bar displayed when a project is open still displays the project name, not the nickname

Do you mean here when a tool is open?
@PhotoNomad0 - Yes, that is in the mockup

**Comment by benjore** [comment]
@cckozie In the top menu bar, please remove the `User:`, `Project:`, and `Tool:`. I must have used an old mockup and forgotten to update it.

**Comment by PhotoNomad0** [comment]
> The UI should limit the field length length to 4 rather that re-disabling the Continue button when the 5th character is entered.
> 
> @cckozie - is this a suggested new requirement?
> @PhotoNomad0  - I would suggest that such is or should be standard coding practice.

@benjore - do you want to limit text input for this to 4 characters?  Do we want to give an audio or visual feedback if the user tries to enter more?

**Comment by PhotoNomad0** [comment]
@benjore - on the design for the Translation identifier info icon.  How we currently implement the info icon is a clickable.  I can implement to show an info popup like such:

![screen shot 2018-06-04 at 4 33 20 pm](https://user-images.githubusercontent.com/14238574/40940250-3b7444a4-6815-11e8-81e5-47078dae435b.png)

But what you have displayed is hover text.  It may take me a while to figure out how to implement hover text as a clickable.  Or did you intend to have hover text shown over the info icon?

**Comment by PhotoNomad0** [comment]
I can implement hover text for the info icon. It will look like this:

![screen shot 2018-06-04 at 4 52 51 pm](https://user-images.githubusercontent.com/14238574/40941085-c86e9182-6817-11e8-9cdf-37af461eccfc.png)

**Comment by PhotoNomad0** [comment]
@cckozie Here is the revised list of changes to address QA issues after spec changes:

1. The Translation Identifier field is now vertically aligned with the Language Name field
2. The info icon with popover is now implemented
3. The menu bar displayed when a tool is open displays the project name and will show the nickname as hover:
4. If A-B is entered in the translation id field, the warning about Latin characters should appear after  the dash is entered rather than after the B is entered.
5. The UI should limit the field length length to 4 rather that re-disabling the Continue button when the 5th character is entered.
6. removed the text "Project:" in the menu title bar between the folder icon and the project name. 
7. did not change project card as it is outside of scope (at least at the moment).

**Comment by cckozie** [comment]
From Bruce's list above.
- [ ] The Translation Identifier field is now vertically aligned with the Language Name field
- [x] The info icon with popover is now implemented
- [x] The menu bar displayed when a tool is open displays the project name and will show the nickname as hover:
- [x] If A-B is entered in the translation id field, the warning about Latin characters should appear after the dash is entered rather than after the B is entered.
- [x] The UI should limit the field length length to 4 rather that re-disabling the Continue button when the 5th character is entered.
- [x] removed the text "Project:" in the menu title bar between the folder icon and the project name.

**Comment by cckozie** [comment]
in 0.10.0 (e6fe53e)
Still a couple unresolved issues:
1. The top row edit boxes are not vertically aligned
![image](https://user-images.githubusercontent.com/8171759/41374139-f694550e-6f17-11e8-80c3-ed7ecc27b814.png)

2. info icon hover is not localized
![image](https://user-images.githubusercontent.com/8171759/41381380-4ace0b00-6f2d-11e8-850b-a38fa47f64bf.png)

**Comment by PhotoNomad0** [comment]
@cckozie - yes the hint localization is fixed as of `Version 0.10.0 (757d4ef)`.  The mis-alignment seems to be only when there are warnings.  Otherwise they line up.  Hmmm.

**Comment by cckozie** [comment]
0.10.0 (a48d474) 
1. The only time the top two fields are vertically aligned is when there are no warnings.
2. There is no hover popup on truncated project names in the title/menu bar if there is no project nickname. (@benjore What is the desired behavior? The second bullet in the first comment indicates that the title bar should show the project nickname. The high level epic mockup shows the project name in the title bar with the nickname as a popup. Which is correct?)

**Comment by PhotoNomad0** [comment]
@cckozie - actually seems to be issue that if there is no text in Language Name it is taller with warning, if I add some text it matches the height of translation ID with warning.

**Comment by PhotoNomad0** [comment]
> 0.10.0 (a48d474) 
> 1. The only time the top two fields are vertically aligned is when there are no warnings.
> 2. There is no hover popup on truncated project names in the title/menu bar if there is no project nickname. (@benjore What is the desired behavior? The second bullet in the first comment indicates that the title bar should show the project nickname. The high level epic mockup shows the project name in the title bar with the nickname as a popup. Which is correct?)

Moving these last two items into separate issues:

https://github.com/unfoldingWord-dev/translationCore/issues/4630
&
...

**Comment by cckozie** [comment]
With the 2 items directly above being moved to new issues, and the other issues related to the parent epic being handled in the sibling issues, I'm QA passing this one.

**Comment by benjore** [comment]
Desired behavior: 
- show the project name in the top menu
- hover function: 
  - if there is a project nickname, display it in the hover
  - if the project name has been truncated, show the expanded version of the project name in the hover. 
  - if there is both a nickname & a truncated name, show them both: first line - expanded project name, second line - nickname
  - if their is neither (nickname or truncated name), show no hover

This will be covered in #4632
