### ISSUE TITLE
rename repos to match spec.

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4404]
### Steps:
- The user should be prompted and asked if they want to update the name of their project to the new naming convention.
- If renamed The repo should also be renamed on DCS (Door43).

### Notes:
- project name will be in format ("Explicit Project and Type"): `[lang_id]\_[resource_id]\_[project_id]\_[type]`
  - the `resource_id` ("Translation Identifier") will be stored in `manifest.project.resourceId`
  - the `project_id` will be stored in `manifest.project.id`
  - `lang_id` stored in `manifest.target_language.id`
- example would be `en_ulb_tit_book`

### Scenarios: 
- existing project in tC needs to be migrated
  - (happens when the user upgrades to 0.10 release)
  - 1. when the user first opens a project, bring up the project details page to confirm/update the project deets
  - 2. when the user clicks save (on the project details page), prompt the user about the project renaming. (Throw prompt telling the user that their project has been renamed.)
  - 3. (Ideal) Repo is renamed on Door43 (if it already exists on D43). 
- import a local tC project in tC (.tcore)
- import a local tStudio project
- import a local USFM project
- import an online Door43 project (tC or tS)

Closely related to #4550

**Comment by PhotoNomad0** [comment]
@RoyalSix - I will be adding resource_id and nickname to projectInformationCheckReducer

**Comment by PhotoNomad0** [comment]
@RoyalSix - when you make the new project name, convert it to all lower case so that it matches spec.

**Comment by PhotoNomad0** [comment]
@benjore @cckozie  - trying to think through the possible workflows here for when we.  What I see:
- [ ] import from DCS: we currently rename project to match spec without asking (and no change to repo name on DCS).  **Do we want to change this behavior to add prompt first?**
- [ ] local import: we currently rename project to match spec without asking. This would remain the same.
- [ ] on open of existing project: we should just prompt to rename if manifest is migrated and project name does not match spec.
- [ ] on edit project details screen: when user clicks save, if project name does not match spec. (e.g. lang_id or resource_id changed) we prompt if OK to rename project.

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - questions about renaming on DCS:
- [ ] if rename fails on DCS do we still want to rename the local project name?
  - not sure what failures we can detect.  Do we just want a generic DCS rename failure message?
- [ ] if we prompt to allow internet usage, and the user selects no, what should be the behavior?

**Comment by PhotoNomad0** [comment]
#### Note - renaming on DCS moved to new issue.

**Comment by cckozie** [comment]
@benjore Re: project name will be in format ("Explicit Project and Type"): [lang_id]\_[resource_id]\_[project_id]\_[type]
Since we don't prompt for 'type' on USFM imports, should the 'type' be left blank or set to something else? (Currently it's being set to 'text'; e.g. en_ult_mat_text)

**Comment by cckozie** [comment]
- The user should be prompted and asked if they want to update the name of their project to the new naming convention.

When I select an existing project it is automatically renamed without a prompt or warning.

**Comment by PhotoNomad0** [comment]
@benjore - since we haven't implemented rename on Door43 yet, shall we still do the prompt and change the text on the prompt to be "The repository for this project will be renamed to: <new_name> How would you like to proceed?"

**Comment by PhotoNomad0** [comment]
@benjore - also what should be the behavior if we prompt to rename and there is a project with that name already?

**Comment by PhotoNomad0** [comment]
@cckozie - to match new requirements, when a project does not match the naming spec, project details are opened to allow them to review translation identifier, then on save the project is renamed and the user is notified of the new name.

**Comment by cckozie** [comment]
0.10.0 (a48d474) 
1. When importing a USFM project, if the user cancels on the project details screen, the import is canceled without warning the user, and the project is left in the imports folder.
2. Some tstudio projects import without the user being taken through the project details screen, so the project is not renamed to meet the spec.
[es-419_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/2115519/es-419_tit_text_reg.tstudio.zip)
3. The primary button on the project stepper screens now has the text 'Save Changes' or 'Overwrite' instead of 'Continue' if the import is canceled when that is the active button text. (This may be a problem caused by the reimport issue which is not yet implemented)

**Comment by PhotoNomad0** [comment]
> 3. The primary button on the project stepper screens now has the text 'Save Changes' or 'Overwrite' instead of 'Continue' if the import is canceled when that is the active button text. (This may be a problem caused by the reimport issue which is not yet implemented)

@cckozie - can you clarify the steps to reproduce this?

**Comment by PhotoNomad0** [comment]
@cckozie - nevermind, finally understood that the button state is persisting.

**Comment by PhotoNomad0** [comment]
being fixed as part of https://github.com/unfoldingWord-dev/translationCore/pull/4642

**Comment by cckozie** [comment]
In reference to the above problem:
  2. Some tstudio projects import without the user being taken through the project details screen, so 
  the project is not renamed to meet the spec.
  [es-419_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/2115519/es-419_tit_text_reg.tstudio.zip)

In 0.10.0 (4add745), the Continue button is disabled on the project details screen even though all required fields have legitimate values when the screen is first displayed. If I change one of the letters in the Translation ID field, then the Continue button is enabled.
After the Continue button is clicked, it takes about 6 seconds before the Missing Verses screen is displayed. (Far longer than when importing any other Titus project)

**Comment by PhotoNomad0** [comment]
> 2. Some tstudio projects import without the user being taken through the project details screen, so
> the project is not renamed to meet the spec.
> es-419_tit_text_reg.tstudio.zip

@cckozie - In 0.10.1 (2c39a1e), the user is taken to project details screen, so that is already fixed.

but the continue button does initialize to disabled, will fix that.

> After the Continue button is clicked, it takes about 6 seconds before the Missing Verses screen is displayed. (Far longer than when importing any other Titus project)

I am seeing a 3 second delay on my 10 year old windows PC before the missing verses page comes up.  Recommend making a new issue as it is a pre-existing condition and looks like not an easy one to fix. @benjore

**Comment by PhotoNomad0** [comment]
> > After the Continue button is clicked, it takes about 6 seconds before the Missing Verses screen is displayed. (Far longer than when importing any other Titus project)
> 
> I am seeing a 3 second delay on my 10 year old windows PC before the missing verses page comes up.  Recommend making a new issue as it is a pre-existing condition and looks like not an easy one to fix. @benjore 

@benjore - maybe as a temporary workaround we put up a progress dialog.  We already have a "Loading..." string we could use on it.

**Comment by cckozie** [comment]
@benjore @PhotoNomad0 I moved the problem with the delay before the missing verses screen to issue #4696.

**Comment by cckozie** [comment]
0.10.1 (b64ddc5)
[en_1th_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/2202592/en_1th_text_reg.tstudio.zip)

If the project has no missing verses (not certain missing verses are the determining factor), the user is returned to the project details screen after responding to the 'your project has been named' alert. If the cancel button is then clicked, the user is sent to the tools page with no project selected.
![image](https://user-images.githubusercontent.com/8171759/42827350-c42b961e-89ab-11e8-847e-ab4259fe0187.png)

**Comment by PhotoNomad0** [comment]
Fixed in PR https://github.com/unfoldingWord-dev/translationCore/pull/4669

**Comment by cckozie** [comment]
0.10.1 (ee3f8f5)
@PhotoNomad0 Any idea why I would be getting this error when importing [rmr-x-bsa_mat_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/2207273/rmr-x-bsa_mat_text_ulb.tstudio.zip)

![image](https://user-images.githubusercontent.com/8171759/42906131-c7b33c7a-8a9f-11e8-9b57-49011bb15e8e.png)

**Comment by PhotoNomad0** [comment]
@cckozie - no initial ideas.  I'm guessing this is on Mac?

**Comment by cckozie** [comment]
Yes, on a Mac. Here's the console message:
![image](https://user-images.githubusercontent.com/8171759/42907091-7745ae5a-8aa2-11e8-8a65-bdcac1278978.png)

**Comment by cckozie** [comment]
0.10.1 (ee3f8f5)
1. Translation Identifier shows instead of the book name on new Door43 repos.
I imported the en_act project twice, once giving it the Translation Identifier 'ust' and once 'new'

![image](https://user-images.githubusercontent.com/8171759/42908253-08d41e26-8aa6-11e8-96d4-483df665f0ff.png)

2. I don't know if it's really a problem, but I'm seeing these errors in the console when choosing to create a new repo
![image](https://user-images.githubusercontent.com/8171759/42908321-3cefe14a-8aa6-11e8-8616-bc3eb71e74a7.png)

**Comment by cckozie** [comment]
Moved the above problems with [rmr-x-bsa_mat_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/2207273/rmr-x-bsa_mat_text_ulb.tstudio.zip)  to #4734.

**Comment by cckozie** [comment]
The problem with [en_1th_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/2202592/en_1th_text_reg.tstudio.zip) is fixed in 0.10.1 (b411d84)
