### ISSUE TITLE
Write code to figure out which language should be displayed in the tool dropdown based on available book/tool/language combo

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4424]
**Mclean**: copied from epic:
- Minimum requirements for a checking tool: aligned default_literal translation + required tH (e.g. tW for tW Tool, tN + tA for tN Tool, etc.
- to differentiate in the code between original languages, aligned ULTs (part of GL), other GL texts, and Target Languages.))

#### Questions:
- how do we determine what is a literal translation (versus dynamic)?  Answer - we don't care, we use any bible that has alignment data.  And we show all bibles with alignment data.
- what are minimum requirements for language in WA?  ~Just an aligned default_literal translation?~ Must have a bible with alignment data.

**Comment by PhotoNomad0** [comment]
### tasks:
- [ ] [4] change algorithm to look for bibles with alignments for language
- [ ] [4] change algorithm to verify sets of resources for tools
- [ ] [4] change UI to use tool type as filter for supported languages
- [ ] [4] change UI to dynamically determine default_language resource to use.
- [ ] [8] add unit tests

**Comment by PhotoNomad0** [comment]
#### Note: 

English will now be missing for every book but Titus until this issue is finished: https://github.com/unfoldingWord-dev/translationCore/issues/4805

@cckozie

**Comment by cckozie** [comment]
English and Hindi only available on Titus, none available on other books. Need to wait for #4805 to be implemented before further testing.
QUESTIONS:
1. Should this filter be applied to both tW and wA?
2. Should there be some text similar to (No Gateway Languages available) be displayed rather than a blank dropdown?

**Comment by benjore** [comment]
1. Covered in #4937
2. Covered in #4936

**Comment by cckozie** [comment]
1.0.0 (e375ee0)
I copied the lexicons and translationHelps folders from en to ru expecting Russian to now be an option for the GL on the tW tools card. Only English still appears in that dropdown.
Also need to copy in a resource that is aligned in order for it to appear in the dropdown list.

**Comment by cckozie** [comment]
1.0.0 (e375ee0)
Works
