### ISSUE TITLE
Finish tW Rewrite With Api Changes

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#4534]

**Comment by RoyalSix** [comment]
- [ ] Then we will need to incorporate the changes Joel made in order to receive the correct data for tW to work again (i.e. wordAlignmentReducer from the API of `tc-tool`) 

- [ ] Then we will need to either A. Have the strings in the ui-toolkit (And do it the right way later), or B. Expose the strings from the tool to the toolkit in each component.

- [ ] Then we can make a final PR to `translationCore` (Some things from the original PR in 4492 may not be needed after incorporating Joels changes, forsure somethings will though such as removing the GroupMenu ) and `translationWords` repos and everything should be working.

**Comment by RoyalSix** [comment]
# Tasks 

- [x] Create Method To Get Alignment Data into tW
- [x] Create Method To Get Locale In tW

**Comment by RoyalSix** [comment]
Associated PRs are in #4318

**Comment by cckozie** [comment]
I'm assuming that the work done here will all be tested in #4318
