### ISSUE TITLE
update repo name on DCS when projects are renamed in tC

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4550]
DCS renaming:

See full spec at https://github.com/unfoldingWord-dev/translationCore/issues/3421

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [2] Add check for and prompt to rename Door43 repo
- [ ] [3] Add git commands to rename Door43 repo
- [ ] [1] Add internet access prompt
- [ ] [2] Do Door43 rename repo
- [ ] [2] Add check and prompt on Door43 rename conflict
- [ ] [2] Add error warning for Door43 rename failures
- [ ] [4] Create new alert option dialog with contact help-desk button.
- [ ] [4] add method to dynamically change text on Project InfoCard "Save" button
- [ ] [4] Update unit tests
- [ ] [3] PR review [4550]

**Comment by PhotoNomad0** [comment]
**Blocked** - need DCS api for rename

**Comment by cckozie** [comment]
@PhotoNomad0 You need to add a task to clean up the 'Pardon our mess,...' verbiage on the local rename alert.

**Comment by jag3773** [comment]
@PhotoNomad0 and @RoyalSix If DCS doesn't support the rename currently, then I would suggest you create a new repo and delete the old one.

**Comment by RoyalSix** [comment]
@jag3773
Yes I will do that, the alternative is not working like I’d thought haha

**Comment by RoyalSix** [comment]
```
    if (this.props.alertModalReducer.button1 && button2) {
      buttonActions.unshift(
        <button
          label={translate('buttons.cancel_button')}
          className="btn-second"
          disabled={alertDialogLoading}
          onClick={callback ? () => { callback(button2) } : closeAlertDialog}
        > 
        <div>{this.props.alertModalReducer.button2}</div>
        </button>
      );
    }
```

**Comment by PhotoNomad0** [comment]
@cckozie - after merge found a failure in renaming on DCS if project was originally downloaded from another user and then uploaded to DCS.  Seems to be issue that git origin is not being updated on upload to DCS so it is still pointing to other users account and fails.  So digging into that code.

**Comment by cckozie** [comment]
0.10.1 (ee3f8f5)
1. Translation Identifier shows instead of the book name on new Door43 repos.
I imported the en_act project twice, once giving it the Translation Identifier 'ust' and once 'new'
(It's possible that this problem is unrelated to your work. I can create a new issue for it if you'd rather)
![image](https://user-images.githubusercontent.com/8171759/42908253-08d41e26-8aa6-11e8-96d4-483df665f0ff.png)

2. I don't know if it's really a problem, but I'm seeing these errors in the console when choosing to create a new repo (FIXED IN 0.10.0 (26126c1))
![image](https://user-images.githubusercontent.com/8171759/42908321-3cefe14a-8aa6-11e8-8616-bc3eb71e74a7.png)

3. When no Internet connection available for renaming or creating repo, then clicking the Contact Helpdesk link: 
After entering message text and clicking Submit the user does not receive the 'Cannot connect to server message' as normal when attempting to send feedback w/o an Internet connection. Instead this is written to the log:
![image](https://user-images.githubusercontent.com/8171759/42909464-d8bbed32-8aa9-11e8-8f1a-d28720b87e5f.png)
(I'm OK with making this a separate issue as well as postponing it if @benjore says OK)

**Comment by cckozie** [comment]
0.10.0 (26126c1) 
4. The following alert is displayed when there is not Internet connection regardless of whether the Rename or Create New option was selected. When the Create New option was selected, the text on the alert should have the words 'renamed' and 'renaming' changed to 'created' and 'creating'.
![image](https://user-images.githubusercontent.com/8171759/43007714-c14e832a-8bfe-11e8-9026-e264962b1c0f.png)
5. If the lack of an Internet connection is the reason for the renaming/creating failure, the user should be informed of that rather than just getting the generic message.

**Comment by cckozie** [comment]
@benjore - 
A. Should the problems noted in 1, 3, 4, and 5 above be moved to new issues?
B. You suggested that when the user selects to create a new repo, that new repo should actually be empty rather that the data copied from the original. Is it OK if the repo is also populated?

**Comment by PhotoNomad0** [comment]
@cckozie - I can start looking at item 1 - seems that we need a special case for projects that match the new naming format.

**Comment by PhotoNomad0** [comment]
@cckozie - a bit complicated, since we can have a bunch of project name formats (e.g. en_act, aaw_php_text_reg) and the new format (en_tes_tit_book).  We may have to iteratively try fields to see if they are valid book ids.

**Comment by cckozie** [comment]
@PhotoNomad0 Couldn't we just pull it from the manifest?

**Comment by PhotoNomad0** [comment]
@cckozie - we would have to download all the manifests.  All we have is details about the DCS repo, not the contents such as the manifest.  It looks like testing various fields of the project name, may be a sufficient work-around for now.  

![screen shot 2018-07-20 at 12 09 44 pm](https://user-images.githubusercontent.com/14238574/43013119-dc552400-8c15-11e8-8a2d-73f0b08b4963.png)

**Comment by cckozie** [comment]
@PhotoNomad0 Duh!!! I was thinking we set that value when we created the repo (sucks to lose all those brain cells!)
I think your approach would be better than displaying the xlation id. Wish we had thought of this earlier and challenged Jesse on the order of fields in the project name:)

**Comment by cckozie** [comment]
Issues status as of  0.10.0 (db8cd53) 
1. Fixed
2. Fixed
3. Moved to #4754
4. Moved to #4755 
5. Moved to #4754 
B. Moved to #4757
