### ISSUE TITLE
Hindi appears twice in the locale selector

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4613]
This problem was introduced somewhere between 0.10.0 (45ccd50) and 0.10.0 (e6fe53e)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/9e4a3ddd-f01f-40c9-b383-b6a4840b1f19)

**Comment by richmahn** [comment]
- [ ] [4] Fix locale selector so that Hindi does not appear twice
- [ ] [2] Test for Locale selector to not show a language twice
- [ ] [1] PR Review for #4613

**Comment by da1nerd** [comment]
we just need to delete `%language%-hi_IN.json` from the locale dir. I'm not sure how it got there. Some bug with Crowdin.

**Comment by richmahn** [comment]
Already fixed as Joel mentioned. Not happening in latest build.

**Comment by cckozie** [comment]
Not fixed in  0.10.0 (8ea91f4)

**Comment by cckozie** [comment]
Fixed in 0.10.0 (39713db)
