### ISSUE TITLE
UX Issues

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#462]
As a developer, I want a user to capture all of the UX issues they encounter, so that I know what issues I need to address in my app.

- [x] - Loading Project after Install crashed app (no tools yet)
- [x] - Didn't know how/where to go to install tools
- [x] - Installed tW Tool, and wasn't sure where to go to load it
- [x] - Went back to load Project, but just spun and wasn't sure if it was actually loading or stuck
- [x] - Refreshed window and it loaded quickly, glad I didn't wait on the loading forever
- [x] - Greek text is empty, but gateway and target show
- [x] - Target showed up RTL when it is LTR
- [x] - Resource pane shows a lot of unparsed elements/code/links/nocache
- [x] - Progress bar at bottom looks out of place, remove
- [x] - Uninstalled tools and reloaded, now loading is stuck, and cannot get past the spinner
- [x] - Once resolved, was unable to load reports, gave a fatal error

**Comment by klappy** [comment]
New issues and remaining issues to work through:

## App
- [x] Report link
- [x] Windows Build
- [x] Performance
- [x] Mac Build
- [x] Feedback to include dropdown for type of feedback
- [x] Hide Tools Tester unless in Developer Mode
- [x] Reports need target verse with highlighting.

## Loading
- [x] Remove quirk toggle from tC logo
- [x] Left Menu Project Load button opens wrong menu
- [x] Importing USFM is buggy
- [ ] Specify details for USFM projects if undefined
- [x] Top menu (Application, Project, Tool, Report)

## Checking
- [x] Highlight Gateway "quote" in tN and tW in Scripture Pane
- [x] Target check missing ending punctuation on target verses
- [x] Approving after highlighting unhighlights word(s) should not unselect text
- [x] Unselect Correct or Flag on check
- [x] Clicking Flag for Review, auto selects Propose Change Tab
- [x] Navigation to check defaults to first tab
- [x] Save on blur or any other edit/action, it's not saving enough now
- [x] Help text provided by Perry
- [x] Fill in white gap on right side
- [x] Blue boundary on bottom of checking pane

## Words
- [x] Clean tH resources
- [x] Only use KT folder of key terms and not all

## Notes
- [x] tA Title removed from below the check in the tN tab
- [x] Link removed from below the check in the tN tab
- [x] Clean tA source for the tH pane

**Comment by ihoegen** [comment]
Clean tH resources, Windows Build should be done.
