### ISSUE TITLE
word alignment tool: USFM Markers become words in word bank

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#4645]
From #4554:

* verses with \q and \s5 markers will have unaligned words q & s in WA => medium change to verse parsing? May just need to run through USFM filter before parsing.
* verses with \q and \s5 markers will be flagged as invalidated and will be reset on USF3 export => seems to be due to same issue as above trying to match USFM marker to word in verse.

## Definition of Done
- [ ] No USFM markers should show up as words in the wA tool
- [ ] No truncation should happen as a result of USFM markers
  - [ ] Example: Rev 5:12 used to truncate after the `\pi` marker, that was then fixed, but then the `\pi`, `\s5` (`s`), and `\p` markers all showed up as words. (From Larry's comment, "I just saw an unfamiliar type of markers in the ULT. Rev. 5:12ff truncate verses in tC because of “\pi” markers." Project used, Revelation from https://git.door43.org/unfoldingWord/en_ult . )

**Comment by RoyalSix** [comment]
Is hiding the verse markers a solution? @jag3773 @PhotoNomad0

**Comment by benjore** [comment]
<img width="661" alt="screen shot 2018-06-25 at 12 42 52 pm" src="https://user-images.githubusercontent.com/13352518/41866440-c24ec86c-7875-11e8-8b01-e3f6f9ed6e3e.png">

Here's another example.

**Comment by jag3773** [comment]
@RoyalSix I can't really answer that.  The user doesn't need to see them.

Some things to consider is whether this would affect percentage complete or any other calculations.  Would having them in the data affect word-map @klappy or @neutrinog ?

**Comment by da1nerd** [comment]
Yes, the existence of these markers will slightly skew the results of word map and definitely affect the percentage complete.

**Comment by cckozie** [comment]
0.10.0 (0ef3ec4) 
[67-REV.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2172013/67-REV.usfm.zip)

The \pi marker is not handle properly in Rev 5:12 (See Example above in Definition of Done)
![image](https://user-images.githubusercontent.com/8171759/42400496-6a4c6050-8137-11e8-9b88-36a2b8649a33.png)
