### ISSUE TITLE
Log verse edits during reimport

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4779]
### User Story

As a user, I want the reimport of usfm to log edits so that the edits are up to date and not out of sync.

### Features / Specifications

- [x] Reimporting a project compares each imported verse to the last logged edit, log if different.
- [ ] Write migration to update any gaps of imports from when Reimporting was introduced in case it was used.

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by klappy** [comment]
Since there will be a gap of edits not logged, there will need to be a migration written when this feature is introduced. The migration will need to "catch up" on any differences that exist between the verse text and the known latest logged edits.

**Comment by richmahn** [comment]
- [ ] [8] Write Verse Edits for Reimport
- [ ] [8] Write migration for projects that have been reimported
- [ ] [2] PR Review for #4779

**Comment by cckozie** [comment]
@richmahn - Can you describe what the 'migration to update the gaps' does? 
Does the app use Git to get visibility into external edits that were performed before the upgrade to 1.0.2? I don't believe I'm seeing any of those pre 1.0.2 edits getting logged to the CSV file.

**Comment by cckozie** [comment]
The new external verse edits are logs.
External edits made prior to 1.0.2 are not.

**Comment by richmahn** [comment]
Fail this. We didn't get the migrations in. My fault.

**Comment by richmahn** [comment]
@cckozie When this is back in QA, see the PR test steps for what migration was possible, making sure at least any verseEdits were updated if existing verseEdits were out of sync with the current text: https://github.com/unfoldingWord-dev/translationCore/pull/5366

**Comment by cckozie** [comment]
1.0.2 (ac3d66a)
Edits made in 1.0.0 are propagated to 1.0.2.
In 1.0.2, edits made external to the tool are logged when the project is reimported.
