### ISSUE TITLE
Allow merging of discontiguous Original Language words

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4791]
### User Story

As an aligner, I want to merge two discontiguous Original Language words together so that I can get to 100% alignment.

## Specs
Expanded scope (@PhotoNomad0):
- [x] 1. should be able to unalign any Greek word in an alignment group
- [x] 2. should be able to merge any single Greek word with another single Greek word or an alignment group
- [x] 3. should be able to drag any Greek word in an alignment group to any other alignment group or a single Greek Word
- [x] 4. in a merged group, Greek words always show up in "spacial" order in the merged box, i.e. 1 then 3 (never 3 then 1).
- [x] 5. Alignment groups should be ordered by first word in group.  For example If word 1 & 3 are merged together, then the merged group will show up in the position of the lowest position word, i.e. it will show up in the first position and word 2 will show up after the 1/3 merged group.

- [ ] ~This issue also includes unmerging "middle" Greek words (e.g. if three Greek words are merged together, the middle of these three will now be able to be unmerged)~
- [ ] ~Looks straight forward but it may be more involved than expected.~
- [ ] ~If word 1 & 3 are merged together, then they would always show up in "spacial" order in the merged box, i.e. 1 then 3 (never 3 then 1).~

**Comment by elsylambert** [comment]
Got this Alert message while I was merging the Greek words and one of the Greek word disappeared.
![#4791](https://user-images.githubusercontent.com/51806180/59854172-67318780-9340-11e9-818f-9a60dfde1bf4.png)

[Thu Jun 20 2019.zip](https://github.com/unfoldingWord-dev/translationCore/files/3310693/Thu.Jun.20.2019.zip)

**Comment by cckozie** [comment]
1.2.0 (908e98d) 
[hi_irv_eph_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3311363/hi_irv_eph_book.zip)

[disappearing.mov.zip](https://github.com/unfoldingWord-dev/translationCore/files/3310686/disappearing.mov.zip)
After closing wA and reloadiing the project, the Greek all appear correctly again. It looks like it is likely just a display problem.

**Comment by PhotoNomad0** [comment]
@elsylambert - thanks for attaching the logs.  Can you tell me the sequence you went through to get the error?

**Comment by elsylambert** [comment]
@PhotoNomad0 - The sequence is the same as in the video that Koz posted.
- Moved the Greek Words and merged into groups and then moved one word out of the group, the Greek word disappears.
- It gives an alert message (as in the snapshot above). If I click on Cancel on the Alert message, All the Greek words are back on screen.

**Comment by PhotoNomad0** [comment]
@elsylambert - thanks, that's more clear now.  Trying to make sense of the video - it looks good up to frame 01:14:18.  It looks like you where dragging the word kai into the unmerge box and then the second alignment group disappeared at frame 01:14:51, and that's was the first failure.  Is that correct?

It is looking like the bug is related to the ordering of the instances of the word kai - I'll check into that.

**Comment by PhotoNomad0** [comment]
Found another bug at frame 00:23:57 when two alignments got duplicated.

**Comment by elsylambert** [comment]
@PhotoNomad0 - The video is done in Koz machine with a different Project/Verse. However I got the same observations with my project, so the log and screenshot I provided are unrelated to the Video.

**Comment by cckozie** [comment]
@PhotoNomad0 The first word disappears around 1:33 in the video. I have not seen the error that Elsy recieved about reset alignments.

**Comment by PhotoNomad0** [comment]
@cckozie  @elsylambert - I think the problem started sooner.  After 00.22:14 there are duplicated alignments in the video - quite a big problem with the data from that point on: 
![Screen Shot 2019-06-20 at 10 44 28 AM](https://user-images.githubusercontent.com/14238574/59858143-6bfa3980-9348-11e9-8aae-90f062301a70.png)

**Comment by PhotoNomad0** [comment]
Note to self: looks like the the render() method is hard wired to expect primary words to be contiguous.  Will need some redesign here.

**Comment by RoyalSix** [comment]
[feature testing.mov.zip](https://github.com/unfoldingWord-dev/translationCore/files/3316026/feature.testing.mov.zip)
Is this expected behavior? @PhotoNomad0 @benjore

**Comment by PhotoNomad0** [comment]
@benjore - added occurrence numbers to primary words so that users can keep track of word order when there are multiples.  Thanks to @neutrinog for making this easy!

**Comment by PhotoNomad0** [comment]
verified in translationCore 1.2.0 (f134cbf)

**Comment by cckozie** [comment]
1.2.0 (c625242) 
In OT projects, the Hebrew occurrence number extends off of the top word card.
![image](https://user-images.githubusercontent.com/8171759/60115806-62a01100-973c-11e9-9565-5b64051c4e98.png)

**Comment by cckozie** [comment]
@PhotoNomad0 
1.2.0 (c625242)
[en_new_2th_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3327386/en_new_2th_book.zip)

I was running a script that randomly merges top words, and after every tenth merge, it randomly unmerges one word. After 50 merges it then unmerges all of the top words and then moves to the next verse to repeat the process. When the script moved from the 5th to 6th verse, I got the Invalidated alignments message. Any ideas?
![image](https://user-images.githubusercontent.com/8171759/60136044-cdffd800-9768-11e9-92dd-fcd667aa6e5a.png)

![image](https://user-images.githubusercontent.com/8171759/60136143-030c2a80-9769-11e9-8789-c0e4748a595c.png)

[Tue Jun 25 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/3327380/Tue.Jun.25.2019.log.zip)

It happened again
[Wed Jun 26 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/3332219/Wed.Jun.26.2019.log.zip)

**Comment by cckozie** [comment]
Did not find any problems in 1.2.0 (b757c2a) other than the two invalidated alignment alerts in previous comment.

**Comment by elsylambert** [comment]
Verified in  1.2.0 (4b9a560).
Not able to find any issues.
needs regression
