### ISSUE TITLE
Write a helper function to Parse Catalog

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4831]
Determine format for Catalog Entries.

### Questions:
- [ ] how do we know that an entry has USFM3 (alignment) data that we can consume in tCore?
- [ ] how do we know that an entry contains tW data (so we don't try to parse it out if missing)?
- [ ] what is the overall format for a catalog entry?
- [ ] shall we have separate end-point for tCore resources?

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [4] filter out entries that do not have USFM3 (alignment) data, minimum checking level, 
- [ ] [2] organize and sort remaining entries by language (using localized language name and code)
- [ ] [4] unit tests
- [ ] [4] PR Review [4831]

**Comment by cckozie** [comment]
I assume there is no way to test this other than as part of the dynamic update
