### ISSUE TITLE
Create Door43 Endpoint For tC To Consume

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4832]

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [3] Create Object Structure For Resource List
- [ ] [4] Create Helper Function To Determine Which Resources Are New Based on Catalog
- [ ] [2] Create Lamda Function to pivot catalog on "Subject" attribute
- [ ] [2] Add Trigger For Lamba Function
- [ ] [1] Test New Catalog Endpoint 
- [ ] [1] Update Door43 Documentation

**Comment by RoyalSix** [comment]
@cckozie This might be difficult to test
