### ISSUE TITLE
Write helper function to Retrieve selected resource(s)

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4834]

**Comment by richmahn** [comment]
- [ ] [8] Methods to download a resource
- [ ] [2] Methods to extract resource a resource
- [ ] [4] Method to properly process a resource and move it to resource dir
- [ ] [4] Unit tests for downloading resources
- [ ] [2] PR Review for #4834

**Comment by cckozie** [comment]
I assume there is no way to test this other than as part of the dynamic update
