### ISSUE TITLE
Write helper function to Parse USFM3 data into json (Converting)

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4835]
### Questions that need to be resolved:
- [x] what is the format of the language resource zip file?
  - [x] what does the manifest look like with it's support for multiple bibles as well and TN, TA (TW is parsed from OL)

resources are not combined for a language, so this just needs to parse a bible download.

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [2] Unzip downloaded resource
- [ ] [4] Iterate through bibles in manifest.json
- [ ] [2] parse USFM3 for each book
- [ ] [4] refactor parsing scripts from resource submodule
- [ ] [2] review PR [4835]

**Comment by cckozie** [comment]
I assume there is no way to test this other than as part of the dynamic update
