### ISSUE TITLE
Write helper function to Generate translation helps data

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4836]

**Comment by richmahn** [comment]
- [x] [8] Write tH generator helper for tW
- [x] [4] Write tests for tH generator for tW
- [x] [2] PR Review for #4836

**Comment by cckozie** [comment]
I assume there is no way to test this other than as part of the dynamic update
