### ISSUE TITLE
ID refinement

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4918]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] From Larry: tC 0.10 exports USFM3 with extra data for the ID of the book. For example, 2Ti has “ `\id 2TI EN_ULT en_English_ltr Tue Aug 21 2018 09:02:25 GMT-0400 (EDT) tc` ” whereas the original USFM was @ “ `\id 2TI unfoldingWord Literal Text` ”. What do we want it to include? (edited)
- [ ] Jesse: Similar to the example here https://ubsicap.github.io/usfm/identification/index.html#index-1
- [x] Preserve the original string and make sure it is added on export. Add between `en_English_ltr` and `[date]`

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] Preserve Extra Book Name Information
- [ ] [4] Update Helper Methods to Handle New Data
- [ ] [3] Write Tests To Handle New ID Use Case

**Comment by cckozie** [comment]
Works in 1.1.0 (4f79403)
