### ISSUE TITLE
wA GL dropdown requirements

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4937]
## User Story

As a user I want the GL dropdown for the wA tool to only show GLs that are actually supported so that I don't get confused and think that it has been localized to a language to which it hasn't been. 

## Specs 
- [ ] The requirements for having a GL appear in the wA tool in the GL dropdown: 
  - [ ] For any NT book: 
    - [ ] the GL must have that NT book in tC
    - [ ] the GL must have a Greek Lexicon
  - [ ] For any OT book:
    - [ ] the GL must have that OT book in tC
    - [ ] the GL must have a Hebrew Lexicon

## Notes
- The requirements for having a GL appear in the tW tool remains the same: 
  - the GL must have that aligned book in tC
  - the GL must have the tW translated and in tC

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [3] Write Helper Function To Ensure wA GL requirements
- [ ] [3] Write Tests For Helper Function
