### ISSUE TITLE
Internet connection issues with the source content updater

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#4968]
- [x] If the user selects to Check for content updates when there is no Internet connection, the Cannot connect to serve alert is correctly displayed. However, after restoring the Internet connection, when the Check for content updates is clicked, nothing happens.
(This is fixed in 1.0.0 (dc79cf3) )

If the user loses the Internet connection during a download, it appears that some resources may get updated. In one test of this downloading ru, one of the Bibles made it and the other didn't. In that case, what will get displayed as the local date? Is a partial download the desired behavior?

- [x] If a complete resource has been downloaded, then keep & update that resource. 
- [x] If a resource is partially downloaded, from the user's point of view, they will need to start all over and re-download it. (On the back end, I'm not sure if we delete it and start over or pick up where it left off...)
[I can't tell what happens in this situation. It looks like if any resource does not get fully download the user receives the download failed message and the language still appears on the resources search page. Issue #5043 will help in this situation.]
- [ ] Display the message: ``

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] Fix internet restoration bug
- [ ] [2] Clean up partially downloaded resources

**Comment by RoyalSix** [comment]
It is not possible for a partial resource to be downloaded I believe. I will need to write tests to verify this
