### ISSUE TITLE
App: translationNotes

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#5]
- [x] Ensure all data saves and reloads properly
- [ ] Complete Checking Interface
- [ ] Refine UI/UX
- [ ] Complete Reporting

**Comment by mannycolon** [comment]
Ensure all data saves and reloads properly: done
Complete Checking Interface:in progress
 Refine UI/UX: almost done
 Complete Reporting: in progress
