### ISSUE TITLE
Serious problems if the user misidentifies the project book

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5045]
1.0.0 (6966b10)
Imported an aligned Acts project, but chose John as the book on the project details screen.
The missing verses page correctly identified the missing verse as being Acts 19:41
The app crashes with the "A critical error has occurred message is displayed when the project is loaded in a tool.
When the project is reselected, now the missing verses page list all of the missing verses based on John.

Suggestion: If the project being imported includes the book identification, then don't allow the user to change it on the project details page. Alternatively, warn the user that the project already has a different book identification and ask them if they are really sure.
Additionally, we should apply the same constraints when the user selects to Edit project details from the 3dot menu.

## Specs
- [x] Check the project based on: 
  - [x] existing `project id`
- [x] Warn the user. "This project has been identified as a [book] project. Are you sure you want to change it to a [user-specified book] project?"

## Note
- [x] If the user changes the book, it should trigger the rename workflow

**Comment by RoyalSix** [comment]
# Tasks
- [x] [2] Implement the warning for misidentified books

**Comment by RoyalSix** [comment]
Does this need to happen everytime the user changes the book id? Or just the first time? 
@benjore @cckozie 

@RoyalSix It needs to happen every time.

**Comment by mannycolon** [comment]
Verified on macOS build b67a48e (v1.0.2)

**Comment by cckozie** [comment]
1.0.2 (a5a105b) - The rename workflow for the local project is triggered, but it is not triggered for the Door43 repo when projects from there are imported and the book is changed. (We probably do not need to be concerned about this. Checking with @benjore - He agrees)

**Comment by cckozie** [comment]
Works in 1.0.2 (a5a105b)
