### ISSUE TITLE
Fix handling of USFM tags

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5051]
### User Story

As a user of non-uW USFM, I want tC to display only USFM tags that show actual text so that I don't think that tC is some cut-rate, knock-off software.

### Features / Specifications

This is all based off of the documentation found here: http://paratext.org/about/usfm

- [ ] USFM Markers whose text should NOT be displayed in the Scripture Pane, Check Pane etc., but should show up in an edit box.
  - [x] **_`\ca ... \ca*` Alternate (second) chapter number_**
  - [x] `\cat_<TAG>\cat*` Content Categories
  - [x] `\cd` Chapter description
  - [x] `\cl` Chapter label
  - [x] `\cp` Published chapter character
  - [x] `\ef ... \ef*` Extended footnotes
  - [x] `\esb` + `\esbe` Beginning (opening) + End (closing) of the sidebar content section [and everything in between]
  - [x] `\ex ... \ex*` Extended cross references
  - [x] `\f ... \f*` footnote element
  - [x] `\fdc ... \fdc*` Material only included in published editions that contain the Deuterocanonical books
  - [x] `\fe ... \fe*` Endnotes
  - [x] `\fig ... \fig*` Figures/Illustrations etc.
  - [x] `\fk` Footnote Keyword
  - [x] `\fl` Footnote Label
  - [x] `\fm ... \fm*` Footnote reference mark
  - [x] `\fp` Footnote additional paragraph
  - [x] `\fq` Footnote translation quotation
  - [x] `\fqa` Footnote alternate translation
  - [x] `\fr` Footnote "origin" reference
  - [x] `\ft` Footnote text
  - [x] `\fv ... \fv*` Footnote verse number
  - [x] `\h`, `\h#` Running header text
  - [x] `\ib` Introduction blank line
  - [x] `\id` File identification
  - [x] `\ide` character encoding system
  - [x] `\ie` Introduction end
  - [x] `\iex` Introduction explanatory or bridge text
  - [x] `\ili`, `\ili#` Introduction list item
  - [x] `\im` Introduction flush left (margin) paragraph
  - [x] `\imi` Intruduction flush left (margin) paragraph
  - [x] `\imq` Introduction quote from text paragraph
  - [x] `\imt` Introduction major title
  - [x] `\imte` Introduction major title ending
  - [x] `\io`, `\iot#` Introduction outline title
  - [x] `\ior`, `\ior#` Introduction outline entry
  - [x] `\ip` Introduction paragraph
  - [x] `\ipi` Indented introduction paragraph
  - [x] `\ipq` Introduction quote from text paragraph
  - [x] `\ipr` Introduction right-aligned paragraph
  - [x] `\iq`, `\iq#` Introduction poetic line
  - [x] `\iqt ... \iqt*` Introduction quoted text
  - [x] `\is#` Introduction section heading
  - [x] `\mr` Major section reference range
  - [x] `\ms`, `\ms#` Major section heading
  - [x] `\mt`, `\mt#` Major title
  - [x] `\mte`, `\mte#` Major title at ending
  - [x] `\ndx ... \ndx*` Subject index entry
  - [x] `\periph` Peripheral content elements which may be prepared fro publication in addition to the scripture body text
  - [x] `\pro ... \pro*` Pronunciation information
  - [x] `\r` Parallel passage reference
  - [x] `\rem` Brief comments by a translator, consultant, or support person
  - [x] `\rq ... \rq*` Inline quotation
  - [x] `\s`, `\s#`  section headings
  - [x] `\sr` section reference range
  - [x] `\sts` Project text status tracking
  - [x] `\tc#` Table cell
  - [x] `\tcr#` Right aligned table cell
  - [x] `\th#` Table column heading
  - [x] `\thr#` Right aligned table column heading
  - [x] `\toc1` Long table of contents text
  - [x] `\toc2` Short table of contents text
  - [x] `\toc3` Book abbreviation
  - [x] `\tr` table row start
  - [x] **_`\va #\va*` Alternate (second) verse number_**
  - [x] `\vp # \vp*` Published verse character
  - [ ] ~`\w ... \w*` Wordlist/glossary/dictionary entry~
  - [ ] ~`\wg ... \wg*` Greek word list entry~
  - [ ] ~`\wh ... \wh*` Hebrew word list entry~
  - [x] `\x ... \x*` Cross reference element
  - [x] `\xdc ... \xdc*` References to be included only in published editions that contain Deuterocanonical books
  - [x] `\xk` a keyword from the scripture translation text which the target reference also refers to.
  - [x] `\xnt ... \xnt*` References to be included only in published editions that contain the New Testament books
  - [x] `\xo` Cross reference "origin" reference
  - [x] `\xot ... \xot*` References to be included only in published editions that contain Old Testament books. 
  - [x] `\xq1` A quotation from the scripture text
  - [x] `\xt` Target reference 

- [ ] USFM Markers whose text SHOULD be displayed in the Scripture Pane, Check Pane, etc. 
  - [x] **_`\+nd ... \+nd*` Character Marker Nesting_**
  - [x] `\add ... \add*` Translator's addition
  - [x] `\bd ... \bd*` Bold Text
  - [x] `\bdit ... \bdit*` Bold-italic text
  - [x] `\bk ... \bk*` Quoted book title (Will likely never occur in Scripture, just intros/footnotes/etc.)
  - [x] `\cls` Closure of an epistle/letter
  - [x] `\d` Descriptive title (or "Hebrew subtitle")
  - [x] `\dc ... \dc*` Deuterocanonical/LXX additions
  - [x] `\em ... \em*` Emphasis text
  - [x] `\it ... \it*` Italic
  - [x] `\k ... \k*` Keyword/keyterm
  - [x] `\li`, `\li*` List item
  - [x] **_`\lik ... \lik*` List_** List entry key content
  - [x] **_`\lim#` Embedded list entryList_**
  - [x] `\lit` Liturgical note/comment
  - [x] **_`\litl ... \litl*` List entry total_**
  - [x] **_`\liv ... \liv*` List_** List entry value content
  - [x] `\m` Flush left (margin) paragraph 
  - [x] `\mi` Indented flush left paragraph
  - [x] `\nd ... \nd*` Name of God (name of Deity)
  - [x] `\no ... \no*` Normal text
  - [x] `\ord ... \ord*` Ordinal number ending (i.e. in "1st" -- 1\ord st\ord*)
  - [x] `\pc` Centered paragraph
  - [x] `\ph`, `\ph#` Indented paragraph with hanging indent, "Deprecated"
  - [x] `\pi`, `\pi#` Indented paragraph
  - [x] `\pm` Embedded text paragraph
  - [x] `\pmc` Embedded text closing
  - [x] `\pmo` Embedded text opening
  - [x] `\pmr` Embedded text refrain
  - [x] `\pn ... \pn*` Proper name
  - [x] `\pr` Right-aligned paragraph
  - [x] `\qa` Acrostic heading
  - [x] `\qac ... \qac*` Marker to indicate the acrostic letter within a poetic line
  - [x] `\qc` Centered poetic line
  - [x] `\qm` Embedded text poetic line
  - [x] `\qr` Right-aligned poetic line
  - [x] `\qs_(Selah)\qs` Used for the expression "Selah"
  - [x] `\qt ... \qt*` Quoted text
  - [x] **_`\qt-s |sid="qt_123"...\* ... \qt-e |eid="qt_123"\*` milestone quoted text_**
  - [x] `\sc ... \sc*` Small-cap text
  - [x] `\sig ... \sig*` Signature of the author of an epistle
  - [x] `\sls ... \sls*` Passage of text based on a secondary language or alternate text source
  - [x] `\sp` Speaker Identification (e.g. Job and Song of Songs)
  - [x] **_`\sup ... \sup*` Superscript text._** 
  - [x] `\tl ... \tl*` Transliterated (or foreign) words
  - [x] **_`\ts-s|sid="ts_JUD_5-6"\*... \ts-e|eid="ts_JUD_5-6"\*` Translator’s section milestone_**
  - [x] `\v #` Verse number
  - [ ] ~`\va #\va*` Alternate (second) verse number~
  - [x] **_`\w ... \w*` Wordlist/glossary/dictionary entry_**
  - [x] **_`\wa ... \wa*` Aramaic word list entry_**
  - [x] **_`\wg ... \wg*` Greek word list entry_**
  - [x] **_`\wh ... \wh*` Hebrew word list entry_**
  - [x] `\wj ... \wj*` Words of Jesus

- [ ] USFM Marker with no text associated (but in the case that text does follow on same line, we must preserve as displayed text)
  - [x] `\b` Blank line
  - [x] `\c_#` Chapter number
  - [x] `\nb` Indicates "no-break" with previous paragraph (regardless of previous paragraph type)
  - [x] `\p` Normal paragraph
  - [x] `\pb` Explicit page break
  - [x] ~`\q`, `\q*` Poetic line~  **_`\q`, `\q#` Poetic line_**

### Note: 
edited by @photonomad0 to add newer markers such as USFM3.  Incorrect entries are crossed out and additions are highlighted bold/italic.

**Comment by RobH123** [comment]
The latest USFM 3.0 documentation is at http://ubsicap.github.io/usfm/ -- your v2.4 reference is basically obsolete.

\p Often has text (e.g., a paragraph break in the middle of a verse)
\q# The same, often has text

**Comment by RobH123** [comment]
The latest USFM 3.0 documentation is at http://ubsicap.github.io/usfm/ -- your v2.4 reference is basically obsolete.

\p Often has text (e.g., a paragraph break in the middle of a verse)
\q# The same, often has text

**Comment by PhotoNomad0** [comment]
@benjore - Started checking off the items that we already handle in the usfm to json library that we use for USFM import.  If we leverage that library for cleaning up the displayed text, it will greatly minimize the work and testing needed.

Started listing work to do in https://github.com/unfoldingWord-dev/translationCore/issues/5066

**Comment by PhotoNomad0** [comment]
### Tasks:
* [4] in usfm-js complete unsupported USFM2 support
* [4] add support for nesting USFM markers with spans
* [8] add new support for USFM3 markers/spans
* [8] add usfm-js unit tests for more USFM/USFM3 tags
* [4] in tCore and tools, update usfm dependencies to use latest version
* [8] fix usfm3 export (alignment merge) to preserve new USFM markers.

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-34ddb63.setup.exe

**Comment by RobH123** [comment]
Looking at http://ubsicap.github.io/usfm/milestones/index.html, it seems that the \zaln-s milestones outputted by tC should be self-closing, i.e., end with \\* like the \zaln-e milestones already do.

**Comment by PhotoNomad0** [comment]
@RobH123 @benjore @cckozie @jag3773  - Good catch, that should have been caught when we were in spec phase.  If implemented now, would be a bit painful.  We could maintain backwards compatibility on USFM3 import of older projects.  But it could break USFM3 imports of fixed format into older versions of tCore.

**Comment by cckozie** [comment]
Because of the volume of tags that need to be tested, I am writing up new issues to fix problems I'm finding rather than delay having the fixes worked on until I have tested it all to my satisfaction. I'll attach them as children to this issue.

**Comment by cckozie** [comment]
Documents:
USFM2 - http://paratext.org/system/files/usfmReference2_4.pdf
USFM3 - http://ubsicap.github.io/usfm/master/index.html
USFM3 Index - http://ubsicap.github.io/usfm/master/genindex.html

Here are the lists of the markers that have been tested for, and those that have not yet been addressed. Note that 'tested for' only means they are persisted into the export file and do not corrupt the data there. None of them, other than those noted in #5397, have been verified to not have a negative effect within the app.
162 markers being tested - [tested_usfm_markers.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/2566364/tested_usfm_markers.txt.zip)
48 markers not being tested - [untested_usfm_markers.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/2566340/untested_usfm_markers.txt.zip)

**Comment by cckozie** [comment]
Wait now on #5388

**Comment by cckozie** [comment]
All related child issues have been passed as of 1.1.0 (ac75c11)
