### ISSUE TITLE
Refine tokenizer for Hindi use-case

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5060]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] Increment NPM package version for tokenizer to latest. 
- [ ] NOTE: Create a branch off of the `1.0` release and include this issue in there.

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2]Make PR for correct `string-punctation-tokenizer` module version

**Comment by cckozie** [comment]
Per Klappy: Words in the word bank should exactly match what is in the scripture pane.

**Comment by cckozie** [comment]
The new tokenizer code got merged in earlier (it works properly in 1.0.0 (8adaf14) and then got pulled out in 1.0.1. According the @klappy it has to do with dependencies.

**Comment by klappy** [comment]
The code in the core no longer holds the helpers/utilities that do the tokenization. That was moved to the word-aligner module which includes the tokenizer. That module needs updated to the appropriate version of the tokenizer, published under its new version, repeat with the wordAlignment tool updated accordingly, then tC.

**Comment by cckozie** [comment]
Good:
![image](https://user-images.githubusercontent.com/8171759/46814582-ae419480-cd3e-11e8-9e5e-64e918b94f74.png)

Bad:
![image](https://user-images.githubusercontent.com/8171759/46814741-fb256b00-cd3e-11e8-81db-65812968bb59.png)

**Comment by da1nerd** [comment]
the updated `wordmap-lexer` and `wordmap` need to be used in `wordAlignment@1.0.1` in order for all of this to work. a few minor structural changes will be need as well. e.g. not just a dependency bump.
