### ISSUE TITLE
[4] SPIKE: for #5051 Figure out strategy to holistically deal with USFM tags

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5066]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications for https://github.com/unfoldingWord-dev/translationCore/issues/5051

- [ ] Figure out what text to show and not
- [ ] Maintain all USFM markers (so they are not lost on export)
- [ ] Do not show any markers in the Scripture Pane, Check Pane, wA wordlist 
- [ ] USFM tags don't pose issues for selection #3853
- [ ] All tags are visible in Edit Mode

### Definition of Done

- [ ] Have at least 1 hour of report/review with all/most of devs
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
### @PhotoNomad0 Notes:
* I have clicked check boxes in https://github.com/unfoldingWord-dev/translationCore/issues/5051 to indicate what we already support on usfmToJson() in `usfm-js`. Just a few items left to do:
  * change `\s#` to not display text following 
  * change `wg ... \wg*` to not display text within
  * change `\wh ... \wh*` to not display text within
  * add support for: 
    * nested USFM markers with spans
    * `\d` Descriptive title (or "Hebrew subtitle")
    * `\va #\va*` Alternate (second) verse number
    * `\ca ... \ca*` Alternate (second) chapter number
    * `\li, \li*` List item
    * `\esb + \esbe` Beginning (opening) + End (closing) of the sidebar content section [and everything in between]
    * `\pb`  Explicit page break
* found word alignment code from app to convert verseObjects to displayed text and wrote example code to strip out non-displayed content.  In branch `feature-mcleanb-5051` of `usfm-js`.  This allows us to pick up the full USFM support from usfmToJson.

### Tasks still to do:
* [4] in usfm-js add and change USFM support items listed above
* [4] add support for nesting USFM markers with spans
* add new support for USFM/USFM3 markers
  * [1] sidebar (\esb) support - one-off
  * [2] non-span markers (e.g. `\ts\*`)
  * [2] delimited attributes (`|`) following text
  * [3] complex milestone markers (such as `\qt-s |sid="qt_123" who="Pilate"\*“Are you the king of the Jews?”\qt-e |eid="qt_123"\*`) 
  * [2] odd-ball USFM character level nesting `\+nd` to `\+nd*`
* [8] add usfm-js unit tests for more USFM/USFM3 tags
* [4] in tCore and tools, update usfm dependencies to use latest version
* [8] fix usfm3 export (alignment merge) to preserve new USFM markers.
