### ISSUE TITLE
Performance Optimization

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5067]
### Features / Specifications

- [ ] Tool Loading (7 seconds on "normal" powered Mac with all resources loaded) (1.7 GHz i7 8GB Memory, SSD Hard Drive) (Loading Acts, tW is ~1 minute, wA is ~25 seconds)
- [ ] Navigation within the tool (2 seconds or less between navigating menu items on same computer as ^^)  ~50% faster than 1.0 build

### Definition of Done

- [ ] Tool Loading - 
- [ ] Navigation within the tool - 
- [ ]

**Comment by benjore** [comment]
Talk to the Stakeholders: 

What is acceptable? (~7 seconds?)
What is expected hardware being used?

**Comment by cckozie** [comment]
1.0.2 (6ab77c0)
Loading of tools is consistently 11 seconds when the minimal resources (en,grc,hi) are on on the machine. With all of the resources downloaded the loading of tools is consistently 17 seconds.
Hopefully this will be improved when when #5160 is completed and possibly further when/if #4954 is implemented.
See actual test results of in issue #5093.
This does not meet the suggested 7 second target, but I passed #5093 assuming that additional improvements will be made as a result of the other issues.

Navigating within the tools is consistently 2 seconds or less in both tW and wA.
See actual test results in issue #5092.
This does meet the suggest <= 2 seconds target to navigate within a tool.

**Comment by cckozie** [comment]
As of 1.0.2 (f005f02) :
Tool loading is ~7 seconds even with all available resources on on the machine.
Navigating within a tool is typically sub-second.
