### ISSUE TITLE
Optimize Navigation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5092]

**Comment by mannycolon** [comment]
- [ ] [4] Replace all map and foreach loops in `tc-ui-tololkit` for the scripture pane and the menu.

- [ ] [5] Rewrite `getBiblesWithHighlightedWords()` to only generate content for the current verse and generate all bibles verses when needed.

- [ ] [3] Replace all map and forEach loops in VerseObjectUtils for https://github.com/translationCoreApps/word-aligner

- [ ] [3] Setup why-did-you-update to determine what components are rerendering when they should not.

**Comment by cckozie** [comment]
In Word Alignment tool:
Time to navigate to 10 sequencial verses in unaligned Acts project starting with verse 1:1
en, hi, grc, and pt-br languages in resource folder
target and Greek only in scripture pane
1.0.0 (4bd6856) - 29 seconds
1.0.2 (6ab77c0) - 17 seconds
Nine resources open in scripture pane
1.0.0 (4bd6856) - 33 seconds
1.0.2 (6ab77c0) - 20 seconds
All resource downloaded. Only target and Greek are open in scripture pane.
1.0.0 (4bd6856) - 35 seconds
1.0.2 (6ab77c0) - 17 seconds

Overall 40 - 50% improvement. Much better now, but we still need to have a indicator that processing is occurring between the click time and the screen update time. See issue #3579.

**Comment by cckozie** [comment]
In translationWords tool:
Time to navigate to 10 sequential checks in unaligned Acts project starting with God, verse 1:3
en, hi, grc, and pt-br languages in resource folder
target and Greek only in scripture pane
1.0.0 (4bd6856) - 48 seconds
1.0.2 (6ab77c0) - 20 seconds
Nine resources open in scripture pane
1.0.0 (4bd6856) - 70 seconds
1.0.2 (6ab77c0) - 20 seconds
All resource downloaded. Only target and Greek are open in scripture pane.
1.0.0 (4bd6856) - 51 seconds
1.0.2 (6ab77c0) - 20 seconds

Overall 60 - 70% improvement. Much better now, but we still need to have a indicator that processing is occurring between the click time and the screen update time. See issue #3579.
