### ISSUE TITLE
Support for RTL Projects (in a LTR Gateway Language)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5098]
### User Story

As a speaker of a RTL language, I want the tC app to display my language correctly so that I feel like a first-class citizen.

### Features / Specifications

- [ ] QUESTION: Do references show up with chapter on the left or right for RTL languages (we are currently displaying both)? So for instance, in the English it is written `2:10`, in Arabic written as `10:2` or `2:10`? 
  - [ ] ANSWER: from Donny "The English `2:10` would still be written as `2:10`.  The verse numbering part switches to LTR ... Here is an example spanning multiple verses :  `Rev 1:9-11` would be written as ` 1:9-11 الرؤيا `"
- [ ] See specs below

## Notes
- [ ] This is a fix that only fixes how RTL target languages show up in a LTR Gateway Language/User Interface. Full Gateway Language/User Interface RTL support (for the app itself) will be covered in #5173 

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
2.2.0 (d786804) Current implementaion
![Screen Shot 2020-05-19 at 9 33 00 AM](https://user-images.githubusercontent.com/8171759/82339833-1b55eb00-99b4-11ea-8ff0-ebe6d5e6d2fa.jpg)
![Screen Shot 2020-05-19 at 9 32 13 AM](https://user-images.githubusercontent.com/8171759/82339840-1e50db80-99b4-11ea-8aa9-c4d549d66053.jpg)
![Screen Shot 2020-05-19 at 9 31 34 AM](https://user-images.githubusercontent.com/8171759/82339845-1ee97200-99b4-11ea-8b51-c2458bbc7d15.jpg)
![Screen Shot 2020-05-19 at 9 30 59 AM](https://user-images.githubusercontent.com/8171759/82339847-1f820880-99b4-11ea-8743-4076e018903c.jpg)
![Screen Shot 2020-05-19 at 10 02 11 AM](https://user-images.githubusercontent.com/8171759/82343058-f9f6fe00-99b7-11ea-9d20-f131776a7174.jpg)

![Screen Shot 2020-05-19 at 9 30 46 AM](https://user-images.githubusercontent.com/8171759/82339853-201a9f00-99b4-11ea-99e0-13ff70ced1c0.jpg)

**Comment by PhotoNomad0** [comment]
Highlighted issues I have found:
![82339853-201a9f00-99b4-11ea-99e0-13ff70ced1c0](https://user-images.githubusercontent.com/14238574/82553159-84af3880-9b31-11ea-9dff-3e427bc2cc4d.jpg)
![82343058-f9f6fe00-99b7-11ea-9d20-f131776a7174](https://user-images.githubusercontent.com/14238574/82553167-87119280-9b31-11ea-832f-55b80859a739.jpg)
![82339847-1f820880-99b4-11ea-8743-4076e018903c](https://user-images.githubusercontent.com/14238574/82553170-87aa2900-9b31-11ea-8cf3-bf10bc095b40.jpg)

![82339833-1b55eb00-99b4-11ea-8ff0-ebe6d5e6d2fa](https://user-images.githubusercontent.com/14238574/82553177-8973ec80-9b31-11ea-8e8b-75a88d402a02.jpg)

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert - Most issues are probably to be based off the target language, but a few of these probably should be based off the locale language.

**Comment by cckozie** [comment]
The entire UI definition needs to be mirrored for RTL locales.
