### ISSUE TITLE
Existing 0.7 projects do not generate the unsupported alert after upgrading to 1.0

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5117]
1.0.0 (4bd6856) 
[rmr-x-bsa_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/2421892/rmr-x-bsa_tit_text_ulb.zip)

tC should display an alert informing the user that projects this old are not supported as it did in .10. The message is displayed in the console, but when the user selects the project nothing appears to happen. The app just stays on the projects page.

The proper message is displayed when attempting to import 0.7 projects from Door43.

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/389ec446-1dd7-45d9-b69f-d62b109327da)

**Comment by mannycolon** [comment]
# Tasks

- [ ] [3] Debug problem with the unsupported alert not opening 
- [ ] [2] Fix  problem with the unsupported alert not opening 
- [ ] [2] Cleanup and/or write unit tests

**Comment by cckozie** [comment]
@PhotoNomad0 I'm assuming you meant to move this to In QA, not QA Done. Agree?

**Comment by PhotoNomad0** [comment]
@cckozie - sorry must have clicked too low on the drop down.

**Comment by cckozie** [comment]
Works in 1.0.2 (f005f02)
