### ISSUE TITLE
wA tool: Add support for Machine-generated suggestions

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5118]
### User Story

As an aligner, I want machine-generated suggestions clearly distinguishable from alignment memory so that I can deal with each category of data appropriately.

### Features / Specifications

- [ ] For suggestions that are either statistically derived internally (WordMAP), or machine aligned externally and not human verified, display these suggestions in a orange box, with a orange bar. 
- [ ] Behavior for these machine-derived suggestions functions the same way as alignment memory: 
  - [ ] Accept individual suggestions by clicking on the word
  - [ ] Accept all suggestions by clicking on the "Accept" button. Note: Clicking the "Accept" button will accept all suggestions on the board - both machine-derived, and translation memory. 
  - [ ] Reject individual suggestions by clicking on the X - the word will return to the word list
  - [ ] Reject all suggestions by clicking on the "Reject" button. Note: Clicking the "Reject" button will reject all suggestions on the board. 
  - [ ] Clicking "Alignment Complete" automatically rejects all unaccepted suggestions
- [ ] Expose "Verified" attribute in import process

### Definition of Done

- [ ]
- [ ]
- [ ]

### Mockups

![image](https://user-images.githubusercontent.com/13352518/47458517-5b84c580-d79f-11e8-80f4-626efd0015f8.png)

![image](https://user-images.githubusercontent.com/13352518/47458505-53c52100-d79f-11e8-9191-e294a456b0d8.png)

**Comment by benjore** [comment]
Yellow background or red? 

Answer: orange... go figure
