### ISSUE TITLE
Partially Missing Highlighting in Greek

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#5126]
In 1.0.0 release.

The highlighting for Greek is incomplete based on the data in the Door43-Catalog.

You can see this issue in Titus 3:8 under "believe..." in the tW tool (see screenshot).

![screen shot 2018-10-01 at 10 27 04 am](https://user-images.githubusercontent.com/107731/46294835-afb3d580-c564-11e8-87a2-c2f6eb09301d.png)

The word before the highlighted word in the Greek, 'οἱ', should also be highlighted based on the alignment data here: https://git.door43.org/Door43-Catalog/en_ult/src/branch/master/57-TIT.usfm#L2053 .

I suspect that there may be a systemic problem in how the USFM3 alignment data is being read.

**Comment by jag3773** [comment]
Also noting that just the one word is tagged in the UGNT, https://git.door43.org/Door43-Catalog/el-x-koine_ugnt/src/branch/master/57-TIT.usfm#L673 .  I'm not sure how that and the ULT alignment data are related/prioritized in the Scripture pane.

**Comment by lrsallee** [comment]
@jag3773 The tW tags were added before the alignment began. That part never entered into my thinking when I added the tags. I did a minimal amount of merging of terms such as "Holy Spirit" and "God the Father." But generally, I only tagged the specific noun or verb that related to a tW term. I made no attempt to include articles, pronouns, or any other related words. 

Not sure if that is the right way to do it, but that's how they are done. If we wanted to include everything in a verse that was related to the tW terms in any way, we would have to go back and do a lot of combining of terms in the UGNT.

**Comment by pjoakes** [comment]
So the tW tool finds single words (for the most part) based on word tagging data, but then asks for phrases if the UGNT alignment is a phrase. Would the tool still work if we stopped using the tW tags and only used the alignment data? Somehow the alignment data needs to have priority over the tagging so the tool can show the full highlighting in the UGNT and GL that the tool is asking for.

**Comment by jag3773** [comment]
@benjore As I see it, there are two ways we can address this:

1. Have a dev read the alignment data and update the tW tags in the UGNT to have the more full text highlighted, (e.g. expand the tag to include both οἱ and πεπιστευκότες).  This would create a new set of work for Larry to review.
2. Have tC continue to use the tW tags to generate the index (list of checks), but have it refer to the corresponding alignment data for the highlighting in the Scripture pane (for Greek and the GL).

I think that option 2 is preferable because it is more language neutral. In other words, we are just tagging the essential element in the Greek and then allowing the GL alignment data to dictate how many "helper words" need to be included.  If we go with option 1 then we would be encoding helper words in our base data, which would require GLs to have the Greek helper words in their translated phrases, even if that's not natural for the GL.

Further, I think option 2 is less work :)

**Comment by mannycolon** [comment]
@benjore I'd be interested in working on this issue

**Comment by mannycolon** [comment]
# Tasks

- [ ] [3] Debug Problem w/ Partially Missing Highlighting in Greek 
- [ ] [3] Fix Problem w/ Partially Missing Highlighting in Greek 
- [ ] [3] Write unit tests for Partially Missing Highlighting in Greek

**Comment by benjore** [comment]
@jag3773 The tW for this instance is actually just the word that is highlighted (and not the `oi`)

![image](https://user-images.githubusercontent.com/13352518/57409817-e020b980-71ae-11e9-8926-5ba8ef32391e.png)

The highlighting but has been fixed in so that the highlight in the ULT is showing: 

![image](https://user-images.githubusercontent.com/13352518/57409856-f75fa700-71ae-11e9-9691-06090c4f66b5.png)

The way we are dealing with the data, if the tW authors want both words to show up, then they need to tag both of the words as the tW.

**Comment by benjore** [comment]
I think this is functioning exactly like we planned it. This issue overlaps with secondary alignments. Another issue to consider is that the words that have been merged in other versions & languages will differ. So there will never be a perfect highlight across all languages.

**Comment by jag3773** [comment]
It may be OK to leave it as is.  From my understanding, it would be more accurate to have the 'οἱ' included, but it's not essential.

@benjore I gather that you saying if we want both words highlighted in Greek then we'd need to use a key term milestone for it, correct?

**Comment by benjore** [comment]
@jag3773 Yes that is correct.
