### ISSUE TITLE
WordMAP Roadmap

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5166]
## Roadmap (user benefit/difficulty)
Note: user benefit - lower number is more benefit. Difficult - lower number is less work

- [ ] WordMAP
  - [x] Alignment Memory 
  - [x] Lemma fallback (1/4)
  - [ ] statistical prediction (2/5)
  - [ ] performance optimizations (3/?) - linked to whole language / bundles
  - [ ] morphology (4/14.5)
  - [ ] syntax trees (5/20)
- [ ] Integrations
  - [x] wA consume self 
  - [ ] tW consume self (1/3)
  - [ ] tN consume self (n/a)
  - [x] whole language / bundles (1/10)
  - [ ] consume alignment memory from all tools (2/4)
  - [ ] flag machine aligned data on import (3/1)
  - [ ] Self-tuning algorithms (3/20)
  - [ ] USFM 2/3 import/export (5/5)
  - [ ] Drafting tool (??)
  - [ ] Sharing alignment language pair settings (??)

![IMG_20180827_185244624.jpg](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/5df1b294-18ed-4aa8-840e-6e3460652eba)

**Comment by BincyJ** [comment]
Birch to talk to Joel before priortizing
