### ISSUE TITLE
tW tool card UI changes

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5193]

**Comment by cckozie** [comment]
1.1.0 (413b11c)
Per requirements listed on #2010 the following are not completed:
- By default, all three checkboxes are preselected (Fixed in 1.1.0 (4d06842) )
- If the user unselects a a checkbox or two, save those settings (pegged to the project)
- If a Gateway Language does not have content for all the checkboxes, disable those. (I see that rather than be disabled, the option is not displayed. It seems like if the Launch button is disabled, then the checkboxes should be as well (as in an OT book). @benjore - What say you?)

Also, the UI mockups show the checkboxes in the sequence of Key Terms, Other Terms, Names, but as implemented the sequence is Key Terms, Names, Other Terms.

**Comment by cckozie** [comment]
These problems still exist in 1.1.0 (4d06842):
- If the user unselects a a checkbox or two, save those settings (pegged to the project)
Now it does save the setting, but it is not pegged to the project. It is used for all projects until changed again. 
- If a Gateway Language does not have content for all the checkboxes, disable those. (I see that rather than be disabled, the option is not displayed. It seems like if the Launch button is disabled, then the checkboxes should be as well (as in an OT book). @benjore - What say you? Waiting for his responce)
- The UI mockups show the checkboxes in the sequence of Key Terms, Other Terms, Names, but as implemented the sequence is Key Terms, Names, Other Terms.

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [0] Persist Category Settings To User Project
- [ ] [2] Disable Checkboxes Instead of Having Them Removed
- [ ] [1] Change Sequence of Checkboxes

**Comment by RoyalSix** [comment]
@benjore In order to meet the requirement `If a Gateway Language does not have content for all the checkboxes, disable those.`

That means we have to have a predefined set of checks, and if we wanted to add anymore they would have to hardcoded in. Is that OK? lmk

**Comment by benjore** [comment]
CHANGE OF REQUIREMENTS: If the content is there, show the checkbox, if the content is not there, don't show anything (instead of showing a disabled checkbox).

**Comment by cckozie** [comment]
1.1.0 (2ba28f8) 
It looks like the checkbox settings are being saved by book (or maybe book/language), not by project. I have an English Titus ULB and an English Titus UDB. When I change the boxes checked on one of them it also sets them the same for the other.

**Comment by RoyalSix** [comment]
Can you provide the exact steps you did to recreate this problem? I am not seeing it. @cckozie

**Comment by cckozie** [comment]
@RoyalSix I saw it one time again didn't write down the steps, and now I am not able to able to reproduce it again. I'm moving it back to In QA.

**Comment by cckozie** [comment]
@RoyalSix But now I found other issues when some resources are not available.
1. If Key Terms are not available, the options are again shown in the wrong order
![image](https://user-images.githubusercontent.com/8171759/50308094-e8769300-045f-11e9-852d-094711afd9ce.png)
2. If there is no checked box displayed, the Launch button should be disabled. 
![image](https://user-images.githubusercontent.com/8171759/50308294-6fc40680-0460-11e9-8f08-f666d5d7aaf7.png)

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-win-x64-1.1.0-9e93ea9.setup.exe

**Comment by cckozie** [comment]
Works in 1.1.0 (442929d)
