### ISSUE TITLE
1.0.1 - Missing text warning is not displayed in scripture pane 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5266]
This has been broken post 1.0.0
[es-419_reg_luk_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2490175/es-419_reg_luk_book.zip)

In 1.0.0 (4bd6856)
![image](https://user-images.githubusercontent.com/8171759/47131182-fa229b00-d262-11e8-96e4-965f302d1f82.png)

1.0.1 (4ad2f22) 
![image](https://user-images.githubusercontent.com/8171759/47131157-c8113900-d262-11e8-9e56-a060c5113764.png)

**Comment by mannycolon** [comment]
# Tasks

- [ ] [3] Debug problem w/ missing text warning not displayed in scripture pane
- [ ] [4] Fix problem w/ missing text warning not displayed in scripture pane
- [ ] [2] Write unit tests for missing text warning not displayed in scripture pane

**Comment by cckozie** [comment]
1.0.2 (8c6f266) The warning text now appears but is not italicized. There is an existing issue for this, #4920.
