### ISSUE TITLE
Always export all USFM3 tags except tags pertaining to Alignment Data, unless the user wants Alignment Data then export all

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5388]
## User Story

As a non-uW-ecosystem user, I want to be able to export my text which contains usfm3 markers regardless of whether or not I am exporting alignment data, so that I can import and export my project without losing data (USFM3 markers). 

For reference: Koz, "The testing that I have done to date is only related to usfm2 exports. I have not yet tested to see if they are in the usfm3 export. My rationalization is this: a user may import a usfm project that contains non-alignment usfm3 tags, do some tW work on it, then export it for editing elsewhere. Since no alignments have been done, the usfm3 export is not available, and the noted usfm3 tags and sometimes associated text will be deleted."

*For clarity, this story will be effectively changing the Export options from `USFM2` or `USFM3` to `Text only` with all tags except those for alignment data or `Text + Alignment Data` with all tags preserved.*

## Specs
- [ ] Add support for exporting the following tags: 
  - [ ] `\w`
  - [ ] `\q1`
  - [ ] `\q2-s`
- [ ] Change the export dialog as per the mockup
  - [ ] Note: This dialog will continue to only appear if there is alignment data (as it is now)
  - [ ] All tags except the ones for alignment data are always exported. 
  - [ ] Tags containing alignment data are only exported if the checkbox is selected before clicking `Export`

## Mockups

![image](https://user-images.githubusercontent.com/13352518/48146269-35b8ef80-e27a-11e8-8523-519bdcd18e6d.png)

## Original writup

1.0.2 (7ccb0dc)
Import a usfm file that has non-alignment type usfm3 markers such as \w and \q1 \q2-s.
Export the file to usfm (no option to export to usfm3 since there is not alignment data.
Examine the exported file and note that the \w markers and associated data are missing, and the \q1 \q2-s markers are present, but the quote is missing.

Milestone markers \ts, \ts-s, \ts-e, \qt-s, and \qt-e  markers are preserved.

**Comment by PhotoNomad0** [comment]
I notice that on import tCore itself strips out embedded word tags ('\w') as part of parsing out alignments.  But in the case there is no alignment, on export it does not restore the tags.

**Comment by PhotoNomad0** [comment]
@benjore - current state of tCore (with all the latest USFM updates) is that on import we only strip out the following USFM markers for alignment (all other markers are preserved):
1. `\zaln-s ... \zaln-e\*` - used for marking alignments
2. `\w ... \w*` - used for tagging words in alignment.

Case one is not a problem since that is the flag that there is alignment data, but case 2 is.  Probably need a spike to investigate how to preserve word tags if there are no alignments.  They would need to be preserved in a way that they can be:
- easily restore when exporting to USFM if not inserting alignment data, and
- not cause conflict or confusion if adding alignment data on export to USFM.

**Comment by PhotoNomad0** [comment]
@benjore - does this look good for the dialog?

![screen shot 2018-11-19 at 8 57 38 am](https://user-images.githubusercontent.com/14238574/48711469-62a1c680-ebd9-11e8-9f97-e424a2fb6dfb.png)

**Comment by benjore** [comment]
Looks great!

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-77e70ed.dmg

**Comment by cckozie** [comment]
1.1.0 (8b1ff72) 
The good news is, to the best of my knowledge I have now tested all of the USFM2 and USFM3 markers. Just a couple of problems noted here. Issue A is not really a USFM3 problem, so I can move it to another issue if you prefer.

Issue A: [Still seeing in 1.1.0 (2ba28f8)] [Works in 1.1.0 (ac75c11)]
The \p marker is being stripped out if there is a blank line between it and a preceding \c marker. 
Imported file: [57-TIT-x.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2654684/57-TIT-x.usfm.zip)
Exported file: [57-TIT3-testx.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2654687/57-TIT3-testx.usfm.zip)


Issue B: [Fixed in 1.1.0 (2ba28f8)]
The * is being stripped from the quote end marker. Also, is the missing space between the \q1 and \q2 markers a problem? I have noticed that we do frequently strip out the space between adjoining markers.
Imported string1: \q1 \qt2-s |who="someone"\*‚ÄòIn him we live and move and exist.‚Äô\qt2-e\*
Exported string1: \q1\qt2-s |who="someone"*‚ÄòIn him we live and move and exist.‚Äô\qt2-e
Imported string2: \qt1-e |eid="qt1_ACT_17:22"\*
Exported string2: \qt1-e |eid="qt1_ACT_17:22"
Imported file: [40-Matthew.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2653973/40-Matthew.usfm.zip)
Exported file: [41-MAT-exprt.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2653978/41-MAT-exprt.usfm.zip)

Also, I see that we have some issues with word markers and the text inside them. @PhotoNomad0 -Are we waiting for a spike to investigate how to deal with them? 
[In 1.1.0 (2ba28f8), the lines containing non-alignment related word markers are not being removed in the exported file.]
Imported string3: \w gracious|grace\w*
Exported string3: \w gracious\w*
Imported string4: \w gracious|lemma="grace" srcloc="gnt5:51.1.2.1"\w*
Exported string4: \w gracious|lemma="grace" x-srcloc="gnt5:51.1.2.1"\w*
Imported string5: \w gracious|link-href="http://bibles.org/search/grace/eng-GNTD/all"\w*
Exported string5: \w gracious|x-link-href="http://bibles.org/search/grace/eng-GNTD/all"\w*
Imported file: [usfm body testF.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2653954/usfm.body.testF.usfm.zip)
Exported file: [57-TIT-export.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2653959/57-TIT-export.usfm.zip)
[In 1.1.0 (ac75c11) all of the data is now preserved, although the line feeds after the word marker w* is now being removed. I am assuming that is acceptable formatting for USFM3, and thus am passing the issue]

**Comment by PhotoNomad0** [comment]
#### Tasks
- [ ] [2] Fix missing paragraph markers
- [ ] [8] Fix missing white space in inline quotes
- [ ] [8] Fix USFM word tag parameters when not part of alignment
- [ ] [2] PR reviews for 5388 in usfm-js and tCore

**Comment by PhotoNomad0** [comment]
#### Changes Made:
- fix issue that \p marker lost when newline after verse marker
- fix problems with inline markers such as quotes and formatting
- fix to preserve attributes on word marker that are different than how we use them

**Comment by PhotoNomad0** [comment]
@cckozie 
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-ac75c11.dmg.

**Comment by cckozie** [comment]
The issues are fixed in 1.1.0 (ac75c11). See note above about line feeds being deleted.
