### ISSUE TITLE
Localization of `Target Language`, `Original Language`, and `Gateway Language` in Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5399]
### User Story

As a user who doesn't speak English, I want all of the app to be localized into my language so that I can understand everything on the screen.

### Features / Specifications

- [ ] Note: Right now `Target Language`, `Original Language`, and `Gateway Language` all come from the project/resource manifest. As such they are not localized. 
- [ ] Make these strings localizable 
- [ ] Add these strings to CrowdIn

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by RoyalSix** [comment]
## Tasks
- [x] [3] Add localization to Scripture Pane

**Comment by cckozie** [comment]
1.1.0 (8b1ff72)
Works for Hindi, but does not work for the other non-English languages. I assume that is because those translations have not been made and we are defaulting back to English.
