### ISSUE TITLE
[60] Rework tW Check Card UI/UX, Contextual menu bar

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5601]
### User Story

As a checker, I want tW to force me to assess my selection so that I don't blindly "align" the tW checks without ever stopping to consider if the meaning is retained.

### Features / Specifications

- [ ] Add to UI (ToolKit)
  - [ ] (M) Create Contextual Menu bar with support for icons required
  - [ ] (M) Add support for each 3 subsection (contextual menu)
  - [ ] (S) Add new icons
- [ ] (S) Select Mode 
    - [ ] Note: "No Selection Needed" and "WordMAP" are covered in other issues. As such, the three buttons we currently have in Selection Mode will be the only ones covered/expected when this story is complete (Cancel, Clear Selection, Save)
    - [ ] Note: The "Plus" icon will be covered in another issue. 
    - [ ] Note: Maximize will work the same as it currently does. 
    - [ ] Change checkmark icon to highlighter icon
- [ ] Check Mode
    - [ ] (M) 3 buttons for meaning verification
    - [ ] (M) Update menu filtering to include new icons
    - [ ] (M) Two warnings (for unverified and different meanings). 
      - [ ] If "Unverified" is selected and the user clicks "Save & Next" or "Save & Previous", throw the warning telling them to verify the check. 
      - [ ] If "Different Meaning" is selected and the user clicks "Save & Next" or "Save & Previous", throw the warning telling them to edit or comment. 
      - [ ] For both warnings, "Skip" will take the user to the next check. "X" or "Close" will take them back to the Check Mode for that check.
- [ ] (S) Comment - update header bar
- [ ] (M) Verse Edit
    - [ ] Reconfigure so edit box on left side. 
    - [ ] Add Reset button - resets edits + checkboxes
    - [ ] Note: Edit + checks required before "Save" button activated. 
- [ ] (S) Bookmark - Change location + UI (functionality the same)

### Definition of Done

- [ ]
- [ ]
- [ ]

### Mockups

Select Mode: 
![image](https://user-images.githubusercontent.com/13352518/50162602-62621d00-02a4-11e9-9aa6-57c68e5868ae.png)

![image](https://user-images.githubusercontent.com/13352518/50162650-7d349180-02a4-11e9-8713-06970f6cdf6b.png)

Nothing to Select: 
![image](https://user-images.githubusercontent.com/13352518/50162639-76a61a00-02a4-11e9-9c9d-3645f3faf67b.png)

![image](https://user-images.githubusercontent.com/13352518/50162664-86bdf980-02a4-11e9-8e40-6f64e0e2e2c0.png)

![image](https://user-images.githubusercontent.com/13352518/50162695-8f163480-02a4-11e9-9cac-6579e89675ff.png)

![image](https://user-images.githubusercontent.com/13352518/50162703-95a4ac00-02a4-11e9-8c23-1fc6f0ada4fb.png)

![image](https://user-images.githubusercontent.com/13352518/50162722-9c332380-02a4-11e9-9be2-c7e7798de929.png)

![image](https://user-images.githubusercontent.com/13352518/50162727-a1906e00-02a4-11e9-9ee2-cb69ec5230d4.png)

No Selection Made: 
![image](https://user-images.githubusercontent.com/13352518/50162752-b10fb700-02a4-11e9-9701-8df281538084.png)

![image](https://user-images.githubusercontent.com/13352518/50162766-b836c500-02a4-11e9-8126-06fcbfcc4e8e.png)

Bookmark: 
![image](https://user-images.githubusercontent.com/13352518/50162797-c389f080-02a4-11e9-867f-85d9dc679ffe.png)

Verse Edit:
![image](https://user-images.githubusercontent.com/13352518/50162813-cc7ac200-02a4-11e9-9d24-1e79694a27ee.png)

![image](https://user-images.githubusercontent.com/13352518/50162828-d3a1d000-02a4-11e9-97f7-d6365c0920bb.png)

Comment: 
![image](https://user-images.githubusercontent.com/13352518/50162847-df8d9200-02a4-11e9-97a6-c27e2e7f5722.png)

![image](https://user-images.githubusercontent.com/13352518/50162861-e61c0980-02a4-11e9-9ba2-3297b54be70b.png)

Check Mode: 

![image](https://user-images.githubusercontent.com/13352518/50162879-f0d69e80-02a4-11e9-90fa-c730d78816b0.png)

![image](https://user-images.githubusercontent.com/13352518/50162891-f59b5280-02a4-11e9-9002-a4a90654f2d8.png)

![image](https://user-images.githubusercontent.com/13352518/50162903-fc29ca00-02a4-11e9-805f-bfd9ac83abb3.png)

![image](https://user-images.githubusercontent.com/13352518/50162919-0350d800-02a5-11e9-9b36-74ece41ffd2a.png)

![image](https://user-images.githubusercontent.com/13352518/50162938-08158c00-02a5-11e9-97b2-12d5963e23e7.png)
