### ISSUE TITLE
WordMAP Integration: Consume whole language (per identifier)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5662]
### User Story

As an aligner, I want tC to make suggestions based off of my work on other books so that I can save time and effort.

### Features / Specifications

- [ ] Alignment Memory will be based on the language + identifier (for instance, alignment memory from John English ULT would be used to populate suggestions in Acts English ULT, but NOT in Acts English UST)
- [ ] Needs to work in both the NT & OT (but obviously not across NT & OT since they are different original languages)
- [ ] Note: tN selections should not populate the Alignment Memory, but the tN tool should be given suggestions from the Alignment Memory

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
Assumption: do pair programming with Joel to help with knowledge transfer.

**Comment by da1nerd** [comment]
There are several ways to go about this so I'll just talk out loud here and see what I come up with...

## Requirements
> The **active project** is the project that has been selected and opened in a tool.

For a project to be eligible for alignment memory it must share with the active project a:
* common target language
* common original language
* common identifier (e.g. UST)

## Steps
* **[8]** add an API method to the wA tool that will fetch the global alignment memory.
  * Fetch a list of projects from tC (accessible as read-only ProjectAPIs perhaps?).
  * Filter projects based on the requirements above. The active project will be filtered out as well.
  * Read the project alignment data directly without going through redux or loading another tool instance. This will also not validate anything.
  * Cache alignment memory to at least session storage and possibly local storage.
  * Return combined alignment memory.
* **[8]** do the same for the [Checking tool wrapper](https://github.com/translationCoreApps/checking-tool-wrapper/blob/develop/src/Api.js) (possibly punt on this for now)
* **[5]** Utilize new api method to fetch global alignment memory during wordMAP initialization.
* **[2]** invalidate a project's cached alignment memory when opening the project.
  * This will force it to regenerate next time a different project is loaded.
* **[3]** Add method to the CoreAPI in tC that will return a list of projects. This might be an array of read-only ProjectAPI objects.

## Other Thoughts

wA will continue to fetch alignment memory for the active project from other tools directly. The cache will not be used in this case because the data in the active project is subject to frequent changes.

By keeping a global cache the performance should remain relatively stable except for the initial caching. Suggestions may be slower in appearing the first time the cache is being built.

**Comment by da1nerd** [comment]
This could probably be completed in 2-4 days.

Some additional detail, though the highlights are above:
![IMG_20190626_165122](https://user-images.githubusercontent.com/166412/60222733-4763fd00-9833-11e9-88e8-004cdb47de6f.jpg)

**Comment by cckozie** [comment]
1.2.0 (736956e)
It appears that selections made in tW no longer are included in alignment memory.
[projects.zip](https://github.com/unfoldingWord-dev/translationCore/files/3392756/projects.zip)
The Luke and 1 Peter projects in the attached file was not aligned, the others were.
After making tW selections in Luke for "blood" and "Father", suggestions for them were not shown in 1 Peter wA.
After making a tW selection in 1 Peter for "Father", still a suggestion did not appear for it in 1 Peter wA.
<img width="900" alt="luk1" src="https://user-images.githubusercontent.com/8171759/61226010-51b54080-a6e7-11e9-8b5f-bbe2e8bb38af.png">
<img width="926" alt="luk2" src="https://user-images.githubusercontent.com/8171759/61226058-61cd2000-a6e7-11e9-91ab-db8b854cd3ef.png">
<img width="1366" alt="1pe" src="https://user-images.githubusercontent.com/8171759/61226077-6bef1e80-a6e7-11e9-865a-4c129ee5faff.png">
<img width="905" alt="luk-father" src="https://user-images.githubusercontent.com/8171759/61226189-9640dc00-a6e7-11e9-9f7f-5c28c293eed4.png">
<img width="892" alt="1pe-father2" src="https://user-images.githubusercontent.com/8171759/61226344-def89500-a6e7-11e9-9a62-a70f9168325a.png">
<img width="1163" alt="1pe-father" src="https://user-images.githubusercontent.com/8171759/61226208-9e008080-a6e7-11e9-813c-feb7c1b37e62.png">

**Comment by da1nerd** [comment]
@cckozie You might recall it was agreed we would not support global alignment memory for tW and tN at this time.

**Comment by cckozie** [comment]
@neutrinog - Pretty sure the decision was to not support it for just for tN as per the 3rd bullet under Features above. tW support was there before. What say you @benjore?

**Comment by benjore** [comment]
@neutrinog It was my desire that the tW would continue to work as normal, namely, that selections in the tW tool would populate suggestions in the wA tool.

**Comment by cckozie** [comment]
1.2.0 (9f6a878)
It looks like it is no longer considering Lemma matches, or is it just not considering alignments in the same project? (After aligning Θεοῦ in the second image below, it failed to suggest the same word in the next verse. There are no other projects with a prct translation id on the system)
![image](https://user-images.githubusercontent.com/8171759/61300526-bdf77900-a7a7-11e9-9da2-075cdc7caaf7.png)

![image](https://user-images.githubusercontent.com/8171759/61300545-cb146800-a7a7-11e9-881e-dc6ba49f8492.png)

**Comment by da1nerd** [comment]
@cckozie  @benjore ok that may have been where the confusion started. Because "normal" to me means the way it's always been (e.g. not global). tW works as "normal" :)

We should be all set to support tW, however someone else should probably do it because I'm traveling soon. There's just a method that needs to be added to it's tool api. However, since tW and tN are using the same codebase, they'll need to make sure only to return memory if the tW tool is running. I have some thoughts on how to do this.
Perhaps @RoyalSix could do this since we pair programmed on this update.

**Comment by benjore** [comment]
Need to fix the lemma fallback. 

I'll pull out the "tW support" for now and we'll deal with that in a new issue.

**Comment by RoyalSix** [comment]
@cckozie I am not able to reproduce the issue of the `God` alignment not showing a suggestion. The projects folder shared has a Titus project with alignments already and the screenshots shared do not have any alignments besides God.

I unaligned the verse and realigned "Θεοῦ" in 1:2 to God and the suggestion showed up for the verse 1:3

**Comment by cckozie** [comment]
[projects.zip](https://github.com/unfoldingWord-dev/translationCore/files/3411851/projects.zip)

@RoyalSix - In 2.0.0 (b203700) I am seeing the following:
1. Within the same project I am seeing the lemma fallback working now. The example shown above in Titus 1:2 and 1:3 does now work correctly.
2. Selections made in tW in the same project are reflected in alignment memory for that project. (Christ as a selection in Titus tW does show as a suggestion in Titus wA)
<img width="1146" alt="Titus Christ tW" src="https://user-images.githubusercontent.com/8171759/61549249-2b5c1180-aa15-11e9-8865-b877b352086d.png">
<img width="1034" alt="Titus Christ wA" src="https://user-images.githubusercontent.com/8171759/61549263-344ce300-aa15-11e9-8974-d1abad3dfb2a.png">

3. Selections made in a different project that has the same language and translation id are not reflected in alignment memory. (Christ as a selection in Titus tW does not show as a suggestion in Ephesians wA)
<img width="1009" alt="eph Christ" src="https://user-images.githubusercontent.com/8171759/61549339-61999100-aa15-11e9-824d-8c5d90991153.png">

**Comment by da1nerd** [comment]
@cckozie that makes sense. The global alignment memory is not currently loading up the lemmas so those won't be available. It's possible to provide global lemma support, however that may come at a steep cost to performance. Rather than loading just the resources required for the selected project, tC will need to load resources for all projects at all times (source text and original text).

If tC is already pre-loading everything so that source text and original text is just sitting in redux waiting to be used then there shouldn't be much of a performance hit. However, I'm pretty certain that's not the case.

@benjore a more performant way to use lemmas with the alignment memory would be to store that information along with the alignment data on the disk. This would require a migration to change the structure of the alignment data. On that note: be aware that there's already a half-baked proposal for a new alignment structure at https://github.com/translationCoreApps/wordMAP/blob/master/alignment_output_sample.json. This could be easily extended to support lemmas. @klappy this would also help with the portability of alignment memory.

**Comment by klappy** [comment]
@neutrinog: I do encourage exploring the new alignment structure to support this :)

Not that it is heading this way yet, but wanted to remind us... We do have to be careful not to persist derived data to disk as it becomes a maintenance nightmare long term. Robert is already concerned about suggestions from the alignment memory not being updated (removed) when he removes an alignment. 

As we look at performance optimizations, we have to keep in mind the requirements/principles of WordMAP and that is to be as dynamic as possible and not to store derived corpus or trained data. If we do implement caching for whole language support, we have to be very strategic about it. On these large data sets, sometimes it is tempting to cache the derived data, but many times the parsing/correlating logic can be optimized to achieve similar results. Granted reading 66 files takes longer than 1 file for a language, we need to consider the impact of long term maintenance and troubleshooting that comes with it.

With that said: User's needs do trump developer's needs. If we are unable to do the above, I will concede the "requirement" to a strong recommendation.

**Comment by benjore** [comment]
@neutrinog @klappy We need y'all to come up with the best implementation for this so we can estimate it for future implementation.

**Comment by cckozie** [comment]
2.0.0 (71e7de6)
Passed the following tests for English NT and OT with translation id matches:
- Exact word matches appear as suggestions
- Lemma matches appear as suggestions
- Suggestions are removed when the project from which they came has its translation id changed.

**Comment by elsylambert** [comment]
Verified in 2.0.0 (78cd497) .
Tested for English and Hindi Projects in NT and OT. Exact word matches and Lemma matches are showing up in suggestions from Projects with same translation id.
Needs regression
