### ISSUE TITLE
Handle Importing and Exporting of Verse Bridges

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5679]
### User Story

As an aligner of the UST, I want tC to correctly handle verse bridges on import and export so that it doesn't add in extra verse tags that I have manually delete.

### Features / Specifications

- [ ] Retain verse bridge annotation (e.g. `\v 13-14`
- [ ] Do not add additional USFM codes (e.g. `\v 13` and `\v 14`)

## Tasks
-  Handle empty verse tag removal on export
   - If we find another verse that's covered by the verse span it will also be removed

### Notes
Importing this: 
![image](https://user-images.githubusercontent.com/13352518/51264351-ea0e7a80-197b-11e9-8423-b591671cbb9b.png)
Throws a warning that verses 1,2,3,4,6,7 are missing. Then if you export without even loading it in a tool you get: 
![image](https://user-images.githubusercontent.com/13352518/51264418-0f02ed80-197c-11e9-9fcb-beb57f6a8cef.png)

### Definition of Done

- [ ] This does NOT cover correctly handling verse bridges in any tools
- [ ] This issue only covers correctly handling the codes so that no corruption happens. 
- [ ]

**Comment by RoyalSix** [comment]
@benjore @cckozie  Can we get an example project for this one

**Comment by RoyalSix** [comment]
[tit.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2814193/tit.usfm.zip)
[41-MAT-ust.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2814429/41-MAT-ust.usfm.zip)
