### ISSUE TITLE
Edits made external to tC that invalidate selections are not caught until the project is opened in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5686]
1.1.0 (1034612)
Scenario B:
When a project is edited external to tC and then reimported, broken alignments are handled properly (the alignments invalidated alert it issues during the import and the broken link number is correct on the tool card). Edits that affect tW selections are not caught until the user navigates to the check that has been invalidated. (The alert is not displayed and the broken link number is not updated during the reimport)
To test:
Use a project that has some alignments and some completed checks.
Export the project to USFM not including the alignment data
Make edits to the USFM file that will break alignments, break selections, and break both.
Import the USFM file giving it the same translation ID as the original, and choose the Overwrite options

**Comment by RoyalSix** [comment]
## Tasks
- [x] [3] Add Selection Validation Logic To tW API
- [x] [1] Validate Selections On Tool Connect

**Comment by RoyalSix** [comment]
https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-dc646d8.dmg

**Comment by cckozie** [comment]
I'm not seeing the fix for this in 1.1.0 (edc48cb). tW invalidated selections are not caught until the project is loaded in tW. No warning is displayed during import and no broken links are displayed on the tW tool card until after it is loaded in tW.

**Comment by mannycolon** [comment]
Tested on b25e030 (v1.2.0)

**Comment by cckozie** [comment]
1.2.0 (b25e030) 
There are still several problems, although I'm not sure which should be fixed on this issue and which should be on other issues.
Issue A:
When the file containing the external edits is imported, the user still does not receive the reset alignments alert until the project is loaded in tW.

Issue B:
When the edited project is loaded in tW, the % complete circles are not updated until the check group is opened.

Issue C:
The broken link icon is not displayed on the menu tiles, but only in the hover over.
Note that the completion circle for the "anoint" group shows 100% when the project was loaded (top image), but less than 100% when the group is opened (bottom image).

![image](https://user-images.githubusercontent.com/8171759/53435881-779faa00-39bf-11e9-90b6-c8824ad22dd5.png)

![image](https://user-images.githubusercontent.com/8171759/53436901-d403c900-39c1-11e9-8c8d-6c9d41d96515.png)

**Comment by RoyalSix** [comment]
@cckozie Ok. I will just work on a fix for each one and attach PR here.

**Comment by RoyalSix** [comment]
## Tasks
- [x] When the file containing the external edits is imported, the user still does not receive the reset alignments alert until the project is loaded in tW.
- [x] When the edited project is loaded in tW, the % complete circles are not updated until the check group is opened.
- [x] The broken link icon is not displayed on the menu tiles, but only in the hover over.
Note that the completion circle for the "anoint" group shows 100% when the project was loaded (top image), but less than 100% when the group is opened

**Comment by RoyalSix** [comment]
A) seems to be fixed on the latest. I am using this build https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.2.0-b7e490a.dmg
@cckozie

**Comment by RoyalSix** [comment]
Found another issue when there are two checks in the same verse only the second one will be recognized as a broken link. 
I made a selection on both checks and then exported it to USFM and changed the text that I selected from that verse. In my case it was 1:15

**Comment by cckozie** [comment]
1.2.0 (ddfe57a) **FIXED IN 1.2.0 (de171a2)**
![image](https://user-images.githubusercontent.com/8171759/54629593-e663a680-4a45-11e9-9668-9a6036f87ddb.png)
I'm not sure that this problem is related to this issue, but I haven't seen it before.
I had this project:
[en_ult_act_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2984810/en_ult_act_book.zip)
I received the error when I imported this file selecting Overwrite:
[45-ACT.usfm 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/2984813/45-ACT.usfm.2.zip)

**Comment by RoyalSix** [comment]
@cckozie Just so you know this bug was caused by code being refactored in tW to fix invalidations but those changes were not carried over to tN.
I made a fix.

**Comment by cckozie** [comment]
1.2.0 (de171a2)
There are still problems associated with this issue, but I suspect they will be fixed #6001.
The user is not alerted to both wA and tW resets when the project is reimported.

**Comment by cckozie** [comment]
1.2.0 (1612995)
(Probably related to #5941 and #6001)
[en_test_1ti_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3157968/en_test_1ti_book.zip)
This project is fully aligned and has one tN check completed and one tW check completed.

[55-1TI-all.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3157971/55-1TI-all.usfm.zip)
This usfm2 file has 2 edits, one invalidates the tN check, and one invalidates the tW check. They both invalidate an aligned verse. When the usfm file is imported to overwrite the project, the user receives an alert indicating that the alignments have been reset, but no alert regarding the reset checks for either tN or tW. Also, the broken links on the tN and tW cards both indicate 0 invalidations.
When the project is loaded in tW, it does then indicate that a selection had been reset, although the tW tool card still indicates 0.
When the project is loaded in tN, there is no indication of a selection being reset; i.e. no alert, no broken link or edit icon on the check, and the tool still indicates that the selection is complete (checkmark on the menu tile and in the icon bar.

**Comment by RoyalSix** [comment]
May be fixed by #6000

**Comment by cckozie** [comment]
1.2.0 (f215a2f)
When reimporting a project that was edited outside of tC, the user is warned of reset selections and invalidated alignments and the broken link numbers on the tool cards are correct, but the % complete on the tN and tW tool cards still reflects what was accurate before the overwrite. After loading the project in the tool and returning to the tools page, the % complete is again accurate.

**Comment by RoyalSix** [comment]
@cckozie Can you provide some test projects I can use for overwriting? I am having trouble replicating this one.

**Comment by cckozie** [comment]
@RoyalSix - In 1.2.0 (299b3f7) I'm not seeing any of the problems noted above, but there is still one issue I'm seeing when using the files attached to the May 8 comment above.
After importing the overwrite file and opening the project in wA, only the broken link icon is displayed on verse 1:3. Both the edit and broken link icons should be attached to 1:3.

**Comment by cckozie** [comment]
Works correctly in 2.0.0 (99b8027), although the invalidated alignments and reset selections notices appear in separate alerts. There is already an issue to deal with this, #6188.

**Comment by elsylambert** [comment]
Verified in 2.0.0 (00bca0b). Working fine for wA. However observed an issue in tN: Edit made to selected text for tN did not get invalidated, when the edit is outside the selected string.
- edited verses in USFM that had selection in tN- ( changed Condemnation to Condemnations).
- after overwrite, in tN it showed the edited verse as  Condemnations but the selection was only highlighted for Condemnation.
However, when I did an edit in between the selections e.g "May peace and love be multiplied to you" to "May peace, joy and love be multiplied to you", it catches the invalidation. It only catches the edits inside the selection string, not outside it.

**Comment by elsylambert** [comment]
While testing the same scenario for tW (Edit outside the selected string),  I am getting the following error:
![image](https://user-images.githubusercontent.com/51806180/61889217-09f69c00-aed3-11e9-93c4-8ea65d7c05c5.png)

- Edit the verse in USFM (Edit outside of the selected string in tW for a given verse).
- Import the USFM using Overwrite option.
- Open the imported project, gives the error and not able to open the project.

Here is the log: 
[Thu Jul 25 2019.zip](https://github.com/unfoldingWord-dev/translationCore/files/3432356/Thu.Jul.25.2019.zip)

**Comment by elsylambert** [comment]
Here is the Luke Project:
[43-LUK.zip](https://github.com/unfoldingWord-dev/translationCore/files/3437467/43-LUK.zip)

**Comment by RoyalSix** [comment]
@elsylambert Are you able to send me just that project folder zipped up?
I need the project exactly how you have it in `{user}/translationCore/projects/{project_name}`. Thanks!

**Comment by elsylambert** [comment]
@RoyalSix Here is the Project:
[en_test_luk_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3443204/en_test_luk_book.zip)

**Comment by RoyalSix** [comment]
Hmmm interesting, is this the same project? This one is letting me open completely to the tool.

**Comment by RoyalSix** [comment]
@elsylambert This project has no data it's all missing verses. Should I still apply the test?

**Comment by elsylambert** [comment]
Please try with any other project that you have: 
- make selection in tN.
- edit  the same verse in USFM that had selection in tN- ( e.g Condemnation to Condemnations).
- after Project Import with overwrite, in tN it showed the edited verse as Condemnations but the selection was only highlighted for Condemnation.
However, edit made in between the selections e.g "May peace and love be multiplied to you" to "May peace, joy and love be multiplied to you", it catches the invalidation. It only catches the edits inside the selection string, not outside it.

**Comment by RoyalSix** [comment]
@elsylambert When I test the last case (edits made outside the selection string)
What is the expected behavior? Shouldn't it not show an invalidation in tN because you are not invalidating anything in tN? Only wA? 
When testing the last case and going back to open the tool I am seeing two icons on the menu:

- edited
- selection made

**Comment by elsylambert** [comment]
@RoyalSix : Please refer to the Video shots for better understanding:
Within the Selection String: 
[External edits-inside the selection string.zip](https://github.com/unfoldingWord-dev/translationCore/files/3457996/External.edits-inside.the.selection.string.zip)

At one point the Alert was not shown untill I was in the tN tool and the verse showed Broken link.
Outside of the selection String:
[External edits-outside selection String.zip](https://github.com/unfoldingWord-dev/translationCore/files/3457997/External.edits-outside.selection.String.zip)

**Comment by elsylambert** [comment]
Scope of this issue: the invalidated icon is not showing after an external edit and the fix would be to show that on tN tool card

Separated Issue with Edits outside the selection strings in #6317

**Comment by RoyalSix** [comment]
Steps to replicate:
- Get [this project](https://github.com/unfoldingWord-dev/translationCore/files/3468587/en_test_tit_book.2.zip)
- Export project to USFM2. Restart tC.
- Open the new saved USFM file. Remove the word "and" from "Grace and peace". Save. Close editor.
- Open tC
- Overwrite the project given with the new USFM file
- The broken link icon is not showing on the tool card
- Click "Launch", notice the broken link icon will now show on the tool card once the tool is almost done loading

**Comment by RoyalSix** [comment]
Should be fixed by #6321 @elsylambert

**Comment by elsylambert** [comment]
Working fine in 2.0.0 (3256e93). Invalidations are shown on tN tool card for the edits made externally.
