### ISSUE TITLE
Create Tool Card UI

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5756]
![image](https://user-images.githubusercontent.com/13352518/48024427-3d578780-e106-11e8-9dd1-0d048e2fb143.png)

**Comment by cckozie** [comment]
1.2.0 (d3d469b) - MULTIPLE ISSUES (9)

- [x] ISSUE 1: **Works in 1.2.0 (cc9c5b5)**
The Load button should be disabled when no categories are selected. (May be fixed when #5920 is fixed)

- [x] ISSUE 2: **Works in 1.2.0 (cc9c5b5)**
The top level checkbox should show the indeterminate state when only one or some of the child categories are checked. 

- [x] ISSUE 3: **Works in 1.2.0 (cc9c5b5)**
"Translating Father and Son" does not show up as a category on the tN card, but appears as a group menu item when the tool is open with a book that has that check. (Should be fixed when #5920 is fixed)

- [x] ISSUE 4: **Fixed in 1.2.0 (5ee926c) (see below)**
There are inconsistencies in what a category is named on the tN card and what it is named in the group menu. (Some examples follow)
<img width="980" alt="Numbers" src="https://user-images.githubusercontent.com/8171759/56686156-0e73a480-6699-11e9-9cdb-6fba6d4ff45f.png">
<img width="929" alt="grammar" src="https://user-images.githubusercontent.com/8171759/56686157-0e73a480-6699-11e9-98f3-d7bbd9335250.png">
<img width="942" alt="figures" src="https://user-images.githubusercontent.com/8171759/56686158-0e73a480-6699-11e9-8074-d455c0c42af0.png">
<img width="967" alt="discourse" src="https://user-images.githubusercontent.com/8171759/56686160-0e73a480-6699-11e9-9afb-3665fad30045.png">
<img width="972" alt="culture" src="https://user-images.githubusercontent.com/8171759/56686162-0e73a480-6699-11e9-8c25-3accfdd2e943.png">

- [x] ISSUE 5: **Fixed in 1.2.0 (5ee926c) **
There are inconsistencies between the subcategory name and the title on the popup card. For example:
![image](https://user-images.githubusercontent.com/8171759/56772674-997b9a00-6780-11e9-8ebc-7cde1c937231.png)

- [x] ISSUE 6: **Fixed in 1.2.0 (5ee926c) **
It appears that all subcategories are loaded for a category if any of them are selected.
![image](https://user-images.githubusercontent.com/8171759/56766861-09cdef80-6770-11e9-9549-53a2e27b6875.png)

- [x] ISSUE 7: **Fixed in 1.2.0 (5ee926c) - mr_IN is no longer available as a locale **
Missing translation keys on tool card (locale specific probem)
![image](https://user-images.githubusercontent.com/8171759/56810981-4dbb0600-67fd-11e9-88dc-a4688be104e2.png)

- [x] ISSUE 8: **Fixed in 1.2.0 (5ee926c) **
Some subcategories are not capitalized. For example:
![image](https://user-images.githubusercontent.com/8171759/56836539-31d75480-683d-11e9-8762-6948ee89f326.png)

- [x] ISSUE 9: **Fixed in 1.2.0 (5ee926c) **
The subcategories are sometimes not in alphabetical order. For example:
![image](https://user-images.githubusercontent.com/8171759/56836569-4e738c80-683d-11e9-9d6c-4ec2d5a6ecb2.png)


For reference: the official breakdown of categories is found here: https://docs.google.com/spreadsheets/d/1MCWzmtqetzmZkKj_RouzyJB9b0gLvjLR7ZmiVBJw2fw/edit?ts=5c92ae54#gid=0

**Comment by mannycolon** [comment]
@cckozie`ISSUE 4` is not clear. The screenshots shown seem to be the wrong screenshots.

**Comment by mannycolon** [comment]
@benjore What should we do about `ISSUE 5`?

**Comment by cckozie** [comment]
@mannycolon - Yes, I agree #4 is unclear. I'll try to make a list of all of the inconsistencies and add it to the issue tomorrow.

**Comment by cckozie** [comment]
**Fixed in 1.2.0 (5ee926c) **
Here are the relevant screenshots for ISSUE 4 above. A couple of the problems with Figures of Speech are just capitalization.
<img width="771" alt="culture" src="https://user-images.githubusercontent.com/8171759/57150464-ffc17780-6d93-11e9-88db-ca4e87da0ba9.png">

<img width="771" alt="discourse" src="https://user-images.githubusercontent.com/8171759/57150510-1e277300-6d94-11e9-8070-febc90f4d31c.png">

<img width="759" alt="discourse4" src="https://user-images.githubusercontent.com/8171759/57150526-27b0db00-6d94-11e9-832b-b24c2b4bc16c.png">

<img width="747" alt="figures" src="https://user-images.githubusercontent.com/8171759/57150540-31d2d980-6d94-11e9-8e02-e7c58959d88c.png">

<img width="763" alt="grammar" src="https://user-images.githubusercontent.com/8171759/57150549-3c8d6e80-6d94-11e9-9669-c22f270be5ad.png">

**Comment by mannycolon** [comment]
> @benjore What should we do about `ISSUE 5`?

@benjore ??

**Comment by mannycolon** [comment]
> @benjore What should we do about `ISSUE 5`?

Disregard.

**Comment by cckozie** [comment]
All issues look good in 1.2.0 (5ee926c)
