### ISSUE TITLE
Revert tC back to native Git

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5911]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

## Additional Context
See issue https://github.com/unfoldingWord-dev/translationCore/issues/5798 for reasons behind this.

**Comment by PhotoNomad0** [comment]
**Info from Joel:**
- concourse build is just running commands in https://github.com/unfoldingWord-dev/translationCore/blob/develop/gulpfile.js
- specifically it uses `build` and `release-[os]` (except for linux it uses `release-linux-deb`) commands
- you can see which gulp command it's executing in the `run-build-*` scripts here: https://github.com/unfoldingWord-dev/concourse-pipeline/tree/master/scripts.

**Comment by PhotoNomad0** [comment]
### Tasks
- [ ] [6] update the gulpfile to download git again to include with the builds
- [ ] [3] add back the warning to users if git is not installed
- [ ] [6] update `Repo.js` to use `nodegit` again - use old code as reference

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-win-x64-1.1.3-b525e6c.setup.exe

**Comment by cckozie** [comment]
These timings were made using this project: https://git.door43.org/lrsallee/en_ult_act_book
1.1.3 (64d8fb7) - Isomorphic git
Import from Door43 - 100 seconds
Upload to Door43 - 120 seconds
Reupload to Door43 (no changes) - 24 seconds

1.1.3 (126c679) - Native git. Similar timings to 1.0.2
Import from Door43 - 30 seconds
Upload to Door43 - 16 seconds
Reupload to Door43 (no changes) - 9 seconds

Need to test installation on Windows.
Windows install is OK. Still has the original problem in #5939.
