### ISSUE TITLE
Display alignment data as highlights for translations

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6265]
### User Story

As an aligner, I want to see how translations have been aligned so that I can understand better how alignment is supposed to be done, and so that reference other translations better when I do my work.

### Features / Specifications

- [ ] Rules
- Whatever is right-clicked is highlighted in green (in SP is solid green, solid green outline in Alignment Pane, if applicable, and Word bank, if applicable) 
- For other translations, if there is a complete alignment, highlight it in solid yellow. 
  - If A is right-clicked, and A<>1, then A is green and 1 is yellow. 
  - If A is right-clicked, and A<>1,2,3, then A is green and 1,2,3 is yellow.
- For partial alignments, underline it in yellow. 
  - If A is right-clicked, and A,B<>1,2, then A is green and 1,2 is underlined in yellow
  - If A is right-clicked and A,B<>1, then A is green and 1 is underlined in yellow. 
- For resource translations or target translations, only highlight complete alignments. 
  - If 1 is right-clicked and A<>1,2,3, then 1,2,3 is green and A is yellow. 

- [ ] Highlighting original language words
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/080e0c31-77fd-4666-8e64-b89cd5bd8f37)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/83f6974d-6d2b-4248-8286-70fab96befcc)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/40de0469-eba9-44da-af6d-474e3612eeed)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/5c11942a-e31d-4a46-bbb2-8819537425d0)

- [ ] Highlighting unaligned Target Language words

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/02074f49-932f-4a1e-b9dc-eb1b0bb00a01)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/cea8a416-7552-48f4-a173-fa8dc5ee733a)

- [ ] Highlighting aligned target language words

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/f787b0a1-fa84-45da-ad00-3f3451e7caaf)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/48a3f885-12d4-4c0e-92d9-ce2303c0a115)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/5fa37bcf-3244-4324-a3e4-94718f180b05)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/d741c27f-f8ca-4b7f-b6d5-8268a23f3cd8)

- [ ] Highlighting aligned resources

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/6f4b914e-4bb4-4f91-927f-189cad5af180)

- [ ] Unaligned resources or unaligned words

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/54a67bb5-5468-414e-80aa-6597c8893e24)

  | Target Word (Word Bank) | Target Word (Alignment Pane) | OrigL Word (Alignment Pane) | OrigL word (SP) | Target Word (SP) | Resource Word (SP)
-- | -- | -- | -- | -- | -- | --
Click | Select | Select | Lexical Info (Select if not 1st word selected) | Lexical Info | Nothing | Nothing
Right-Click | Highlight word in SP & WB | Highlights + Alignment Data & SP | Highlights + Alignment Data | Highlights + Alignment Data | Highlights + Alignment Data | Highlights + Alignment Data
Cmd/Ctrl-Click | Select | Select everything in Dropbox | Select everything in Dropbox | Nothing | Nothing | Nothing
Shift-Click | if selection, then multi-select | Nothing | Nothing | Nothing | Nothing | Nothing

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by birchamp** [comment]
Needs spike to see what modules need to be reworked and how much effort will be involved
