### ISSUE TITLE
Tools breakdown

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#677]
# User Story

As a _checker_ I want _smaller tools_ so that _I don't feel so overwhelmed_.

# Definition of Done

**Preparation Checks**
- [ ] Completeness Check = #247 
  - [ ] Check that all books/chapters/verses exist in project, 
  - [ ] according to specified versification pattern
- [ ] Verse Length Comparison
  - [ ] for duplication/omission/excessive elaboration of verse content

**Translation Hazards**
- [ ] Kinds of Writing
  - [ ] translate_symaction
  - [ ] writing_proverbs
  - [ ] writing_symlanguage
  - [ ] writing_apocolypticwriting
  - [ ] figs_parables
  - [ ] writing_poetry
  - [ ] writing_quotations
- [ ] Transitions
  - [ ] writing_newevent
  - [ ] writing_background
  - [ ] figs_events
  - [ ] writing_endofstory
  - [ ] writing_connectingwords
  - [ ] writing_intro
- [ ] Who Does What
  - [ ] writing_participants
  - [ ] translate_names
  - [ ] figs_gendernotations
  - [ ] figs_123person
  - [ ] figs_rpronouns
  - [ ] figs_genericnoun
- [ ] Implied Information
  - [ ] figs_explicit
  - [ ] figs_ellipsis
- [ ] Ancient and Unknown Things
  - [ ] translate_bmoney
  - [ ] translate_unknown
  - [ ] translate_bvolume
  - [ ] translatebweight
  - [ ] translate_bdistance
  - [ ] translate_hebrewmonths
- [ ] Figures of Speech Check - #643 
- [ ] Grammar Check
  - [ ] figs_quotation
  - [ ] figs_activepassive
  - [ ] figs_you
  - [ ] figs_hypo
  - [ ] figs_inclusive
  - [ ] figs_exclusive
  - [ ] figs_doublenegatives
  - [ ] figs_abstractnouns
  - [ ] figs_distinguish
  - [ ] figs_nominalad
  - [ ] figs_youdual
  - [ ] figs_yousingular
  - [ ] figs_youcrowd
  - [ ] figs_youformal
- [ ] Divine Father-Son
  - [ ] guidelines_sonofgodprinciples

**Words**
- [ ] importantWords
  - [ ] Key Words
- [ ] Names
- [ ] otherWords
  - [ ] Other Words

**Quality Rubric**
- [ ] Quality Assurance Rubric

**Pre-publication**
- [ ] Spelling
- [ ] Punctuation
- [ ] Headings
- [ ] Footnotes
- [ ] Formatting 
  - [ ] quotes, poetry, page layout
