### ISSUE TITLE
Training Team Retrospective

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#683]
- [x] Chunk/Chapter links in Scripture pane
- [x] Scroll through verses/chunks in scripture pane ( #654 )
- [x] Collapsible menu, to give more screen real estate (less on screen)
- [x] Smaller space for add resources, make room for text
- [x] Put check in the top menu navigation
- [ ] Greek parse the verbs (dependent on importing UGNT 0.2)
- [ ] Auto close the greek pop-up when advancing verses
- [ ] Have greek gloss come up on hover (wait ~.5 seconds) ( #689 )
- [x] Color scheme for helps to match before pop-up, and lighter gray ( #690 )
- [x] Auto-complete propose change when flag is clicked 
- [x] Add UDB to Scripture Pane References ( #667 )
- [x] Move save confirmation message to somewhere in the middle
- [x] Pre-populate proposed change to what they highlight in an area that is unchangeable and light gray, and they edit the text below it to propose the change. 
- [x] Notes are not visible when proposing a change, and some changes need the notes
- [x] Move notes to the side panel so they are visible when proposing changes
- [x] Do not allow checkmark if there is a proposed change
- [x] Tabs in modal need text like top navigation menu, don't know what icons mean yet

- [x] User needs to only change the check in the proposed changes, notes used for other changes right now, because user just can't let other changes go.

- [x] Potentially move help to a corner of the screen
- [x] Hover to open up tA
