### ISSUE TITLE
Project Import Check

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#691]
Based on #301 
https://xd.adobe.com/view/6509deb3-015c-4926-829d-dcefea2a0624/

- [ ] A User may only import one project at a time
- [ ] When a user imports a project either locally or from online... 
  - [ ] While the spinner is spinning tC should run the following checks:
    - [ ] Merge Conflict check
      - [ ] If there is a merge conflict, abort the import process and give the following message: "Import Failed - This project has merge conflicts. Please resolve these conflicts and re-import the project. You may be able to use translationStudio to help you resolve these merge conflicts." One primary button - "Cancel Import"
      - [ ] If no merge conflicts, continue to next check
    - [ ] File format check
      - [ ] If the text is in the wrong format, abort the import process and give the following message: "Import Failed - This project is not in a supported format. Please convert your project to a supported format and re-import." One primary button - "Cancel Import"
      - [ ] If file format is supported, continue to next check
    - [ ] Corrupted Data??
    - [ ] Fatal Errors??
  - [ ] Keep the spinner spinning and perform the following checks. If all the info is present and in order, skip straight to the "Success Message". If one or more of the following fail, open the stepper and take the user to the first check that fails. 
    - [ ] Step 1: Copyright Check #1710 
    - [ ] Step 2: Project Info Check #1711 
    - [ ] Step 3: Missing Verses Check #247 
  - [ ] Success Message: "Success! Your project has been imported!"

**Comment by klappy** [comment]
# Project Validation

## Front End
Epic to hold all front end stories
### ProjectValidation: Stepper UI (Jay)
- Create ProjectValidationStepper container and components
- Implement ProjectValidationStepper Styling
- Implement ProjectValidationStepper Reducer and Actions
### ProjectValidation: Copyright Check (Manny)
- Create ProjectValidation CopyrightCheck component
  - ProjectValidation/CopyrightCheck Folder with index.js for main component
- ProjectValidation CopyrightCheck Instructions
- Create ProjectValidation CopyrightLicenceCard component
  - Icon, license id, license name, overview text.
### ProjectValidation: Project Information (Manny)
- ProjectValidation ProjectInformation Instructions
  - Move Attention data to instructions
  - Remove cancel import
- Create ProjectValidation ProjectInformation components
  - ProjectValidation/ProjectInformation Folder with index.js for the main component
  - Form for manifest details
  - Book drop down
### ProjectValidation: Merge Conflicts (Klappy)
- ProjectValidation MergeConflict Instructions
- Create ProjectValidation MergeConflicts component
  - ProjectValidation/MergeConflicts Folder with index.js for the main component
- Create ProjectValidation MergeConflictCard component
  - Create ProjectValidation MergeConflictOption component
### ProjectValidation: Missing Verses (Klappy)
- ProjectValidation MissingVerses Instructions (no report)
- Create ProjectValidation MissingVerses component
  - ProjectValidation/MissingVerses Folder with index.js for the  main component
- Create ProjectValidation MissingVerseCard component
  - Create ProjectValidation MergeConflictOption component


## Back End
Epic to hold all back end stories

### Integrate ProjectValidation Stepper in Project Open
Having two steppers seems confusing, seems like it should be a modal.
- ProjectValidation Stepper Determine which checks to prompt
- ProjectValidation Stepper Opens when project is selected
### CopyrightReducer and Actions
- CopyrightReducer has an array of all valid copyrights and their data
  - Icon, license id, license name, overview text, path to license md
  - Find license file and overview paragraph of each license.
- CopyrightActions
  - Saves current copyright in project manifest and LICENSE file.
### ProjectValidation ProjectInformation Reducer and Actions
- ProjectInformationReducer
  - manifest, project save location and progress of tools
- Update prop references from params to ProjectDetailsReducer.manifest
  - Update book id\name to come from manifest.project.id\name
- ProjectInformationActions
  - Manifest save/load to fs in project folder
  - Action to edit the ProjectInformationReducer
### ProjectValidation MergeConflicts Reducer and Actions
- MergeConflictsReducer 
  - Array of all merge conflicts
- MergeConflictsActions
  - Find merge conflicts
    - Look for node library for merge conflict parsing
  - Populate reducer with merge conflicts
### ProjectValidation MissingVerses Reducer and Actions
- MissingVersesReducer 
  - Array of all missing verses
- MissingVersesActions
  - Find missing verses
  - Populate reducer with missing verses

**Comment by cckozie** [comment]
[fr_eph_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1242999/fr_eph_text_reg.usfm.zip)
Imported usfm file.
Cancelled out of copyright screen.
Project does not appear in project list (even after restrarting tC), but when I attempt to import it again, I get the "selected project already exists..." message.
Yes, it does show up in the project directory on my computer.
This appears to happen whenever the user cancels out of the import check at any step.

**Comment by mannycolon** [comment]
# QA Tasks:
- [1] Debug USFM project importing bug with project validation
- [3] Fix USFM project importing bug with project validation

**Comment by cckozie** [comment]
Covered by other issues.
