### ISSUE TITLE
Export Data for tN - To determine essential checks

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#693]
# User Story

As a _data checker_, I want to _indicate which tNotes are essential_ so that _the tNotes check can be divided into essential and other checks_. 

# Definition of Done

- [ ] Google docs that can be edited to show which notes are essential. 
  - [ ] Categories: essential?, book, chapter, verse, quote, Note, tA slug
  - [ ] One book per sheet/tab
- [ ] Titus & Ephesians
- [ ] STRETCH: All Bible

**Comment by ihoegen** [comment]
https://docs.google.com/spreadsheets/d/1GwBxAqvSm9uNN4MIONV0rQqrEmHh70ttaEmhduGzvGU/edit?usp=sharing
