### ISSUE TITLE
Choose and use complex script font for a project

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6935]
### User Story
As a tC user, I want to be able to choose a font from a list of limited font options that will then display the project's language so I can check my text.  Fonts are limited to: Noto Sans, Padauk, Sheherazade, and Awami Nastaliq.
 
### Features / Specifications

- [ ] Add font selection dropdown to project info screen with Noto Sans as the default and Awami Nastaliq, Scheherazade, Padauk fonts as options.
![Font_Choice.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/222b5772-7e29-4b13-b8d7-485fab69bf8c)
- [ ] Save font choice to the project 
- [ ] Use chosen font wherever the project is displayed (Sample projects in #6788)

### Definition of Done

- [ ] Chosen Font is used and should render text correctly to a native user wherever that project is opened in tC.

**Comment by mannycolon** [comment]
@birchamp 
1. What do you mean when you say `standard Unicode font`? Do you mean keep using the regular font we currently use?
1. `Current Unicode, Sheherazade, and Awami Nastaliq.` Is this the correct list? Aren't we missing `Padauk` on that list?
1. What does `Render the project as Right-to-Left (RTL) if it is designated as such` entail?

**Comment by birchamp** [comment]
@mannycolon 
1. Yes.  I'm not sure what the name itself is.
2. Padauk is lower priority than the other 2 at this point. If we can get these 2 in then we can work on Padauk.
3. We just want to make sure if the project is set as a RTL project, that it's shown RTL wherever it's displayed.

**Comment by mannycolon** [comment]
@birchamp Okay, we'll discuss tomorrow in sprint planning

**Comment by mannycolon** [comment]
Fonts can be found here https://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_fonts#9af3d9fe

**Comment by mannycolon** [comment]
I would suggest including the Padauk font in this issue since adding it wouldn't change the estimate or the technical scope of the issue. It would allow us to easily validate complex script because of how easy it is to identify when the Burmese is rendering correctly.

**Comment by birchamp** [comment]
@mannycolon that development use increases the value of the Padauk. I'll add it.
