### ISSUE TITLE
Adjust text size of scripture text

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6943]
### User Story

As a checker using tC, I want to be able to change the size of the text in a specific pane so I can read the text more clearly or see more of the text at one time. The sizes of the text should be saved so it remains the same.

### Features / Specifications

- [x]  Each scripture text pane should have a text size adjustment icon and slider (see mockup below)
- [x] Sizing should range from the `default font size` - 20% to `default size` + 80%
  - Example: if `default font size` is 110% then the font range is 90 to 190
(This was later changed to be 80% to 240%)
- [x] Size adjustments should happen as the slider is moved to provide immediate feedback
- [x] Clicking off the slider will cause the slider to hide.
- [x] The expanded scripture pane should maintain the size chosen in the scripture pane.
- [x] The size of the text in the tN/tW highlight area will be maintained after the highlight is saved.
- [ ] Size choices in the scripture pane persist across tools (low priority)

### Definition of Done

- [ ] The user can adjust the text of any scripture on the screen.

### Mockups
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/dd8f497b-2814-4ae0-b62f-cdccb4e017a5)
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/8dcb8cb1-ffac-4308-a1a8-74bb6fdd13fb)
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/8cf98a94-f891-4a4a-b531-4548f84b0951)

**Comment by mannycolon** [comment]
- [ ] Create font size slider component (UI)
- [ ] Change scripture panes' X icon to 3-dot menu
- [ ] Design scripture pane's 3-dot menu items (UI)
- [ ] Design font resizing backend functionality 
- [ ] Add font size slider 3-dot menu to multiple UI components

**Comment by mannycolon** [comment]
@birchamp We're missing the tN/tW mockups

**Comment by elsylambert** [comment]
@birchamp Expand button in the check pane in tN and tW , is to be added.
Not seeing the expand button in tN and tW.
<img width="1212" alt="Screen Shot 2020-06-07 at 4 16 34 PM" src="https://user-images.githubusercontent.com/51806180/83979164-532cc000-a8da-11ea-950b-b36fc7c57b0f.png">

Expand button appears only when there is a selection in the "Please select translation for" pane
<img width="1212" alt="Screen Shot 2020-06-07 at 4 20 51 PM" src="https://user-images.githubusercontent.com/51806180/83979318-7dcb4880-a8db-11ea-851e-f015c085d7c7.png">

**Comment by birchamp** [comment]
Examples of sliders for text resize
Android and ChromeOS
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/0583fcac-997b-4ce7-b52d-6da46ebdc0de)

iPhone:
<img src="https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/9b942ba2-b8b5-493d-80e8-cefccfc65f92" width="300">

Windows:
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/552e665e-29bc-40f5-a4db-9e1b8b25fe4d)

Logos app:
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/b6edbdf5-eff9-4b2a-bd85-b71124f0309e)

**Comment by mannycolon** [comment]
Verified on 80e133b
