### ISSUE TITLE
3.0.2 Release Checklist

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7110]
Release Steps Sign Off

### Definition of Done

- [x] QA signs off on specific build in regression testing: current for `v3.0.2`, build number: `0f2d103`
- [x] Update changelog 
- [x] create draft release on github for translationCore 
- [x] Attach the github action builds (same build as QA signed off) to the draft release as assets 
- [x] Update Release Notes to the draft release
- [x] after everyone has reviewed translationCore  draft release, make it an official release.
- [ ] ~Update language database in tCore (Note: this is probably not necessary for a point release)~ - this is an automatic script run on every build
- [ ] ~Updated resources (Note: normally N/A for this point release since we chose not to update resources) - we only updated en and hbo resources~ - not needed for point releases
- [ ] ~Create Mac Build on Mac PC (use same commit as QA signed off on, makes a smaller build, is~ - not needed for github actions builds
- [ ] ~QA does quick check of Mac Build on Mac PC (to make sure resources and features not changed from build in regression testing).~ - not needed for github actions builds
- [x] Confirm all links to the release download:
  - [x] translationcore.com
  - [x] unfoldingword.org - https://www.unfoldingword.org/for-translators/tools ?
  - [x] github release page - https://github.com/unfoldingWord/translationCore/releases
  - [x] door43 forum

**Comment by PhotoNomad0** [comment]
@RoyalSix release notes - see steps in [Dev Workflow Document](https://docs.google.com/document/d/1-dJvDrxjIYwiUKUnH-E8qZel-DCDhsgM8iR-n9Cm57w/edit#heading=h.kwwwpmel1ulv) (scroll down to Release Process section)
