### ISSUE TITLE
UX/UI Tweaks from Demos

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#72]
There are a handful of UX/UI suggestions that have been made during demos. Not that we accept them all but it helps us identify opportunities for improvements.
- [ ] Fix Progress Bar
- [x] Way to cancel if progress bar is stuck (button to refresh?)
- [x] Highlighter instead of colored words
- [ ] Address Door43 Confusion in Intro Tutorial
- [ ] Headings on each "well" or section
- [x] Confusing names for translationNotes and translationWords
- [x] Key Words Check for tW.
- [x] Literary Devices Check for tN.
- [ ] Tooltips or instructions for each section (?)
- [x] Way to close the current project without closing tC
- [x] Target on Left instead of Right for focus on Checking
- [ ] Notify of updates to check app or new check apps
- [ ] Ask to save/sync on close/exit.
- [x] Confusing to have apps inside of an app.
- [ ] Introduce tC to answer why people should trust it. Best Freely Available Resources created by the best available team.
- [ ] Change font size, especially for Arabic.
- [x] Label content so that they know what it is.
