### ISSUE TITLE
3.1.0 Release Checklist

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7215]
Release Steps Sign Off

### Definition of Done

- [x] QA signs off on specific build in regression testing: current for `v3.1.0`, build number: `a7d2893`
- [x] Update changelog 
- [x] create draft release on github for translationCore: https://github.com/unfoldingWord/translationCore/releases/edit/untagged-28788b7faf74a4cc5bf7
- [x] Attach the github action builds (same build as QA signed off) to the draft release as assets 
- [x] Update Release Notes to the draft release
- [x] after everyone has reviewed translationCore  draft release, make it an official release.
- [x] Confirm all links to the release download:
  - [x] translationcore.com
  - [x] unfoldingword.org
  - [x] github release page - https://github.com/unfoldingWord/translationCore/releases
  - [x] door43 forum

**Comment by birchamp** [comment]
@elsylambert can you confirm that the links are correct on translationcore.com and any other places you normally would check? and then we can close this

**Comment by elsylambert** [comment]
@birchamp Verified. The build links are correct on the Release Page and on Translationcore.com.
