### ISSUE TITLE
Ease of setup for new developers

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#8]
This Epic should include tasks/user stories for making the setup of tC much easier and simpler for new developers.

The current process is very cumbersome and challenging.
# Mac OSX Instructions (Needs updating)
- [ ] Install X-Code
- [ ] Install Node.js
- [ ] Clone Repo (or Fork if not internal team)
- [ ] Pull latest develop branch
- [ ] sudo npm install -g electron
- [ ] Run application with `electron .`
# Instructions for contributions
- [ ] Let the team know what you are working on
- [ ] Create feature branch
- [ ] Develop
- [ ] Commit early and often
- [ ] Ensure your code works. Test, Test, Test
- [ ] Push your branch
- [ ] Submit PR
- [ ] Rinse, Repeat, ..., Profit.

**Comment by ihoegen** [comment]
I can write a guide to this when my new laptop comes in.

**Comment by klappy** [comment]
Okay thanks, once that guide is ready, we can assess how to simplify the process.

**Comment by ihoegen** [comment]
One thing we have to do for sure is centralize the auth tokens

**Comment by klappy** [comment]
My Mac had issues and I had to reinstall OS X from scratch... Now I'm needing to setup the app again, anybody got some pointers for me? I'd like to use this opportunity to test an overview/documentation for setup.

**Comment by RoyalSix** [comment]
That is unfortunate... well for now you will need:
Authentication file in the src/, modules/lexical_check_module, and modules/phrase_check_module
A TS project, with completed chunks. There's one on the slack if you search the chat for "test_files"
I believe that's all you need, I recently cloned the new fork and thats all I had to do.

**Comment by RoyalSix** [comment]
That is unfortunate... well for now you will need:
Authentication file in the src/, modules/lexical_check_module, and modules/phrase_check_module
A TS project, with completed chunks. There's one on the slack if you search the chat for "test_files"
And do a "npm install" in the root folder
I do not have a .config file and the app is running fine without it, not sure why.
I believe that's all you need, I recently cloned the new fork and thats all I had to do.
Make sure you have no trace of old projects when starting the app or it may search for an old one and not load the parameters correctly.

**Comment by klappy** [comment]
@RoyalSix: Thanks! That helps get me started, however that doesn't seem to get electron up and running. Before I debug that on my own, I'll wait to try out the instructions that is provided so we can test it.

**Comment by RoyalSix** [comment]
Ohhh yeaaa electron. I would like to see that as well because I don't recall.

**Comment by ihoegen** [comment]
To bring in electron, it's `npm install -g electron`

**Comment by klappy** [comment]
Also, what instructions would you like to provide for installing node.js? I haven't done that yet and can help try out what we suggest. For OS X anyway, we'll have to use a virtual machine or somebody else's windows install to test Windows.

**Comment by ihoegen** [comment]
There's a really easy to use Windows installer.

**Comment by ihoegen** [comment]
I can write the Windows setup guide when my new laptop comes in.

**Comment by klappy** [comment]
We could post a link to their site and just ask them to follow their instructions so we're not responsible for updates.
https://nodejs.org/en/download/

Also, I think we should use LTS as long as possible, and only change to Current/Latest if we absolutely have a good reason like for new requirements.

What version did the team use for development this far?

**Comment by ihoegen** [comment]
# Windows

These are the setup and contribution instructions for Windows users

## Dependencies

**Git**: Download installer from [https://git-scm.com/](https://git-scm.com/)
Install using whatever settings you would like, as long as you make sure to choose the option that allows git to be accessible from the Windows Command Prompt.
**Node and NPM**: Download installer from [https://nodejs.org/en/download/](https://nodejs.org/en/download/)

## Project Setup
1. Open a Windows Command Prompt wherever you would like to work on translationCore.
2. Run the command `git clone https://github.com/unfoldingWord-dev/translationCore.git`, or you may clone your own fork.
3. Change directories to the repository directory and run the command `npm install` to install all required Nodejs modules.
4. Create a file `.auth` in the root folder of the project.
5. Compile and run the project by running `npm run start`

# Project Contributions
1. Let the team know what feature you are working on.
2. Contributions should be done on a branch named with your initials and the feature being brought in. Example: `ih-instructions`. This branch should be based off develop.
3. Commits should be in detail and give a clear idea of what is being done and why. Same goes for pull request. It is important to commit early and often.
4. Merge locally with develop when changes occur. 
5. Ensure your code works. Test, Test, Test.
6. Push your branch to your remote.
7. Submit a Pull Request with develop.
8. ???
9. Profit

**Comment by ihoegen** [comment]
Here's a draft of the setup process on windows. What do you think?

**Comment by ihoegen** [comment]
@klappy I've eliminated the steps that involve installing anything globally. Now they just have to run some npm scripts as defined in the manifest. They'll be a part of my pull request tomorrow.
