### ISSUE TITLE
Select Mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#859]
# User Story

As a *checker* I want *to easily align my translation* so that *I can leverage computer-assisted checking and do manual checking in the process*. 

# Definition of Done
- [x] Left side - the translation of the verse where the check is being performed. 
- [x] Right side - instructions + the check that is being performed (this is the same as the left ~1/3 of the check info card)
- [x] Links to Comment and Edit Modes
- [x] "Save & Continue" is always active. If nothing is highlighted, a pop-up with further directions appears (see mockup)
- [x] "Save & Previous" saves the progress on the current check and returns the user to the previous check
- [x] Remove bold on highlight
