### ISSUE TITLE
Implement Redux

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#874]
- [x] Make Object Spread Operator usable in tC.  (Manny)
- [x] Change reducers from  using **lodash.merge** to **Object Spread Operator.** (Manny)
- [x] SPIKE: research how to handle data persistence in redux. (Manny)
- [x] SPIKE: Make a list of Actions that need to be converted to Redux Actions #886
- [x] SPIKE: How can we clean app.js to make it more redux like? (Jay and Manny)
- [x] List what components need to be refactored. (Jay and Manny)
- [x] Identify all API calls that need to be refactored. (Jay and Manny) #899
   1. api.getDataFromCheckStore
   2. api.getDataFromCommon 
   3. api.putDataInCheckStore
   4. api.emitEvent
   5. api.convertToFullBookName
   6. api.getAuthToken

- [x] Implement redux actions to handle: (Jay and Manny)
```
   ScripturePane = api.getModule('ScripturePane');
    ProposedChanges = api.getModule('ProposedChanges');
    CommentBox = api.getModule('CommentBox');
    TranslationHelps = api.getModule('TranslationHelps');
```
- [x] Implement redux for the PopoverApi. (Manny)
- [x] Refactor doneLoading (Jay)
- [x] Refactor setToolNamespace (Jay)
- [x] Refactor loaderModal (Jay)
- [x] Refactor alertModal (Jay)
- [x] Refactor api.saveModule and api.getModule w/ redux (Manny)
- [x] Refactor ModuleWrapperContainer (Manny)
- [x] Refactor SideBarContainer (Manny)
- [x] Removed all **Event Listeners** and **Event Emiters**
- [x] Refactor CheckStoreActions functions out of app.js (This actions can be part of project load actions) (Jay)
- [x] Change the way we require modules in order to import them using ES6 convention
- [x] Remove commentBoxStore and proposedChangesStore
- [x] Resources Implementation w/ Redux (Manny)
- [x] Refactor AccessProject, UploadMethods and CheckDataGrabber using redux (Jay)

**Comment by mannycolon** [comment]
@RoyalSix I added this few tasks and ideas how we can break things down. what do you think?
