### ISSUE TITLE
Roadmap for Private Beta Release

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#90]
As a user I want to know what features will be available when the Public Beta is available so that I can set my expectations.
## Priority Filter:

Due to the exhaustive list potentially not meeting timeline for public beta release, we need a filter to determine priorities.
1. Stability (of the core, reduce crashing, data loss)
2. Usability (ease support/training)
3. Extensibility (modular design)
4. Interoperability (tC, tM, other editors…)
5. Maintainability (reduce dev efforts for future)
6. Extendability (Adding new features, translate new resources)
# Features/Functions

**High Level Features/Functions:** Only Product Owner should check these off when it is accepted.
## App:
- [x] Build/Installer/Uninstaller for Windows 64 bit
- [ ] Build/Installer/Uninstaller for Windows 32 bit
- [x] Build/Installer for Mac
## Project:
- [x] Load tS Bible Translation Project
- [x] Save check data to view later
- [x] Close and save project
- [x] Resume where left off when restarting app
## Workflow:
- [x] Text Complete (book level)
- [x] Choose a project (book level)
- [x] Choose a check
- [x] Complete a check (book level)
- [ ] Apply a check (book level)
## Door43:
- [x] Login to D43 account
- [x] Sync with D43
- [x] Load remote D43 Bible Translation Project
- [x] View my D43 Bible Translation Projects
- [ ] View other user's D43 Bible Translation Projects
## Offline/Security:
- [x] Load projects completely offline
- [ ] Load check app completely offline
- [ ] Hand off work completely offline
- [ ] Ensure app does not use internet after first load
- [ ] Operate completely offline via sharing
## USFM:
- [ ] Load USFM Bible Translation Project
- [ ] Render/Display some USFM Markup
- [ ] Export USFM File
- [ ] Maintain USFM Markup in export
## Checks/Apps:
- [x] Choose Check to be performed
- [x] Check key terms from translationWords
- [ ] Check literary devices from translationNotes
- [ ] Review Suggested Changes
- [ ] Apply changes to translation project

Metadata to be saved:
- [ ] Username and/or alias
- [ ] Timestamp
- [ ] UUID
## Context Scripture Resource (Tri-pane):
- [x] Display Greek Source for NT
- [ ] Display Lexicon for Greek
- [ ] Display Hebrew/Aramaic for OT
- [ ] Display Lexicon for Hebrew/Aramaic
- [x] Display English Gateway Language (tied to check sources)
- [ ] Display non-English Gateway Language (dependent on check sources)
- [x] Display Target Language (including RTL languages)
## Components:
- [ ] Align/Highlight target translation of word/quote being checked
- [ ] Select Status of check
- [x] Propose change of aligned/highlighted target translation
- [x] Notes section for each check
- [ ] Display linked resource article for each check
- [ ] JIT Resources with links to be parsed and function*
- [ ] Bookmarks to serve as a reference point other than flagging something for review
## Usability:
- [x] Navigation Menu for Checks
- [ ] View Overall Progress
- [ ] Easily understand UI with minimal training
- [ ] Training manual
## Testing:
- [ ] QA Script of happy path for manual user UI testing
- [ ] QA automated tools for scripted UI testing
- [ ] Automated tests created
- [ ] Travis CI generating builds

**Comment by ChrisJarka** [comment]
Something to consider to add to this impressive list:
Under Project:
Maybe it is meant by: "Save check data to view later" that there will be the ability for each user to enter personal bookmarks and to be able to view other users' bookmarks. 
If not, that would be a nice thing for me as an end user. That I would be able to mark something that I might want to come back and look at again.
Maybe it would be a history of the user that can be accessed by the end-user?

**Comment by klappy** [comment]
@ChrisJarka: Added "Bookmarks to serve as a reference point other than flagging something for review" under Components.

**Comment by pjoakes** [comment]
Under usability: 
The 3 options to be selected for Notes checks aren't completely clear. They originated for figures of speech, but have been applied to other things now, so I think need to be adjusted. 
The first button ("retain") now means that the target closely reproduces the source. I propose: "same." If allowed, there could be a parenthetical explanation under that, "(matches source)." 
The second button ("changed") is a little confusing, because the implication is that if something has been changed from the source, it is wrong, which is the third button. But it means that something has been changed on purpose for the sake of comprehension. For example, passive may have been changed to active because the target lang. doesn't have passives. So I propose a parenthetical underneath that says, "(for clarity)" or have the button say "adjusted" (or both), which implies a positive change on purpose. 
The parenthetical under the third button ("wrong") could be "(should replace)," and then the replacement is given in the field provided.
