### ISSUE TITLE
Scripture Pane updates - All verses across translations should line up

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#930]
For the Scripture Pane modal popup...
- [ ] Each verse should have the same number of lines across all translations (e.g. all verse 1's are 3 lines long, all verse 2's are 4 lines long, etc.)
- [ ] All translations should scroll together

**Comment by klappy** [comment]
# Overview
Render Scripture Pane modal by rows instead of columns.
- Bible Heading component for unique bible
- Bible Heading Row component (renders all Bible Headings)
- Verse component for unique bible/verse combo
- Verse Row component for unique verse (renders multiple Verses)
- Chapter component (renders Bible Heading Row and all Verse Rows)

**Comment by klappy** [comment]
# Tasks

## Create
- [ ] [3] Create components
  - [ ] Bible Heading component for unique bible
  - [ ] Bible Heading Row component (renders all Bible Headings)
  - [ ] Verse component for unique bible/verse combo
  - [ ] Verse Row component for unique verse (renders multiple Verses)
  - [ ] Chapter component or container (renders Bible Heading Row and all Verse Rows)
## Style
- [ ] [2] Copy style of previous components to match design
## Tests
- [ ] Decide if we can test this since it is in a tool and not the root application.
- [ ] [2] Write test to ensure container renders properly
