### ISSUE TITLE
1. User: Login with Door43

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#964]
- [ ] The first screen will contain two options
  - [ ] Option 1: Login with Door43 (covered in this issue)
  - [ ] Option 2: Create Door43 Account (full functionality is covered in #965 )
    - [ ] For the Beta, a modal pop-up shows up when the button for this is clicked. See mockup. When clicked, the hyperlink should open up the user's web browser.
- [ ] The "Log In" button is inactive until a username and password have been entered then it becomes active
  - [ ] The first time they log in, Door43.org is pinged
  - [ ] The user remains logged in, even if they close tC and reopen.
- [ ] An info (i) next to Door43 displays a pop-up showing the content in the mockup

**Comment by Thajny** [comment]
![door43 info](https://cloud.githubusercontent.com/assets/21183377/24412530/50220714-139e-11e7-8734-dba8c37cf7f7.png)
![log in 2](https://cloud.githubusercontent.com/assets/21183377/24412548/5e62d2ae-139e-11e7-9e97-31aebf02a2cf.png)
![log in](https://cloud.githubusercontent.com/assets/21183377/24412547/5e5e88e8-139e-11e7-8b9a-9560cb069266.png)

**Comment by Thajny** [comment]
![profile 1](https://cloud.githubusercontent.com/assets/21183377/24562428/688d40ce-1610-11e7-949f-78fcefdee502.png)
![profile 1 4](https://cloud.githubusercontent.com/assets/21183377/24562431/68933862-1610-11e7-9b2c-db8d9e8a2105.png)
![profile 1](https://cloud.githubusercontent.com/assets/21183377/24562432/6893befe-1610-11e7-8f64-6ee6b011c562.png)
![profile-1](https://cloud.githubusercontent.com/assets/21183377/24562430/689185a8-1610-11e7-8948-ae6497aa9924.png)
![profile](https://cloud.githubusercontent.com/assets/21183377/24562429/688f0580-1610-11e7-8647-44955cc10cd1.png)

**Comment by Thajny** [comment]
![profile 1](https://cloud.githubusercontent.com/assets/21183377/24711760/7e76c1ba-19e6-11e7-82db-52bba943fdf6.png)
![profile 1 4](https://cloud.githubusercontent.com/assets/21183377/24711761/7e7866fa-19e6-11e7-9a29-d1d2cb8bb4bc.png)
![profile](https://cloud.githubusercontent.com/assets/21183377/24711762/7e79e3d6-19e6-11e7-9716-3b893e181bf4.png)
![profile 1](https://cloud.githubusercontent.com/assets/21183377/24711763/7e79e84a-19e6-11e7-916f-afce96f2bc30.png)

**Comment by mannycolon** [comment]
http://www.material-ui.com/#/components/auto-complete

**Comment by klappy** [comment]
- [ ] Use a pop-over from react bootstrap for information popup

**Comment by mannycolon** [comment]
http://www.material-ui.com/#/components/text-field

**Comment by Thajny** [comment]
![log in](https://cloud.githubusercontent.com/assets/21183377/25150150/8b8b1cf6-2446-11e7-8bfa-4e7c1b364e1d.png)
![profile - log in](https://cloud.githubusercontent.com/assets/21183377/25150151/8b8c24ca-2446-11e7-9b62-87c302ce1416.png)
![profile](https://cloud.githubusercontent.com/assets/21183377/25150154/8b8f8570-2446-11e7-816f-8b6b30b0ff8f.png)
![profile_popup](https://cloud.githubusercontent.com/assets/21183377/25150153/8b8c3082-2446-11e7-860f-208a3c938f0c.png)
![profile_incorrect](https://cloud.githubusercontent.com/assets/21183377/25150152/8b8c1804-2446-11e7-9ef7-68bba8bf294c.png)

**Comment by Thajny** [comment]
![create d43 modal](https://cloud.githubusercontent.com/assets/21183377/25150546/f9b82290-2447-11e7-9e81-87e6c1ad3346.png)

**Comment by Thajny** [comment]
There is no "Continue Offline" button as suggested on the instructions card.

![log in done](https://cloud.githubusercontent.com/assets/21183377/25457388/b91e8f80-2a9b-11e7-8343-fbe3e21773e4.png)
![log in 2](https://cloud.githubusercontent.com/assets/21183377/25457389/b91fab90-2a9b-11e7-803e-c6065224abd9.png)
![log in incorrect](https://cloud.githubusercontent.com/assets/21183377/25457390/b92008b0-2a9b-11e7-8842-bda3219323de.png)
![profile_popup](https://cloud.githubusercontent.com/assets/21183377/25457398/bf8fc6d6-2a9b-11e7-92c7-ab9829a1204c.png)
![log in](https://cloud.githubusercontent.com/assets/21183377/25457418/d6eb7654-2a9b-11e7-85fe-324f19a15333.png)

**Comment by cckozie** [comment]
1. The log in button is active when the screen is first displayed. It should not be active until both a username and password are entered
2. The wrong email address is displayed for the user after logging in. (I created the account using a gmail address and what is displayed is for the user @noreplay.door43.org)
3. The Next button should be disabled until user logs in

**Comment by benjore** [comment]
Change "Go Home" to "Go Back". It should take the user back one screen.

**Comment by mannycolon** [comment]
working on `QA fail`

**Comment by mannycolon** [comment]
1. Done
2. The gogs API doesn't return the correct email account. Therefore, decided to removed email label.
3. Will be addressed by another story.

**Comment by cckozie** [comment]
1. OK
2. OK
3. The Next button is not disabled. This will be dealt with in issue #2027
