### ISSUE TITLE
1. User: User Page - signed in

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#968]
- [ ] How to access
  - [ ] When a user has logged in and is in the "Project" or "Tool" or "Home Screen" and clicks on the "User" in the stepper, they are brought to this screen. 
  - [ ] When a user has loaded a tool and is checking, by clicking "User" in the top menu, they are brought to this screen.
- [ ] Actions
  - [ ] "Continue to Projects" will bring the user to "Project"
  - [ ] "Log Out" will log out the user and bring them to the "Log In" screen

**Comment by Thajny** [comment]
![user logged in](https://cloud.githubusercontent.com/assets/21183377/24563047/bd414a14-1612-11e7-9dd4-bc6add9446e2.png)
![offline logged in](https://cloud.githubusercontent.com/assets/21183377/24563060/c3d25274-1612-11e7-80cd-6fba460692d2.png)

**Comment by Thajny** [comment]
![user logged in](https://cloud.githubusercontent.com/assets/21183377/25457466/0d2fb45a-2a9c-11e7-92d9-31f057a51187.png)

**Comment by benjore** [comment]
- [ ] Add "Log in with Door43"

**Comment by Thajny** [comment]
Seems weird that we're instructing the user to log in with a Door43 account on this screen. 
The instruction suggest that the user can create a Door43 account, but there is no link to do so.
The instructions refer to selecting "Continue Offline", but the text on the button is different.

![user logged in 1](https://user-images.githubusercontent.com/21183377/27201799-a08d7dd0-51e4-11e7-98f0-931d2101515d.png)

**Comment by klappy** [comment]
## Tasks - User Page - Signed In
- [1] UserManagementContainer Layout and display as Card
- [2] UserLoggedIn component with ProjectButton and LogoutButton
- [2] ProjectButton to change home screen mode to ProjectsManagement
- [1] LogoutButton to log user out, use existing actions

**Comment by cckozie** [comment]
Typo on instruction card.
![image](https://user-images.githubusercontent.com/8171759/27592822-0e52320e-5b1b-11e7-976b-3a7788e461af.png)

**Comment by cckozie** [comment]
@benjore Where should the "Go Back" button take the user?

**Comment by benjore** [comment]
Change Instructions to say: 

You are currently logged in. 

To continue to Projects, click "Continue to Project". 

To log out, click "Log out".

**Comment by cckozie** [comment]
@benjore It also seems like we should add some verbiage to the user card. Maybe something like "You are logged in as" at the top. Otherwise it seems like the user would be confused by this screen.

**Comment by benjore** [comment]
Good point, Koz. Let's make the verbiage on the main card be: 

You are logged in as: 
[username]
How would you like to proceed?

**Comment by benjore** [comment]
"Go Back" should act like a web browser "Go Back" button that takes you to the last page/screen visited.

**Comment by mannycolon** [comment]
working on `QA fail`

**Comment by cckozie** [comment]
Looks good in beta.54 on Mac
