### ISSUE TITLE
2. Project: Main Page

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#969]
- [ ] Toast - saying that the user is successfully logged in (see mockup)
- [ ] Overview
  - [ ] This screen displays a list of cards, all imported projects appear here
- [ ] Project Cards
  - [ ] Each imported project shows up as its own card
  - [ ] If "Select" is clicked, go to "Tools" screen 
  - [ ] Add a spacer/gutter after the last project so that when scrolled all the way to the bottom, the hamburger does not cover the last project card. 
  - [ ] Each project has a 3-dot menu
    - [ ] *Edit Project Details ( #972 )
    - [ ] Export to CSV ( #973 )
    - [ ] Upload to Door43 ( #974 )
    - [ ] *Archive Project ( #975 )
- [ ] Hamburger
  - [ ] *Import Local Project ( #970 )
  - [ ] Import Online Project ( #971 )
  - [ ] *Restore Archived Project (this is the reverse action of #975 ) ( #978 )

Future capability (not required for Beta)
  - [ ] *Sort
    - [ ] *ascending/descending
    - [ ] *category

**Comment by Thajny** [comment]
![project - overflow 1](https://cloud.githubusercontent.com/assets/21183377/24414435/063057d6-13a4-11e7-8221-ae239523fc38.png)
![project overflow](https://cloud.githubusercontent.com/assets/21183377/24414437/0636fe56-13a4-11e7-9eb2-baf746e7aa69.png)
![project - cards](https://cloud.githubusercontent.com/assets/21183377/24414438/06385fd0-13a4-11e7-9165-5bc9496ad1a4.png)
![project - dropdown](https://cloud.githubusercontent.com/assets/21183377/24414440/063caffe-13a4-11e7-96b2-c26a61250547.png)
![project import](https://cloud.githubusercontent.com/assets/21183377/24414439/063be286-13a4-11e7-8d16-86eb52e554eb.png)
![project_fab](https://cloud.githubusercontent.com/assets/21183377/24414436/0635e7c8-13a4-11e7-9d96-4e5dd6a1dac8.png)
![project-1](https://cloud.githubusercontent.com/assets/21183377/24414441/063f2b8a-13a4-11e7-89d8-1f842493ceef.png)
![project](https://cloud.githubusercontent.com/assets/21183377/24414442/0644c00e-13a4-11e7-8811-1716bacc7304.png)

**Comment by Thajny** [comment]
Some notes:

The toast that appears (you are logged in as....) should go away automatically after a second or two, whatever feels right.

**Comment by Thajny** [comment]
![project - overflow 1](https://cloud.githubusercontent.com/assets/21183377/24428711/f041d93c-13d4-11e7-96ba-bb6ecdf73621.png)
![project overflow](https://cloud.githubusercontent.com/assets/21183377/24428712/f0456d90-13d4-11e7-9197-140e43e39e30.png)
![project-1](https://cloud.githubusercontent.com/assets/21183377/24428713/f047ace0-13d4-11e7-972c-23c0d169004a.png)
![project-2](https://cloud.githubusercontent.com/assets/21183377/24428714/f0490856-13d4-11e7-951a-b911de916af1.png)
![project-3](https://cloud.githubusercontent.com/assets/21183377/24428716/f0499eec-13d4-11e7-9228-4090f58f5a19.png)
![project-4](https://cloud.githubusercontent.com/assets/21183377/24428715/f0493524-13d4-11e7-86b3-422abc1492d8.png)
![project-5](https://cloud.githubusercontent.com/assets/21183377/24428718/f0562b94-13d4-11e7-998a-643f9460c603.png)
![project](https://cloud.githubusercontent.com/assets/21183377/24428717/f053b292-13d4-11e7-8303-56eee78c0e69.png)

**Comment by Thajny** [comment]
![edit details 1](https://cloud.githubusercontent.com/assets/21183377/24563247/577ce552-1613-11e7-8ef7-8cf9c9990a81.png)
![import online 1](https://cloud.githubusercontent.com/assets/21183377/24563249/577fdd48-1613-11e7-81fa-b872f794a587.png)
![import online](https://cloud.githubusercontent.com/assets/21183377/24563248/577e7552-1613-11e7-81b4-12aa8c0e9fae.png)
![project - overflow 1](https://cloud.githubusercontent.com/assets/21183377/24563252/5785fc78-1613-11e7-8a3e-8b3e1f6667bb.png)
![project overflow](https://cloud.githubusercontent.com/assets/21183377/24563250/57809a44-1613-11e7-8d53-dc70de64a430.png)
![project context menu](https://cloud.githubusercontent.com/assets/21183377/24563251/5781a6c8-1613-11e7-95d4-61d54df25aae.png)
![project fab](https://cloud.githubusercontent.com/assets/21183377/24563253/578b7bc6-1613-11e7-9098-48a60116ced4.png)
![project import](https://cloud.githubusercontent.com/assets/21183377/24563254/578e0760-1613-11e7-9e85-12dc841e5a02.png)
![project license 1](https://cloud.githubusercontent.com/assets/21183377/24563255/57935cf6-1613-11e7-9441-863315c2404c.png)
![project license](https://cloud.githubusercontent.com/assets/21183377/24563257/5795d724-1613-11e7-99da-54b6b49f1028.png)
![project restore](https://cloud.githubusercontent.com/assets/21183377/24563258/57966d4c-1613-11e7-9b76-999506892fe6.png)
![project sort](https://cloud.githubusercontent.com/assets/21183377/24563256/57950fba-1613-11e7-80b3-3e8a374d4dc8.png)
![project-1](https://cloud.githubusercontent.com/assets/21183377/24563259/579c4dde-1613-11e7-8fcc-2b718f989724.png)
![project-2](https://cloud.githubusercontent.com/assets/21183377/24563260/579d2ace-1613-11e7-84cd-df541d6c70c7.png)
![project-remove](https://cloud.githubusercontent.com/assets/21183377/24563261/579f8cec-1613-11e7-9c41-f6c1bfcfda18.png)
![project](https://cloud.githubusercontent.com/assets/21183377/24563262/57a1b1c0-1613-11e7-9ecf-e0205a4affba.png)

**Comment by Thajny** [comment]
![project _upload successful](https://cloud.githubusercontent.com/assets/21183377/25150361/4588e5d4-2447-11e7-88af-136586ab5c81.png)
![project context menu](https://cloud.githubusercontent.com/assets/21183377/25150366/45978616-2447-11e7-8821-2e7a1f34d30d.png)
![project fab](https://cloud.githubusercontent.com/assets/21183377/25150363/45936eaa-2447-11e7-84a6-7266e42b09a1.png)
![project sort order](https://cloud.githubusercontent.com/assets/21183377/25150362/45915c6e-2447-11e7-8fb6-cc8b372c535a.png)
![project sort kind](https://cloud.githubusercontent.com/assets/21183377/25150364/45943240-2447-11e7-97a5-54f6f0b248a5.png)
![project_toast](https://cloud.githubusercontent.com/assets/21183377/25150365/45959aea-2447-11e7-9e3b-3e74eb20ab7d.png)
![project_empty](https://cloud.githubusercontent.com/assets/21183377/25150367/45997a98-2447-11e7-9bf9-8e234b0cfc43.png)
![project_loaded](https://cloud.githubusercontent.com/assets/21183377/25150368/45a16ec4-2447-11e7-8f00-b5fc23aa1de6.png)
![project upload modal](https://cloud.githubusercontent.com/assets/21183377/25150369/45a1aa56-2447-11e7-8838-7268787cc63c.png)

**Comment by Thajny** [comment]
![project _upload successful](https://cloud.githubusercontent.com/assets/21183377/25457566/63c86258-2a9c-11e7-999e-f7eba1c3f508.png)
![project context menu](https://cloud.githubusercontent.com/assets/21183377/25457568/63cd178a-2a9c-11e7-8f34-4fc316a38d70.png)
![project_empty](https://cloud.githubusercontent.com/assets/21183377/25457567/63cc822a-2a9c-11e7-9a96-d689900fc8b8.png)
![project_loaded 1](https://cloud.githubusercontent.com/assets/21183377/25457570/63ceac80-2a9c-11e7-9a4b-66a288b949bd.png)
![project_loaded](https://cloud.githubusercontent.com/assets/21183377/25457571/63cfca16-2a9c-11e7-977d-fa59869138d0.png)
![project_loadingscreen](https://cloud.githubusercontent.com/assets/21183377/25457569/63cde372-2a9c-11e7-8044-a01d98464aeb.png)
![project_toast](https://cloud.githubusercontent.com/assets/21183377/25457572/63d3e858-2a9c-11e7-8761-b2bf436c5ab8.png)
![project_upload progress](https://cloud.githubusercontent.com/assets/21183377/25457573/63d83e8a-2a9c-11e7-8dad-c45c48795847.png)

**Comment by Thajny** [comment]
Suggest changing "latest edition" to "version 11 or greater"
Should there be some instruction text referring to the 3-dot "menu"
Suggest that we do not implement the "toasts" (you are logged in as, successfully uploaded, etc). Instead continue with the processing and success dialogs as in 0.7.0
Do we want to change the current import metaphor to separate out from URL?

![project _upload successful](https://user-images.githubusercontent.com/21183377/27201444-5426a6a2-51e3-11e7-82a9-499b2a3a3014.png)
![project context menu](https://user-images.githubusercontent.com/21183377/27201447-542ca390-51e3-11e7-8139-eb5268d32921.png)
![project_loaded](https://user-images.githubusercontent.com/21183377/27201446-542bee1e-51e3-11e7-94e3-a03e062a913a.png)
![project_toast](https://user-images.githubusercontent.com/21183377/27201445-5428b15e-51e3-11e7-9788-7cc16b6ffc79.png)
![project fab](https://user-images.githubusercontent.com/21183377/27201448-564390ee-51e3-11e7-831b-a39d05381e6b.png)

**Comment by klappy** [comment]
## Tasks: 
[3] Populate ProjectManagementContainer
[2] Project Management Instructions
[4] Project Management ProjectCard UI Design
[2] Project Management ProjectCard Functionality
[4] Project Management FAB
[2] Project Management FAB lighten rest of screen

**Comment by benjore** [comment]
Modification in the Instructions: 

[import project instructions...]

To upload or export a project click [three-dot menu icon]

Only projects that have been saved with version 11 or greater in translationStudio can be opened...

**Comment by cckozie** [comment]
See Ben's last comment above regarding the instruction card:
1. '(=)' is displayed on the instructions card rather that the FAB image
2. Add the text for upload/export
3. Change the text referring to tS projects
4. The "c" should be capitalized on the FAB's close "button"
![image](https://user-images.githubusercontent.com/8171759/28218503-5d0c3a8c-687e-11e7-9bad-ed6284017c6c.png)

**Comment by klappy** [comment]
@cckozie: Creating tasks for addressing QA Failed issues.
1. Will address.
2. Upload/Export makes no sense as we don't know what to export. That functionality is added on each Project Card individually. Needs decision on what to do with that button if it was created.
3. Will address.
4. Will address.

**Comment by cckozie** [comment]
@klappy 2. The comment doesn't relate to the FAB , but to the 3 dot menu. See Ben's comment from 20 days ago. "To upload or export a project click [three-dot menu icon]"

**Comment by cckozie** [comment]
@benjore 
1. Do you want the dashed line circle around the 3 dots on the instruction card?
2. Now that we support USFM import do we want to redo the text referring to tS version 11? I think it sounds like we only support tS projects.

**Comment by benjore** [comment]
1. No dashed line circle 
2. "USFM projects and translationStudio projects (saved in version 11 or greater) are supported."

**Comment by cckozie** [comment]
From the July 11 comment:
1. Fixed
2. Text added, but dashed circle on 3-dot should be removed. (See Ben's comment 1. above)
3. Updated, but again out of date. (See Ben's comment 2. above for correct verbiage)
4. Fixed

**Comment by klappy** [comment]
## Tasks 
[2] Project Instructions: Update text and remove dashed circle around 3-dot menu
