### ISSUE TITLE
2. Project: Import Local Project

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#970]
- [ ] Order
  - [ ] [user clicks "Import Local Project" > Select file from system > (c) status > import project
  - [ ] If "None of the above" is checked, the user is immediately taken to the "I'm Sorry" modal. The project is not imported. 
- [ ] .tstudio files should be importable
  - [ ] unzip

# Notes
- For Beta, we will only be supporting open-licensed projects (Public Domain, CC0 [zero, not "o"], CC BY, and CC BY-SA)

**Comment by Thajny** [comment]
![project import](https://cloud.githubusercontent.com/assets/21183377/24415948/b72eff7a-13a8-11e7-844d-196cb51a8ff3.png)

**Comment by Thajny** [comment]
![project import](https://cloud.githubusercontent.com/assets/21183377/24563370/a8863de0-1613-11e7-90d5-38abe502c5af.png)
![project license](https://cloud.githubusercontent.com/assets/21183377/24563371/a88a731a-1613-11e7-92e4-51b2040f1ec6.png)

**Comment by Thajny** [comment]
![local_import_copyrighted](https://cloud.githubusercontent.com/assets/21183377/24665493/2ca29486-1923-11e7-8f39-d66e27d570b4.png)
![loacal_import_cc2](https://cloud.githubusercontent.com/assets/21183377/24665498/307afbac-1923-11e7-97d4-12f3326107ae.png)
![project import](https://cloud.githubusercontent.com/assets/21183377/24665519/3e49a8dc-1923-11e7-9ad3-a268f8bd8c6b.png)
![local_import_cc1](https://cloud.githubusercontent.com/assets/21183377/24665520/3e4b9ef8-1923-11e7-8944-158ce74e2144.png)

**Comment by Thajny** [comment]
![loacal_import_cc2](https://cloud.githubusercontent.com/assets/21183377/24668044/18bdb7fe-192b-11e7-936c-2657a14a7581.png)
![local_import_cc1](https://cloud.githubusercontent.com/assets/21183377/24668046/18bfaa1e-192b-11e7-8252-c2377b0b06a9.png)
![project import](https://cloud.githubusercontent.com/assets/21183377/24668045/18bf4bf0-192b-11e7-9415-8266275613b2.png)

**Comment by Thajny** [comment]
![local_import_copyrighted](https://cloud.githubusercontent.com/assets/21183377/24668056/272f417c-192b-11e7-95cd-212e5ba612f9.png)

**Comment by Thajny** [comment]
![local_import_copyrighted](https://cloud.githubusercontent.com/assets/21183377/24878252/08db61d4-1df8-11e7-8ed8-2eafb7ff76c9.png)

**Comment by Thajny** [comment]
![new-terms 2](https://cloud.githubusercontent.com/assets/21183377/24878333/51850e80-1df8-11e7-9e3d-29e8f691fe98.png)
![new-terms](https://cloud.githubusercontent.com/assets/21183377/24878334/5185ea12-1df8-11e7-8486-61914662744a.png)

**Comment by Thajny** [comment]
![local_import_cc1 1](https://user-images.githubusercontent.com/21183377/27200255-bd352556-51de-11e7-8360-0e9d4f47229a.png)
![local_import_cc1 2](https://user-images.githubusercontent.com/21183377/27200258-bd3a0c74-51de-11e7-831a-24d5e70f22d6.png)
![local_import_cc1](https://user-images.githubusercontent.com/21183377/27200257-bd397926-51de-11e7-8aa8-8315ec5315a5.png)
![project fab](https://user-images.githubusercontent.com/21183377/27200256-bd37a5b0-51de-11e7-9cb6-aaf93f9d78bb.png)
![project import](https://user-images.githubusercontent.com/21183377/27200259-bd477a80-51de-11e7-8b37-3580b1f6c480.png)

**Comment by benjore** [comment]
- [ ] The selection of the copyright status is covered in the Import Project Check ( https://xd.adobe.com/view/6509deb3-015c-4926-829d-dcefea2a0624/ )
- [ ] Remove the "Import from URL" option

**Comment by mannycolon** [comment]
@benjore the comment above looks like `import from d43` and this story is `import local`

**Comment by mannycolon** [comment]
is this right?

**Comment by mannycolon** [comment]
# Tasks

- [3] Create an action to open a file/browse dialog to access local project.
     - Link action to selectProject("Path to local project") in projectSelectionActions.js
- [2] Create an action to unzip .tstudio files to tC compatible.
- [1] Create/include modal alerts to let user know when a non-tC compatible file is being loaded.

**Comment by cckozie** [comment]
@benjore Currently when importing a local project the user is not allowed to see or navigate into hidden folders even if he has configured his computer to allow that (only tested on Mac at this time). It seems to me that we should allow that if the system is configured that way. Your thoughts?

**Comment by benjore** [comment]
My preference would be that the app follow the system settings. If this is not copious amounts more work, then let's do that. @cckozie

**Comment by klappy** [comment]
Is there a use case where these hidden files/folders will contain the desired import files?

**Comment by cckozie** [comment]
@klappy Who knows? Tech Advance may do many seemingly strange things when setting up computers. Why would we preclude the user from seeing those files if the system was so configured?

**Comment by mannycolon** [comment]
@benjore @klappy @cckozie I don't think this story should be failed. another story should be created instead for hidden files. 

hidden files were never part of the story and we never had that functionality.

**Comment by cckozie** [comment]
Your call @benjore 
For future reference, I would expect the app to take such settings into account without them being expressly stated in the issue.

**Comment by benjore** [comment]
@cckozie I'm fine with a new issue. Can you set that up?

**Comment by cckozie** [comment]
New issue is #2138

**Comment by klappy** [comment]
I have to respectfully push back on this one. For two reasons. 1) Not that it's my place to question, but I still haven't heard a use case for finding projects in a hidden folder. 2) I have tried 4 other Mac applications and none of them respect my OS settings to show hidden files/folders.
