### ISSUE TITLE
2. Project: Import Online Project

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#971]
- [ ] Workflow
  - [ ] [user clicks "Import Online Project"] > Modal with Search Bars > List of projects > Selected project is imported > User is returned to "Project"
- [ ] Features
  - [ ] Two search boxes, one for the repo/username, one for the language/book of the bible

# Notes
- No (c) control is needed as that has already been taken care of when it was uploaded to Door43.

**Comment by Thajny** [comment]
![import online 1](https://cloud.githubusercontent.com/assets/21183377/24563392/bd1ebff2-1613-11e7-8b04-3d965454b479.png)
![import online](https://cloud.githubusercontent.com/assets/21183377/24563391/bd1dc3fe-1613-11e7-82a9-75e65d300706.png)

**Comment by Thajny** [comment]
![import online 1](https://cloud.githubusercontent.com/assets/21183377/24666594/68802740-1926-11e7-834b-d792afa01ee6.png)
![import online 2](https://cloud.githubusercontent.com/assets/21183377/24666595/688042de-1926-11e7-9a47-9deaf6ae2374.png)
![import online](https://cloud.githubusercontent.com/assets/21183377/24666596/68829052-1926-11e7-99a9-ab7de7db1dd6.png)

**Comment by Thajny** [comment]
![import online 1](https://cloud.githubusercontent.com/assets/21183377/24725615/342bc270-1a15-11e7-82df-f498da735338.png)

**Comment by benjore** [comment]
- [ ] Project/Repo Name + Username is necessary to display in the search results. 
- [ ] Search on username first, filter on book/language

# Note 
-book/language is actually just searching in project names

**Comment by Thajny** [comment]
![import online final](https://cloud.githubusercontent.com/assets/21183377/25150446/89f2ff16-2447-11e7-897c-8124d1f273eb.png)
![import online modal](https://cloud.githubusercontent.com/assets/21183377/25150447/89f58678-2447-11e7-8f0f-705c33d74f5b.png)
![import online search](https://cloud.githubusercontent.com/assets/21183377/25150448/89f73e50-2447-11e7-9bcd-cf1861cc2651.png)

**Comment by benjore** [comment]
- [ ] Only allow one import at a time
- [ ] Allow URL project import
- [ ] Prepopulate the user's username in the search box by default

**Comment by Thajny** [comment]
![import online modal](https://user-images.githubusercontent.com/21183377/27199417-7b4a164a-51db-11e7-885b-867fbbb576cd.png)
![import online search 2](https://user-images.githubusercontent.com/21183377/27199419-7b501950-51db-11e7-8bef-f5a76c3239dc.png)
![project fab](https://user-images.githubusercontent.com/21183377/27199416-7b489bb2-51db-11e7-91d3-6115cbe7a267.png)
![project_loadingscreen](https://user-images.githubusercontent.com/21183377/27199418-7b4c30b0-51db-11e7-94e5-4e5bbf7c596c.png)

**Comment by mannycolon** [comment]
# Tasks

- [5] Design `Import from Door43` modal.
    - Design modal.
    - Design project list component to display projects details. 
- [3] SPIKE: Research backend implementation for searching & Importing Online Projects.
- [5] Implement backend for searching & Importing Online Projects.

**Comment by cckozie** [comment]
1. Previous search results are displayed if the current user does not have any projects on Door43.
To replicate:
- Log in with a username that has no projects and go to import online projects. A message is displayed correctly indicating that no projects were found.
- Enter a username who has some projects. Import one of the projects or just cancel.
- Go back to import online projects. You'll see that the username is now correctly switched to the logged in user, but the previous result set it displayed.
- The same thing happens if you have a result set and then change the username in the search to one who has no projects.

2. If the using the Internet warning is displayed after clicking the Import button, the "Importing..." message is not displayed after dismissing the warning.

3. If the import fails because the project already exists, when I go back to import online projects the previously selected project is still selected.

**Comment by mannycolon** [comment]
@cckozie could you please give me the usernames you used for number 1.

**Comment by mannycolon** [comment]
# Tasks
- [2] Fix previous users projects showing for another user with no projects in door43.
- [3]  Fix missing `Importing` modal.
- [2] Fix Checkbox bug with selected project when importing an existing project.

**Comment by cckozie** [comment]
@mannycolon I used local user tt and door43 user tc01.

**Comment by mannycolon** [comment]
@cckozie thanks

**Comment by cckozie** [comment]
@mannycolon Item #2 above is no longer a problem in beta.42

**Comment by cckozie** [comment]
It looks like the items above about the project list being displayed  has been fixed, but the app now hangs when importing https://git.door43.org/tc03/bhd_tit_text_reg
(Actually, it looks like it fails to import any project)
![image](https://user-images.githubusercontent.com/8171759/29319152-956d6350-8198-11e7-9c15-8c21deef12d5.png)
