### ISSUE TITLE
2. Project: Upload to Door43

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#974]
- [ ] If someone is signed in to Door43...
  - [ ] Their username will appear in black bold letters (e.g. Busifish456)
  - [ ] The hyperlink will be "https://git.door43.org/[username]"

**Comment by Thajny** [comment]
![project license 1](https://cloud.githubusercontent.com/assets/21183377/24563507/272b0d10-1614-11e7-9a45-a30b460052aa.png)

**Comment by Thajny** [comment]
![project upload](https://cloud.githubusercontent.com/assets/21183377/24670012/1aba5a88-1932-11e7-957d-98a5b33513eb.png)

**Comment by Thajny** [comment]
![project upload modal](https://cloud.githubusercontent.com/assets/21183377/25150474/a1f5d606-2447-11e7-8dce-f9fc2c386d00.png)

**Comment by Thajny** [comment]
![project_upload progress](https://cloud.githubusercontent.com/assets/21183377/25457847/4bf8a2fe-2a9d-11e7-9cc6-76fd48aaba1b.png)

**Comment by benjore** [comment]
- [ ] Change verbiage to "Your project was uploaded successfully to [URL]." Add close button.

**Comment by Thajny** [comment]
![project upload modal](https://user-images.githubusercontent.com/21183377/27199200-c6c4f9ec-51da-11e7-9859-348512c57f9c.png)

**Comment by klappy** [comment]
[2] Upload to D43: Success Dialog to include link and username.
  - Use existing alert already used.
  - Use description over image uploaded.
  - Use tC logo for now.

**Comment by cckozie** [comment]
beta.54
The upload works properly but there are some problems with the success dialog.
1. When hovering over the url, the cursor should be a hand cursor.
2. There should be a space between the colon in the message text and the url.
3. When the link is clicked it does not link to the url (see console log below)
![image](https://user-images.githubusercontent.com/8171759/28084553-8feca0e6-663e-11e7-96b1-89ad94db2815.png)

**Comment by klappy** [comment]
Issues 1 and 2 are addressed with upcoming PR #2184 
Issue 3 is more of a build issue, will look into separately.

**Comment by cckozie** [comment]
Issues 1 and 2 are fixed in build beta.39.
Issue 3 is not fixed in beta.39.
There is one more issue now; if the "You are about to use the Internet..." message is displayed, the upload alert is not displayed and the user has no indication anything is happening until the success message is displayed. I the user has chosen for the "You are about to use the Internet..." message to not be displayed, then it works properly.

**Comment by cckozie** [comment]
All 3 issues, as well as the one about the uploading alert not being displayed are all fixed in beta.42.
