### ISSUE TITLE
3. Tool: Main Page

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#976]
- [ ] Actions
  - [ ] "See More" expands the tool card to show the extended description
  - [ ] "Select" brings the user back to "Home"
- [ ] Progress bar
  - [ ] Displays for the progress that has been made in checking that project for both tools.

**Comment by Thajny** [comment]
![tool 11](https://cloud.githubusercontent.com/assets/21183377/24563589/8bb3ff26-1614-11e7-98fa-e6631ad51187.png)
![tool 13](https://cloud.githubusercontent.com/assets/21183377/24563592/8bb4ea1c-1614-11e7-8cfc-dd8e7e88b586.png)
![tool fab](https://cloud.githubusercontent.com/assets/21183377/24563590/8bb41812-1614-11e7-8ea6-0e3e2980e2a7.png)
![tool-1](https://cloud.githubusercontent.com/assets/21183377/24563593/8bcd48fa-1614-11e7-9df9-265b353566d3.png)
![tool](https://cloud.githubusercontent.com/assets/21183377/24563591/8bb424ec-1614-11e7-9d57-a649fb9d62c2.png)

**Comment by Thajny** [comment]
![tool_default 1](https://cloud.githubusercontent.com/assets/21183377/25457873/63035d2c-2a9d-11e7-82fb-a07af963c1fe.png)
![tool_default](https://cloud.githubusercontent.com/assets/21183377/25457876/63041640-2a9d-11e7-8abb-a5fb5b431b80.png)
![tool_scroll](https://cloud.githubusercontent.com/assets/21183377/25457875/6303fbf6-2a9d-11e7-9e5f-2c27fcc19f6b.png)
![tool_tn desc](https://cloud.githubusercontent.com/assets/21183377/25457874/6303be02-2a9d-11e7-8e85-49083ec5193d.png)
![tool_tw desc](https://cloud.githubusercontent.com/assets/21183377/25457877/63056ac2-2a9d-11e7-974c-4a7880aac3f7.png)

**Comment by Thajny** [comment]
![tool_default 1](https://user-images.githubusercontent.com/21183377/27196868-d39a121e-51d1-11e7-9c82-4fc0572ecc11.png)
![tool_scroll](https://user-images.githubusercontent.com/21183377/27196871-d39b4008-51d1-11e7-8780-ea9bce406255.png)
![tool_tw desc](https://user-images.githubusercontent.com/21183377/27196872-d39caf4c-51d1-11e7-9437-3f350ba79de2.png)
![tool_default](https://user-images.githubusercontent.com/21183377/27196870-d39ab21e-51d1-11e7-8a92-a0d7bee6f3da.png)
![tool_tn desc](https://user-images.githubusercontent.com/21183377/27196869-d39a6fa2-51d1-11e7-8be0-aff43edc3be8.png)

**Comment by benjore** [comment]
- [ ] Make the "Select" buttons say "Launch" - clicking it will launch tC (rather than take the user back to the Home Screen.
- [ ] Note: when a card is expanded, the "See More" should become "See Less" (mockups are inconsistent)

**Comment by mannycolon** [comment]
# Tasks

- [4] Design Tool Cards to look like the mockups.
- [3] Populate progress for all available tool cards.
- [1] Implement tool launching functionality for tool cards.

**Comment by mannycolon** [comment]
<img width="168" alt="translationnotes 2x" src="https://user-images.githubusercontent.com/17072300/27806774-954365fa-600a-11e7-8f11-27d456048bf1.png">
<img width="171" alt="translationwords 2x" src="https://user-images.githubusercontent.com/17072300/27806773-9541ad5a-600a-11e7-8254-8f2f1cb7461b.png">

**Comment by cckozie** [comment]
The instructions card should display the text "Select a tool from the list"

**Comment by mannycolon** [comment]
## Tasks

[1] Fix instructions message for Tool Selection Page.
