### ISSUE TITLE
0. Home Screen

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#989]
- [ ] Availability
  - [ ] The home screen is accessible at any time during the setup
  - [ ] Even when the tool is launched and the user is checking, the home screen is accessible through the menu. 
- [ ] The Home Screen shows the current status of User, Project, and Tool
- [ ] Workflow
  - [ ] When a user opens tC, he is brought to the Home Screen. 
    - [ ] The first time opening tC, the preferred workflow will be Home Screen > User Setup > Project Setup > Tool Setup > Home Screen > Launch the app. 
    - [ ] If the user has worked in tC and re-opens the app, he will be brought to the Home Screen. The last used User, Project, and Tool will persist. That way by clicking the Launch button, they will be able to return to the project, tool, and location where they left off. 
- [ ] Buttons/links
  - [ ] If no user has been logged in and "Log In" is clicked, the user is brought to the Sign-in screen
  - [ ] If a user has been logged in and "Log Out" is clicked, the user is brought to the Sign-in screen
  - [ ] If a user has logged in and no project has been selected, clicking "Project" will take the user to the projects screen.
  - [ ] If a project has been selected and the user clicks "Change Project", the user is brought to the projects screen
  - [ ] If a user has been logged in and a project has been selected but no tool has been selected, if the user clicks "Tool" they will be brought to the tools screen
  - [ ] If a tool has been selected and the user clicks "Change Tool", the user is brought to the tools screen
  - [ ] "Launch" is only active when User setup, Project setup, and Tool setup have been completed. "Launch" opens up the project in the tool allowing the user to start checking

# Notes
- [ ] The only way from the setup/stepper to the launched tool is by clicking the "Launch" button on the Home Screen. 
- [ ] If the "User" is changed, then the project and tool reset and must be selected before launching the tool and starting checking
  - [ ] Likewise, if the "Project" is changed, the tool is reset and must be selected before launching the tool

**Comment by Thajny** [comment]
![home-1](https://cloud.githubusercontent.com/assets/21183377/24563690/f67ccb1c-1614-11e7-86ce-8327baf4beab.png)
![home-2](https://cloud.githubusercontent.com/assets/21183377/24563691/f67e6f6c-1614-11e7-9318-2133442bcbd7.png)
![home-3](https://cloud.githubusercontent.com/assets/21183377/24563693/f6851d76-1614-11e7-8e5c-8bc85f01e9cd.png)
![home](https://cloud.githubusercontent.com/assets/21183377/24563692/f680b01a-1614-11e7-9cf3-4ac7ecc42ac5.png)

**Comment by Thajny** [comment]
![home _empty](https://cloud.githubusercontent.com/assets/21183377/25150096/61770d26-2446-11e7-8eec-c056a162da1c.png)
![home_project context](https://cloud.githubusercontent.com/assets/21183377/25150098/617ab0e8-2446-11e7-8316-63e1a7c5e92a.png)
![home_project](https://cloud.githubusercontent.com/assets/21183377/25150097/61790c52-2446-11e7-9641-ab84c515d4c2.png)
![home_signed in](https://cloud.githubusercontent.com/assets/21183377/25150099/618d4ed8-2446-11e7-84c8-dfe7a4a6aacc.png)
![home_tool launch](https://cloud.githubusercontent.com/assets/21183377/25150101/61906ba4-2446-11e7-9135-fd8d2f2bd7b2.png)
![home_tool progress](https://cloud.githubusercontent.com/assets/21183377/25150100/618f1f56-2446-11e7-9301-503831c68ae3.png)

**Comment by Thajny** [comment]
![home _empty](https://cloud.githubusercontent.com/assets/21183377/25457907/80a7e83e-2a9d-11e7-9630-179dfe9dc84f.png)
![home_project context](https://cloud.githubusercontent.com/assets/21183377/25457903/80a5a3da-2a9d-11e7-89a6-18291b5c9d43.png)
![home_project](https://cloud.githubusercontent.com/assets/21183377/25457905/80a6579e-2a9d-11e7-9e08-c973d713b11c.png)
![home_signed in](https://cloud.githubusercontent.com/assets/21183377/25457906/80a64dbc-2a9d-11e7-845a-f94ae6f78bf7.png)
![home_tool launch](https://cloud.githubusercontent.com/assets/21183377/25457904/80a628dc-2a9d-11e7-868e-6197b157d3d4.png)
![home_tool progress 50](https://cloud.githubusercontent.com/assets/21183377/25457902/80a3d960-2a9d-11e7-928d-4d7df1694c4a.png)
![home_tool progress](https://cloud.githubusercontent.com/assets/21183377/25457908/80b2e482-2a9d-11e7-9bb2-da3b174a03d3.png)

**Comment by Thajny** [comment]
![home _empty 1](https://user-images.githubusercontent.com/21183377/27194667-0ee4f6b2-51c9-11e7-8289-1ff5eb82fc08.png)
![home_project](https://user-images.githubusercontent.com/21183377/27194664-0ee2d21a-51c9-11e7-9c9e-79aa9b09f798.png)
![home_signed in](https://user-images.githubusercontent.com/21183377/27194665-0ee3e29a-51c9-11e7-8868-3f7369ed9abb.png)
![home_tool launch](https://user-images.githubusercontent.com/21183377/27194666-0ee46080-51c9-11e7-8ba1-4e481180cc1f.png)

**Comment by klappy** [comment]
# Tasks - Overview Container
- [4] DisplayContainer
  - [1] DisplayContainer Layout
  - [1] Conditional Switch to mode in DisplayContainer
  - [1] OverviewContainer Layout
  - [1] Version Number and Information Icon
- [8] Create/Style Components
  - [1] DefaultCard with enabled/disabled state for User/Project/Tool to use
  - [1] UserCard to display User Info and fallback to DefaultCard
  - [2] ProjectCard to display Project Info and fallback to DefaultCard
  - [2] ToolCard to display Tool Info and fallback to DefaultCard
  - [1] LaunchButton
  - [1] Instructions to display and render html passed as props
- [5] Functionality
  - [4] ToolCard Progress
  - [1] DefaultCard Button to take text and action from props

**Comment by cckozie** [comment]
The project name flows off of the project card. Suggest eliminating the path and also allowing the text to  wrap.
![image](https://user-images.githubusercontent.com/8171759/27591998-fae5539c-5b18-11e7-8dac-2936bd7110b2.png)

**Comment by benjore** [comment]
- [ ] only show the file name (e.g. fr_eph_text_ulb) and not the path
- [ ] Truncate the text if it runs off the card

**Comment by mannycolon** [comment]
working on `QA fail`

**Comment by klappy** [comment]
@mannycolon This is due to a string split that worked for mac but not windows, path.basename() is cross compatible. But maybe this should be moved to the reducer, that way we don't have to generate it everywhere.

**Comment by mannycolon** [comment]
did you address this in you reducer implementation??

**Comment by klappy** [comment]
I addressed it partially and didn't want to cause a merge conflict. We can update other occurrences in a similar fashion as the one that did get addressed.

**Comment by mannycolon** [comment]
@klappy Did you fix this QA issue in one of you latest PRs?

**Comment by mannycolon** [comment]
@klappy How could I include or implement the same here?

**Comment by klappy** [comment]
I just checked and the issue is addressed here. I think I was thinking of somewhere else.

**Comment by cckozie** [comment]
beta.54
Only the project name and not the path is now displayed as the header on the project cards.
